### ISSUE TITLE
Statistics Canada Drupal Implementation Architecture

### ISSUE THREAD

**Issue by Pacoup** [wet-boew/wet-boew-drupal#1003]
@sylus, I was wondering if you'd be willing to share an overview of the Stats Can's Drupal implementation; i.e. what server OS are you using, what web server software and DBMS are you using, is it hosted on Shared Services and if so, how has working with them been so far, have you established special procedures, etc.

We're implementing Drupal across the board at the Canadian Institutes of Health Research and we're looking for any kind of tips and information to help us speed the process and have the best approach with Shared Services.

**Comment by StephenOTT** [comment]
@sinkinsona

**Comment by sinkinsona** [comment]
In regards Infrastructure setup here is how we are setup:
We have a separate server for our Web server, database server and Solr + have a fail over servers for the 3 listed above.

OS = RHEL v6.1 across all server
Web Server= Apache 2,2 ,  Varnish, MemCache
Database = Postgresslq 8.7 (moving away from MySQL5.5 )
Solr = 4.X

For working SSC my understanding is that you need to have your project on their list of priorities.  This is done by communicating with your SSC CRM representative.  Once you are on the list your project would be actioned but this can take sometime.  Start this process early as it will take months from my experience.

Let me know should you have any other questions.

**Comment by Pacoup** [comment]
For the purposes of helping anyone who falls on this post in the future, would you mind explaining why the move away from MySQL?

I know I would be moving to MariaDB for both software quality and political reasons; I don't think Oracle is planning to do much good to MySQL. This echoes the sentiment of the community I believe, but PostgreSQL is not a drop-in replacement for MySQL, not that it matters for Drupal, but it would be interesting to hear your point of view on this.

Also, out of curiosity, how difficult is setting up Memcached and Varnish with Drupal, would you recommend both or either or just Varnish depending on the scenario (for high traffic vs low traffic sites), can any of those speed up admin pages and not just static content, etc.

**Comment by sinkinsona** [comment]
The main reason we are moving away from Oracle MySQL is that our database hosting team does not want to support 2 open source databases.  When we launched Opendata we used a data catalogue called CKAN and it will only work with PostgreSql.  We also ran performance tests and PostgresSql was faster so the choice for us was obvious. This being said I have heard + seen good performance from both Percona and Mariadb flavours of MySQL.

I would strongly recommend using both varnish and memcache for any Drupal site as it really speeds things up but you might need to ban pages or lower the cache refresh setting depending on the nature the site.  (Example would be a page that users comment + vote on and you need to see the results displayed in real-time)
Setting up varnish or memcache it is pretty straightforward.  Here are some tutorials that explains it well https://www.digitalocean.com/community/articles/how-to-install-and-configure-varnish-with-apache-on-ubuntu-12-04--3

https://www.digitalocean.com/community/articles/how-to-install-and-use-memcache-on-ubuntu-12-04

Also check out https://drupal.org/project/varnish 

Also keep in mind that Varnish is not used for logged in users. When time permits I will see about having someone from my team do a write up on configuring Drupal + Varnish as this is something we should all be doing when putting our sites into production.  Hope that this was helpful.

**Comment by nschonni** [comment]
I know the MySQL community evangelist (former Percona guy), is there any interest in getting some MySQL 5.6 implementation guides for WET? I get that Oracle is the "Evil Empire" :smile: but we could probably get some good writeups ...

**Comment by Pacoup** [comment]
Closing issue because the answer has been provided.
