### ISSUE TITLE
Problem with the mid-footer menu

### ISSUE THREAD

**Issue by nrc-cnrc-web** [wet-boew/wet-boew-drupal#1009]
The mid-footer, when set up to have a top-level link but no children, creates an &lt;h4&gt; and an empty &lt;ul&gt;&lt;/ul&gt;.

As per @pjackson28's response in the wet-boew repository (https://github.com/wet-boew/wet-boew/issues/3100), in this case the &lt;h4&gt; needs to change to a &lt;div&gt; and the empty list needs to be removed.

**Comment by nrc-cnrc-web** [comment]
Opened the issue on drupal.org. Closing as dupe.

**Comment by sylus** [comment]
Fixed over at: https://drupal.org/node/2104319

Yeah sorry active issue queue is over there since closer to packager. I am looking at a way to mirror the issue queue as would be good to reflect the 60 issues solved over there during past month.
