### ISSUE TITLE
RC14: Admin theme seems to have a minor CSS glitch

### ISSUE THREAD

**Issue by nrc-cnrc-web** [wet-boew/wet-boew-drupal#1024]
Please see the screen shots below to see what happens. It is caused by scrolling down the page. Browser is Chrome 29.

![pre-scroll](https://f.cloud.github.com/assets/2982689/1248866/ff76def2-2ad5-11e3-8a47-c7cb7f101e43.jpg)

![post-scroll](https://f.cloud.github.com/assets/2982689/1248869/02d11f7c-2ad6-11e3-9540-1d0d80491b7b.jpg)

**Comment by MikeDucharme** [comment]
I'm seeing this issue as well at RC19.

**Comment by RobJohnston** [comment]
I'm not seeing it using Chrome Version 30.0.1599.66 m (and there's even another update I haven't applied yet).

**Comment by nrc-cnrc-web** [comment]
This is RC20, with latest update to Chrome applied:

![rc20-issue](https://f.cloud.github.com/assets/2982689/1345442/c186666a-368f-11e3-9937-ede5dbbbf5ab.jpg)

**Comment by MikeDucharme** [comment]
I can confirm this in rc20 but it seems to pop in at random locations

![wetkit_chrome_bug](https://f.cloud.github.com/assets/82974/1363131/71ca529c-3826-11e3-8e95-784632b2c64c.gif)

**Comment by sylus** [comment]
Fixed a while ago and reported in D.O.
