### ISSUE TITLE
RC15: Problem with Content admin page and custom content types

### ISSUE THREAD

**Issue by nrc-cnrc-web** [wet-boew/wet-boew-drupal#1027]
When creating content of a custom content type, the Content admin page (admin/content) does not show pages from the custom content type. If you filter by that particular type, it says "No content available".

![content-all](https://f.cloud.github.com/assets/2982689/1255163/b137d01a-2b80-11e3-9b48-b04fa94d0eda.jpg)

![content-filtered](https://f.cloud.github.com/assets/2982689/1255165/b4fec8e8-2b80-11e3-81fc-96d1a8c12068.jpg)

**Comment by mxlav** [comment]
I'm guessing you're custom type has "multilingual disabled" selected?

A similar issue was raised on the drupal issue site here https://drupal.org/node/2097675

work around... use dashboard/content..that view seems to work a bit better

fyi, I think most people or posting there now.

**Comment by nrc-cnrc-web** [comment]
Ahh, cool. Thanks very much. I just used the default settings (which seem to be "disabled"). I was using RC4 prior, so I guess, as your post there notes, this was added after that. Much appreciated, @mxlav!
