### ISSUE TITLE
Better software release cycle scheme for Drupal WxT 7.x-2.0 and 8.x-1.0

### ISSUE THREAD

**Issue by Pacoup** [wet-boew/wet-boew-drupal#1043]
<h2>What's the issue?</h2>

The problem is, the Drupal WxT distribution has been using a release scheme which is not at all in line with normal release schemes and is thus not conducive to properly communicating the state of the project.

This is apparent in the frenetic release of Release Candidates. Essentially, it tells us that Drupal WxT RC'd too early.

<h2>Quick definitions of release cycles</h2>

To help in properly defining a context for this conversation, the following is a short summary of the different release cycles, as defined on Wikipedia:

<strong>Pre-alpha</strong>
All activities before testing; i.e. development.

<strong>Alpha</strong>
First phase of software testing. The software is generally considered feature complete, although features may be changed, added or removed, especially when using Agile software development methodologies.

<strong>Beta</strong>
Normally happens when the software is feature complete. In other words, apart from improvements and bug fixing, new features should not be added.

<strong>Release Candidate</strong>
This is a beta version with potential to be a final product, _which is ready to release unless significant bugs emerge_; in other words, this means a version that is essentially considered stable unless found otherwise after more testing.

<h2>Where's Drupal WxT and what can be done</h2>

If you look at these definitions and Drupal WxT's release notes, the WxT distribution has entered beta in RC8, after the last feature change (alpha stage) which was the addition of a new backend theme in RC7.

Since the releases are frequent and contains lots of fixes, and, oddly enough, fixes that are qualified as features but are really fixes, the project is obviously still in beta phase.

Furthermore, the “beta” releases are too frequent. Fixes can and should be fixed and tested on the dev branch and subsequently released in betas less frequently for more general non-developer testing by the community. Beta releases can be arbitrarily limited to fixed timeframes, such as monthly, which is typical of many open source projects.

Then, only when the project is considered stable, a Release Candidate is in order. In most projects, RC1 is often the only RC, because the project is properly considered stable. Most projects never go above RC3. Drupal WxT is now up to RC19.

<hr>

Evidently, going back now is not a solution. It's too late. But it's likely worthwhile to establish proper guidelines for future releases such as 7.x-2.0 and 8.x-1.0.

**Comment by StephenOTT** [comment]
:+1:

**Comment by nschonni** [comment]
I know you're aligning with the Drupal release number, but you may also want to consider http://semver.org/

**Comment by mgifford** [comment]
Given all of the patches required to contrib modules, I do like the idea of the 2.0.0 approach so that frequent updates are encouraged. However, following Drupal's model might be easier to follow.  I'm fine with either.

RC shouldn't see any module/theme swaps as far as I'm concerned.  RC's are useful for QA, but they are not an alternative to an internal QA process.

**Comment by Pacoup** [comment]
@mgifford I don't really see how 2.0.0 changes anything from regular Drupal module versioning except splitting MINOR and PATCH, the rest is all the same, but I'm not sure whether we can do it: <a href="https://drupal.org/node/467026">Version numbers | Drupal.org</a>. Nevertheless, this issue is not really about the versioning scheme, but the release cycles for each version.

And I agree with the internal QA process. We have the issues on Drupal.org and GitHub for this.

**Comment by mgifford** [comment]
Yup, it was just the minor/patch modification..  Perhaps even Minor, and Very minor. Say when upgrading from an Omega RC to the full release it would be reason to make Minor version number increment.  If there's a CSS change that fixes an admin page for IE8 users then this would be considered a Very minor version number increment.  

I do think that the Version numbers page on Drupal is more geared to themes/modules than distributions.  The folks with kickstart seem to be sticking with the standard Drupal approach (which is fine). 
https://drupal.org/project/commerce_kickstart

Switching the base theme or removing a base distribution is cause to make a major version increment.

**Comment by Pacoup** [comment]
And so is <a href="https://drupal.org/node/1541150/release">Spark</a>.

According to Drupal.org, this is for any kind of release; Modules, Themes, Distributions; those are all types of Drupal.org projects. So according to this: <a href="https://drupal.org/node/1015226">Release naming conventions</a>, no, you can't have your own versioning scheme.

@sylus please confirm

**Comment by sylus** [comment]
We are aware we released RC too early and agree with the naming convention. We are closing in on a 1.0 release.

For future releases we will follow the conventions a bit more closely. We do have a lot of RC's but have found it easier to for our developers to work with stable packaged builds as the drupal dev packager has problems whereas the stable tagging does not. Therefore have been forced to do stable releases more often then like.

I am currently talking with the infrastructure team to figure out what is wrong with the drupal packager when trying to package -dev releases. If you notice it hasn't been updated in a while.

No new features will be added in the current 1.x builds, we are purely in a bug fix phase atm.

1.0 will be released when it is ready and we are confident with the quality.

At which point when 1.0 will be released we will be moving to 2.x for new features.
