### ISSUE TITLE
Unable to create features in RC20

### ISSUE THREAD

**Issue by Gale-ccohs** [wet-boew/wet-boew-drupal#1055]
Attempting Create Feature results in the following error:

Fatal error: Unsupported operand types in /Users/brianc/Sites/owm/profiles/wetkit/modules/contrib/entity/entity.features.inc on line 31

**Comment by RobJohnston** [comment]
Looks like it is a new problem with the entity module:  https://drupal.org/node/2106149.

BTW, looks like most people are filing issues here now:  https://drupal.org/project/issues/wetkit.

**Comment by Gale-ccohs** [comment]
Thank you very much. I’ll do that. Do you want me to remove the issue?

Gale

**Comment by RobJohnston** [comment]
No, I don't control things... just trying to help-out.

**Comment by RobJohnston** [comment]
Hi Gale,

I noticed you closed the issue but wanted to tell you that it looks like the main developer of wet-boew-drupal found the same issue and has just added the fix.  See https://drupal.org/node/2115137.

**Comment by Gale-ccohs** [comment]
Thank you for babysitting me through this Rob. I should have realised right at the beginning it was an issue outside of the wetkit. Duh.
