### ISSUE TITLE
Broken path in the french FIP.

### ISSUE THREAD

**Issue by rousellb** [wet-boew/wet-boew-drupal#1070]
Noticed a broken path in the Fip when I tried to make a change for our site. The broken link only happens when french is selected.

&lt;object type="image/svg+xml" aria-label="Government of Canada" tabindex="-1" role="img" data="/drupal_wet_rc20/profiles/wetkit/libraries/wet-boewdist/theme-gcwu-intranet/images/sig-blk-fra.svg"&gt;

Wet-boewdist should be wet-boew/dist

**Comment by sylus** [comment]
Was reported over in the drupal issue queue and resolved. Thanks a bunch!
