### ISSUE TITLE
Production Considerations

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#111]
Hi All,

Looking to find out if there is any documentation that has been put together on production considerations for using the wet drupal variant?  I know the base drupal requirements.  But anything special for the enhancements that have been made, and the security requirements for gov?

Thanks

**Comment by mgifford** [comment]
I believe there are plans for a Security App which would include modules like Paranoia, but don't think it's been built yet.

**Comment by StephenOTT** [comment]
so has wet-boew-drupal been used in production, public facing environments?  Is Canadian transport agency using this or their own variant?

**Comment by joejoseph00** [comment]
Hi StephenOTT , I work at the Canadian Transportation Agency (note: we are not Transport Canada, I have no idea what they run)
here at the Canadian Transportation Agency, for our intERnet site we're using Drupal 6 and a CLF theme based on the work of OpenConcepts implemented by LiquidCMS

However, our intRAnet site is being re-done on Drupal 7, but it is not using the WET theme at all.  We are however looking into this distro for future extranet sites and we are in the process of developing PD, at some point I might create a github for it but it's still in the very early stages of dev.  It would be neat to hear of someone else who has finished PD, so that we don't have to , but until then, hopefully we'll have enough time to finish it this summer or by fall.

**Comment by sylus** [comment]
Hey @StephenOTT in terms of production instances I know of only two which is SCC.ca but that was version 1 and some intranet sites we have set up here at Stats. I do know of an additional two in particular that will be launched soon but until they do I have been asked to not talk about it though could prolly email you with some details.

I can say that there is a lot of work going into this distribution and that we have key collaborators from Ottawa University, Health Canada, Statistics Canada, Fintrac, and Shared Services. All of which are currently evaluating  and helping to improve version 2 of the distribution. I know Shared Services in particular is looking to set this up fast for one of their outward facing sites and will also be hosting the Drupal App Store for us. In addition to the ones I named there are a few more departments looking into this but I think right now we are all actively developing and improving this distribution before the next official release of WET which is fast approaching.

In terms of readiness / security for production we are working on a security app but won't be finalized until a couple of weeks as we require feedback from Shared Services. I would still say there is no inherent security problem with this distribution as it has faced coder review (drupal) and peer review from many different people. Ultimately though the goal of this distribution is to just provide you with the possible base foundation leaving the rest up to the developers.

As for @joejoseph00 I would love to create an app for proactive disclosure maybe we could work together on this :)

**Comment by sylus** [comment]
I forgot we do have some incredibly detailed security / deployment / server documentation. We will be releasing these documents as well as a few other ones shortly. Likely before the end of next week as need to make sure we don't publish internal security policies.

**Comment by StephenOTT** [comment]
Hi @joejoseph00,
Do you have any documentation or knowledge of how the following type of page was set up?
http://www.cta-otc.gc.ca/eng/fly-smart.

Specific set of modules being used?

**Comment by joejoseph00** [comment]
Hi @StephenOtt , that page is a page from our old Drupal 6 internet site that will be completely re-done in Drupal 7 asap.  That's one of the simpler pages called a publication (custom content type using CCK) you could probably make your own publication content type based off of one of the Drupal 6 or Drupal 7 variants found here:
http://www.gcpedia.gc.ca/wiki/Drupal_CLF_2.0_template

That fly smart page is using the old 2 column CLF 2.0 standard GOC template.

Keep in mind, CLF 2.0 has been replaced by the WET kit  as the new Treasury Board government website standard.  I think there's also a few other wetkit variants you can try.  What is it that you're trying to accomplish?

**Comment by mgifford** [comment]
If it's useful, would be great if someone would roll up this approach and post it here so that it can be included in the distribution.  

Not being on the government network I can't comment on anything in GCPedia.  I am always a bit shocked though when I hear about MediaWiki being used like a code repository in the government. Just seems all wrong, particularly when there were tools (before github) like IRCan that allowed people to manage code properly.

**Comment by StephenOTT** [comment]
Hi @joejoseph00,
Would love to see this as part of the distribution as it is a very common problem for governments and would solve a great number of issues around page reduction and simplification of website structure.  We have to populate the large amount of data in a accessible and usable format.  The issue is created when we have to populate the information on a single page or multiple pages.  Using dynamic table of contents we can reduce the content to a single page, and use potentially something like Views to filter the content.

What are you using with CCK to preform these actions?  Mix of Views, CCK, and a PDF handler?  Any dynamic content integration - ie. XML or ms word,etc format being dynamically converted for TBC view, full page view and individual section views?
Any details on how it is planned to be rebuilt in D7?

**Comment by joejoseph00** [comment]
@mgifford and @StephenOtt , sorry for the late reply, I just sent you an e-mail with my response.

**Comment by mgifford** [comment]
Thanks for the email. Wanted to just update a link to the thread about the Security App - https://github.com/wet-boew/wet-boew-drupal/issues/248

**Comment by sylus** [comment]
Cleaning up some old issues. :)
