### ISSUE TITLE
administrative menu hidden from all administrators other than master admin user

### ISSUE THREAD

**Issue by joejoseph00** [wet-boew/wet-boew-drupal#112]
administration role of web-boew drupal distro blocked from users other than admin

Steps to reproduce:
1) install wet-boew
2) log in as admin
3) create new user (admin2 for example) and assign administration role
4) log in as admin2 , try to find the admin menu (I couldn't find it)

in our drupal 6 cms we have several administrative users , not necessarily admin.  I don't know if this is intentional or not.

**Comment by sylus** [comment]
Hey @joejoseph00 this was intentional though could be persuaded to remove this functionality. We basically set user 1 as allowed to use admin_menu and all others as using toolbar. I could switch this logic so that user 1 and all users of role admin are allowed to use as well.

**Comment by joejoseph00** [comment]
Hi Will, thanks for the quick response.  Our security policy is super anal here, we can't even use the username admin, it's too easy to guess.  It makes more sense to me to have a toolbar role where users assigned to the toolbar role get the toolbar menu.  Administrator role users get the administrator menu, and so on. ?  

When we do go live we'd probably want to change this, but where would we look for the logic?  Is it in a module or is in the database?

**Comment by sylus** [comment]
Hey @joejoseph00 I will likely make this fix so all you would have to do is a git pull but as your security may not permit that from happening the logic itself resides in: 

wetkit_admin.module

line 42-54

**Comment by joejoseph00** [comment]
Thanks for the valuable info @sylus .  For dev we can use admin, just if we go to production they'd probably want us to change it at some point.  We've got security maniacs that love making us make passwords so long that we have to write them down (a bad side-effect of tight security policies).

**Comment by sylus** [comment]
Fixed though some better default permissions will likely need to be created and added in later.
