### ISSUE TITLE
ordered list issue

### ISSUE THREAD

**Issue by realredd** [wet-boew/wet-boew-drupal#1125]
I'm using WET 3.1 DRUPAL 7.

When creating an ordered list, with a nested ordered list, using the WYSIWYG editor, i attempt to have level 1 list as numbers and the nested level 2 list as roman numerals.

using the class "list-lower-roman" in the nested `<ol>` i assume that my second level will be listed with roman numerals.

When i save, my second `<ol>` uses the alphabetical lower case.

**Comment by joejoseph00** [comment]
please check out RC25 on drupal.org
https://drupal.org/project/wetkit
