### ISSUE TITLE
Layout not applied to the French custom page

### ISSUE THREAD

**Issue by rousellb** [wet-boew/wet-boew-drupal#1148]
I created a home page using Pages. The English page displays properly with a 2 column display using the AT Two column 50/50 layout. The issue is when I switch to french, the 2 column layout do not get applied. They are displayed one on top of the other. I tried to create a variant with a selection rule using the language but it still display the 2 panels one on top of the other. Anyone has a solution? I'm using RC2 with an Intranet theme.

**Comment by joejoseph00** [comment]
Hi Rouselib , this project has moved to drupal.org,
 please try RC25 from www.drupal.org/project/wetkit as RC2 is a few steps behind.  You can easily upgrade your install to RC25.  If you have questions about upgrading, let us know.  It's pretty simple, keep your sites folder and copy it to the RC25 folder, then rename it to the previous after removing or renaming the original, then run drush updatedb and you'll be in business.

http://ftp.drupal.org/files/projects/wetkit-7.x-1.0-rc25-core.tar.gz
There's a tonne of fixes in RC25 and probably some more in the dev branch.
We're in bug-fix mode.
or try the dev version:
http://ftp.drupal.org/files/projects/wetkit-7.x-1.x-dev-core.tar.gz

A 1.0 release is our goal, please see the details on drupal.org
https://drupal.org/project/wetkit
