### ISSUE TITLE
Define the Governance Model

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#1150]
I like this article here - http://oss-watch.ac.uk/resources/governancemodels

It's been one that's been discussed with Drupal 8 & Backdrop.  Worth looking at it here for Wetkit.

As they say in the conclusion - "The idea is to start with a simple and manageable model that will send clear signals to potential contributors."

**Comment by joejoseph00** [comment]
@mgifford Are there any specific governance models that you might recommend looking at?

**Comment by mgifford** [comment]
@joejoseph00 I had no specific alternative to propose, but just wanted to ensure that this was flagged as a discussion that needs to be had.

**Comment by joejoseph00** [comment]
Perhaps a rotating maintainership, to avoid the all eggs in one basket problem.  If our key maintainer gets hit by a bus we could really be caught in a pinch.  Transfering ownership temporarily would be a good way to prepare ourselves to keep the project going should someone like the key maintainer get hit by a bus or change industries or projects.  Not that we would want that to happen, but it might also help us look at possible governance alternatives.

**Comment by mgifford** [comment]
I think part of this is looking up at TBS and getting them to take a more long term approach on how projects are managed, resourced & maintained.  Thus far I haven't seen any particularly mature approaches to IT governance in the GoC.  That being said, I've got a pretty minor exposure and really am not an expert at governance.
