### ISSUE TITLE
Printed page break control of data tables

### ISSUE THREAD

**Issue by realredd** [wet-boew/wet-boew-drupal#1187]
I have a long table with appropriate thead, tbody tags setup.

I'm wondering if there is a class in place that can control where a table will split when the HTML page is printed.

Currently "row 7" of my table gets split onto two pages and the first columns row heading does not duplicate onto the second page.

So although my column heading is shown on the second page, the "7" in the row header shows on the first page but does not repeat on the second page with the split content of said row.

Thoughts?

**Comment by sylus** [comment]
I'd move this issue to the wet-boew repo itself as isn't a specific Drupal problem. :)
