### ISSUE TITLE
Error on Panelizer Layout

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#119]
Getting the following error notice:
Notice: unserialize() [function.unserialize]: Error at offset 106 of 937 bytes in panels_common_get_allowed_layout_object() (line 426 of /Users/MyUser/Sites/WET/drupal_wet/profiles/wetkit/modules/contrib/panels/includes/common.inc).

Error appears from the following action:
1. Create new Basic Page.
2. Create English Content and Save
3. View newly created page and select the Panelizer Tab
4. Under the Operations column for Full Page Override select the layout link.
5. Layout options appear and Error appears.

**Comment by sylus** [comment]
Fixed!
