### ISSUE TITLE
Tooltip information for WYSIWYG Configuration expands off screen

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#120]
The tool tip for for the HTML Elements and Attributes in the WYSIWYG Filter settings in the Configuration Window at: Admin>Config>Content Auth>Text Formats>WYSIWYG has a huge tool tip that expands way beyond the screen.

**Comment by sylus** [comment]
Thanks for the issue, this will likely have to be fixed upstream though at the Rubik project on D.O. at http://drupal.org/project/rubik

If you could file an issue would be greatful. In the mean time I can look for a temporary workaround.

**Comment by sylus** [comment]
We may have to fix this on ours and then I will create a patch to place upstream. Any frontend developers want to deal with this error? :)

**Comment by sylus** [comment]
Woot there is now a fix for this out which places it inline see: http://drupal.org/node/1730844

**Comment by sylus** [comment]
Fixed!
