### ISSUE TITLE
User Login Error while in Site Maintenance Mode

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#122]
While in Site Maintenance Mode and logged out, if you to go to: yoursite.com/user you will get the following error notices:

Notice: Undefined index: menu_lang_bar in wetkit_adaptivetheme_preprocess_page() (line 164 of /Users/myuser/Sites/WET/drupal_wet/profiles/wetkit/themes/wetkit_adaptivetheme/inc/template-preprocess.inc).
Notice: Undefined variable: polyfills in include() (line 27 of /Users/myuser/Sites/WET/drupal_wet/profiles/wetkit/themes/wetkit_adaptivetheme/templates/maintenance-page.tpl.php).

**Comment by sylus** [comment]
Fixed!
