### ISSUE TITLE
Bean Slide Block bugs out

### ISSUE THREAD

**Issue by rgalipeau** [wet-boew/wet-boew-drupal#1226]
Created a Bean Slider on a fresh 1.1 instance... seamed fine, added to frontpage:
Tried disabling WetKit Metatag module, still persists (even after clear a cache all).

Notice: Undefined property: UUIDFieldCollectionItemEntity::$type in _metatag_entity_is_page() (line 1387 of /var/www/html/drupalwxt.org/profiles/wetkit/modules/contrib/metatag/metatag.module).

**Comment by rgalipeau** [comment]
Will, renders when signed in, but not anonymous.
You can actually see on drupalwxt.org (same creds as usual)

**Comment by sylus** [comment]
Was just a permission not being set "view bean slideshow"

As for the other error looking into it.

Edit

Looks like a problem with Field Collection there is a bug reported for this.

**Comment by sylus** [comment]
Fixed upstream see D.O.
