### ISSUE TITLE
Accessible Survey Tool

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#123]
Anyone know of a Accessible Survey tool that can be integrated with Drupal or something similar?
WET have anything of use?  Have not found anything that could do this.

**Comment by mgifford** [comment]
Well, why not just use - http://drupal.org/project/webform

The accessibility enhancements that were brought into Drupal 7 Core are generally inherited by modules like this.

There are some accessibility problems, particularly with multi-part forms like dates & phone numbers.  However, these can be addressed.

It can be extended pretty easily as well to give you some basic reporting tools too.

**Comment by StephenOTT** [comment]
The problem we run in too is the reporting side.
We can put together some modules to make the reporting.  Was just hoping to find a package that was ready to go.
Unfortunately pretty much every survey tool out there is not AODA compliant

**Comment by StephenOTT** [comment]
I am thinking that webform will meet the data intake.  Will brick together a reporting package for the needed common reporting practices.

Will share when ready

**Comment by sylus** [comment]
Awesome would love to see this :) Thanks @StephenOTT

**Comment by StephenOTT** [comment]
Should be valuable.  Other aspect is allowing for intercepts/popups/modals for the survey intake 

@sylus 
you get my email ?

**Comment by sylus** [comment]
@StephenOTT Yup I have recieved the email ^_^ Will likely get back to you within a day or so. ^_^

**Comment by mgifford** [comment]
Modal dialogs are very, very difficult for accessibility.  See http://drupal.org/node/1175830 as approaches for D8.

There's hope that this will be resolved in the dev version of jQuery, but that still needs some testing.

As far as reporting, there's always - http://drupal.org/project/webform_report & http://drupal.org/project/webform_localization
