### ISSUE TITLE
Responsive Images *Need Feedback*

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#130]
I have been following with active interest the following thread which discusses how responsive images should be handled in Drupal 8. A module has been created based on this feedback for both Drupal 7 and 8.

I would like to know what other people think about this module before I add it to the distribution: http://drupal.org/project/resp_img

The project page itself talks about other similar modules near the bottom.

Would love feedback!

People can see a tutorial of how this works here: http://atix.be/ZkM

**Comment by mgifford** [comment]
We used http://drupal.org/project/flexslider when putting together the new OC site.  Looks like we could have used the Responsive Images module too.  

It's an important piece for mobile, wondering if it should be bundled in an extra package.  It would be a better show if the images in the slider were just smaller too, but then while the distro is still using jQuery Mobile that's probably less important.

Also for consideration http://drupal.org/project/adaptive_image which might work better with the base theme.

**Comment by sylus** [comment]
Panopoly is going resp_img and we are following suit :)
