### ISSUE TITLE
More Documentation on GitHub

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#131]
Documentation work has started in earnest. It would be greatly appreciated if we could get some people skilled at writing and correct documentation to ensure the best readability.

@LeeHunter I don't suppose could persuade you to give some of the Wiki Pages a gander? :)

More coming tomorrow!

**Comment by sylus** [comment]
Hey @LeeHunter I see you did some documentation improvements I really appreciate you taking the time :)

**Comment by LeeHunter** [comment]
Thanks @sylus. I haven't done much yet but I've started a page for theming (https://github.com/wet-boew/wet-boew-drupal/wiki/Theming-Guide). One question I have (which you can see from the gap in the page) is what is the best practice for modifying and extending the Drupal WET theme? Should I copy the whole thing over to the sites/all/themes directory, rename it and start working from there or is there a better way.

**Comment by sylus** [comment]
Hey @LeeHunter I saw you send me an email I am available anytime this week to sit down with you :)

**Comment by LeeHunter** [comment]
How about Wednesday afternoon at 2 at your office? You at Tunney's Pasture?

**Comment by sylus** [comment]
Works for me and yeah at RH Coates. I will email details :)

**Comment by sylus** [comment]
Hey Lee are we still on? and also I am located at Jean Talon 4th floor :)

**Comment by LeeHunter** [comment]
Great. See you soon.

**Comment by sylus** [comment]
Closing this issue as documentation is being worked on :) Reopen when needed! :)
