### ISSUE TITLE
Admin menu performance

### ISSUE THREAD

**Issue by joejoseph00** [wet-boew/wet-boew-drupal#132]
Disable Overlay: 
For improved performance of the admin menu and to get more admin menu real-estate, we (OTC-CTA) disable the overlay module manually after install and have not noticed any problems

**Comment by sylus** [comment]
Yeah I tend to agree, in the next commit I will disable overlay by default.

**Comment by thriuin** [comment]
Absolutely - it's one of the first things I do after installing.
