### ISSUE TITLE
Scheduler module

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#135]
Any discussions for added content scheduling into the distro?

Sets dates and times for ready content to be published and unpublished?

In many cases we have content that is time sensitive.  It is prepared before hand but only to go only at a certain time.  Ability top schedule the content for publication would be valued, followed by the ability to set a un-publish date and time for when the content should be removed.

**Comment by sylus** [comment]
Rules Scheduler I think works with this? While this wouldn't be added to WetKit Core as it is supposed to be kept minimal. I can definitely see this being converted to an App that we could then host on the Drupal App Server.

**Comment by StephenOTT** [comment]
Agreed.  Should be a App.
Yes Rules Scheduler 'could' do it.  But a lot of effort to make happen for something that can occur thousands of times
I was thinking more along the lines of:
http://drupal.org/project/scheduler

**Comment by thriuin** [comment]
For me, the drawback with the scheduler module is that it is attached at the content type level and it relies on the Drupal cron job to make it work.If you need to release something at a precise time, you need to make sure the cron runs approximately at the same time. I assume Rules Scheduler allows for more logic and doesn't apply to every instance of a content type, but still depends on the Drupal cron. Depending on your requirements this may be sufficient or perhaps one could consider a solution that involves a real cron and a Drush scriptl

**Comment by StephenOTT** [comment]
Agree on the Cron issue.  Was always an annoyance.

From a Distributed Publishing model where there are hundreds of contributors using the system.  Most without a lot of technical knowledge, the Scheduler module integration is very clear and easy to secure and implement.

**Comment by joel-osc** [comment]
I use scheduler on another project, it is a nice little module. I would be concerned that it does not integrate with workbench moderation. Ideally, the 'scheduled for publishing' should be part of the Workbench workflow, ie. Draft->Needs Review->Scheduled for Publishing->Published. May be something to re-visit as part of WET once the workbench module overhaul has been completed.

**Comment by StephenOTT** [comment]
Looks like some work has started by some groups to make this integration happen:
http://drupal.org/project/scheduler_workbench

**Comment by sylus** [comment]
Cleaning up some old issues. :)
