### ISSUE TITLE
Error after installing drupal WET

### ISSUE THREAD

**Issue by jilusan** [wet-boew/wet-boew-drupal#1389]
Hello,

I downloaded "Web Experience Toolkit" at https://drupal.org/project/wetkit
After the installation is finished, I got the message:

Congratulations, you installed WetKit!

But, when I try to lauch the site, I get an ugly text page:

Additional uncaught exception thrown while handling exception.

Original

PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away: SELECT base.vid AS vid, base.name AS name, base.machine_name AS machine_name, base.description AS description, base.hierarchy AS hierarchy, base.module AS module, base.weight AS weight, base.language AS language, base.i18n_mode AS i18n_mode FROM {taxonomy_vocabulary} base WHERE (base.machine_name = :db_condition_placeholder_0) ORDER BY base.weight ASC, base.name ASC; Array ( [:db_condition_placeholder_0] =&gt; wetkit_categories ) in DrupalDefaultEntityController->load() (line 191 of /Applications/MAMP/htdocs/travel-voyage/includes/entity.inc).

....

I checked the database. It has been populated correctly.

Could you help?

Thanks 

Gil

**Comment by mxlav** [comment]
@jilusan It looks like you might need to tweak you MySQL settings.

see posts here https://drupal.org/node/1014172

Also make sure to changes some of the properties mentioned here 
http://wiki.drupalwxt.org/architecture/system-requirements/

**Comment by jilusan** [comment]
@mxlav 
Ok. Finally it works.
Is there another way to install Drupal WET and have the list of mandatory modules?
Because I am not sure if I will need all the admin modules that have been installed automatically with the installation.
Thanks,
Gil

**Comment by mxlav** [comment]
You can install via the web installer or using drush (http://wiki.drupalwxt.org/architecture/drush-make/) but either case, you'll end up with the same sets of modules.

Any module that has been enabled by the installation is marked as mandatory by some WETKIT module and probably shouldn't be disabled.

If you want to see all the contrib modules packaged with WETKIT, you can find them here profiles\wetkit\modules\contrib. There are currently 91 modules located there.

**Comment by jilusan** [comment]
Ok Marc. Merci.
If for intance, we want to develop a module, which directory you suggest to add in, sites/all/modules/custom ?

**Comment by mxlav** [comment]
Yes, that would be where I would create any custom modules.
Any additional contrib modules you decide to download should go in 
sites/all/modules/contrib, to keep things nice and organised.

You really shouldn't touch anything in the profile/wetkit folder, in order to avoid any future upgrade issues.

**Comment by jilusan** [comment]
@mxlav 
Thanks.
