### ISSUE TITLE
Canada.ca Theme

### ISSUE THREAD

**Issue by jilusan** [wet-boew/wet-boew-drupal#1390]
Hi,
I would just wondering if a Drupal theme for Canada.ca has been developed? 
Thanks

**Comment by sylus** [comment]
It is in process along with all the others leveraging the bootstrap theme. We have actually finished the leg work for this but are now doing testing and getting some beta users in before we do a 2.x branch.

Sorry for the lateness of the reply usually I track the Drupal issue queue :)
