### ISSUE TITLE
Accessing WET Updates

### ISSUE THREAD

**Issue by nickoz** [wet-boew/wet-boew-drupal#141]
I hope this is the right place to ask this question! I have the WET distro up and running and I'm wondering how to update my copy of WET when updates to are committed? Are WET updates accessible through Drupal's update manager?

**Comment by sylus** [comment]
Hey ^_^

You would usually do a git clone to retrieve the WET updates themselves, however depending on when you cloned things might have changed as a few modules might have made it in. We are releasing version 3.0 on September 17th. :)
