### ISSUE TITLE
Updates through the UI

### ISSUE THREAD

**Issue by at88mph** [wet-boew/wet-boew-drupal#1410]
I don't see a way to update just the wet-boew files.  A new version (3.1.10) has been released, but it's not in the list of Available Updates.

Are the available updates maintained differently?

Thanks!

**Comment by Pacoup** [comment]
+1 Would like to know for documentation purposes. Not sure this was ever outlined clearly.

**Comment by at88mph** [comment]
It doesn't even need to be through the UI; I would happily use drush to do it, if it's easier.

Thanks again.

**Comment by Pacoup** [comment]
This thread actually has a lot of relevant information. It's not exactly updating through the UI, but I think that's the only supported method right now.

https://drupal.org/node/2127181

**Comment by sylus** [comment]
Hey for the wet-boew jQuery library it is handled through the make file in wetkit_wetboew. I have just released v1.4 of the distribution which does have the latest version of the WxT jQuery framework for v3. Next phase is v4!
