### ISSUE TITLE
Notice: Undefined index: simplenews in _locale_translate_seek() (line 1931 in D:\Website\drupal\includes\locale.inc).

### ISSUE THREAD

**Issue by TheMMMM** [wet-boew/wet-boew-drupal#1454]
When I try to filter translatable strings in the following page:
http://localhost/?q=admin/config/regional/translate

I get an error message:
Notice: Undefined index: simplenews in _locale_translate_seek() (line 1931 in D:\Website\drupal\includes\locale.inc).

Request for help，thanks！

$rows = array();
  foreach ($strings as $lid => $string) {
    $rows[] = array(
      $groups[$string['group']], //line 1931
      array('data' => check_plain(truncate_utf8($string['source'], 150, FALSE, TRUE)) . '<br /><small>' . $string['location'] . '</small>'),
      $string['context'],
      array('data' => _locale_translate_language_list($string['languages'], $limit_language), 'align' => 'center'),
      array('data' => l(t('edit'), "admin/config/regional/translate/edit/$lid", array('query' => drupal_get_destination())), 'class' => array('nowrap')),
      array('data' => l(t('delete'), "admin/config/regional/translate/delete/$lid", array('query' => drupal_get_destination())), 'class' => array('nowrap')),
    );
  }

**Comment by sylus** [comment]
I don't think this is related to the WxT distribution nor do we ship with Simplenews as part of the build. I see you have asked this question in the simplenews issue queue so might be best to let that issue handle this.

**Comment by TheMMMM** [comment]
Okay, thank you.
