### ISSUE TITLE
Update to 1.4 broken with drush?

### ISSUE THREAD

**Issue by at88mph** [wet-boew/wet-boew-drupal#1473]
I'm running 1.3 right now on 64-bit Debian and the latest MySQL.  I'm trying to upgrade to version 1.4 of the distro.

If I run drush --backup-dir=/var/backups/drush pm-update like I've always done, I get this error:
Do you really want to continue with the update process? (y/n): y
sh: line 1: 25131 Segmentation fault      svn info /var/www/wet-boew-drupal/profiles/wetkit/modules/contrib/panopoly_magic 2>&1
Project panopoly_magic was updated successfully. Installed version is now 7.x-1.5.
Backups were saved into the directory /var/backups/drush/wet/20140502170757/modules/panopoly_magic.                    [ok]
sh: line 1: 25145 Segmentation fault      svn info /var/www/wet-boew-drupal/profiles/wetkit/modules/custom/wetkit_admin 2>&1
Project wetkit_admin was updated successfully. Installed version is now 7.x-1.4.
Backups were saved into the directory /var/backups/drush/wet/20140502170757/modules/wetkit_admin.                      [ok]
sh: line 1: 25157 Segmentation fault      svn info /var/www/wet-boew-drupal/profiles/wetkit/modules/custom/wetkit_bean 2>&1
Project wetkit_bean was updated successfully. Installed version is now 7.x-1.6.
Backups were saved into the directory /var/backups/drush/wet/20140502170757/modules/wetkit_bean.                       [ok]
sh: line 1: 25169 Segmentation fault      svn info /var/www/wet-boew-drupal/profiles/wetkit/modules/custom/wetkit_core 2>&1
Project wetkit_core was updated successfully. Installed version is now 7.x-1.8.
Backups were saved into the directory /var/backups/drush/wet/20140502170757/modules/wetkit_core.                       [ok]
sh: line 1: 25181 Segmentation fault      svn info /var/www/wet-boew-drupal/profiles/wetkit/modules/custom/wetkit_images 2>&1
Project wetkit_images was updated successfully. Installed version is now 7.x-1.3.
Backups were saved into the directory /var/backups/drush/wet/20140502170757/modules/wetkit_images.                     [ok]
sh: line 1: 25193 Segmentation fault      svn info /var/www/wet-boew-drupal/profiles/wetkit/modules/custom/wetkit_language 2>&1
Project wetkit_language was updated successfully. Installed version is now 7.x-1.6.
Backups were saved into the directory /var/backups/drush/wet/20140502170757/modules/wetkit_language.                   [ok]
sh: line 1: 25205 Segmentation fault      svn info /var/www/wet-boew-drupal/profiles/wetkit/modules/custom/wetkit_menu 2>&1
Project wetkit_menu was updated successfully. Installed version is now 7.x-1.4.
Backups were saved into the directory /var/backups/drush/wet/20140502170757/modules/wetkit_menu.                       [ok]
sh: line 1: 25217 Segmentation fault      svn info /var/www/wet-boew-drupal/profiles/wetkit/modules/custom/wetkit_migrate 2>&1
Project wetkit_migrate was updated successfully. Installed version is now 7.x-1.3.
Backups were saved into the directory /var/backups/drush/wet/20140502170757/modules/wetkit_migrate.                    [ok]
sh: line 1: 25229 Segmentation fault      svn info /var/www/wet-boew-drupal/profiles/wetkit/modules/custom/wetkit_search 2>&1
Project wetkit_search was updated successfully. Installed version is now 7.x-1.4.
Backups were saved into the directory /var/backups/drush/wet/20140502170757/modules/wetkit_search.                     [ok]
sh: line 1: 25241 Segmentation fault      svn info /var/www/wet-boew-drupal/profiles/wetkit/modules/custom/wetkit_users 2>&1
Project wetkit_users was updated successfully. Installed version is now 7.x-1.1.
Backups were saved into the directory /var/backups/drush/wet/20140502170757/modules/wetkit_users.                      [ok]
sh: line 1: 25253 Segmentation fault      svn info /var/www/wet-boew-drupal/profiles/wetkit/modules/custom/wetkit_wetboew 2>&1
Project wetkit_wetboew was updated successfully. Installed version is now 7.x-1.4.
Backups were saved into the directory /var/backups/drush/wet/20140502170757/modules/wetkit_wetboew.                    [ok]
sh: line 1: 25265 Segmentation fault      svn info /var/www/wet-boew-drupal/profiles/wetkit/modules/custom/wetkit_widgets 2>&1
Project wetkit_widgets was updated successfully. Installed version is now 7.x-1.4.
Backups were saved into the directory /var/backups/drush/wet/20140502170757/modules/wetkit_widgets.                    [ok]
sh: line 1: 25278 Segmentation fault      svn info /var/www/wet-boew-drupal/profiles/wetkit/modules/custom/wetkit_wysiwyg 2>&1
Project wetkit_wysiwyg was updated successfully. Installed version is now 7.x-1.4.
Backups were saved into the directory /var/backups/drush/wet/20140502170757/modules/wetkit_wysiwyg.                    [ok]
sh: line 1: 25290 Segmentation fault      svn info /var/www/wet-boew-drupal/profiles/wetkit/themes/ember 2>&1
Project ember was updated successfully. Installed version is now 7.x-2.x-dev.
Backups were saved into the directory /var/backups/drush/wet/20140502170757/themes/ember.                              [ok]
sh: line 1: 25302 Segmentation fault      svn info /var/www/wet-boew-drupal/profiles/wetkit/themes/wetkit_ember 2>&1
Project wetkit_ember was updated successfully. Installed version is now 7.x-1.5.
Backups were saved into the directory /var/backups/drush/wet/20140502170757/themes/wetkit_ember.                       [ok]
sh: line 1: 25314 Segmentation fault      svn info /var/www/wet-boew-drupal/profiles/wetkit/themes/wetkit_omega 2>&1
Project wetkit_omega was updated successfully. Installed version is now 7.x-1.6.
Backups were saved into the directory /var/backups/drush/wet/20140502170757/themes/wetkit_omega.                       [ok]
The wetkit directory could not be found within the modules directory at /var/www/wet-boew-drupal/profiles/wetkit, perhaps  [error]
the project is enabled but has been deleted from disk.

If I run svn info manually it says it's not a working copy.  Are these actually checked out of Subversion?

Thanks for all the work on this.  I'm very much looking forward to Drupal WxT with WET 4.

Dustin

**Comment by sylus** [comment]
The build itself is using git so no svn. If you are interested in how our builds are leveraged via drush for Travis CI take a look at: https://github.com/wet-boew/wet-boew-drupal/blob/7.x-1.x/.travis.yml. However this is mostly for development it is best to follow the official route with a non working copy for production sites.

The error makes sense to me as the wetkit directory should not be found within the modules directory as it is an install profile. Maybe consult http://wiki.drupalwxt.org/architecture/release-cycle for a manual route.

**Comment by at88mph** [comment]
Thanks, Sylus.  I'll try the manual route.

Of note, if I update through the UI, I get this error message:

wetkit-7.x-1.4-core.tar.gz does not contain any .info files.

Thanks,
Dustin

**Comment by sylus** [comment]
This means that you didn't unzip in the directory to which it resides. Likely because your drush command didn't work as expected.

See: where it states pm-update doesn't quite work right for distribtions.

http://drupal.stackexchange.com/questions/49474/right-way-to-update-a-drupal-distribution

**Comment by at88mph** [comment]
Thanks again, Sylus.

For anyone else having this issue, using the 'drush dl wetkit' in my installation directory worked.  All it seems to do is replace the entire profiles/wetkit directory, which, as far as I know, never really gets modified by the end user, so it should be safe.

Dustin
