### ISSUE TITLE
Solr Search config

### ISSUE THREAD

**Issue by dsamojlenko** [wet-boew/wet-boew-drupal#1476]
Trying to get Solr search working.  

Did a clean install of wetkit, get solr installed and copied in the config files from the profiles/wetkit/modules/custom/wetkit_search/solr-conf directory, then created a bunch of missing config files etc... enabled the wetkit_search_api module and get all its dependencies... once all that's done, Solr is running and Drupal can connect to it fine and all that.

But when I do a search through the Search bar at the top of the page, it always runs a regular Database search.  On the search results page if I search in the box that appears below, it runs a Solr search.  Am I missing some config or something to get the site-wide search bar to use Solr?

**Comment by mxlav** [comment]
What version of WET are you using?
A similar issue (https://drupal.org/node/2229433) was resolved in v1.4

**Comment by dsamojlenko** [comment]
Just did a brand-new install of 1.4.  Topbar search directs to search/node (database search) and the search field on the results page directs to search/site (solr search).

**Comment by mxlav** [comment]
I had the same issue as you did when I started playing around with Solr. 

One solution/workaround I found was installing https://drupal.org/project/search_api_page
This in conjunction with https://drupal.org/project/custom_search (already included in WxT) lets you override the search block to a custom search result page.

I went with that option for now, because I didn't have time to invest in figuring out how to over write it. 

I have several issues here https://drupal.org/project/issues/search/wetkit?text=search&assigned=&submitted=mxlav&project_issue_followers=&issue_tags_op=%3D&issue_tags=, but no "real" solution, such as how to properly do it in code.

**Comment by mxlav** [comment]
@dsamojlenko any luck?

I stumbled on this module https://drupal.org/project/pm_existing_pages, looks promising, but haven't tried it.

**Comment by joel-osc** [comment]
If I understand correctly all you want to do is make the top search box go to search/site/[keyword]?

The top search box comes from custom search blocks module, the top box is configured here: admin/structure/block/manage/custom_search_blocks/1/configure under the custom search paths section you can change the path to search/site/[key].

**Comment by dsamojlenko** [comment]
@joel-osc that did it.  Should this be getting set by Wetkit Search module or Wetkit Search API module?

**Comment by joel-osc** [comment]
It looks like wetkit_search is the module that sets this up... so you could likely raise a defect on drupal.org for this issue.

FYI, there is another challenge you may run into in that custom search blocks are not multilingual, so if you want the French search to go to 'recherche/site/[key]' then you will need a bit of code.

One option is to form_alter the custom search block, but if you link directly to the search anywhere else then you will need to custom code it as well. A solution that we found works nicely is to use a path alias for the base (search/site => recherche/site) and then hook_url_inbound and hook_url_outbound to do the redirect when there is an argument present.

```
/**
 * Implements hook_url_outbound_alter().
*/
function mymodule_url_outbound_alter(&$path, &$options, $original_path) {
  global $language;
  $lang = $language->language;
  if (preg_match('|^search/site(/.*)?|', $path, $matches) && ($lang == 'fr') ) {
    $path = !empty($matches[1]) ? 'recherche/site' . $matches[1] : 'recherche/site';
    $options['alias'] = TRUE;
  }
}

/**
 * Implements hook_url_inbound_alter().
 */
function mymodule_url_inbound_alter(&$path, $original_path, $path_language) {
  global $language;
  $lang = $language->language;
  if (preg_match('|^recherche/site(/.*)*|', $path, $matches) ) {
    $path = !empty($matches[1]) ? 'search/site' . $matches[1] : 'search/site';
  }
}
```

**Comment by sylus** [comment]
Sorry I don't see this queue as much as D.O.

However for a solution going forward I am thinking about adding this code to wetkit_search_api:

```

/**
 * Customize custom search blocks.
 */
function wetkit_search_api_update_7101() {
  if (module_exists('custom_search')) {
    $blocks = variable_get('custom_search_blocks_number', 1);
    for ($delta=1 ; $delta<=$blocks ; $delta++) {
      if (variable_get('custom_search_blocks_' . $delta . '_paths', FALSE) == '') {
        variable_set('custom_search_blocks_' . $delta . '_paths', 'search/site/[key]');
      }
    }
    drupal_set_message(t('<a href="@custom_search">Custom Search</a> paths have been updated to: <em>search/site/[key]</em>', array('@custom_search' => url('http://drupal.org/project/custom_search'))), 'status');
  }
}

```

**Comment by sylus** [comment]
Closing legacy issue though there has been some work around improving custom search.
