### ISSUE TITLE
Figure out mobile device support for responsive preview

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#1492]
WxT 2.x will be shipping with Navbar so the complete administrative layer can be leveraged via touch screens and  Responsive Preview so we can immediately see how content will look on a mobile device.

One of the issues though is that we will need to decide which mobile devices we should support in the preview by default?

The following is currently what we will be using:

a) iPhone 4/5
b) iPad
c) Blackberry 10

It is relatively easy via the interface to create additional devices as long as you specify their ppi and resolution but are there any others we should ship with by default?

**Comment by sylus** [comment]
![responsive_navbar](https://cloud.githubusercontent.com/assets/984304/3458634/6edf17f0-0203-11e4-8e45-8c233b8d650d.png)

**Comment by sylus** [comment]
@LaurentGoderre I don't suppose you would know of any other **common** phones that should be supported by default?

**Comment by LaurentGoderre** [comment]
Well there is the whole Android thing, perhaps anything higher than version 4

**Comment by Pacoup** [comment]
Here's a variety of sizes you could add:
http://pacoup.com/run/ti_tester.html

Most recent phones have the exact same display aspect ratio so nothing changes.

**Comment by sylus** [comment]
This is exactly what I wanted looks like a good range. Thx!

**Comment by sylus** [comment]
We settle on a good default range for this :)
