### ISSUE TITLE
Unable to patch wet-boew with patch-001-wet-boew

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#15]
I started with:

Mikes-MacBook-Pro:htdocs mike$ drush make --no-gitinfofile --working-copy https://github.com/wet-boew/wet-boew-drupal/raw/master/distro.build wet-boew-drupal

And got stopped here:

Unable to patch wet-boew with patch-001-wet-boew.                                                                                                                                                            [error]

Any ideas?

**Comment by sylus** [comment]
Hey Mike yeah WET-BOEW actually removed the need for this patch as per this issue: https://github.com/wet-boew/wet-boew/issues/36.

This actually just got fixed today so my bad for not removing the patch.

I am just waiting on this pull request and everything should work again. https://github.com/wet-boew/wet-boew/pull/37

**Comment by sylus** [comment]
Also you will have to definitely pull this done next week as well, I am almost done integrated panopoly's usability improvements. Yay Panels + In place editor!

**Comment by sylus** [comment]
@mgifford according to http://travis-ci.org/#!/wet-boew/wet-boew-drupal it is passing on latest commit. However until wet-boew takes in my pull request you will get a javascript error from wet-boew/src/js/dependencies/resize.js.

Also so you are aware once they take my pull request I will be changing the js I load to point to wet-boew/build/js as I no longer will need to work and patch on the uncompressed js as it will fully work with Drupal! Yay!

**Comment by sylus** [comment]
Pull request has been accepted you should be good to go!

**Comment by mgifford** [comment]
I'm not a panels fan, but Panopoly certainly is doing some interesting stuff.

**Comment by sylus** [comment]
Yeah I wasn't at first either but when combined with Page Manager I am amazed by what can be done. I am mostly trying to follow ctools context workflow as looks to be a major component of drupal 8.

I think Zen will soon be adding panels everywhere support too. http://drupal.org/node/1540948
