### ISSUE TITLE
Working Example Site for Validation Review

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#150]
The WET-BOEW working group has asked for a newer working example site to be set-up so review can happen on the markup etc.

**Comment by openplus** [comment]
Do you wan't us to fire up a fresh instance for them to use? (on our Amazon EC2 instance).

**Comment by sinkinsona** [comment]
@openplus - If you are able to host the WET Drupal example site on one of your EC2
 servers that would be great and help get the project into beta testing.

**Comment by sylus** [comment]
Site setup at wet.openplus.ca
