### ISSUE TITLE
UX and Design improvements feedback (Layouts)

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#1500]
The change layout screen as one of our core workflows needs a bit of UX love. I'd like to use this issue to discuss possible improvements to that screen.

A mockup has been provide by @draganstudios and think it serves as a great foundation for how the layout screen can be improved.

![layout_screen](https://cloud.githubusercontent.com/assets/984304/3460453/531d90a0-0217-11e4-9130-81334868f102.png)

**Comment by aastrong** [comment]
I personally really like this new UX/UI for the layouts, while it is still fairly simple, this show's much more detail with the percentages on the right, a small description as well as the legend. 

Did we discuss possibly having the actual layouts themselves done in CSS + HTML rather than PNG's ?

**Comment by sylus** [comment]
This for the most part has made it in to the 4.x branch.
