### ISSUE TITLE
Manage Fields Undefined Index Notice - Panels

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#158]
Getting the following notice:
Notice: Undefined index: fields in _field_ui_bundle_admin_path() (line 325 of /Users/MyUser/Sites/WET/drupal_wet/modules/field_ui/field_ui.module).

Recreate Notice:
Admin>Structure>Panels>Manage Fieldable Panels Panes>
Select "List" from any of the panes

**Comment by sylus** [comment]
This has been fixed in a recent commit ^_^

**Comment by StephenOTT** [comment]
mmmm.  I guess i need to be pulling the latest commits more often.

**Comment by sylus** [comment]
I am soon going to be adding a dev branch once drupal 7.15 comes out tomorrow. Master will always be stable ^_^
