### ISSUE TITLE
Slider Panel bounding box expanded right

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#159]
When adding the Slider to a panel from the Add Content from the modal window, the Slide bounding box is expanded over modal window to the right.  User must scroll significantly right to see the Add button.

**Comment by sylus** [comment]
The Slider has been replaced with Tabbed Interface which can be added through the tabbed interface button at the bottom of the modal window... All WET plugins will be implemented this way. The old wetkit_slider will be deprecated in next commit ^_^
