### ISSUE TITLE
Drush Make on windows fails

### ISSUE THREAD

**Issue by mantham** [wet-boew/wet-boew-drupal#1604]
I have been trying to use Drush to build the website and everytime I run the command on step 5 (drush make --prepare-install --no-gitinfofile --working-copy wet-boew-drupal/build-wetkit-github.make C:\Websites\wetkit-drupal --yes) the destination folder is not created. I is weird because I don't get any error messages and I can see the files in my drush app folder in windows. I tried to manually copied the downloaded files to my website folder then run Drush CLI but then I get the following error:
Exception: Sorry, the profile you have chosen cannot be loaded. in install_load_profile()

Here are my environment details:
Windows Server 2008
IIS 7.5
Drush 6.0 (I used the windows installer)
GitBash 1.9.4

One thing to note, I have added the --verbose and --debug options and sent the output to a file when running the drush make command and I noticed 2 odd things, I get the following notices:
- Undefined property: DrushMakeProject_Library::$type                     [notice]

-Executing: cd C:/Users/adminuser/AppData/Local/Temp/2/make_tmp_1418842554_5491d1baeeaf7/**build** && GIT_DIR=. git apply --check -p1 C:/Users/adminuser/AppData/Local/Temp/2/make_tmp_1418842554_5491d1baeeaf7/aria-describedby_2.patch --verbose
  'GIT_DIR' is not recognized as an internal or external command,
  operable program or batch file.

Did anyone encounter any issues with Drush 6.0 on windows recently?

**Comment by sylus** [comment]
I think I might have encountered this I'd recommend updating Drush to the latest stable release, and if any other issues persist file an issue in the Drush issue queue.
