### ISSUE TITLE
Drupal 7.15 release

### ISSUE THREAD

**Issue by sinkinsona** [wet-boew/wet-boew-drupal#164]
Drupal 7.15 will be released August 1, 2012 and we will need to update wetkit-core.make to reflect the core update and many patches can be removed from the file as well.  We will also need to perform testing to ensure that nothing is broken by the update.  The release contains security updates and more.  Have a look here to see what changed. http://groups.drupal.org/node/167169/feed

**Comment by sylus** [comment]
Upgraded!
