### ISSUE TITLE
Menu Translation Mode

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#166]
Hello,

I just reinstalled the latest distribution and looking at the menus I can see that the setting for translation mode is set by default to 
"Translate and Localize..."

The problem is that every time I hit the save button this option resets to "No multilingual options for menu items... "  And there is no way to save it back to "Translate and Localize..."

(this means i cannot use the translation on any of the menu items if i save the menu once after initial installation)

This use to work fine in previous versions

Do you guys know why this is and/or do you have a solution to save back to "Translate and Localize..."

Thanks in advance

TRANSLATION MODE
 -->No multilingual options for menu items. Only the menu will be translatable.
 Translate and Localize. Menu items with language will allow translations. Menu items without language will be localized.
 Fixed Language. Menu items will have a global language and they will only show up for pages in that language.

**Comment by sylus** [comment]
I will take a look at this tonight :)

**Comment by sylus** [comment]
Hey I managed to take a look at this and get everything working using translate and localize and not seperate entire menus. All I have to do is figure out how to make it happen during the installation and will commit the code. I anticipate by tomorrow afternoon.

**Comment by ssari** [comment]
Thanks William for taking care of this.
Solange.

**Comment by sylus** [comment]
All fixed up. Please try a fresh drush make + install to verify.

**Comment by ssari** [comment]
Thanks William,
It's working. I tested the menus: mega-menu and mid-footer.

However the issue 155 still remain in the mega-menu.
https://github.com/wet-boew/wet-boew-drupal/issues/155

Regards,

 Solange Sari 

Ottawa - ON

solange_sari@hotmail.com

**Comment by sylus** [comment]
Yeah I'd have to check this further to be sure but I believe this is a js problem with WET-BOEW.

**Comment by sylus** [comment]
Hey @ssari I have fixed the menu order problem as well in recent commit :)
