### ISSUE TITLE
Installation Documentation update

### ISSUE THREAD

**Issue by wilroboly** [wet-boew/wet-boew-drupal#1662]
The installation documentation found on this page: http://wiki.drupalwxt.org/architecture/drush-make/ is out of date. 

<pre>
drush si wetkit wetkit_theme_selection_form.theme=wetkit_omega ....
</pre>

As can be noted here, the theme wetkit_omega does not exist in 4.x-rc1. I would consider adding an extra line which suggests which theme to have when doing this drush command. I ran into difficulty trying to solve some annoying errors on install:

<pre>
You are about to DROP all tables in your 'drupalwxt' database. Do you want to continue? (y/n): y
sh: /tmp/drupal-backup/@DATABASE_@DATE.sql: No such file or directory
Starting Drupal installation. This takes a few seconds ...                                                                            [ok]
WD php: Warning: Cannot modify header information - headers already sent by (output started at                                        [warning]
/usr/share/pear/drush/includes/output.inc:38) in _drupal_bootstrap_page_cache() (line 2446 of
/var/www/html/drupalwxt/webroot/includes/bootstrap.inc).
WD form: Illegal choice wetkit_ember in theme element.                                                                                [error]
WD php: Exception: An illegal choice has been detected. Please contact the site administrator. in install_run_task() (line 414 of     [error]
/var/www/html/drupalwxt/webroot/includes/install.core.inc).
WD php: Warning: Cannot modify header information - headers already sent by (output started at                                        [warning]
/usr/share/pear/drush/includes/output.inc:38) in drupal_send_headers() (line 1251 of
/var/www/html/drupalwxt/webroot/includes/bootstrap.inc).
Exception: An illegal choice has been detected. Please contact the site administrator. in install_run_task() (line 414 of /var/www/html/drupalwxt/webroot/includes/install.core.inc).
Drush command terminated abnormally due to an unrecoverable error.
</pre>

**Comment by lpgascon** [comment]
So what is the correct theme now?

**Comment by sylus** [comment]
I updated the docs @ drupalwxt.github.io mentioning that in 4.x the theme is wetkit_bootstrap.
