### ISSUE TITLE
Can't login to Drupal Admin interface

### ISSUE THREAD

**Issue by lpgascon** [wet-boew/wet-boew-drupal#1681]
I just setup a new environment to install the latest WetKit distro and i'm 90% there.

I've installed the latest Xampp Stack along with Git & Drush latest version and configs (Win2008R2).
I was able to install the Distro and the site is running.
I've modified the PHP.ini with memory_limit = 292M and max_execution time to 300s

When i try to login to the Drupal Admin interface (using the credentials i created during drush install) i get an SQL error

Any ideas on what could be the issue. I have recently re-installed everything as i was having the same issue the first time around and thought i may have made an error during install. But still the same issue.

---

Additional uncaught exception thrown while handling exception.

Original

PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away: SELECT ml._, m._, ml.weight AS link_weight FROM {menu_links} ml LEFT OUTER JOIN {menu_router} m ON m.path = ml.router_path WHERE (ml.link_path IN (:db_condition_placeholder_0)) ; Array ( [:db_condition_placeholder_0] =&gt; demo ) in menu_link_get_preferred() (line 2511 of C:\xampp\www\wetkit\includes\menu.inc).

Additional

PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away: SELECT 1 AS expression FROM {variable} variable WHERE ( (name = :db_condition_placeholder_0) ); Array ( [:db_condition_placeholder_0] =&gt; drupal_css_cache_files ) in variable_set() (line 1009 of C:\xampp\www\wetkit\includes\bootstrap.inc).

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in C:\xampp\www\wetkit\includes\database\database.inc:2171 Stack trace: #0 C:\xampp\www\wetkit\includes\database\database.inc(2171): PDOStatement->execute(Array) #1 C:\xampp\www\wetkit\includes\database\database.inc(683): DatabaseStatementBase->execute(Array, Array) #2 C:\xampp\www\wetkit\includes\database\database.inc(2350): DatabaseConnection->query('SELECT expire, ...', Array, Array) #3 C:\xampp\www\wetkit\includes\lock.inc(167): db_query('SELECT expire, ...', Array) #4 C:\xampp\www\wetkit\includes\lock.inc(146): lock_may_be_available('theme_registry:...') #5 C:\xampp\www\wetkit\includes\theme.inc(449): lock_acquire('theme_registry:...') #6 C:\xampp\www\wetkit\includes\bootstrap.inc(455): ThemeRegistry->set(Array) #7 [internal function]: DrupalCacheArray->__destruct() #8 {main} thrown in C:\xampp\www\wetkit\includes\database\database.inc on line 2171

**Comment by joejoseph00** [comment]
yes, this is caused by your my.cnf settings for mysql.  You'll need to set your max_allowed_packet to at least 16M

**Comment by sylus** [comment]
Guessing this is good now :)
