### ISSUE TITLE
Drush Make instructions issue

### ISSUE THREAD

**Issue by lpgascon** [wet-boew/wet-boew-drupal#1699]
So i was able to install the previous distro with the previous Drush Make instructions (1 month ago) but the new Modified instructions for the latest release are all over the place and not working for me...

I was able by modifying the lines to unpack / create the profile but i'm unable to run this line:

drush si wetkit \
  wetkit_theme_selection_form.theme=wetkit_bootstrap install_configure_form.demo_content=TRUE \
  --db-url=pgsql://drupal:drupal@127.0.0.1:3306/wetkit_db \
  --sites-subdir=default \
  --account-name=admin \
  --account-pass=Password@1234 \
  --site-mail=admin@example.com \
  --site-name='Web Experience Toolkit' \
  --yes;

First off i feel like the db-url should be mysql using the root account as before?

Drush si wetkit doesn't seem to work looking at how the other command lines are ran.

Hopefully someone can troubleshoot this and help modify the instructions to the proper command lines.

Thanks

**Comment by lpgascon** [comment]
Anyone got a lead on this...i'm sorta stuck and can't install the distro anymore.

**Comment by joejoseph00** [comment]
you're using postgresql?

**Comment by joejoseph00** [comment]
if you're trying to use MySQL or compatible then you'll have to change your --db-url

**Comment by lpgascon** [comment]
I have tried all sorts of settings (including changing the --db-url) but it seems like i'm missing something during the unpacking of the distro or where to unpack it... it use to create a "Wetkit" directory with the Drupal core files but now the instructions don't work the same way but the "Drush si" command is still mentioning a Wetkit directory...the error i get relates to not being able to find the wetkit_bootstrap theme. As i said...very confusing.

**Comment by lampson** [comment]
- Are you getting your instructions here?: http://drupalwxt.github.io/architecture/drush-make/ 
- So did you run the drush make command prior to drush site-install?
- Why do you need to have the latest development code?  Usually the package builds at https://www.drupal.org/project/wetkit are sufficient to stay on top of things.  The WET4 branch is released regularly (once per month) and then packaged by drupal.org so the drush make is already done for you.  You just do a site-install via drush or from the web interface afterwards.  So I suggest downloading the 7.x-4.x branch and posting issues on the drupal.org issue queue, and just forget drush make altogether.

If you're really want drush make to work on your system, then check the actual travis build script at:  https://github.com/wet-boew/wet-boew-drupal/blob/7.x-4.x/scripts/travis-ci.sh.  You'll see the drush make and drush si commands being called for postgresql (pgsql) and mysql.  Maybe there's something you missed or wasn't documented.

Then go to checkout the travis build and see if they are passing here: https://travis-ci.org/wet-boew/wet-boew-drupal.  Pick a build and expand the section you're interested in by clicking on that triangle symbol (e.g. https://travis-ci.org/wet-boew/wet-boew-drupal/jobs/77493003)

I hope that helps!

**Comment by joejoseph00** [comment]
Ya, what lampson said, even I being one of the more frequent contributors to the wetkit distro source code do NOT use drush make or drush si for installing the wetkit distro.

While I HAVE done this at least once in the past, I stopped because I could no longer keep up with the build environment changes that Sylus has configured.  He has done a lot of good work to make things easy for us.  That is why I go directly to http://drupal.org/project/wetkit and download the distro from there and install the normal drupal way that everybody else uses.

In fact, I normally now mostly use the git repositories from drupal.org when creating patches for the wetkit distro because it's all there.

Sylus has taken the time to put the source code and build config in TWO places, for various reasons.  The same exact source code is on drupal.org AND github simultaneously.  The full build ends up on drupal.org/project/wetkit where you can just download and extract it like any other drupal distro and install it like any other drupal distro.

You can even try out the wetkit distro here on 
https://simplytest.me
Type "web experience toolkit" in the empty box,  select the "version" and then press "Launch sandbox"

**Comment by lpgascon** [comment]
This is wonderful info. I now understand. Didn't know it was available this way. Thanks again

**Comment by lpgascon** [comment]
Install went fine but i can't access my site...must be a PHP settings or something

Additional uncaught exception thrown while handling exception.

Original

PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away: SELECT ml._, m._, ml.weight AS link_weight FROM {menu_links} ml LEFT OUTER JOIN {menu_router} m ON m.path = ml.router_path WHERE (ml.link_path IN (:db_condition_placeholder_0)) ; Array ( [:db_condition_placeholder_0] =&gt; demo ) in menu_link_get_preferred() (line 2511 of C:\xampp\www\wetkit\includes\menu.inc).

Additional

PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away: SELECT 1 AS expression FROM {variable} variable WHERE ( (name = :db_condition_placeholder_0) ); Array ( [:db_condition_placeholder_0] =&gt; drupal_css_cache_files ) in variable_set() (line 1009 of C:\xampp\www\wetkit\includes\bootstrap.inc).

Uncaught exception thrown in shutdown function.

PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away: DELETE FROM {semaphore} WHERE (value = :db_condition_placeholder_0) ; Array ( [:db_condition_placeholder_0] =&gt; 195714850855e46ff5d1d777.95686542 ) in lock_release_all() (line 269 of C:\xampp\www\wetkit\includes\lock.inc).

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in C:\xampp\www\wetkit\includes\database\database.inc:2171 Stack trace: #0 C:\xampp\www\wetkit\includes\database\database.inc(2171): PDOStatement->execute(Array) #1 C:\xampp\www\wetkit\includes\database\database.inc(683): DatabaseStatementBase->execute(Array, Array) #2 C:\xampp\www\wetkit\includes\database\database.inc(2350): DatabaseConnection->query('SELECT expire, ...', Array, Array) #3 C:\xampp\www\wetkit\includes\lock.inc(167): db_query('SELECT expire, ...', Array) #4 C:\xampp\www\wetkit\includes\lock.inc(146): lock_may_be_available('schema:runtime:...') #5 C:\xampp\www\wetkit\includes\bootstrap.inc(433): lock_acquire('schema:runtime:...') #6 C:\xampp\www\wetkit\includes\bootstrap.inc(455): DrupalCacheArray->set(Array) #7 [internal function]: DrupalCacheArray->__destruct() #8 {main} thrown in C:\xampp\www\wetkit\includes\database\database.inc on line 2171

Uncaught exception thrown in session handler.

PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away: SELECT 1 AS expression FROM {sessions} sessions WHERE ( (sid = :db_condition_placeholder_0) AND (ssid = :db_condition_placeholder_1) ); Array ( [:db_condition_placeholder_0] =&gt; dPojWKBznDPwW_BvyibgjXLh39gO7RwLHCOay_hY6Nk [:db_condition_placeholder_1] =&gt; ) in _drupal_session_write() (line 209 of C:\xampp\www\wetkit\includes\session.inc).

**Comment by joejoseph00** [comment]
Start by increasing your max_allowed_packet size variable to about 16M and this will solve the mysql server gone away error. Setting is in etc/my.cnf for your mysql server settings

**Comment by lpgascon** [comment]
Worked! Wonderful!

**Comment by joejoseph00** [comment]
Works every time
