### ISSUE TITLE
Notice: Undefined index: field in _fences_theme

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#17]
Just after the install

Notice: Undefined index: field in _fences_theme() (line 30 of /Users/mike/shared/htdocs/wet-boew-drupal/profiles/webexp/modules/contrib/fences/fences.admin.inc).
x
Notice: Undefined index: field in _fences_theme() (line 32 of /Users/mike/shared/htdocs/wet-boew-drupal/profiles/webexp/modules/contrib/fences/fences.admin.inc).

**Comment by sylus** [comment]
Yeah I have made an issue about this a few weeks ago: https://drupal.org/node/1561244

Once you clear cache it goes away but should not present itself in the browser.

**Comment by mgifford** [comment]
Right, thanks!

**Comment by sylus** [comment]
Fixed with patch in make
