### ISSUE TITLE
Minor CSS bug (font declaration)

### ISSUE THREAD

**Issue by sboots** [wet-boew/wet-boew-drupal#170]
Just a tiny thing, in a few spots there's a declaration for,
`font: bold 12px/32px 'Open Sans', 'Lucida Sans', 'Lucida Grande',  verdana sans-serif;`
eg. for the "Save" buttons on node edit pages.

There's a comma missing between verdana and sans-serif, so if you don't have the other fonts installed, you get Times. Bad times!  : P

So minor it's almost not worth bringing it up, but just in case.

Rock on!
Sean

**Comment by sylus** [comment]
Closing this issue as corresponding issues have been filed a while back at the upstream modules.
