### ISSUE TITLE
Upgrading modules

### ISSUE THREAD

**Issue by lpgascon** [wet-boew/wet-boew-drupal#1713]
I've updated some modules by mistake and now i get the following error trying to launch my site:

Fatal error: Cannot redeclare field_collection_entity_uuid_load() (previously declared in C:\xampp\www\wetkit\profiles\wetkit\modules\contrib\field_collection\field_collection_uuid\field_collection_uuid.module:14) in C:\xampp\www\wetkit\profiles\wetkit\modules\contrib\uuid\uuid.core.inc on line 365

Any idea how i can revert back or migrate my db to a new install?

**Comment by sylus** [comment]
You probably have an identical field_collection module in sites/all/modules as well as profiles/wetkit/modules/contrib. Try to remove the one in sites/all/modules. If you have a db backup which you should whenever updating modules then can just revert to that one.

**Comment by sylus** [comment]
Guessing that solved the issue! Let me know if missed anything, thx!

**Comment by lpgascon** [comment]
In the end I rebuilt the site (it was only at an early phase). I will make sure I backup my db more often. (and not do the module upgrades)

Thanks

**Comment by sylus** [comment]
Yeah backups often are key. You can of course do module updates yourself (often in the case of security releases). The distro tries to stay up to date but of course for security I can understand a manual upgrade of a module. The best advice I can give is check our *.make files under profiles/wetkit/custom and see if any patches are being used for the module in question. Always here to help!
