### ISSUE TITLE
MegaMenu Link in new Tab

### ISSUE THREAD

**Issue by lpgascon** [wet-boew/wet-boew-drupal#1717]
Any easy way of forcing the Mega-Menu to open certain links in a new Window/Browser Tab?

Can the mega-menu items also contain icons or only text?

Thanks

**Comment by sylus** [comment]
We align to how WxT renders there menus so if it is supported by them we can support it as well. So i might ask that question on the wet-boew repo.

As for the mega menu items the recent dev has proper support for <nolink> and can also use the icon_menu module for glyphicon support.

**Comment by lpgascon** [comment]
Thanks for the feedback. Opening menu links in new tabs would be really useful for external links.

I’ve installed the menu_icon module but doesn’t seem to show up in my menu items config yet. I’ll try to troubleshoot this and play with it.

Thanks

**Comment by lpgascon** [comment]
menu_icon module screws up with the CSS of the menu items row spacing and it only does background images (no inline). But it was worth a try.

**Comment by sylus** [comment]
Hey sorry not menu_icon but icon_menu. The icon menu module is a submodule of: https://www.drupal.org/project/icon . We use that module with our bootstrap theme in the 4.x branch. This functionality is only in 4.x though.

**Comment by lpgascon** [comment]
icon_menu got it. Seems to work! Now i only need to figure out how i can create personalized icons as i don't need a bank of icons. (we have our own)

**Comment by sylus** [comment]
You should use the fontcustom library to convert your icons to a format support by icon_menu. Then it is just a simple hook function to get it registered. http://fontcustom.com/

**Comment by lpgascon** [comment]
Thanks, this is a bit too much work to get it working as i'm running the distro in a Windows Environment. I found some windows converter that may work but the instructions and scripting is quite intense potentially unstable. Hopefully there will be a better drupal module for customized icons in the future.

**Comment by sylus** [comment]
fontcustom isnt a drupal module just a way to get your images to use proper glyphicons workflow. You can just run the tool in a linux environment separately then copy the build to your windows box or I am sure windows has a tool that can accomplish the same thing.
