### ISSUE TITLE
Migrate Demo Content

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#172]
In the WetKit Web Usability Settings - Migrate, when the buttom Migrate Demo Content is pressed an error message is displayed: 

Fatal error: Class 'Migration' not found in D:\Ampps\www\wet\profiles\wetkit\modules\apps\wetkit_web_usability\wetkit_web_usability.admin.inc on line 45

**Comment by sylus** [comment]
Yeah I should remove this or make it only show up when app is download (wetkit_migrate) Thanks :)

**Comment by sylus** [comment]
This has been fixed and removed for now :)
