### ISSUE TITLE
Web applications: Date Modified field

### ISSUE THREAD

**Issue by sarasuri** [wet-boew/wet-boew-drupal#1739]
One of our clients wants to use the date and version in the "Date Modified" field (e.g. Date modified: 2015-10-01 - Version 3.0) for their applications as it will help them to know the  date when it was modified and the version number. 

These non-login Web applications will be integrated into Canada.ca. 
Can we use both  on the application pages? The "Technical specifications for the Web and mobile presence" says "The date modified is removed where a version identifier is used."

Is there be any implications on using both when the applications are moved to MWS?
Thanks,

**Comment by sylus** [comment]
I might need more information, the date modified field should only contain the date why is the version included in that information?

For Drupal we have the following rules:

a) Dynamic Pages will always have a date modified showing the date the page was generated
b) Node Pages (Content Types) will always have the date modified using the date when the node was created / last modified

Both comply with the technical specifications but I can't speak on any implications.

**Comment by sarasuri** [comment]
I realised that I asked the question in the wrong section. Sorry about that. Thank you for your reply.
