### ISSUE TITLE
Metadata  - TBS Standards

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#174]
Following:
http://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=18909&section=text
Appendix C,
The Web Resource Discovery metadata fields have not been provided as standard metadata options.
Assume this is a feature that has not bee added as of yet?

**Comment by StephenOTT** [comment]
Has anyone implemented the full TBS requirements? from Appendix C?
http://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=18909&section=text

And has anyone implemented the Audience scheme?
http://www.collectionscanada.gc.ca/webarchives/20071207091037/www.tbs-sct.gc.ca/im-gi/mwg-gtm/aud-aud/docs/2003/schemfinal/schemfinal_e.asp

**Comment by StephenOTT** [comment]
Also as a note section 5 of appendix C:

Populating the Subject property with terms from a value domain using:
The Government of Canada Core Subject Thesaurus, as the preferred source; or
A bilingual and publically available thesaurus that complies with the ISO standards 2788, Guidelines for the establishment and development of monolingual thesauri, and 5964, Guidelines for the establishment and development of multilingual thesauri, and that is registered with Library and Archives Canada or the Dublin Core Metadata Initiative; or
Another type of bilingual and publically available controlled vocabulary registered with Library and Archives Canada or Dublin Core Metadata Initiative.

Here there been any groups that have implemented the thesaurus approach?  I think the best option would be to allow people to link to a URL. That way we could use the current goc thesaurus but also generate a fork from the current base to support more specific keywords that may not be apart of the master dataset.

**Comment by sylus** [comment]
Hey @StephenOTT thanks for all of the resources I have a working draft coming through the pipe should be ready by Thursday for initial eval.
