### ISSUE TITLE
Menu setup - page hierarchy UX issue

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#175]
When you are creating the page hierarchy for menus, the user must use the "drop down menu" to select the placement for the page/node in the menu hierarchy.  This because troublesome for sites that can have a deep site structure (yes, preferably we want a flat structure). 
A Tree like menu should be offered instead of the drop down menu in the menu configuration to make it easier to set up the hierarchy.

Thanks

**Comment by sylus** [comment]
At this moment not much can be done other then perhaps using the content menu module which I am looking into. Can possibly work on something for the next release.
