### ISSUE TITLE
WxT Drupal Working Group

### ISSUE THREAD

**Issue by sinkinsona** [wet-boew/wet-boew-drupal#176]
The [Wxt Drupal project](https://github.com/wet-boew/wet-boew-drupal) is looking for people that want to be part of our working group metings.  These people will be involved in the decision making, direction and vision of the project.  We are going to try to meet once a month starting in September 2012 in Ottawa, Ontario.  If you are interested in participating please let us know who you are by registering here: https://github.com/wet-boew/wet-boew-drupal/wiki/WxT-Drupal-Working-Group

**Comment by sinkinsona** [comment]
I have sent out the meeting request for the WxT Drupal Working Group meeting that will be hosted at City Hall on September 25th from 1:00 pm to 3:00 pm.  If you had signed up for the meeting and not received an invite please let me know.  Also if you would be interested in participating add your name to the list and I will forward you the invite.

https://github.com/wet-boew/wet-boew-drupal/wiki/WxT-Drupal-Working-Group

Thanks and looking forward to collaborating with everyone !

**Comment by StephenOTT** [comment]
Draft Minutes for Sept 25 Working Group have been posted
https://github.com/wet-boew/wet-boew-drupal/wiki/WxT-Drupal-Working-Group

**Comment by StephenOTT** [comment]
Minutes for Sept 25 working group have been made final

**Comment by StephenOTT** [comment]
Next working group meeting will be at the Colonel By Room at Ottawa City Hall.  November 16, 2012.  1:00pm to 3:00pm.  There will be public Wifi.  - See #486 for more details

**Comment by StephenOTT** [comment]
Looking to have the next working group meeting on January 24, 2013 1pm to 4pm.  See post #664

**Comment by StephenOTT** [comment]
Anyone have issues if we move this meeting to January 25, 2013 1pm to 4pm?
That is moving it from the Thursday to the Friday

**Comment by joejoseph00** [comment]
Friday Jan 25, 2013 sounds good.

**Comment by StephenOTT** [comment]
Date has been moved to Jan 25.  Please see #664

**Comment by StephenOTT** [comment]
Minutes and presentation have been posted for the working group:
https://github.com/wet-boew/wet-boew-attachments/tree/master/Working%20Groups/Drupal%20Variant/Meetings/January%2025%202013

**Comment by StephenOTT** [comment]
Looking to Book the next working group meeting on March 22, 2013 1 to 4pm.

Anyone see any issues with this date and time?

**Comment by StephenOTT** [comment]
Stays open for people to monitor working groups events

**Comment by sylus** [comment]
Again closing this as the website is the best place for these type of noticiations.
