### ISSUE TITLE
"Dashboard" broken

### ISSUE THREAD

**Issue by MichaelClift** [wet-boew/wet-boew-drupal#177]
When I click on the "Dashboard" link I get:

Exception: Manifest: http://wetkitappdev.devcloud.acquia-sites.com/app/query/WetKit%20App%20Server Forbidden in apps_apps() (line 91 of /srv/www/htdocs/profiles/wetkit/modules/contrib/apps/apps.manifest.inc).

How do I fix this?

**Comment by sylus** [comment]
Are you behind a firewall? With Drupal 7.15 _being updated tonight_ you can specify your proxy options. Though for now you could just disable this app in wetkit.profile. I will take a further look into this.

The Dashboard itself is not broken though? If it still works might change the title to more accurately reflect.

Thanks for the issue! :)

**Comment by MichaelClift** [comment]
My dev server is behind a firewall.  My production server will not be able to make outgoing requests (proxy or NAT).

The Dashboard is completely non-functional, rendering only the error message and "The website encountered an unexpected error. Please try again later. "

> > > William H reply@reply.github.com 2012-08-01 12:42 >>>
> > > Are you behind a firewall? With Drupal 7.15 _being updated tonight_ you can specify your proxy options. Though for now you could just disable this app in wetkit.profile. I will take a further look into this.

The Dashboard itself is not broken though? If it still works might change the title to more accurately reflect.

Thanks for the issue! :)

---

**Comment by sylus** [comment]
Hmm I might disable the outwards app server till Shared Services hosts the App Server for us which will be done within the next 2 weeks. Out of curiosity will you guys be able to pull from Shared Services hosted servers?

**Comment by MichaelClift** [comment]
I don't know for certain.  The server is hosted at PWGSC currently, so it may be feasible.  I'm not sure what the implications are to our Threat Risk Assessment would be.

> > > William H reply@reply.github.com 2012-08-01 12:50 >>>
> > > Hmm I might disable the outwards app server till Shared Services hosts the App Server for us which will be done within the next 2 weeks. Out of curiosity will you guys be able to pull from Shared Services hosted servers?

---

**Comment by sylus** [comment]
Hmm I don't know to much about this but will talk to a few people over there. I do know they will be performing thorough security review on every apps that will be hosted over there. It is relatively important though to us that all instances using wetkit drupal can all see the apps server as there are going to be some awesome apps coming in there. (Proactive Disclosure, Organic Groups, Migration, Search, etc)

**Comment by sylus** [comment]
Dashboard has been replaced with admin views so no longer a problem :)
