### ISSUE TITLE
Warning message while running third step of drush update command

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#178]
I have ran the third step of the Update process layed out in the primary Readme.md file.
The following response is given in Terminal (mac, localhost)

Per site policy, you must add a secret --token complete this command. See                     [warning]
examples/policy.drush.inc.  If you are running a version of drush prior to 4.3 and are not
sure why you are seeing this message, please see http://drupal.org/node/1024824.
No database updates required                                                                  [success]
Finished performing updates.    

Is this the expected behaviour?
If so, the Readme should be updated to reflect the warning message as many users will wonder if the process was successful.

**Comment by ssari** [comment]
I got the same message.
Any how, the updates were made.

**Comment by sylus** [comment]
It looks like your using the /profiles/wetkit/scripts/drush/policy.drush.inc commands, these are example scripts that have to be tailored to your setup. Did you manually set this up or was it auto detected? If it was auto detected I will try to find a way to disable it so has to be manually configured and not instantly used.

**Comment by sylus** [comment]
Fixed!
