### ISSUE TITLE
Content - Permalink: .... magically generated

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#179]
I'm afraid we have problems with the permanent link generated automatilly.  
I added couple basic pages, and the title wasn't converted to page name.  
All the existing pages have the links as expected.
Any ideas?

**Comment by sylus** [comment]
Hmm could you give me a step by step to reproduce? ^_^

**Comment by ssari** [comment]
+Add Content
Basic page
add title --> My page
**\* Permlink: http://domain/<magically generated>
      normaly we don't add anything here

when this page is created, the system generates the following permanent link:
     http://domain/my-page.

but now, it shows only the node id, for instance:
     http://domain/node/8

Hopefully, it explains.

Thanks.

 Solange Sari 

Ottawa - ON

solange_sari@hotmail.com

**Comment by ssari** [comment]
Comparing with the WebExp version I figured it out.

In the previous version, each content (node)  has a configuration option:  
 "URL path settings"    Automatic alias
where by default the option "Generate automatic URL alias"  is checked .

Now, in the new WetKit, each content has the option  "Generate automatic URL alias"  unckecked, and additional message " Uncheck this to create a custom alias below...."  

Would it be possible to generate automatic URL alias by default? In other words, keep the option  "Generate automatic URL alias"  ckecked,

Thanks,

**Comment by sylus** [comment]
I think this is fixed in recent commit can you take a look again? :) Please reopen if still persists!
