### ISSUE TITLE
Menus Showing Both English and French Simultaneously

### ISSUE THREAD

**Issue by kristremblay** [wet-boew/wet-boew-drupal#1796]
I went into `structure/menu` and clicked on `Mega Menu` to look around.  Once I left, both the english and french links for the Mega Menu were across the top of the page.  This has happened before when I tried reordering menu items, is this something I've done wrong or a bug?

![Menu](https://cloud.githubusercontent.com/assets/7587183/12595485/c11ba2e2-c438-11e5-850a-c3e4fa9fcc49.png)

**Comment by mxlav** [comment]
Apparently this is known bug in the i8ln module. I've also encountered this issue.
See issue on WETKIT https://www.drupal.org/node/2656160

**Comment by kristremblay** [comment]
Has anyone found a workaround?  As per that bug report,

> It only does this when you are on a node/edit or menu edit link page. Clear cache on any other page and will be fixed.  

I have cleared my cache from the front page and any number of sub pages, and it is still the same.  Did I misinterpret his response?  Did clearing the cache work for you?

**Comment by sylus** [comment]
Try going to: admin/config/development/performance

And clearing both caches + wxt caches, at that point it should defnitely not be present.
