### ISSUE TITLE
Deployed content does not preserve menu link.  New menus do not appear in View for deploy.

### ISSUE THREAD

**Issue by kristremblay** [wet-boew/wet-boew-drupal#1797]
If I create a `basic page` (for example) and choose to deploy it, that works great.  However, if I assign it a menu link, even if that menu exists on the destination server, the destination content does not have a menu link associated with it.

It seems that you cannot build a menu on stage and deploy that menu either.

**Comment by sylus** [comment]
Menu Links do deploy when the node deploys but they shouldn't exist on the destination side ahead of time. It gets deployed with the node through the entity dependency module. Certain other types of menu links that aren't linked explicitly to a node (using node/*) will have to be manually deployed either through shared_content interface or the new deployment interface.

**Comment by kristremblay** [comment]
I'm sorry, Will, I must be incredibly dense.  I cannot find the shared_content interface to save my life.  As far as deploying a node is concerned, I am still unable to find a reason why the node will deploy but the menu link disappears into the universe.

**Comment by kristremblay** [comment]
I think this likely is the root of the problem, but I'm not sure what to do about it :/

> Notice: Undefined property: stdClass::$mlid in entity_menu_links_linked_entity() (line 220 of /web/sites/../docroot/profiles/wetkit/modules/contrib/entity_menu_links/entity_menu_links.module).

**Comment by kristremblay** [comment]
Upon further investigation, I've been able to get this working!  However, the View issue persists, and even with Shared Content enabled, menu links are not auto-deploying.  I had to make a change to the view in order to get my links to appear.

It seems that items in the view will not appear if a language is not specified.  Is there a way around this?

**Comment by sylus** [comment]
Hmm might have something to do with code here:

http://cgit.drupalcode.org/wetkit_deployment/tree/wetkit_deployment_source/wetkit_deployment_source.views.inc#n45

**Comment by sylus** [comment]
Guessing this is good now if any other issues please file @ drupal.org/project/wetkit

Thx!
