### ISSUE TITLE
Strick Warning Message - Slider/Tabbed Interface

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#180]
Got the Following message after uploading image to Slider/Tabbed interface:

Strict warning: Only variables should be passed by reference in wetkit_magic_form_alter() (line 191 of /Users/MyUser/Sites/OttawaWET/drupal_wet/profiles/wetkit/modules/apps/wetkit_magic/wetkit_magic.module).

Same message appears after removing uploaded image.

Also is there any default image restrictions on the app?  Auto-crop, resize, etc?

**Comment by sylus** [comment]
Hmm I have seen this error but on recent commit I no longer see it, will do more evaluation. Also will be upgrading to Drupal 7.15 tonight and baking in entity translation for our fieldable panels panes. Will see if error persists after all that. :)

**Comment by StephenOTT** [comment]
10-4

This was on a fresh clean install about 30 min ago

**Comment by StephenOTT** [comment]
Just ran fresh install.
Still getting the error when selecting the upload button for the image.

**Comment by StephenOTT** [comment]
Getting the following ajax error when user types in a title for a image but does not supply an image:

An AJAX HTTP request terminated abnormally.
Debugging information follows.
Path: /en/panels/ajax/ipe/edit-pane/panel_context%3Apage-wetkit_demo_front%3Apage_wetkit_demo_front_panel_context/5/form
StatusText: n/a
ResponseText: 
City
Error
Error message   Notice: Trying to get property of non-object in file_field_presave() (line 220 of /Users/myuser/Sites/OttawaWET/drupal_wet1/modules/file/file.field.inc).  Strict warning: Creating default object from empty value in file_field_presave() (line 221 of /Users/myuser/Sites/OttawaWET/drupal_wet1/modules/file/file.field.inc).  Notice: Undefined property: stdClass::$uri in file_save() (line 570 of /Users/myuser/Sites/OttawaWET/drupal_wet1/includes/file.inc).  Notice: Undefined property: stdClass::$uri in file_entity_file_presave() (line 14 of /Users/myuser/Sites/OttawaWET/drupal_wet1/profiles/wetkit/modules/contrib/file_entity/file_entity.file.inc).  PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'uri': INSERT INTO {file_managed} (filemime, filesize, status, timestamp, type, uuid) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5); Array
(
[:db_insert_placeholder_0] =&gt; application/octet-stream
[:db_insert_placeholder_1] =&gt; 0
[:db_insert_placeholder_2] =&gt; 1
[:db_insert_placeholder_3] =&gt; 1344004628
[:db_insert_placeholder_4] =&gt; application
[:db_insert_placeholder_5] =&gt; 68df814f-4713-f874-b14b-2dc7091da7a0
)
in drupal_write_record() (line 7036 of /Users/myuser/Sites/OttawaWET/drupal_wet1/includes/common.inc).  
The website encountered an unexpected error. Please try again later.      

ReadyState: undefined

**Comment by sylus** [comment]
This has been fixed a while back :)
