### ISSUE TITLE
Upgrade to Drupal WxT 4

### ISSUE THREAD

**Issue by Nasr2013** [wet-boew/wet-boew-drupal#1817]
Hello All,
I am looking guideline or documentation to upgrade site from Drupal WxT 3 to Drupal WxT 4
Much appreciated for your help
Thank You, Nasr

**Comment by mxlav** [comment]
The only documentation i know of is here http://drupalwxt.github.io/architecture/release-cycle/ .

You can also find some documentation on the issue queue here https://www.drupal.org/project/issues/wetkit?categories=All . Concerning theme and menu issues when upgrading.

Here are some of the steps I've been using while testing the upgrade process
- change site theme to bartik & admin theme the wetkit ember
- disable any omega subtheme and the disable the wetkit omega theme
- perform any backups such as folder structure and DB
- extract desired version of wetkit 
- copy sites folder from current site
- i attempted to log in at this point and was having issues with panels (https://www.drupal.org/node/2652188). Got around the issues buy running module registry_rebuild
- log in, clear cache
- run update.php
- revert wetkit features

Note:
- any omega sub theme would now need to be "ported" over to a new bootstrap subtheme
- might need to rebuild mega menu

**Comment by sylus** [comment]
Lets file this one over at drupal.org queue. drupal.org/project/wetkit.
