### ISSUE TITLE
WetKit Layout changes?

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#182]
What specific changes were made to the WetKit layout variations?

Were these just the column widths?

**Comment by sylus** [comment]
The markup was changed for the WetKit layout variations. More work needs to be done on adding the other litany of layouts and apply the conditional css.

For a complete example of how a layout is built with conditional css look at: /profiles/wetkit/themes/adaptivetheme/at_core/layouts/panels/five_5x20

Ours are located at:
/profiles/wetkit/themes/wetkit_adaptivetheme/custom_panels/*

We will be removing all of the default Panopoly ones as not really responsive.

**Comment by StephenOTT** [comment]
Is the plan to support all of the response layouts that are supplied as part of AT beyond the CLF layout?
