### ISSUE TITLE
Can't Exclude Demo Content (Drush install)

### ISSUE THREAD

**Issue by kristremblay** [wet-boew/wet-boew-drupal#1822]
`install_configure_form.demo_content=FALSE` Does not work when trying to install WxT 4.x from drush.  Is there an alternative method I am missing?

**Comment by mxlav** [comment]
try not using that parameter at all
https://www.drupal.org/node/2099395

**Comment by kristremblay** [comment]
Wow that was fast...thanks!  I'm installing now, we will see if that does the trick.

**Comment by kristremblay** [comment]
Worked!  Perfect, thank you.
