### ISSUE TITLE
Language Toggle not visible on mobile when using the "Internet" as base theme. 

### ISSUE THREAD

**Issue by aastrong** [wet-boew/wet-boew-drupal#1823]
_Please let me know if this issue is not in the correct location,_

I have noticed that when I do a base Drupal WxT install ( v4.6 ) - and I set the base theme to be "Internet" - when I shrink to mobile and click on the hamburger to open up the menu - the menu that was at the top right corner of the site, including the language toggle, is not in the mobile view. 

Is this something that was done by design, or possibly something that was missed ( im assuming the later of the 2 ). It seems to be there in all other variations of the base themes. 

Thanks.

**Comment by sylus** [comment]
Can you file this over at drupal.org/project/wetkit. It will let me correlate changelog with issue.

**Comment by aastrong** [comment]
Created case over here - https://www.drupal.org/node/2696227
