### ISSUE TITLE
Varnish + Expire + Deploy (continued from Drupal.org)

### ISSUE THREAD

**Issue by kristremblay** [wet-boew/wet-boew-drupal#1826]
For some reason drupal.org (https://www.drupal.org/node/2693251) won't let me post :/  If you notice the comment numbers you can see it is skipping numbers...those are my comments.

---

<code>  
   Expiration was executed for the next URLs:

```
URL: http://prod.example.com/en
Wildcard: false
Expired object: node
--------
URL: http://prod.example.com/en/demo
Wildcard: false
Expired object: node
--------
URL: http://prod.example.com/en/node/4
Wildcard: false
Expired object: node
--------
URL: http://prod.example.com/en/content/very-basic-page
Wildcard: false
Expired object: node
--------
```

</code>

Correct me if I'm wrong, but that looks like it IS expiring the page I just deployed (the last one, very-basic-page).  However this isn't actually expiring it in varnish it would seem.

**Comment by sylus** [comment]
Yeah this sounds exactly like problem I was having, will take a look this week, lets keep this issue tracked over at: https://www.drupal.org/node/2693251
