### ISSUE TITLE
Fresh Install, "Entities Deployment" Pane Broken

### ISSUE THREAD

**Issue by kristremblay** [wet-boew/wet-boew-drupal#1830]
Good afternoon, time to start the week off with a bang.

After installing fresh and enabling deployment-related modules, I am presented with the following at the bottom of the deploy page:

![image](https://cloud.githubusercontent.com/assets/7587183/14124245/c206511a-f5c1-11e5-995e-9e7d2154f160.png)

The list shows up for a fraction of a second and then vanishes.

Would this have anything to do with changes that were committed over the weekend?

**Comment by kristremblay** [comment]
At first I thought it was a firefox thing because it showed up properly in chrome...however I reloaded the page in chrome and THERE IT IS AGAIN.  Drupal is gaslighting me.

**Comment by kristremblay** [comment]
My colleague just tried it out and had the same experience.  It seems to be linked to the session in some way, as it will load correctly on first view, but fails on subsequent loads unless the browser is closed and restarted.  _UPDATE:_ This works BUT if you click on any of the tabs it breaks as well, not not working perfectly even under the described circumstances.

**Comment by sylus** [comment]
Lets close this issue and just focus over on the issue @ https://www.drupal.org/node/2697989
