### ISSUE TITLE
(Meta) Panelizer Broken Node Powered Pages

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#184]
Follow these steps:
1. Go to WetKit Demo Page
2. Select Customize this page
3. Drag the configure tabs pane up above the pane that it sits below.
4. Select Save.

After reload the configure tab should not even appear any more.  If you go back into customize, the pane appears broken.
If you select configure for the broken pane. then select ok.  then save the configuration. When the page reloads, All content on the page is gone.  Going back into customize shows all the panes have been removed or deleted or lost.

**Comment by StephenOTT** [comment]
It looks like doing any configuration change on the "Configure tabs" where the New Draft, Moderate, etc options are, causes the entire pane to go blank.

After the first save, if you reopen the same configuration screen for the Configure Tabs pane, do not make any changes, and just select save, and then save configuration, the entire node/page deletes all panes/are blank

**Comment by sylus** [comment]
Thanks for catching this you are 100% correct this is an issue with workbench moderation. I was super worried at first but it is much better this is only contained to workbench powered screens.

We are actually using a patch to get this to properly work and the node reference is here: http://drupal.org/node/1285090

**Comment by sylus** [comment]
[#1572202: Panelizer default content and IPE, without page refresh panel is emptied on second save](http://drupal.org/node/1572202)
[#1520492: Saving a change in the IPE results in a blank page, fine after refresh, no error](http://drupal.org/node/1737766)

**Comment by sylus** [comment]
I believe this is now all fixed in latest updates! The title and tabs will still disappear momentarily but the panelized pages will no longer disappear.

Will file a seperate issue for missing areas that temporarily disappear
