### ISSUE TITLE
Consistant Interface Language

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#185]
Unless i am missing the options.....
There should be a option to set a consistent interface language.
Current interface changes to the language that the content is set too.  User should be able to set a language that would be the consistent language that the interface remains in for that specific user.  

Many content providers could very possibly only speak a single language, but be posting translated content.

**Comment by joejoseph00** [comment]
Hi @StephenOTT, I don't think that will be possible however, take note, there is work underway to bring in an interface created by UOttawa (form) that allows side-by-side english-français data entry.  This would allow one to create content for both languages from the same page.  We do have this in a custom one-off form for our main business requirement using D6, the problem we had with our implementation is that it was a bit of a cludge customisation and requires that we apply and manage numerous patches every time we want to update core (whenever we decide we need to update our core for security reasons usually).   I'm hoping that the D7 version created by UOttawa is more modular and hopefully is it'self localisable.

**Comment by StephenOTT** [comment]
I have used some modules in the past that allow the user to set a consistent language of choice for the interface.  The issue you bring up about the patching is from using one of these modules?

The issue that people bring to me is that, "just because i am inputting French content, the interface should not have to be in french", and vice versa for French interface inputting english.

Would see this as a very common complain from content contributors that are mainly unilingual but have had their content translated, and/or content contributors who understand the interface terminology in english but do not necessarily know the interface language in french (or again, vice versa for knowing the French interface better than english).

**Comment by joejoseph00** [comment]
On our D6 CMS, for a specific content type (our main content type that we have about 60000 nodes), we have an english-french bilingual data entry form , the whole interface is in english, when using it in french mode , it breaks.  But it does allow both languages to be inputted from one single form (side-by-side).

For D7, the University of Ottawa has gratiously created a similar interface (side-by-side) that is probably better than ours (IE hopefully it doesn't break in french), however I have not tested it, and apparently @sylus is in the process of acquiring this interface and attempting to migrate it into this distro.

**Comment by joejoseph00** [comment]
Please refer to issue #86

**Comment by sylus** [comment]
Closing this issue as #86 exists
