### ISSUE TITLE
Ajax error while creating view

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#186]
Steps:
1. Create a view
2. select save and edit.
3. following ajax error should appear:

An AJAX HTTP error occurred.
HTTP Result Code: 500
Debugging information follows.
Path: /en/admin/structure/views/view/residents_topics/preview/page/ajax
StatusText: error
ResponseText: EntityMalformedException: Missing bundle property on entity of type taxonomy_term. in entity_extract_ids() (line 7590 of /Users/stephenrussett/Sites/OttawaWET/drupal_wet/includes/common.inc).

**Comment by sylus** [comment]
This error is no longer present or can't be reproduced :) Not sure what fixed it but looks good. Please reopen if problem persists.
