### ISSUE TITLE
Undefined index: SERVER_ADDR in webexp_apps_servers_info()

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew-drupal#19]
IIS does not have a server variable called SERVER_ADDR.  When installing, and in some operations (such as clearing the cache) the following notification is shown:

Notice: Undefined index: SERVER_ADDR in webexp_apps_servers_info() (line 193 of D:\internet\dmz_drupal\profiles\webexp\webexp.profile).

I've fixed this after installation by changing line 193 to:
'server_ip' => gethostbyname($_SERVER['SERVER_NAME']),

**Comment by sylus** [comment]
Recent code commit I think negates the need for this as relevant line is commented out.

However in case code does come back should add it.

I can reroll this pull request to put it into the new codebase but won't apply as is due to changes.
