### ISSUE TITLE
Scope of the official bilingual documentation

### ISSUE THREAD

**Issue by LeeHunter** [wet-boew/wet-boew-drupal#190]
It would be useful to know the planned scope of the official bilingual documentation. Is it all documentation related to this project or just the more public facing elements like maybe overview, installation guide, descriptions of apps in the app store etc? Are there certain things that are higher priority than others?

I've started a doc plan here https://github.com/wet-boew/wet-boew-drupal/wiki/Documentation-Plan which is intended to help get a sense of the entire documentation effort (although some of this probably won't be ready for quite a while).

**Comment by StephenOTT** [comment]
Can do the translation.  Just let me know.

**Comment by joejoseph00** [comment]
@StephenOtt @LeeHunter , I've started the french wiki, added about a half dozen documents translated and also updated another half dozen placeholders and linked the english wiki side for those dozen documents.  Please feel free to continue my work, does the City of Ottawa have some spare cycles?

I'll do some more work on this myself but there is quite a bit of documentation , technical .

I've used termium to use standardized terminology as much as possible.

https://github.com/wet-boew/wet-boew-drupal/wiki/Accueil

**Comment by joejoseph00** [comment]
@StephenOTT , I've been working on the wiki translation, we're currently in the process of implementing MultiTrans by MultiCorpora , I'll try to use this , but takes a while to build up a contextual text base.  If I had some technical documents perfectly translated I could use this to build a text base that would help in translating this documentation.
Our technical documentation is a bit lacking.  I'll probably contact MultiCorpora to see if they offer a sample text base for technical development type documentation, might speed things up.
