### ISSUE TITLE
Docker + Drupal WET

### ISSUE THREAD

**Issue by AlexCreamer** [wet-boew/wet-boew-drupal#1916]
I tried installing Drupal WET 7.x and I have successfully gone through some of installation pages. Now I'm getting a problem where the "configure site" step is giving me a blank page. After constantly refreshing and going back and forth between page, I was finally able to have the "configure site" page to render properly with an "active batch" error shown at the top. Furthermore, I was able to get the rest of installation to complete with the default content landing page showing. One problem with the landing page though, the feedback promo section has overlapping text.

**Comment by mxlav** [comment]
RE: WPOD (Whihte page of death) Check out the tips section here [http://drupalwxt.github.io/architecture/system-requirements/](http://drupalwxt.github.io/architecture/system-requirements/) . You are probably running out of memory.

**Comment by AlexCreamer** [comment]
Here's some of my configs (I'll look to do some changes to the recommendations):
max_execution_time = 60
realpath_cache_size = default
max_input_time = default

**Comment by mxlav** [comment]
make sure to change this one also 
memory_limit variable in php.ini to be at least 256M

**Comment by AlexCreamer** [comment]
Oops forgot to mention that I had changed that also. :)

**Comment by joel-osc** [comment]
Any time you get a whitescreen you should look at the 'recent logs' menu in Drupal or even better your apache error log. Whatever caused it will be detailed there.

**Comment by AlexCreamer** [comment]
Hi Joel, I checked my Drupal logs 'recent logs' and I don't know if I found anything worth reporting. I am getting some error messages there though. Furthermore, I tried checking my Apache, access and error logs, and Vim is not returning any content and is saying they're not files. Cat doesn't return anything either.

**Comment by AlexCreamer** [comment]
I should note that I was using PHP 7.1 which was disallow me to add a view. PHP 7.0 worked though.
