### ISSUE TITLE
How to Make Textboxes Bigger using a Webform

### ISSUE THREAD

**Issue by AlexCreamer** [wet-boew/wet-boew-drupal#1919]
I tried setting the webform `size` value to something but it doesn't seem to get used. `width-80` for css worked but it doesn't adjust the height plus I want text to go to a new line whenever inputted text goes past the end of a line.

**Comment by joejoseph00** [comment]
https://www.w3schools.com/css/css_intro.asp

**Comment by AlexCreamer** [comment]
Textarea was what I was looking for. Thanks.
