### ISSUE TITLE
Setting up working examples that can be used for working group testing

### ISSUE THREAD

**Issue by pjackson28** [wet-boew/wet-boew-drupal#192]
@sylus We need to send the Drupal variant to the working groups soon to ensure there is enough time for testing before the WET v3.0 release in September. Please set up working examples that can be shared with the working groups for testing purposes.

**Comment by sylus** [comment]
Hey @pjackson28 I will be sending you a link tonight for this. So you know I am on vacation next week but will try to periodically check in on the working example review status.

**Comment by sylus** [comment]
Hey @pjackson28 sorry for the lateness but an example site is up at http://wet.openplus.ca

There is a wave error I know about on the search box and a few other minor things but please tell the accessibility experts to have at it :)

I'll likely be updating this daily as an bringing it all of the wet plugins and want to add some example pages featuring them. I'll update this issue with relevant page paths as they are built.

**Comment by sylus** [comment]
Closing this for now :) Will update with status updates where necessary.
