### ISSUE TITLE
Latest PHP 5 Version Supported and Whether MySQL 8.0

### ISSUE THREAD

**Issue by AlexCreamer** [wet-boew/wet-boew-drupal#1924]
Is the latest version of PHP 5 supported? Also, is MySQL 8.0 supported?

**Comment by joejoseph00** [comment]
I use MariaDB 10.0.34-MariaDB-0ubuntu0.16.04.1

PHP 5.6.x is supported.  PHP 7.0 should also work fine as well with the latest version.  I use php 7.0 for development.  If you want higher versions of php there is an available patch for 7.2.x support in core https://www.drupal.org/project/drupal/issues/2947772#comment-12625478
 
I'd recommend 7.0.x or older for now.

**Comment by joejoseph00** [comment]
You could also try https://www.drupal.org/project/wxt if you want to run D8
