### ISSUE TITLE
fix the latest builds, require composer 1x not 2.x

### ISSUE THREAD

**Issue by joejoseph00** [wet-boew/wet-boew-drupal#1936]
Composer people upstream are forcing 2.x downstream and it's breaking our build so I added in a pull request the `--1` flag

see pull request:
https://github.com/wet-boew/wet-boew-drupal/pull/1935

just waiting for the builds to complete, hope this fixes the issue.

**Comment by joejoseph00** [comment]
all green 

https://travis-ci.org/github/wet-boew/wet-boew-drupal/builds/745252246

see pull request 
https://github.com/wet-boew/wet-boew-drupal/pull/1935

**Comment by joejoseph00** [comment]
@rikarux  @sylus  one line fix for the build issue, please review pull request

**Comment by olstjos** [comment]
great job on the latest release 7.x-4.54, really impressed with the upgrade to gcweb version 9 and wet-boew 4.40 , so far it looks very good.

**Comment by olstjos** [comment]
@rikarux @sylus  great job on the 7.x-4.54 release
gcweb9 and wetboew 4.40

**Comment by joejoseph00** [comment]
@joejoseph00  great job @rikarux  @sylus  @nathanpw  thanks!
