### ISSUE TITLE
missing "Date modified:" field 

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#196]
Before the update date was defined in the node.tpl.php, and now this file only print $submitted.
What we should expected to see in the page?

old..................

  <dl id="cn-doc-dates" role="contentinfo">
    <dt><?php print t('Date modified:'); ?></dt>
    <dd><span><time pubdate="pubdate" itemprop="dateModified"><?php print $date; ?></time></span></dd>
    </dl>
  <div class="clear"></div>
  
new .....................
<?php if(!empty($user_picture) || $display_submitted): ?>
    <footer<?php print $footer_attributes; ?>>
      <?php print $user_picture; ?>
      <p class="author-datetime"><?php print $submitted; ?></p>
    </footer>
  <?php endif; ?>

**Comment by sylus** [comment]
Fixed Thx!
