### ISSUE TITLE
Install fails on MS SQL Server with i18n error

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew-drupal#20]
See the issue at:  http://drupal.org/node/263141

The patch applied, located at http://drupal.org/files/issues/rollout_server.module_0.patch, fixes the install on IIS6 using MS SQL.  Can this patch be included with the drush make command?

**Comment by sylus** [comment]
Thank @robjohnston for the catch I will include this shortly in the make file. Probably should also include mssql in my travis.yml as well for testing as well.

**Comment by sylus** [comment]
This patch refers to a deprecated module called roll out which I do not include in my make? Unless I am missing something which is probably likely? Either way should give it a shot now as the build out now uses latest i18n 1.7.

Can reopen if still have a problem ^_^
