### ISSUE TITLE
Slideshow/Tabbed-interface translatable?

### ISSUE THREAD

**Issue by dsamojlenko** [wet-boew/wet-boew-drupal#202]
The fields on items are not bilingual, so I tried creating two slideshows - one in english and one in french - and then set the View Access to restrict based on Language, but that doesn't seem to work.

**Comment by sylus** [comment]
Entity Translation needs to be enabled for this to work, testing is being run on it to make sure no regressions. As I am on vacation next week will likely be a week before fully tested. Though have a few other people looking into this :)

**Comment by sylus** [comment]
duplicate of #231 should be solved within the next day or two. Woot Entity Translation
