### ISSUE TITLE
Content Type - Panelizer

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#203]
I indentified two minor problems when configuring the panelizer tab /  +Full page override option .

1) The operations (settings, context, layout, and content) are displayed behing the views.

2)  In the content operation, the Sidebar region doesn't show the menu (to add content) when the left-top buttom is pressed.
      The alternative was to add the element (ex. Main menu)  in other region, and then drag and drop it in the Sidebar

**Comment by sylus** [comment]
I think this error has been fixed. Marking to closed but please reopen it persists :)
