### ISSUE TITLE
 Issue Management for WET Drupal Variant

### ISSUE THREAD

**Issue by thriuin** [wet-boew/wet-boew-drupal#206]
The Drupal WET variant has been gathering momentum and soon a steering committee drawn from government and private industry will be guiding its future direction. As the variant becomes more widely used and more people and organizations participate in its development, there will be a need for a somewhat more structured approach for providing both support and new releases. GitHub provides some tools for this, including issues, milestones, and the ability to assign issues to repository members.

As a first step towards this, I am proposing a more coherent set of labels for the issues. For inspiration, I looked to the categories and issues used at Drupal.org.
- Announcements
- Bug Report: Critical
- Bug Report: Major
- Bug Report: Minor
- Bug Report: Normal
- Documentation
- Feature Request
- Out of Scope
- Release: 7.x - 1.0
- Support Request
- Task

![Issue Label Proposal, Summer 2012](https://raw.github.com/thriuin/wet-boew-drupal/master/images/Issue%20Label%20Proposal,%20Summer%202012.jpg)

Drupal uses four levels of issue priorities ([http://drupal.org/node/73179](http://drupal.org/node/73179)). While GitHub allows multiple labels per issue, I thought it might be simpler to just have four labels.
- **Bug Report: Critical**
- **Bug Report: Major**
- **Bug Report: Minor**
- **Bug Report: Normal**

The other labels match the categories used at Drupal.org ([http://drupal.org/node/73179](http://drupal.org/node/73179)).
- **Feature Requests** are for situations where the software works as designed, but the design can be improved.
- **Tasks** are for something that just needs to get done, where the parameters are well understood. Whitespace repairs, adding translation function support, fixing spelling errors etc are usually just 'tasks'.
- **Support Requests** are for situations where you wish to ask about a specific component. 

The remaining labels are meant to capture the other uses of labels without creating a plethora of categories
- **Announcements** are for important information and news. In general, the issues should not be used for news and announcements, but at certain times it may be the best way to share information quickly.
- **Documentation** is a catch all for any issue that is either related to documentation, or where new or updated documentation would be very helpful.
- **Out of scope** indicates an issue is related to either Drupal core or other code or tools that are used by the distribution but are not actually a part of this distribution. It can also be used to indicate an issue is not related to the WET Drupal variant.

Finally, **Release X.x** labels can used to indicate to which release the issue is related. This isn't important right now, but will be when there are multiple releases of the distribution.

Please share any comments or suggestions you may have on this proposal. I will re-organize the labels later next week.

**Comment by thriuin** [comment]
By the way, [Drupal.org](http://drupal.org/node/73179) describes their bug categories as:
- **Critical**: Critical bugs either render a system unusable (not being able to create content or upgrade between versions, blocks not displaying, and the like), or expose security vulnerabilities. These bugs are to be fixed immediately.
- **Major**: Issues which have significant repercussions but do not render the whole system unusable are marked major. An example would be a PHP error which is only triggered under rare circumstances or which affects only a small percentage of all users. These issues are prioritized in the current development release and backported to stable releases where applicable. Major issues do not block point releases. In Drupal 7 this also applies to test failures in secondary environments. Major priority is also used for tasks or features which consensus has agreed are important (such as improving performance or code refactoring), but which are not functional bugs.
- **Normal**: Bugs that affect one piece of functionality are normal priority. An example would be the category filter not working on the database log screen. This is a self-contained bug and does not impact the overall functionality of the software.
- **Minor**: Minor priority is most often used for cosmetic issues that don't inhibit the functionality or main purpose of the project, such as correction of typos in code comments or whitespace issues.

**Comment by StephenOTT** [comment]
The News and Upstream tags i think are very useful.

News being news stories and items to share with the community.
Upstream being issues that will be resolved as part of a upstream update.  Nice filter to no about issues that are waiting resolution from a upstream fix

**Comment by thriuin** [comment]
Thanks Stephen, I will use "News and Annoucements" for a category. In my opinion, the term "upstream" is not very clear to those not steeped in Drupal development jargon. I propose the term "Dependancy Fix Required" instead.

**Comment by thriuin** [comment]
Actually, having gone through all the issues and applied the new labels, upstream seems to be used a lot. Best thing is probably just to document the labels, so I withdraw my previous comment. Thanks again.

**Comment by StephenOTT** [comment]
Haha.
May something like: "Upsteam Dependency Fix"

Also any plans to start using Milestones?

And may I say that with everything tagged, the issue queue is very colourful!!

**Comment by sylus** [comment]
Lol I noticed that as well. Very pretty! I started a basic milestone as well for the big release date though I can think of a few others I'd like to create.

**Comment by StephenOTT** [comment]
Reopening

Would like to add a few more tags to fill in the gap we currently have for the many pull requests that are done by @sylus that are not from reported bugs but they are upstream fixes or general updates.  We do not appear to be able to tag issues with attached code so we will most likely have to use a milestone.  Would like to hear some thoughts??
