### ISSUE TITLE
Error notice when removing translation link of node

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#207]
Getting the following error notice:

Notice: Undefined index: fr in _language_switcher_wetkit() (line 79 of /Users/myuser/Sites/OttawaWET/drupal_wet/profiles/wetkit/modules/apps/wetkit_language/wetkit_language.module).

Steps:
1. Go to the "WET Drupal Distribution" node.
2. Select the Translate tab in the node.
3. In the "Select translations for WET Drupal Distribution" section type in "WET Distribution Drupal". This will allow you to select "WET Distribution Drupal [nid:1]"
4. Select update translation.
5. View the published node and select the french link in the top right corner of page to make sure the translation link works.
6. Assuming it works, go back to the "WET Drupal Distribution" node.
7. Select the Translate tab in the node.
8. In the "Select translations for WET Drupal Distribution" section remove the text in the field and select update translation.

**Comment by sylus** [comment]
Fixed!

**Comment by sylus** [comment]
Actually if you or @mgifford have the time I'd like to do more testing on the language switcher. I particularly like our implementation but I would just like to make sure there are no other regressions. If we find any further errors can likely use another way of doing this. I know liquidcms and a few other firms have their own variations.

**Comment by mgifford** [comment]
@sylus you looking through the logs for php notices in the distro?  

I'm sure there will be others for unique use cases (like disabling i18n).  However, if you're not looking through the logs when testing it's easy to miss.  

Stripping the tags of the output from i18n's i18n_menu_navigation_links() gives you a lot of flexibility.  Allows it to work easily if there was ever a need to add Spanish or Arabic to the general English/French.  Seems like a good generalized solution.

**Comment by sylus** [comment]
Hey @mgifford yup the log now only lists one type of error (though about 20) to do with http_request, which is related to #194, other then that there should be no other errors in the watchdog :)
