### ISSUE TITLE
Installation Troubles

### ISSUE THREAD

**Issue by Pacoup** [wet-boew/wet-boew-drupal#208]
# Server Specs

Linode 512 MB
Ubuntu 12.04
Prequisites: Installed
Configuration: As outlined in the Wiki, including 120 max execution time and 220 MB memory for PHP scripts
# Problem

Installation times out during the apps install
# Things tried
## Installing pre-compiled version

Status: Failed
Reason: Wiki link broken: https://github.com/sylus/wet-boew-drupal-compiled
## Boosting max execution time to 300

Status: Failed
Reason: Still times out
## Installing via command line

Status: Failed
Reason: Inputing the command as shown on the Wiki in step 4 results in an open command line prompt (" >") and nothing else
# Further explorations

I tried installing Drupal Core to test if it wasn't just Drupal that was plain bad, but I was able to successfuly and quickly install it on my server VM with no issues at all.

Therefore, it is quite obvious that the issue is in the wet-boew-drupal distro. If the answer is hardware, note that a well built dynamic application can run quickly and serve many pages simulatenously on only a 512 MB VM on Linode, which means your distro, or a combination of it + Drupal, is quite badly coded.

I have successfuly run a number of MODX CMS and WordPress installations on such a VM, all at the same time, in the past. I do not believe Drupal WET should require more capable hardware, otherwise there is an inherent performance issue.

**Comment by sylus** [comment]
The Distribution has been installed on a variety of platforms (graphical + command) needing only 192MB and a minimum max_execution_time of 120. Though on initial install this might have to be bumped up to 300 max_exec.

It would be easier to identify your issue with a detailed log.

**Comment by Pacoup** [comment]
Thanks, at least I know it's me, not the distro itself, which is very
encouraging.

I'll get back to you later after I try a few more things.

Can you just tell me which Linux distro is this typically installed on?

**Comment by sylus** [comment]
The Distribution is mostly tested and used with CentOS or RHEL. However I know of quite a few people using Debian.

**Comment by Pacoup** [comment]
Thanks for the help.

I'll post back a more constructive issue if I have problems when testing on CentOS.

**Comment by sylus** [comment]
No problem,

I would recommend you to try and use the drush based install as it only takes about 2 mins compared to about 20 for a browser based one. Another useful thing about the drush si based install is that you can append the --debug parameter and that will tell you alot about what is going on.

I know you mentioned that drush si was not working for you. Does your drush si resemble the following? Keeping in mind some of your --db-url credentials will be different

```
drush si wetkit wetkit_theme_form.theme=wetkit_adaptivetheme --sites-subdir=drupal_wet --db-url=mysql://drupaluser@127.0.0.1:33066/wetkit_db --account-name=admin --account-pass=WetKit@2012 --site-mail=admin@example.com --site-name="Web Experience Toolkit"
```

Also please make sure:

a) Drush Version >= 5.4
b) GIT Version >= 1.7.8

**Comment by Pacoup** [comment]
I used the wiki format,

Wiki: <pre>--db-url=mysql://&lt;username>:&lt;password&gt;@&lt;domain&gt;:&lt;port&gt;/&lt;database&gt;</pre>
Yours: <pre>--db-url=mysql://&lt;username>@&lt;domain&gt;:&lt;port>/&lt;database&gt;</pre>

also, what's supposed to go into --sites-subdir=&lt;domain&gt;?
I put my domain as in the instructions on the wiki, but yours seems to be the name of your installation folder?

**Comment by sylus** [comment]
Sites Subdir is just the domain but creates the directory in sites/\* 

Just a coincidence that same name as my install folder.

**Comment by Pacoup** [comment]
Ok, I'll try again on a CentOS box later and I'll keep you posted if I have any issues.
