### ISSUE TITLE
Error during install at Configure Page

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#211]
Error notice during installation of fresh install that was downloaded from github less than 10 min ago.:
Appears on the Configure Site page.

Notice: Undefined index: items in panels_flexible_panels() (line 257 of /Users/myuser/Sites/OttawaWET/drupal_wet1/profiles/wetkit/modules/contrib/panels/plugins/layouts/flexible/flexible.inc).
Warning: Invalid argument supplied for foreach() in panels_flexible_panels() (line 257 of /Users/myuser/Sites/OttawaWET/drupal_wet1/profiles/wetkit/modules/contrib/panels/plugins/layouts/flexible/flexible.inc).
Notice: Undefined index: items in panels_flexible_panels() (line 257 of /Users/myuser/Sites/OttawaWET/drupal_wet1/profiles/wetkit/modules/contrib/panels/plugins/layouts/flexible/flexible.inc).
Warning: Invalid argument supplied for foreach() in panels_flexible_panels() (line 257 of /Users/myuser/Sites/OttawaWET/drupal_wet1/profiles/wetkit/modules/contrib/panels/plugins/layouts/flexible/flexible.inc).

**Comment by StephenOTT** [comment]
Few extra errors at end of install:

Notice: Undefined index: items in panels_flexible_panels() (line 257 of /Users/myuser/Sites/OttawaWET/drupal_wet1/profiles/wetkit/modules/contrib/panels/plugins/layouts/flexible/flexible.inc).
Warning: Invalid argument supplied for foreach() in panels_flexible_panels() (line 257 of /Users/myuser/Sites/OttawaWET/drupal_wet1/profiles/wetkit/modules/contrib/panels/plugins/layouts/flexible/flexible.inc).
Notice: Undefined property: stdClass::$original in file_field_update() (line 265 of /Users/myuser/Sites/OttawaWET/drupal_wet1/modules/file/file.field.inc).
Notice: Undefined property: stdClass::$original in file_field_update() (line 265 of /Users/myuser/Sites/OttawaWET/drupal_wet1/modules/file/file.field.inc).
Notice: Undefined property: stdClass::$original in file_field_update() (line 265 of /Users/myuser/Sites/OttawaWET/drupal_wet1/modules/file/file.field.inc).
Notice: Undefined property: stdClass::$original in file_field_update() (line 265 of /Users/myuser/Sites/OttawaWET/drupal_wet1/modules/file/file.field.inc).
Notice: Undefined property: stdClass::$original in file_field_update() (line 265 of /Users/myuser/Sites/OttawaWET/drupal_wet1/modules/file/file.field.inc).
Notice: Undefined property: stdClass::$original in file_field_update() (line 265 of /Users/myuser/Sites/OttawaWET/drupal_wet1/modules/file/file.field.inc).

**Comment by sylus** [comment]
Hey aware of these errors waiting on upstream patches :)

**Comment by StephenOTT** [comment]
Perfecto!

**Comment by StephenOTT** [comment]
Any timeline on the upstream patches?

**Comment by sylus** [comment]
Probably within a day or two. I engaged in a lengthy talk today with populist (prolific drupaler behind panopoly) and he is aware of the second problem. As a side note he is very interested in the work we are doing and hopeful we can all push improvements we make back to panopoly.

For the first one it is related to Display Suite and i have filed an issue. I have some further testing to do with a vanilla drupal just for a sanity check but ideally could be resolved with a simple isset.

**Comment by sylus** [comment]
This has been fixed :) Though the flexible bug technically still persists but the grids + layout module are disabled for now. The stdclass::$original bug though has been fixed with a core patch :)
