### ISSUE TITLE
Upstream Bug - Panels/Panopoly- Save Modal and Save Customize this Page conflict

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#224]
When creating a new pane by selecting the "customize this page" button and then going through the add pane interface.  In some instances users will select the Save options for the overall Customize This Page rather than the specific pane they are creating.  They causes the page to save with the pane creation window remaining open.

During a pane creation this is not such a big deal because the user can still select save in the pane creation modal and the pane will save to the page as expected.  But when the same steps are followed but the user is updating a panes settings, when the user selects the save button for the pane a Ajax error appears.

An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /en/panels/ajax/ipe/edit-pane/panel_context%3Apage-wetkit_demo_panel_front%3Apage_wetkit_demo_panel_front_panel_context/new-1/form
StatusText: OK
ResponseText: [{"command":"settings","settings":{"basePath":"\/","pathPrefix":"en\/","ajaxPageState":{"theme":"wetkit_adaptivetheme","theme_token":"rVvVB7mNWBBtD3dKzsQfP9Lde88nJ_VNRz9k8tC39Lg"},"CToolsModal":{"modalSize":{"type":"scale","width":".9","height":".9","addWidth":0,"addHeight":0,"contentRight":25,"contentBottom":75},"modalOptions":{"opacity":".55","background-color":"#FFF"},"animationSpeed":"fast","modalTheme":"CToolsModalDialog","throbberTheme":"CToolsModalThrobber"},"custom_search":{"form_target":"_self","solr":0}},"merge":true},{"command":"modal_display","title":"Error","output":"Invalid pane id."}][{"command":"settings","settings":{"basePath":"\/","pathPrefix":"en\/","ajaxPageState":{"theme":"wetkit_adaptivetheme","theme_token":"rVvVB7mNWBBtD3dKzsQfP9Lde88nJ_VNRz9k8tC39Lg"},"CToolsModal":{"modalSize":{"type":"scale","width":".9","height":".9","addWidth":0,"addHeight":0,"contentRight":25,"contentBottom":75},"modalOptions":{"opacity":".55","background-color":"#FFF"},"animationSpeed":"fast","modalTheme":"CToolsModalDialog","throbberTheme":"CToolsModalThrobber"},"custom_search":{"form_target":"_self","solr":0}},"merge":true},{"command":"modal_dismiss"}]

**Comment by sylus** [comment]
I believe this is fixed in recent commit (bout 30 mins ago) as the save button (customize this page location) no longer appears when you are adding / editing a pane. :) Woot!
