### ISSUE TITLE
Field List Error Notices

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#228]
Errors appear when viewing field lists:
Admin>Reports>Field Lists

Notice: Undefined index: callout in _field_ui_bundle_admin_path() (line 325 of /Users/myuser/Sites/OttawaWET/drupal_wet1/modules/field_ui/field_ui.module).
Notice: Undefined index: callout in field_ui_fields_list() (line 35 of /Users/myuser/Sites/OttawaWET/drupal_wet1/modules/field_ui/field_ui.admin.inc).
Notice: Undefined index: existing_content in _field_ui_bundle_admin_path() (line 325 of /Users/myuser/Sites/OttawaWET/drupal_wet1/modules/field_ui/field_ui.module).
Notice: Undefined index: existing_content in field_ui_fields_list() (line 35 of /Users/myuser/Sites/OttawaWET/drupal_wet1/modules/field_ui/field_ui.admin.inc).
Notice: Undefined index: existing_content in _field_ui_bundle_admin_path() (line 325 of /Users/myuser/Sites/OttawaWET/drupal_wet1/modules/field_ui/field_ui.module).
Notice: Undefined index: existing_content in field_ui_fields_list() (line 35 of /Users/myuser/Sites/OttawaWET/drupal_wet1/modules/field_ui/field_ui.admin.inc).
Notice: Undefined index: quote in _field_ui_bundle_admin_path() (line 325 of /Users/myuser/Sites/OttawaWET/drupal_wet1/modules/field_ui/field_ui.module).
Notice: Undefined index: quote in field_ui_fields_list() (line 35 of /Users/myuser/Sites/OttawaWET/drupal_wet1/modules/field_ui/field_ui.admin.inc).
Notice: Undefined index: quote in _field_ui_bundle_admin_path() (line 325 of /Users/myuser/Sites/OttawaWET/drupal_wet1/modules/field_ui/field_ui.module).
Notice: Undefined index: quote in field_ui_fields_list() (line 35 of /Users/myuser/Sites/OttawaWET/drupal_wet1/modules/field_ui/field_ui.admin.inc).

**Comment by sylus** [comment]
This has been fixed :)
