### ISSUE TITLE
Draggable field location in WetKit Panel layout 40/40/20 has broken right side

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#229]
Right panel drop location is not sizing properly on 40/40/20 webkit layout.
To recreate: Change page layout to 3 column 40/40/20 webkit layout and then select customize this page.

**Comment by sylus** [comment]
This works just not ideally, you have to refresh the page after you change the layout. Will look into better usability of this feature.

**Comment by sylus** [comment]
Have attached a warning when changing layouts about need to refresh the page. In RC2 will find a way to get this done automatically.

**Comment by sylus** [comment]
Unfortunately the refresh is the only way to fix this and it has been documented. Closing this issue despite wishing there was a better fix.
