### ISSUE TITLE
Rules doesn't work well with jQuery Update

### ISSUE THREAD

**Issue by LeeHunter** [wet-boew/wet-boew-drupal#23]
There seems to be a problem with using Rules with jQuery Update. 

*Create rule
*Add an event (after saving content, content is viewed, or whatever)
*Add a condition 
*Select Data Comparison
*Click Continue

At this point nothing happens and there is no error message, I just remain on the Add a New Condition page.

If I disable jQuery Update it works as expected. Since Rules is not very useful without being able to do Data Comparison, I'm wondering if I can just leave the jQuery Update module disabled, or if it's needed for something else in Wetkit.

**Comment by sylus** [comment]
Hmm I will have to take a further look into this likely after the big commit later this week. I should mention though that jquery_update + patch (in make file) is very important. This is because WET expects to be running on Jquery 1.7. What jquery_update with the patch allows is for the front end to use jquery 1.7 and the backend to use 1.5.

Not sure why the rules interface isn't working though likely some js mucking it up

**Comment by LeeHunter** [comment]
I wonder if this patch would solve my problem: http://drupal.org/node/874942  Not sure if it works with 7.x though.

**Comment by LeeHunter** [comment]
Now that I think about it a bit more, if it's only the Rules UI that's impacted (and not the rule itself), I should be able to just turn off JQuery Update while I develop my rules and then turn it on again when the site goes into production. Not a big deal at all.

**Comment by sylus** [comment]
Hey @LeeHunter you can also in jquery update set it to use jQuery 1.5 for administrative pages when working with rules and then switch back once you are done so WET works properly. Unfortunately this is a loaded error that will take a fair amount of code wizardry to fix. I saw you opened up the issue on JQuery Update or Rules (forget which) but might make sense to reopen on D.O.

**Comment by sylus** [comment]
I really want this issue closed but is up to the rules maintainers to support newer versions of jquery. Issue is here: http://drupal.org/node/1810656

**Comment by sylus** [comment]
This has finally been fixed upstream at Rules as it seems to work now using jQuery v1.7 please reopen if problem still persists.
