### ISSUE TITLE
Entity Translation + Fieldable Panel Panes

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#231]
Entity Translation still has work to be done for node bundles. However we are using fieldable panel panes for plugins and this currently work very well with the entity translation module and will absolutely be needed for the WET plugins

A problem I am running into is that when I use features to generate default settings for entity translation such that it only applies to fieldable panel panes the distro installation fails:

```
Fatal error: Cannot access empty property in /Users/username/Desktop/Sites/drupal_wet/profiles/wetkit/modules/contrib/entity_translation/includes/translation.handler.inc on line 323
```

Based on the following strongarm variable:

```
  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'entity_translation_entity_types';
  $strongarm->value = array(
    'fieldable_panels_pane' => 'fieldable_panels_pane',
    'node' => 0,
    'file' => 0,
    'taxonomy_term' => 0,
    'user' => 0,
  );
  $export['entity_translation_entity_types'] = $strongarm;
```

Note that if entity translation is enabled post installation everything works great and WET plugins (tabbed interface) can be fully translated.

**Comment by sylus** [comment]
Entity translation is in and now working for foldable panel panes. Some more work needs to happen though to make the integration tighter particularly with the preview.

**Comment by StephenOTT** [comment]
@liquidcms are you able to help out with this issue?

**Comment by sylus** [comment]
Wow this issue is finally resolved! WOOT

**Comment by StephenOTT** [comment]
:+1:
