### ISSUE TITLE
Vagrant Box: Anyone have ideas where I can host?

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#232]
In an effort to assist people in evaluating and developing with the WetKit distro I am nearing completion on my work for a Vagrant package. 

As a quick aside:

Vagrant (http://vagrantup.com/) allows for you to create and configure lightweight, reproducible, and portable virtualized development environments. You can then use such commands as vagrant ssh and vagrant up etc.. (Vagrant builds itself on top of Virtual Box).

The box package I am working on will have (powered through a Chef provision - CHEF ROCKS!):

a) RHEL 6.4 (Government Preferred Linux Standard)
b) The WetKit Distribution
c) All needed php libraries
d) Apache 2.4
e) Apache Solr 3.6 + Tomcat 7
f) Varnish
g) Memcache
h) Alfresco (https://github.com/fnichol/chef-alfresco) - might come in later

The problem I am running into is where I can host the Vagrant base box for RHEL 6.4? Looked everywhere for another pre hosted box but only found puppets version.

At least the vagrant package itself is of course minimal (2.9mb) in size and enables a preconfigured and working dev environment that yields a rapid evaluation and development environment with WetKit! An initial alpha version will likely be committed tomorrow or monday :) Was thinking about putting these files in a devops folder in this repo itself. Or should they committed elsewhere?

@openplus do you think your Red Hat contact would be amenable to assist in hosting the base box if they don't already have one (would be surprised as I bet they do RHEL 6.4 64Bit)? :D

**Comment by patcon** [comment]
Nice! Was just working on getting this working with the environment we've been using, [Ariadne](https://github.com/myplanetdigital/ariadne/tree/develop). Figured I could use it as an excuse to get solr working! (It's on Ubuntu Lucid though, but only because Acquia and Pantheon are still using it, and we wanted to simulate their offerings as closely as possible.)

I haven't done it yet for myself, but I've seen [people host baseboxes on github via the "Downloads" section](https://github.com/mariussturm/vagrant_graylog2/downloads) of a project. Could probably only host an unconfigured basebox or else the image would be pretty huge, but I'm slightly partial to that way of operating anyhow, so the idea always seemed appropriate :)

**Comment by patcon** [comment]
And hey: WAHAHOOIE CHEF! It always feels Chef is winning in the wider world lately, but Puppet is winning in Drupal-narnia, so I'm pumped that you chose it

I guess I didn't give context before, but the goal with that Ariadne project (the vagrant project I'm working on) is to extract all the general setup into one vagrant environment, and then have simple little custom cookbook repos to do the last mile of setup for each project -- sql-sync's or site-install or whatever it takes to get the site working in browser with just `vagrant up`.

Technically... chef cookbooks should work fairly well in between systems, if we're using robust ones... So what if I hacked on our environment (ie. submitted PR's for opscode cookbooks and generalized our custom stuff) in such a way that it worked for RHEL? Not saying our project is going to be defacto or anything, but I've had brief discussions with the Drupal Quickstart guys, and they're interested in moving from using a golden image to using vagrant. They seem amenable to chef. Also, some folks at xforty have [an environment published](https://github.com/xforty/vagrant-drupal), and we've been talking about merging efforts somehow. I guess I'm just saying that it seems a shame to start yet another drupal vagrant environment...

**Comment by patcon** [comment]
> a) RHEL 6.4 (Government Preferred Linux Standard)

Wait... Is that out yet? http://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux#Version_history

Seems there's already a veewee definition for centos 6.3: https://github.com/jedi4ever/veewee/tree/master/templates/CentOS-6.3-x86_64-minimal

I don't tend to use enterprise linux. Could we swap out rhel for centos so that folks people can more easily play around without licenses? The cookbooks would be the same, right?

**Comment by sylus** [comment]
Hey @patcon yeah should actually be 6.3 (right now only testing with Ubuntu, so still have to make base box). As for your suggestion to use CentOS I am not sure. I know when the government releases next month the WCMS mandate that RHEL will be the only Linux standard that Shared Services will be setting up so wanted to align everyone with that. As am basing work off of http://drupal.org/project/vagrant (albeit an updated version) the scripts  should work on CentOS, Debian, RHEL etc though! Would be no problem to support CentOS + RHEL.

I am interested in your discussions with the quickstart folks. After some research a few months ago Vagrant + Chef is definitely the way to go. Were you thinking about taking over (co-maintaining) the vagrant project on D.O or branching the quickstart project or a completely new one? GitHub?

I just started also playing around with http://drupal.org/project/drush-vagrant which is also pretty cool :)

Anyways I am completely open to whatever suggestions you have as I know you guys have a lot of experience with this :)

**Comment by sylus** [comment]
Also looking @ Ariadne I have to say it is pretty cool, wouldn't mind aligning with it although we would have to support windows I think.

**Comment by sylus** [comment]
Released an initial commit that works still using Ubuntu Lucid: https://github.com/sylus/wet-boew-drupal-devops

Uses drush make + drush si, and all code in site-cookbooks has been updated with latest packages + some minor patches to make build work.

**Comment by sylus** [comment]
Was having problems with vcl as was expecting v3.0 but popped in your guys one from: Ariadne

Had to modify the regex in the default vcl to: 

```
__[a-z0-9_]*|utm.*|has_js
```

Ottawa University used this expression as it seems google analytics had a few more files then expected.

**Comment by sylus** [comment]
Played with ariadne a bit more today and have to say it is awesome, will likely switch to using that :) @patcon

**Comment by patcon** [comment]
Wahoo! That's so cool! Thanks man. I'm at Drupalcon Munich now trying to get in touch with the folks working on other vagrant-related projects, so I'll keep you posted :)

**Comment by patcon** [comment]
Oh hey, and no pressure, but if you have any time, it would be ridiculously awesome if you were interested in providing feedback on the docs. It's really hard to see them with fresh eyes, so anything you think is lacking, feel free to open a issue in the ariadne queue

**Comment by sylus** [comment]
Hey @patcon,

I actually had a bit of feedback. Some are probably pretty trivial but would like to toss your way. I am not sure how pertinent everything is so just did a quick write up here for now. Please keep in mind most of these things are nice to have and me trying to align with government needs so quite possibly not good recommendations.

Overall though I love ariadne and really think the work you have done with it is exceptional.

Points:

1) .rvmrc and ruby install can fail in MacOSX (even with command line tools) Not sure why but I kept getting a make compile error having to do with a readline problem and gcc (still not sure what I did to fix it lol!).

2) Some documentation on how to extend ariadne would be useful unless we are just supposed to fork it and modify it which also makes sense. :)

3) Was worried a bit about performance in the VM and read an issue which you took apart of. Do you maintain it is largely the setup and not the VM itself? I notice xforty/vagrant-drupal uses a few performance settings in their Vagrantfile. Possibly relevant?

```
# VirtualBox performance improvements
  config.vm.customize ["modifyvm", :id, "--nictype1", "virtio"]
  config.vm.customize ["modifyvm", :id, "--nictype2", "virtio"]
  config.vm.customize ["storagectl", :id, "--name", "SATA Controller", "--hostiocache", "off"]
```

4) I would love if we adapted and integrated the https://github.com/wch/vagrant-ec2-r repo so can do a simply deployment to ec2 without needing chef server. I tested it myself and worked great with their custom cookbooks. Looking at the code it only parses the run_list and converts to json (runs chef -c .... -j dna.json) but would be great to add roles etc. This could be used for users who don't have a capable enough local computer. If we included a step by step on running on a m1.small server could help alot!

5) If we could discuss and have a step by step guide on how to use veewee to build custom boxes (RHEL for government) I think that also could help. I know there are some already around but perhaps more tailored to integrating with ariadne.

6) A solr cookbook would be a great addition. I'd love to help on this space. We could base off of: https://github.com/theozaurus/chef-solr and modify it to instead support tomcat 7.

7) You host alot of the chef recipes yourself, how to they differentiate between opscode hosted ones?

8) Windows support would be needed (even though personally would like to ignore) but thinking shouldn't be to hard to use pik for windows? Again I'd love to help in this area.

9) More of a future issue but I would LOVE and so would Shared Services Canada if we could find a way to make Vagrant + Chef output in VMDK format so they can simply spool it up. (Think what I just said made sense but don't quote me!)

Anyways I admit I have entered the devops space rather recently so maybe a lot of my suggestions don't make any sense but thought I would throw them out there. :)

Overall though I love the modular design and after looking at tons and tons of other repos think ariadne is pretty special! :) I would like to standardize wet-boew-drupal on it. It also doesn't hurt that you guys align with acquia on your setup :)

**Comment by openplus** [comment]
Hey Will...

I'll talk ro Richard at RedHat, I'm pretty sure he'd help out on this (Given the CosCoe.org affiliation).
We're also open to providing an Amazon EC2 instances.

Let's talk in person.

**Comment by patcon** [comment]
@sylus thanks man! copied this into an issue in the ariadne queues, and will get back to you on those points tomorrow during the drupalcon sprint day. You're a hero

**Comment by patcon** [comment]
Oh hey, quick point on making ariadne deployable -- really like that idea, and the approach in that repo. Might be worth looking into knife-solo or pocketknife -- I've been meaning to use them for deploying the [Inception CI stack](https://github.com/myplanetdigital/inception) as it matures :)

https://github.com/matschaffer/knife-solo
https://github.com/igal/pocketknife

**Comment by sylus** [comment]
Work is starting on ariadne and hosting options for a custom redhat box forthcoming. ^_^
