### ISSUE TITLE
uOttawa posted their under development Drupal Modules on GitHub

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#239]
Some Great news out of uOttawa.ca

Today they have posted their works in progress.  Some of the most interesting being their side by side WYSIWYG editor and their migration UI.
https://github.com/uottawa-wcms

Check it out and remember that these are works in progress and still under heavy development.

@sylus can speak more to some of the work that still needs to be done.

**Comment by sylus** [comment]
I am particularly keen about the migration work that University of Ottawa has done. I can say that next week migration comes at the forefront at Statistics Canada.

I was hoping next week it would be possible to get the Ottawa U folks to spare an hour or two as I'd like to see how best StatCan can leverage this and improvements can be made.

Would City of Ottawa like to join in on this conversation? Assuming Ottawa U is good to spare an hour or two?

**Comment by StephenOTT** [comment]
City of Ottawa is interested.  Have current migration and future systems and sub applications to move over
