### ISSUE TITLE
Cache doesn't refresh for base page when adding translation

### ISSUE THREAD

**Issue by dsamojlenko** [wet-boew/wet-boew-drupal#24]
When you create a page and then add a translation to that page, the first page is cached before the translation link is made.  So after creation if you visit the second page, the language toggle will take you to the first.  But, since the first page was cached before the translation link was made, the language toggle does not work on that first page.

Clearing the drupal cache after page creation fixes this, but it would be nice if the system automatically refreshed the cache of the base page when adding a translation.

**Comment by sylus** [comment]
This should now be fixed in latest release!
