### ISSUE TITLE
Dries Keynote

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#243]
Not really an issue but for anyone using Drupal and wanting to see the defacto visionary behind Drupal I ask you to spare 30 minutes and watch Dries' Keynote from Drupalcon Munich (August 21st, 2012).

You can probably skip to minute 22 if you just want to see Dries' interview. :)

http://munich2012.drupal.org/live

**Comment by StephenOTT** [comment]
Love the new Layout feature in D8

**Comment by joejoseph00** [comment]
The link no longer works

**Comment by sylus** [comment]
Thanks @joejoseph00 ^_^ New link at: http://munich2012.drupal.org/speakers/keynote/dries-buytaert
