### ISSUE TITLE
TMGMT: Translation Management

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#244]
I keep forgetting how awesome the TMGMT module is and how can greatly assist in Translation workflow.

This is an issue assigned so at some point can fully test this out and see how it should be included:

http://drupal.org/project/tmgmt

**Comment by StephenOTT** [comment]
Correct me if I am wrong.
But there is currently no workbench integration correct?

**Comment by sylus** [comment]
I really want this module added but will likely have to talk with City of Ottawa and Government translation services and see what plugins we have to make.

**Comment by StephenOTT** [comment]
I will talk to our people about what sort of services they use and integration opportunities.  There may be some good savings potential through reduction of routine administrative activities between content producers and translators

**Comment by StephenOTT** [comment]
So we currently have custom system but we are looking to replace with a new system.    There is an API for the current system but apparently it does not work.

So may have to discuss further to determine way forward.

**Comment by sylus** [comment]
Cleaning up some old issues. :)
