### ISSUE TITLE
Need advice:  Setting up many (>100) sites that share content

### ISSUE THREAD

**Issue by MichaelClift** [wet-boew/wet-boew-drupal#245]
I work for a large government agency that has a presence in many cities and towns across the country.  

We need to set up a content management system that allows the "local" users to post content to their own website.  That content is then aggregated at a provincial and national level.  Content that is created at the national and provincial level will appear on the "local" websites as well.

Each of the "local" websites will be identified by a host-name such as:  someLocale.department.gc.ca, and the provincial level websites will be "someProvince.department.gc.ca".  Also, with official languages support required for some local sites, the french/english and bilingual department name will need to be supported, so that:

FrenchLocale.FrenchDepartmentName.gc.ca points to the French language version 
EnglishLocale.EnglishDepartmentName.gc.ca points to the English language version
BilingualLocale.BilingualDepartmentName.gc.ca points to the language version the "Admin" has chosen as default.

What approaches can I take?  I started looking at a module called "domain access", but it doesn't seem to play nice with the wet-drupal variant.

**Comment by StephenOTT** [comment]
Are each of the local users completely responsible for their website.  Is this something a multi-site setup would be good for?
http://drupal.org/documentation/install/multi-site
Could then aggregate the data in various ways including something such as feeds.

**Comment by MichaelClift** [comment]
Each of the local users is a content author and can't manage a website on their own (usually).  Multi-site might work, but I have no idea how the content aggregation would work between the various sites.

**Comment by openplus** [comment]
Hey Michael,

This will be a difficult topic to answer from a discussion thread, as there are several big factors and considerations here (and this is rather a big decision - a critical part of planning, and certainly worth prototyping as their are most likely pigeon wholes here and there).

We've discussed this with other active clients with similar scope-relevant challenges for distributed content management. (re: We are working with the University of Ottawa as their lead Drupal7WET consultant - they have close to 900 websites they plan to move to Drupal7 WET). Also have a Federal GoC client for Drupal Intranet with Provincial chapters - looking at Geo-locate HTML5 options and User Profiles to help content relevancy.

Here are some open discussion ideas...

a) Search Method
Providing a good search experience is a bigger factor then ever - and even though you'll most certainly use solr (assumption) to manage search in Drupal, It's critical to know your options - as you can leverage solr in this use case to present external cores/indexes - e.g. even form other Drupal sites, multi-sites, and even non-drupal sites/DBs.

b) FEEDS and re-aggregation
Like Stephen mentioned... Depending on key considerations for the Content Architecture (e.g. Do you need to be able to retract from all sites, if not... simple Drupal Feeds is an option to consider. - Translations FEEDS would be important to discuss further here.

c) Multi-Site
This will introduce other issues also, multisites aren't as unified as I'd expected. (it's more code sharing and resources planning then anything). Hence, you'll still challenges to architect the ACL/Roles/Permissions. - Is LDAP in the mix?

d) Panels + Taxonomy
Both of these will likely still be part of your Content Architecture, also worth understanding their potential role (likely more in a single larger site scenario - I think this is where we're going with the City of Ottawa). That's in discussions.

Lastly...
I'm sure there are other options, and I could see why you'd consider Domain Access.
We recently deployed D7WET for GoC (a crown corp) using "domain access" (www.scc.ca) ...It did introduce other problems, including site title translations - yet does work. (the issues we had then I believe are now resolved). Mike Gifford would likely have more insight on this one.

Man, I hope this helped! lol

**Comment by sylus** [comment]
I think @openplus' comment is bang on and worth taking a look at the options discussed. The only thing I would add is the http://drupal.org/project/deploy module which is gaining traction but likely not there yet.

As for Domain Access in a seperate issue could you mention the issues that are cropping up when used with WET. There should be no interference.

I would try to get in touch with some of our contacts at University of Ottawa as they might be able to share some of their architecture.

**Comment by sylus** [comment]
In a day or two the session video should be posted: http://munich2012.drupal.org/program/sessions/multi-headed-drupal

**Comment by sylus** [comment]
Video is out @MichaelClift :)

**Comment by sylus** [comment]
Closing for now but please reopen if have additional questions :)

**Comment by strinh** [comment]
Hey, now that we've just uploaded our Secure Synchronization module, I thought we could reopen this up for discussion especially since we'll want some feedback from folks who would to use such a module.  Check it out here: 

https://github.com/uottawa-wcms/secsyn

Basically it allows you to syndicate content across multiple sites residing on multiple servers.  Right now it assumes that key fields are matching for content types, however we're planning on doing some extra thinking around how to ensure that content types are also synched between installations.

We had to strip out a lot of the security stuff that we had built into it, however the framework is there for you to build out based on your own security needs.  If you want more info on the technicalities, please open a discussion in the issue queue.

Hope this helps!
