### ISSUE TITLE
Drupal WET Distro Security App

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#248]
MODIFIED SUMMARY:

So we need to start thinking about approaches to tighten up site security beyond the defaults to think about Intrusion Detection & Protection Systems as well as Security Information and Event Management.

Some modules to start reviewing and considering for integration for a separate Drupal App include:
1. [Hacked!](http://drupal.org/project/hacked)
2. [Paranoia](http://drupal.org/project/paranoia)
3. [Security Kit](http://drupal.org/project/seckit)
4. [Security Review](http://drupal.org/project/security_review)
5. [Password Policy](http://drupal.org/project/password_policy)
6. [Bad Behavior](http://drupal.org/project/badbehavior)
7. [GoAway](http://drupal.org/project/goaway)
8. [http:BL](http://drupal.org/project/httpbl)
9. [md5check](http://drupal.org/project/md5check)
10. [Drupal Tiny-IDS](http://drupal.org/project/tinyids)
11. [Encrypt Submissions](http://drupal.org/project/encrypt_submissions) 
12. [Secure Pages](http://drupal.org/project/securepages)
13. [Secure Permissions](http://drupal.org/project/secure_permissions)
14. [ClamAV](http://drupal.org/project/clamav)
15. [login history](http://drupal.org/project/login_history)
16. [two factor authentication](http://drupal.org/project/tfa)
17. [filter html image secure](http://drupal.org/project/filter_html_image_secure)

ORIGINAL TITLE & SUMMARY: Drupal WET Distro Security Lockdown and Monitoring Considerations

So we need to start thinking about specifically which modules should be used for security purposes.
- Intrusion Detection Systems
- Intrusion Protection Systems
- Security Information and Event Management

Some modules to start reviewing and considering for integration would potentially be:
1. [Hacked!](http://drupal.org/project/hacked)
2. [Paranoia](http://drupal.org/project/paranoia)
3. [Security Kit](http://drupal.org/project/seckit)
4. [Security Review](http://drupal.org/project/security_review)

Would see this as more of a "available options" for security based on risk and needs.  Would be good to have a series of best practices and security scenarios that could leverage the optionally integrated modules into the base of the distro.

**Comment by mgifford** [comment]
There are [great lists like of contributed security modules](http://drupalscout.com/knowledge-base/contributed-modules-securing-your-drupal-site). Sadly this one is mostly D6 at this point.

[Password Policy](http://drupal.org/project/password_policy) would be good.

[Bad Behavior](http://drupal.org/project/badbehavior), [GoAway](http://drupal.org/project/goaway), [http:BL](http://drupal.org/project/httpbl), [md5check](http://drupal.org/project/md5check), [Drupal Tiny-IDS](http://drupal.org/project/tinyids), [Encrypt Submissions](http://drupal.org/project/encrypt_submissions) - although https should be sufficient, [Secure Pages](http://drupal.org/project/securepages), & [Secure Permissions](http://drupal.org/project/secure_permissions)

[ClamAV](http://drupal.org/project/clamav) to make sure staff don't accidentally end up uploading viruses with content.

I don't think [login history](http://drupal.org/project/login_history) would be helpful, although maybe when citizens have login credentials.

Would be good to consider [two factor authentication](http://drupal.org/project/tfa) for when the users surge.

There are certainly others that need consideration, but this is a big starting list.

Don't forget [PHP hardening suhosin](http://www.hardened-php.net/suhosin/)

**Comment by StephenOTT** [comment]
great list @mgifford 

I think this will be a great wiki page to get started for the specific use cases that we will run into.  Definitely something that can be leveraged between Github and drupal.org content

**Comment by mgifford** [comment]
Based on http://drupal.org/project/guardr there are a few other modules to mention:

http://drupal.org/project/view_profiles_perms
http://drupal.org/project/user_registrationpassword
http://drupal.org/project/user_readonly
http://drupal.org/project/role_delegation
http://drupal.org/project/username_enumeration_prevention
http://drupal.org/project/settings_audit_log
http://drupal.org/project/session_limit
http://drupal.org/project/session_expire
http://drupal.org/project/role_watchdog
http://drupal.org/project/permission_watchdog
http://drupal.org/project/reroute_email
http://drupal.org/project/r4032login
http://drupal.org/project/permission_grid
http://drupal.org/project/mail_logger
http://drupal.org/project/login_history
http://drupal.org/project/inactive_user
http://drupal.org/project/filter_perms
http://drupal.org/project/field_permissions
http://drupal.org/project/email_confirm
http://drupal.org/project/diskfree
http://drupal.org/project/autologout

**Comment by StephenOTT** [comment]
Looks like we have some homework to do :)

**Comment by StephenOTT** [comment]
anyone had comments on:
https://www.acquia.com/resources/acquia-tv/conference/securing-drupal-sites-government-agencies-september-5-2012

?

**Comment by sylus** [comment]
Great issue for people to read and will be kept for posterity but nothing that WET can do as its module scope is defined and locked down now.
