### ISSUE TITLE
Dublin Core Metatags  convert to evolving HTML5 standard

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#255]
Currently we were using the Dublin Core http://purl.org/dc/elements/1.1 schema.

WET uses the new HTML5 (evolving) standard.

As such a lot of our meta properties are incorrect and a few terms are no longer need as well an array of other caveats.

I am filing an issue so can keep track of the module I am working on and will do an initial push in a few minutes. The distribution will now use this module instead of metatags_dc.

**Comment by StephenOTT** [comment]
different schema standard but same value sets?

**Comment by sylus** [comment]
Initial module has been pushed and works for existing test cases. Will likely need more improvements but closing issue for now.
