### ISSUE TITLE
Running Drupal without Name-based Host

### ISSUE THREAD

**Issue by Pacoup** [wet-boew/wet-boew-drupal#262]
I'm trying to run Drupal, due to network limitations, from a VM accessible directly by a local network IP. The website loads once everything is set up, but trying to login via the /user page simply forwards me back to that same page without logging me in.

Upon inspecting errors, it turns out that the apache actually sends back 404 headers, despite the page loading. My guess is that Drupal is having some trouble with the --sites-subdir argument being an IP address instead of hostname.

Any idea if what I'm trying to do is even possible or does Drupal's configuration only accept URL hostnames? The machine is being built for local development but I'm not allowed to have a hostname on the network, and I don't have admin rights for the desktop Windows XP machine I'm going to use to access the website, so I can't rewrite the hosts file and use my own domain.

**Comment by joel-osc** [comment]
I have used IP address in sites folder without an issue before...the only time I have seen that issue is when cookies were disabled.

**Comment by Pacoup** [comment]
Right, although I did not disable cookies. Seems to be a rewrite issue with Apache.

I just found out that using "?q=" instead of clean URLs works. And the Clean URL test in the Drupal admin panel fails. I'll look into the htaccess configs further. Possibly not Drupal's fault but mine.

**Comment by StephenOTT** [comment]
If you are working on local development, take a look at Acquia Dev Desktop.  Will let you import new distros.

For people that have very locked down systems, Acquia Dev Desktop seems to work better than the VM

**Comment by sylus** [comment]
Have you enabled mod_rewrite? 

Also do you have a vhosts file like so? 

```
<VirtualHost *>
  ServerName localhost
  DocumentRoot "/var/www/drupal"
  <Directory "/var/www/drupal">
    Options Indexes FollowSymLinks ExecCGI
    AllowOverride All
    Order allow,deny
    Allow from all
  </Directory>
</VirtualHost>
```

**Comment by Pacoup** [comment]
(Stephen, can you stop publicizing Acquia every time I have an issue with my server? It's not constructive.)

Thanks William, you're a life saver as always. Looks like Ubuntu doesn't have mod_rewrite enabled by default, Fedora does, and the system I'm testing on right now runs Ubuntu.

Anyway, I didn't have to configure my virtual host file like what you wrote, but I did went and enabled clean URLs within Drupal itself:

<pre>http://[...]/?q=en/admin/config/search/clean-urls</pre>
