### ISSUE TITLE
error notice on Categories Panelizer Page

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#264]
Notice: unserialize() [function.unserialize]: Error at offset 121 of 1050 bytes in panels_common_get_allowed_layout_object() (line 458 of /Users/myuser/Sites/OttawaWET/drupal_wet2/profiles/wetkit/modules/contrib/panels/includes/common.inc).

showing up at:

Admin>Structure>Taxonomy>Categories>Panelizer

**Comment by StephenOTT** [comment]
Also if you go into the suboptions for the Full Page Override and Default, there is text/links that are showing up behind the UI.

**Comment by sylus** [comment]
Simple problem to fix have fixed it in a few other areas already, will resolve in next commit.

**Comment by StephenOTT** [comment]
Have been finding the text/links behind ui all over admin pages.  Very common problem

**Comment by sylus** [comment]
Fixed! Might need to do a bit more work on the css but at least renders them so are usable.
