### ISSUE TITLE
Autocomplete indicator spinner not aligned in Translate Text field

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#266]
Go to a translation page for a node.
Under the select translations section there is the text field to type in the node name of the translation.
On the right hand side of the field you can see at the bottom edge the spinner graphic not aligned with the text box.

**Comment by StephenOTT** [comment]
Same issue with the Author Field in the Author Information section when Editing a page.

**Comment by StephenOTT** [comment]
Issue also appears when creating a Content Item Pane

**Comment by sylus** [comment]
Fixed!
