### ISSUE TITLE
WET CSS Messages support in WYSIWYG

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#268]
Support for the CSS Messages in the WYSIWYG is not active:
http://wet-boew.github.com/wet-boew/demos/grids/grid-message-eng.html

**Comment by sylus** [comment]
Great idea and super easy to implement, look for it probably by tonight will post back here.

**Comment by StephenOTT** [comment]
There are a bunch of other WYSIWYG editor tweaks to be made.  I can post each individual or start a thread.  Which do you prefer? @sylus

**Comment by sylus** [comment]
Please create a META issue (much like multilingual + documentation) ^_^

**Comment by sylus** [comment]
Can't reproduce and would be an error with WET-BOEW not Drupal ^_^
