### ISSUE TITLE
Set default path prefix language code for "en"

### ISSUE THREAD

**Issue by sboots** [wet-boew/wet-boew-drupal#27]
Small suggestion related to URL path design -- it might be worth changing the default "path prefix language code" for English, from nothing, to "en", on eg. /admin/config/regional/language/edit/en

That way, instead of having URLs such as
example.com/contactus
and example.com/fr/contacteznous
...both languages will then have a language code (and avoid English being seen as primary, French secondary, etc.)

There doesn't seem to be a GoC standard on URL design, but we're tentatively planning to move to language prefixes (eg. en/ and fr/) rather than "something-eng.html" and "something-fra.html" as in the past.

**Comment by wilroboly** [comment]
to note: within the government of canada URL standard, you can approach your naming convention also using language specific domains as in:
- buyandsell.gc.ca
- achatsetventes.gc.ca

The nice thing about using such an approach, is it keeps the language identifier out of the equation and also means you can avoid using a splash screen so you're branding is a lot easier to deal with. Nothing like having relevant URLs that match your language!

Just something to think about.

**Comment by sboots** [comment]
Whoa, actually that's very true - thanks for the reminder!  That might work very well for our purposes.

**Comment by sylus** [comment]
Fixed
