### ISSUE TITLE
(META) WYSIWYG Tweaks - Release 1

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#270]
Catch all for WYSIWYG improvements

**Comment by StephenOTT** [comment]
Support for the CSS Messages in the WYSIWYG is not active:
http://wet-boew.github.com/wet-boew/demos/grids/grid-message-eng.html

**Comment by StephenOTT** [comment]
How will HTML Tables be supported? Inline within WYSIWYG editor? If so, this needs to be activated in configuration and CSS options enabled.
css stylings: http://wet-boew.github.com/wet-boew/demos/grids/grid-table-eng.html

Also alignment/styling options should be CSS and not inline.

**Comment by StephenOTT** [comment]
Proximity Options:
http://wet-boew.github.com/wet-boew/demos/grids/grid-proximity-eng.html

**Comment by StephenOTT** [comment]
WYSIWYG Text alignment using inline styling should be css styling.  Allows better maintenance and better compliance with accessibility

**Comment by StephenOTT** [comment]
Add ability to create Definitions

**Comment by StephenOTT** [comment]
Add ability to create footnotes
http://ircan-rican.gc.ca/projects/wet-boew-footnotebas
http://ircan-rican.gc.ca/projects/wet-boew-footnotebas/wiki/Accessible_footnotes_-_Feature_guide
http://wet-boew.github.com/wet-boew/demos/footnotes/footnotes-eng.html

**Comment by StephenOTT** [comment]
Adding to previous posts.
TinyMCE should support only be applying CSS styles and no HTML inline styling.

**Comment by joejoseph00** [comment]
Hi @sylus, I see you sacrificed another beautiful long weekend for our benefit,

I tested the new TinyMCE integration, bilingual functions are much better than our D7 implementation that we have for our Intranet.  Super happy that you were able to get that working!

One item I noticed on the french side of it: 

A) Alpha sort of translated WetBoew menu 
- Would be nice if we could Alphabetical sort for the "WetBoew Outils et Opérations de Nettoyages" menu items
- currently they have the english sort order, would be nice to have the alphabetical sort of menu items occur after translation.  This would require some effort to improve as I think the order is currently hard coded.

B) "Separate the teaser and body of this content" , missing translation, but what does this function really do?
missing the translation "Séparer le sujet et le corps de ce contenu"  - I'm not really sure what this does other than put a blank row in the content body.  
- So actually this item might make more sense if it was called "paragraph break" ,  "saut de paragraphe"  or something to that effect.  
- Unless of course the feature isn't working correctly and it does something else other than just put in an empty row.

Many thanks again,

**Comment by StephenOTT** [comment]
ISSUE: Expect Error Message: 

When creating a new content page, if the user inputs a page title but does not add any content into the body and selects save the page refreshes but does not save the page. The user must supply body content in order to save the page.  The user is not supplied with a error message that tells them they must supply body content.

**Comment by sylus** [comment]
Closing this issue as believe all problems fixed. If a specific problem still exists please file an issue for that.
