### ISSUE TITLE
Error notice when modifying a box

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#273]
following:
Notice: Undefined property: stdClass::$body in _linkchecker_add_block_custom_links() (line 889 of /Users/myuser/Sites/OttawaWET/drupal_wet2/profiles/wetkit/modules/contrib/linkchecker/linkchecker.module).
Notice: Undefined property: stdClass::$body in _linkchecker_add_block_custom_links() (line 893 of /Users/myuser/Sites/OttawaWET/drupal_wet2/profiles/wetkit/modules/contrib/linkchecker/linkchecker.module).

Go to edit a box and make a simple change in the  WYSIWYG editor and press save.  The error appears after save

**Comment by sylus** [comment]
Fixed! ^_^
