### ISSUE TITLE
Scrolling Issues when in the Pane creation/configuration modal windows

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#277]
When creating a new pane to place on a page, if the configuration modal for that window requires scrolling, there is noticeable flickering that occurs on the page.  Also if you are on a Mac it is even worse because once the modal reaches the bottom of the modal window for scrolling the browser attempts to scroll the content behind the modal window.

Very noticeable when adding a Content List pane

**Comment by sylus** [comment]
I believe the flickering is resolved but for the scrolling issue I think this more of a usability problem then a bug. Moving to appropriate area.

**Comment by sylus** [comment]
This should be fixed upstream in either Panopoly or Panels.

**Comment by sylus** [comment]
Closing this for now as not something in WET's perview but will stay as an issue for posterity in case anyone does want to tackle this.
