### ISSUE TITLE
Splash Pages

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#280]
Need to provide capabilities for Splash Page generation
http://wet-boew.github.com/wet-boew/demos/theme-gcwu-fegc/index-eng.html#splash

**Comment by sylus** [comment]
I am looking at this module http://drupal.org/project/splashify to solve this as the code looks pretty clean at a cursory glance. Opinions @mgifford?

**Comment by StephenOTT** [comment]
There is also the 404 pages to look into

**Comment by StephenOTT** [comment]
The ability to show the splash page on any page will be a great feature.   Highly valued

**Comment by mgifford** [comment]
In general I think splash pages are a usually complete waste of time.  I can't wait till that's embraced by the UX usability folks.

There are some examples in splashify where I could see it being of an actual benefit, but for the distro I think it's probably overkill.

For GoC splash pages I think it's easiest to set up a index.html file that apache reads by default.  We might need do have a quick javascript file look for a local cookie to decide to redirect the user to the index.php page.

That's worked alright for some sites we've built in the past as we could ensure all internal links went to the index.php file (ie. /home will with clean url's enabled).  

I like the ability to show a notice on any page as @StephenOTT but wonder if it should be in the distro or in an extra app that is installed with other options.

**Comment by colans** [comment]
Don't bother with splash pages.  They decrease usability by adding an extra click for users to get to the data they want.  Instead, do what we're doing on https://buyandsell.gc.ca/ : Use different language domains.  Core Drupal supports this.  We've been doing it for a while, and the CLF folks were fine with it.

**Comment by pjackson28** [comment]
In the GC, you are still required to have a splash page in the odd chance you don't know the language preference, but the recommendation is to avoid sending the user there wherever possible. You should be sending the user to a language-specific page wherever you can make a reasonable assumption regarding the user's language preference (e.g., based on domain name language, referring search engine language, referring site language, etc).

**Comment by mgifford** [comment]
Sounds like a nice little module that someone could set up to extend Drupal's language awareness options.

Are browser preferences considered a reasonable option?  I think they'd be as accurate as referring search engine language.

i18n doesn't have a means to present an optional splash page if there is no reasonable default. 

Although as @colans said, with https://buyandsell.gc.ca/ or https://achatsetventes.gc.ca/ you know.

If there are double barreled names - https://achatsetventes-buyandsell.gc.ca/ & https://buyandsell-achatsetventes.gc.ca/ then you're likely going to use the server or a separate PHP script to check for reasonable assumptions and if there isn't a reasonable one, present a splash page.

For sites like https://fin.gc.ca however, you might not be able to use this approach.

Would be fun if location was something that could be considered as part of a reasonable assumption. I'd think most people from Quebec would want https://fin.gc.ca served in French & most folks in BC would want it served in English.  I'd say that's reasonable.

**Comment by StephenOTT** [comment]
Could we extend the splashify module slightly to use the option to display the slash page when no preference is available?

**Comment by pjackson28** [comment]
What is reasonable should probably be figured out through Web analytics. For instance what % of users originating from Quebec continue in French? What percentage of users with English browsers continue in French? How accurate is search engine referrer language? Would be good to have data to either validate or refute the assumptions. Does anyone have access to such analytics?

**Comment by pjackson28** [comment]
Where there is a clear majority then it would likely be reasonable to assume language preference. Where it is not clear, then should probably use a splash page. For the minority that the assumption is wrong, they always have the option of switching the language on the resulting page.

**Comment by colans** [comment]
> you are still required to have a splash page in the odd chance you don't know the language preference

I can't see a situation where this would ever happen.  If a user types in buyandsell.gc.ca, he/she wants English.  If a user types in achatsetventes.gc.ca, he/she wants French.  Any links to the site would hopefully be sent to the proper domain that matches the context of the source.  If the source author gets it wrong, the user can hit the language switcher.  This is the same number of clicks as with the splash page, but the splash pages forces the user to click, when with the language switcher, it's generally not necessary.

Therefore, there is no need.  Let's not reduce usability unnecessarily.

**Comment by pjackson28** [comment]
What about canada.gc.ca, servicecanada.gc.ca, ec.gc.ca, justice.gc.ca, fin.gc.ca, tc.gc.ca, pch.gc.ca, etc? There are many domain names that are the same in both languages (including when fully expanded) so it is not always clear what the language preference is from domain name alone. You are just fortunate enough to have English and French domain names that are unmistakeably different.

**Comment by StephenOTT** [comment]
@colans You are also assuming that the user is typing in a URL.
Example: QR codes are used on Land Development signs to allow people to scan the QR code and take them directly to the detailed information page.  This URL is much to long for a user to remember or type in and they are new ones all the time.  Currently on the signs there are two QR codes (one for the English url and one for the French).  This was done because the splash page option was not available as a callable feature.
Also lets not forget about the multilingual splash pages.  While not used often, they do have their purpose for several types of pages.
Example: the City has immigration and visitor landing pages that are available in multiple languages.  We would not want to constantly have to provide different URLs for every language.  One url that activates the multilingual splash page.

**Comment by colans** [comment]
That's a good point; you're right.  I didn't realize those existed; I've only ever gone to sites like "cra.gc.ca"/"arc.gc.ca".   In that case, if you can't detect it from the browser or the geographic region, I suppose it's necessary.

**Comment by dsamojlenko** [comment]
I tried the splashify module but I didn't like it... it uses javascript that fires a redirect on front page (or any arbitrary page) load.  Problem is, the full page loads before the javascript fires so you get a rather long flash of the front page before going to the splash.

I have another method that works, but would like opinions on if there is any reason not to do it this way.  In the .htaccess file, I've changed the DirectoryIndex default to index.html (instead of index.php) and I just have a static index.html splash page that links to either /eng or /fra.  Since the rewrite rules take over once there's a path, anything below / gets processed by index.php.

I guess this wouldn't work if you have language-specific domains (since your front page would always be domain.gc.ca with no path), but we're using the path prefix option for language detection, and that's the default for the distro, so this method should work for many.

**Comment by RobJohnston** [comment]
One problem I can think of is with multisite because if there is a single index.html file at the root it will be used for all the sites, and all sites won't have the same name (obviously!) and possibly won't have the same links to the English, French, or Terms and conditions pages.  

The best way I see around it is to create a server-side script page that gets processed by the web server before index.php and within that file read the domain name and either go to the English if it is one of the English domains, go to the French if it is one of the French domains, or show the splash page with the titles and links set for the domain of the multisite.

**Comment by sylus** [comment]
Cleaning up some old issues. :)
