### ISSUE TITLE
wet.openplus.ca not going into mobile mode on iphone

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#283]
When you access wet.openplus.ca site does not go into mobile mode.

**Comment by StephenOTT** [comment]
@sylus This a planned change?

**Comment by sylus** [comment]
Hmm there must be something missing as if you use your browser it does indeed switch although for iphone it is not working. I will talk to Paul Jackson about it tomorrow. Likely something simple ^_^ Thanks for catching!

**Comment by StephenOTT** [comment]
Also does not work for ipads or Blackberry playbook.  Same issue.  No switch to mobile version.

**Comment by sylus** [comment]
Fixed!
