### ISSUE TITLE
Lightbox support?

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#284]
Are we expecting Lightbox support?
http://wet-boew.github.com/wet-boew/demos/lightbox/lightbox-eng.html

**Comment by sylus** [comment]
This is now enabled by default on the field_featueed_image. Only thing now is to make it work on another field for gallery type functionality when dealing with many images.

**Comment by sylus** [comment]
Closing this for now as lightbox is working :)
