### ISSUE TITLE
Intranet:  Remove Blue Banner Margin

### ISSUE THREAD

**Issue by csedev** [wet-boew/wet-boew-drupal#288]
The blue header bar has a margin-bottom that needs to be set to 0.  Current version displays a gap between the blue and green bar.

**Comment by csedev** [comment]
Code to fix:

```#gcwu-bnr-in {
  #gcwu-title {
    margin-top: 0px;
    padding-top: 7px;
    margin-bottom: 0px;
  }

```
```

**Comment by sylus** [comment]
Please create a pull request ^_^

**Comment by sylus** [comment]
Fixed thanks!
