### ISSUE TITLE
Intranet: Server Warning Pages Broken

### ISSUE THREAD

**Issue by csedev** [wet-boew/wet-boew-drupal#289]
The Intranet server message pages aren't loading properly.   See attached screenshot.  

![Access Denied Screenshot](http://www.opin.ca/dvp/access-denied.png)

**Comment by sylus** [comment]
I can't reproduce this. Can you grab the absolute latest and check your permissions?

**Comment by sylus** [comment]
Check out http://wet.openplus.ca I switched to Intranet mode and everything is a-ok.

**Comment by sylus** [comment]
Oh actually I can, it is something to do with adaptivetheme + generated_files and permissions. A secondary save seemed to fix it but think it has to do with the generated_files not having permissions on the server to regenerate themselves. I likely should be saving them in default/files rather then in the theme.

**Comment by StephenOTT** [comment]
I ran into the same problem the other night after your recent pull request and i ran a drush update on the config.  Did not troubleshoot just reinstalled base

**Comment by sylus** [comment]
Looks fixed now!
