### ISSUE TITLE
json2 library was not found

### ISSUE THREAD

**Issue by csedev** [wet-boew/wet-boew-drupal#290]
After installation, status report shows "json2 library was not found".  Should we be including this library in the installation profile?

**Comment by sylus** [comment]
Hmm it is for grid builder and layout which are disabled, so is json2 in the make file. I guess it can be included by default

**Comment by csedev** [comment]
If you don't need the library, just disable the JSON2 javascript library module by default.

**Comment by sylus** [comment]
Fixed
