### ISSUE TITLE
How do I get the default toolbar back?

### ISSUE THREAD

**Issue by csedev** [wet-boew/wet-boew-drupal#292]
I've disabled the administration menu modules and have enabled the toolbar module, but the toolbar still does not appear.  Does anyone know what other changes are required to restore the toolbar back to its default settings?

**Comment by sylus** [comment]
The admin menu is present for user 1 by design, if you were any other user if would be regular toolbar. Why do you want to change this?

**Comment by csedev** [comment]
What was the design reasoning for replacing the toolbar for user 1?

**Comment by csedev** [comment]
Answered my own question.  For anyone else that is interested in doing this, 

Edit the wetkit_users module file and comment out this function.

`function wetkit_users_page_build(&$page) {
  // $page['page_top']['toolbar']['#access'] = wetkit_users_toolbar_access();
}`

**Comment by sylus** [comment]
I still don't get the point for this. User 1 is the super user and I know most developers prefer admin menu then toolbar. In fact it was based on developer opinions this was brought in. I am all for open discussion but definitely need to make sure we are not setting a precedent for debating every design decision that have already been discussed.

Of course by that token not against debating some decisions if there is a clear rationale. All about balance. :)
