### ISSUE TITLE
Install fails due to missing entitycache module

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew-drupal#31]
I get the following error when pointing a web browser to the site for the install:
<code>
Fatal error: require_once() [<a href='function.require'>function.require</a>]: Failed opening required 'D:\internet\dmz_drupal/profiles/webexp/modules/contrib/entitycache/entitycache.module' (include_path='.;C:\php\pear') in D:\internet\dmz_drupal\includes\bootstrap.inc on line 3069
</code>

Looking at the directory structure, I see that there is an "entity" directory but not an "entitycache" directory.  For what it's worth, the Drush Make command's only reference to entity is:

<pre><code>
 >> Project entity contains 2 modules: entity, entity_token.
entity-7.x-1.0-rc3 downloaded.
</code></pre>

and

<pre><code>
file_entity cloned from http://git.drupal.org/project/file_entity.git.
</code></pre>

**Comment by sylus** [comment]
Hey yeah entitycache has been removed from the install. Are you trying to use drush make to update an existing install or run a fresh one. If running a fresh one there should be no reference to entitycache so am unsure why you are getting this error.

You could go to your .drush directory and remove the cache folder which could be causing some of these problems. I think for some reason you are using an outdated webexp.info file which probably has the entitycache entry.

Overall this is likely a cache issue. Please let me know more about this if the problem persists as want to get as many people as I can evaluating the new (and amazing) changes!

**Comment by RobJohnston** [comment]
I was trying to do the install fresh by wiping out all the old files and deleting the database.  I had deleted the cache/download directory but realized upon retrying that the database tables were still there.  Sorry for scaring you... forward we go.  Got a redirect loop on the install.php page which I'll look at after lunch.

**Comment by RobJohnston** [comment]
Got past this issue.  Installed on IIS6 and MS SQL Server without problems.  For issue #20, it's clear now that the description is something I was researching for issue #19.  That's a cut-and-paste error and after 23 days I no longer have the correct page and patch, but believe me... it was true at the time.
