### ISSUE TITLE
Kick out of mobile and into full version of website

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#317]
Probably more of a wet issue.  But when we go into mobile mode, how does a user on a mobile device that is in mobile mode kick out into the full version?  Often users will like to go to the full version of the website and use the devices page zoom capabilities.

**Comment by sylus** [comment]
Yeah this is more of a WET issue :) Please repost in WET-BOEW :)

**Comment by StephenOTT** [comment]
Done.  Posted in wet-boew
