### ISSUE TITLE
Web feeds widgets

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#318]
Meta catch all for the different web feeds, rss, twitter, etc.

**Comment by sylus** [comment]
This is integrated as a cutom formatter along with lightbox and a few others :)

**Comment by StephenOTT** [comment]
I assume the configuration options are provided in the configuration modal window when adding the pane?

**Comment by sylus** [comment]
Leaving issue open for now as need to write documentation as these are different then adding through the pane. They use custom formatters which is on the field level. Very cool!

**Comment by sylus** [comment]
Added!

**Comment by mgifford** [comment]
Can you send a link to the documentation?

Also, are there any examples in Drupal of the Share Widget for social media? https://github.com/wet-boew/wet-boew/issues/2569
