### ISSUE TITLE
Pre-Built Server Clusters hosted by SSC (working plan)

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#319]
So we are in talks with SSC and a key sticking point with the WET Drupal Distribution is the amount of time it takes to setup the environment that Drupal runs on.

There is where work has been done using Vagrant + Chef in the https://github.com/sylus/wet-boew-drupal-devops repository.

Based on this initial work it is time to build a complete and performant stack that both developers and hosting providers (SSC) can all use.

After an exhaustive amount of researching I believe Vagrant and Chef is the way to go and now see the only problem explaining the power of these two applications to people who might not have heard about them before.

As a quick reminder:

> Vagrant (http://vagrantup.com/) allows for you to create and configure lightweight, reproducible, and portable virtualized development environments. You can then use such commands as vagrant ssh and vagrant up etc.. (Vagrant builds itself on top of Virtual Box).

The box package I am working on will have (powered through a Chef provision - CHEF ROCKS!):

> RHEL 6.3 (Government Preferred Linux Standard)
> The WetKit Distribution
> All needed php libraries
> Apache 2.4
> Apache Solr 3.6 + Tomcat 7
> Varnish
> Memcache

What benefits can be gained from such work?

> 1) A preconfigured standardized stack across all development and hosted environments (VMDK)
> 2) Best practice implementations and configuration of all configuration files
> 3) When bugs in the distribution are discovered we can be assured it is not to do with an incorrect setup or permissions problem
> 4) The ability to show how Drupal interacts with services such as Solr + Alfresco
> 5) No need to install and configure custom applications on Windows computers other then Virtualbox + Vagrant. A simple vagrant destroy will also completely remove the built VM

So this is a call to arms as I see the biggest barrier to mass Drupal adoption in government the lack of resources to install and configure an appropriate stack. I know Shared Services Canada is behind us but we need to do the work here first before the hosted solution can be up and running. As an aside I know previously this was marked as low priority but I believe that is incorrect and this should be marked of highest priority. We need to simplify all possible barriers and show just what Open Source can do! 

So who wants to help? I can say any individuals, departments, governments, private companies who assist in this will get a special mention in our soon to be released contributor page! Which should help to increase your profile and count greatly to collaboration with Drupal WET a skill that will soon be in high demand!

@StephenOTT @mgifford @patcon @joel-osc @joejoseph00 @eleclerc @openplus @sinkinsona @pjackson28 @LeeHunter and countless others :)

**Comment by StephenOTT** [comment]
@sylus As always you can count us in.

**Comment by sylus** [comment]
Requirements

> 1) Must work on Windows (no exception)
> 2) Must meet the package requirements discussed above (RHEL, Varnish, Memcache, etc)
> 3) Must be a VM that doesn't suffer from slowdown as some VirtualBoxes do (However some great minds seemed to have solved this problem)
> 4) Must have the ability to convert to the format Shared Services requires so they can easily host
> 5) Must have complete documentation on what is installed and configured and custom configurations (Chef has a lot of this)
> 6) Must pass a strict security review (We have RedHat contacts for this)
> 7) Must have a policy for VirtualBox + Vagrant to be installed on local computers in government (Working on this on higher up levels)

Nice to have:

> 1) Ability to provision to an Amazon EC2 server for people whose local computer (on dev installs) are not powerful enough and not able to deal with SSC

**Comment by StephenOTT** [comment]
> Nice to have:
> 
> 1) Ability to provision to an Amazon EC2 server for people whose local computer (on dev installs) are not powerful enough

What do you see as the minimal sys requirements for the VM?

**Comment by sylus** [comment]
Usually the minimum requirements for a local VM is:

1) Duo Core @ 2.4 GHZ
2) 4Gigs Ram (8 gigs would be preferred)
3) 1-2 Gigs space for swap + vm format

**Comment by sylus** [comment]
@ottawadeveloper

**Comment by sylus** [comment]
Hey @joejoseph00 I get your frustration but lets not confuse the issue. I know some people at SSC will be reading this post and I don't want them or other departments thinking we are asking for a Wild West type of development. The idea here is we get SSC to help us convince management across departments that there are a few applications (x2 VirtualBox + Vagrant) that should be allowed to be installed and absolutely do not constitute a security risk. In fact the argument can be made this is more secure as a VM is logically separate from Windows installations and can be completely destroyed.

If some departments do not agree with this maybe SSC can step up and provide shared development environments.

Also not everything goes at statscan we just recognize that developers should be allowed to develop. Of course there are approvals that have to be followed and rationale given. Common sense prevails here.

As for cost I will run that through today and see what we can do about that.

Your point about running php 5.2 validates my points given in post 1 we are not all on the same environment. Also I bet your configuration for varnish + memcache is wildly different as well. We absolutely need to minimize complexity and have consistency across environments if only to minimize bug reports and have a more stable platform :)

**Comment by StephenOTT** [comment]
@joejoseph00   It is vitally important for new developers to be able to get a stable development and future production system up in short periods of time with relatively few resources.  Those are the conditions we work under: Short Timeline expectations with minimal resources.  

If we are able to provide a standardised base for developers to build on and deploy to, we can help to ensure that development islands are not created in a scenario where that island cannot find help from the community because they have created a completely custom scenario that is troublesome for anyone to replicate.

If we provide an environment that fosters easy adoption of Drupal Wxt, we can usher in new developers very easily and ensure that the learning curve for the distro is not so great that developers are either extremely slow to learn and take a long time until they are able to contribute back to the community, or have a situation where the initial setup is something left to a very few group of people.  if either of those occurs we are hurting the development community and focus is not spent on drupal development, it is spent on troubleshooting server configurations against Drupal Wxt.

The focus is Drupal.  A Drupal development community that can easily support Drupal Wxt under standards and common configurations (both server and drupal).  We should be striving to help mitigate the amount of time spent on troubleshooting a configuration issue, so developers can actually develop new functionality and features, and one of the first steps in doing this is providing a base/benchmark that we know is functional.

**Comment by joejoseph00** [comment]
I am open to using SSC hosted servers for Drupal hosting.  We'll need to know:
1) how much it will cost per month
2) what are the restrictions/conditions/terms of service
3) is it mandated to use the SSC servers for Drupal or is it optional ?
4) does the server include other services such as a business continuity plan, recovery plan

Note: If it is mandated by SSC (as in, not optional), we'll have an easier time ramming it through the FUD .

**Comment by openplus** [comment]
Hey Will,

We can help on several fronts... with the key issues being planning and timelines.
It's clear many people have vested interest in having such a set-up.

Some of this conversation should be elevated... as I think RHEL can help here, I'll talk to my contacts (I think they know the PWGSC VMWARE set-up more than anyone). I'm sure they can't help with item#1 lol tough !!!

Jose at our end can also commit to some time here.

P.S. I can't help but mention that PWGSC and Shared Services should really step-up here. Keep in mind they charge for their hosting... as leveraging the a free and willing community should for contributions should only go so far. I think some would prefer to help with Drupal code, as this is primarily infrastructure.

**Comment by mgifford** [comment]
Can you provide verification that this can be also used to manage configuration of both a physical server and a virtual  Xen instance?

VirtualBox is a bit of a performance pig but I'd like some clarification that this is indeed only needed on a local dev environment and that we're not choosing a solution that is fixed on Amazon.

Vagrant & VirtualBox are distributed with open licenses, so that helps the costs.

**Comment by LeeHunter** [comment]
There's also ansible as an alternative to chef http://ansible.github.com/ 

It is supposed to be easier to work with and, at least in certain ways, more powerful.

**Comment by patcon** [comment]
@mgifford

> Can you provide verification that this can be also used to manage configuration of both a physical server and a virtual Xen instance?

Do you mean documented verifications, or just verbal confirmation? I can confirm that Chef doesn't care whether it's running on a virtualized system or physical one

**Comment by mgifford** [comment]
@LeeHunter It's really a question of where is the Drupal community on this.  If we can leverage the work of others then the trail will be easier for everyone.  I hadn't heard of Ansible before.

@patcon thanks for the Chef verification.  Is there documentation for using Vagrant to manage the configurations for a dedicated box? I could just have missed that in Vagrant as the defaults seem to be written for VirtualBox and Amazon.  I'm just looking for examples and best practices that are going to be useful for the bulk of government departments that aren't going to be able to use Amazon.

**Comment by patcon** [comment]
@mgifford 

>  Is there documentation for using Vagrant to manage the configurations for a dedicated box?

Ah, ok, maybe that's the confusion. Vagrant does not (at this point), support anything to do with decicated servers. All Vagrant does is manage vbox, send in files, and "kick" the internal chef provisioner to get it running. So we would run chef on the dedicated box, using the config files we've already designed to run in vagrant's VM's :)

Likely the simplest way to get this going would be knife-solo or pocketknife:
https://github.com/matschaffer/knife-solo
https://github.com/igal/pocketknife

@sylus has showed me the approach below (to use the json array built by vagrant, and send it to a remote server running chef), but I think knife-solo would be part of a longterm solution :)
https://github.com/wch/vagrant-ec2-r

**Comment by joejoseph00** [comment]
@sylus , here's a script http://wet.7pro.ca/sites/wet.7pro.ca/files/wet_drush_sh.txt for installing your drupal wet variant

The idea is to simplify the install procedure, or at least make it a bit more user friendly.

I've updated it with an updated permissions script and and re-tested it.  You may want to include this on your VM distribution, so that users can more easily install/re-install or install multiple times the distro on the same VM.  This will install the wetboew drupal distro under ~User/blah
I could polish it up aesthetically and add some code comments if you like.

Also works for those that don't have VM's

**Comment by joejoseph00** [comment]
Just want to appologize to @sylus here for comming acrosse as a sourpuss and a tad jaded.  This idea of a turn-key virtual box is a great idea.  Helps people get up and running right away so they can play.  What I like most about the group here is the spirit of creativity and getting things done.   BTW, is a virtual box ready for download ;)  ?  

I'm currently assisting Canadian International Trade Tribunal | Tribunal Canadien du commerce extérieur to get set up on Drupal for the first time.

**Comment by joejoseph00** [comment]
citt-tcce is installing centos as we speak, they're going to install the basics to get up and running and then get them to run this script  http://wet.7pro.ca/sites/wet.7pro.ca/files/wet_drush_sh.txt

**Comment by patcon** [comment]
@joejoseph00 no worries :) I'm not working on government-related work atm, but I totally understand that we need to be cautious about newfangled things. I've personally created bad experiences by pushing untested new tools into team workflows, and it's taken awhile to regain trust. So I totally understand the need to be wary, and appreciate the reality check!

PS, I'll try to work on getting the [Ariadne](https://github.com/myplanetdigital/ariadne) environment working on CentOS soon, as the automated configuration instructions should be comparable to RHEL for all intents and purposes (but I won't have to deal with licenses that I don't have)

**Comment by StephenOTT** [comment]
Great!

On 2012-09-11, at 10:03 AM, J Olstad notifications@github.com wrote:

citt-tcce is installing centos as we speak, they're going to install the
basics to get up and running and then get them to run this script
http://wet.7pro.ca/sites/wet.7pro.ca/files/wet_drush_sh.txt

—
Reply to this email directly or view it on
GitHubhttps://github.com/wet-boew/wet-boew-drupal/issues/319#issuecomment-8460676.
