### ISSUE TITLE
Use `defaults[projects][subdir] = contrib` in makefile

### ISSUE THREAD

**Issue by patcon** [wet-boew/wet-boew-drupal#321]
Drush windows installer for 5.7 is out, so can now bring back the defaults array in makefile if we want:

https://github.com/patcon/wet-boew-drupal/commit/e4ee9ab88fb61889d920946fc3876e0faa8e8a36

http://www.drush.org/drush_windows_installer

**Comment by sylus** [comment]
Unfortunately Drush past 5.4 has problems in native windows environments and still unsure why but once resolved happy to do this :)

**Comment by patcon** [comment]
I think I _just_ hit those with a coworker who I asked to upgrade. Something about the tmp directory and copying files... :(

//cc @sebsebseb123

**Comment by sylus** [comment]
Yeah exact issue we are having :) Let me know if any new developments come up. I am pretty sure any windows user would hit these problems.

**Comment by sylus** [comment]
@patcon have you heard anything more about issues with drush + windows post 5.4? (tmp + copying files fails)

**Comment by patcon** [comment]
Hm. They might not even be aware? I haven't seen the issue firsthand, and don't have a windows machine to test -- would you know whether any of these cover it?
http://drupal.org/project/issues/search/drush?text=&assigned=&submitted=&participant=&status%5B%5D=1&status%5B%5D=13&status%5B%5D=8&status%5B%5D=14&status%5B%5D=15&status%5B%5D=2&status%5B%5D=16&issue_tags_op=or&issue_tags=windows

And if not, do you have access to a machine to file a detailed bug report?

**Comment by sylus** [comment]
Yeah none of those cover the issue. I can try to file an issue when I have time ^_^

**Comment by patcon** [comment]
Or if you want to copy the error in here, I can file it

//cc @sebsebseb123: I know you're crazy-busy, but if you happen to have time (or remember details), feel free to paste here too

**Comment by sylus** [comment]
Just letting you know @patcon the latest dev of Drush fixes the Windows Installer problem. Hoping they will role a new installer soon, once that happens fixes can go in as well as default PO downloads during make process! Woot!

http://drupal.org/node/1786934

**Comment by patcon** [comment]
:+1: :)
