### ISSUE TITLE
Panel Maps Address Refresh should occur on field focus change

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#324]
When creating or editing a map location in panels focus is lost on the address field if the uses pauses for a moment. This is being caused by the GIS map refreshing it self during that pause.  A button for map refresh should be supplied and/or a map should refresh when focus moves out of address field.  If we are going to keep the auto refresh of the map, then when a refresh occur the address field just have focus so the user does not have click into the address field.

**Comment by StephenOTT** [comment]
Location on map is also not centred and popup gets cut off.

**Comment by sylus** [comment]
These automatic refreshes have been adjusted in panopoly )
