### ISSUE TITLE
Choose Theme: WetKit Adaptive Theme appears twice

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew-drupal#33]
During the install, when asked to select a theme, the "WetKit Adaptive Theme" appears twice.  The first time with a thumbnail to the left of it (just like all the other themes) and the second time right below without the thumbnail.  The titles and descriptions are identical.

I've got a screenshot if you want it.

**Comment by sylus** [comment]
Oh thanks for the catch! I really appreciate you taking the time with all of this :)

**Comment by RobJohnston** [comment]
I concur that the pull request resolved this issue and hereby humbly close my issue.
