### ISSUE TITLE
Configure Site Error Notice - Undefined Index: field_name in title_field_replacement_enabled()

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#338]
Error notice appears on Configure Site page during install.  Appears about 30 times in a row on the page.:

Notice: Undefined index: field_name in title_field_replacement_enabled() (line 220 of /Users/myuser/Sites/OttawaWET/drupal_wet/profiles/wetkit/modules/contrib/title/title.module).

**Comment by StephenOTT** [comment]
Appears another 5 times on Verify Apps Support page

**Comment by sylus** [comment]
Bah the new title integration seems to be causing this. Does not appear in drush site install.

**Comment by StephenOTT** [comment]
In a related error message.  There has been a lot of the same types of error appearing when you run a module update.  The page becomes consumed with red "x"'s

**Comment by sylus** [comment]
Fixed for now by temporarily disabling title module.

**Comment by uottawa-wcms** [comment]
Did you ever figure a fix for this @sylus? We have the same issue occuring on first installation as well (which I'm getting around by hiding all the error messages on install).

**Comment by sylus** [comment]
Nah no fix atm but most certainly annoying!

**Comment by sylus** [comment]
Wow this has been fixed for a while. Closing!
