### ISSUE TITLE
Obfuscating E-mail Addresses

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#343]
Anyone have a nice easy to use solution that is still accessible?

**Comment by sylus** [comment]
This might work: http://drupal.org/project/geo_filter

**Comment by timwood** [comment]
We use Graceful Email Obfuscation Filter (GEO Filter) on the Drupal 6 website for the US Department of Commerce. http://www.commerce.gov/

**Comment by sylus** [comment]
Looks like this is the way to go then :)

**Comment by sylus** [comment]
So looking to close this issue but wanted to confirm that geo_filter should then be added to the distro?

**Comment by StephenOTT** [comment]
I would support adding it to the distro. +1

**Comment by StephenOTT** [comment]
Is this being added to distro? @sylus

**Comment by sylus** [comment]
This is in the CKEditor 4.1 by default as it encodes all email addresses for us automatically :)
