### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by uottawa-wcms** [wet-boew/wet-boew-drupal#352]
@sylus or anyone else with experience.

We just deployed the latest version of WET here and found the memory needs to be drastically increased (our other installs were working off of a 128MiB limit for PHP scripts, we had to increase it to 256MiB to successfully install and view most pages - the modules page is still reporting errors). 

Has anyone had similar issues and/or have any ideas on how we can cut down on the memory usage?

Rob

**Comment by sylus** [comment]
You should be able to install with 192MB which is the requirement. The distro now includes search api + some crazy ctools enhancements which increases the footprint no way around it ^_^ However nothing significant above and beyond our old distro.

192MB is acceptable for distributions, in fact Open Public and Panopoly (which ours is based on) both recommend minimum 192MB.

I am a bit confused why you have to jump up to 256MB to install though. This could be related to some other settings in your php.ini perhaps max packet size is only set to 1M or 2M?

I can confirm based on a drush install with --debug that the memory never actually exceeds 128M

Are you doing a drush or browser based install?

Also keep in mind after the initial install the memory limit needed is dramatically lower. Default Content uses a lot of the memory during first install.

I definitely think this is related to some other settings in your php.ini file. ^_^

**Comment by sylus** [comment]
Actually the memory used is far lower then I originally thought only 85MB as per the end of the drush install below:

<img src="http://dl.dropbox.com/u/38413195/drush_install.png">

**Comment by uottawa-wcms** [comment]
I did a browser install, but I was receiving errors even after I got past the installation procedure. Boosting the memory to 256MiB fixed it (Xavier has been handling that side of things). I am still actually getting errors at 256MiB of memory available, but only on the module page.

The specific error is a warning "Unable to allocate memory for pool" which is being triggered by calling a require or include. The more complex the page, the more warnings are triggered.

I have a bit more information now - other teams here that are using non-WET Drupal distributions reported similar issues after upgrading to 7.15. They removed them by upping the memory limit, but obviously we don't want to do that too much. So it may not be WET specific.

**Comment by sylus** [comment]
I know that error lol :) It is an apc.shm_size error set it to something higher in php.ini :)

**Comment by uottawa-wcms** [comment]
Gotcha - Xavier just looked at those settings and boosted the shm_size to 1GB. Error is gone now.

**Comment by sylus** [comment]
Wow lol that is a bit high no? lol

**Comment by uottawa-wcms** [comment]
I'm actually not really sure lol - I'm a software guy mostly. It's what he set the production environment to and it seems to be working, so I'm not really going to complain :).

**Comment by sylus** [comment]
The range I am accustomed to is between 100MB - 250MB. Remember this is a multiplier to apc.shm_segments, while the default is one this could cause a problem down the line.

**Comment by joejoseph00** [comment]
We could probably share our prod settings for the php.ini and apache memory settings, I know we did have to adjust both of those.
