### ISSUE TITLE
Drupal 7 WET Distro Geo App 

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#361]
Given the collection of OpenLayers modules:     
- geofile  
- openlayers_filters  
- geocoder  
- geophp  
- openlayers  
- openlayers_plus  
- geofield  
- mapbox  
- openlayers_blocks  
- staticmap  
- location  
- leaflet  
- openlayers_solr  
- views_geojson  
- search_api_location 
- geoserver
- postgis
- OpenLayers Locator - ol_locator
- openlayers_proximity

The fact that there is now plausible support for a more accessible 2.12 version of OpenLayers.  Might make sense to try to wrap these up as an app.

Frankly, mapping is complicated.  The more we can do to simplify it through configurations we know to work, the easier it will be for everyone to use.  

Also, one of these modules requires beans and how will that work with boxes?

**Comment by StephenOTT** [comment]
Another to add is AddressField and geoRSS

**Comment by sylus** [comment]
Hey @mgifford bean seems to be where everyone is going. Ideally i'd like to replace boxes with bean as it also seems the projects are merging. Have to look more into this.

**Comment by mgifford** [comment]
GeoRSS hasn't been ported to D7.  I'm not clear what's the best path to replace it though.  As I said on d.o it might be http://drupal.org/project/rss_field_formatters

However with all of these tools they take time to put together & maintain.

**Comment by StephenOTT** [comment]
@mgifford   may want to look at mapbox module as it is fairly out of date

**Comment by StephenOTT** [comment]
Openlayers is pretty heavy.  Would be good to add leaflet in for the general uses.  Most users do not need the massive amounts of features and projection options that openlayers provides.  Usually mapping needs are to show a very specific dataset with some filtering options

Previous GIS WET discussions at #246

**Comment by mgifford** [comment]
I haven't evaluated mapbox lately. All of the modules I listed above simply meet the criterion of having an active D7 release.  That's not really enough though for me to be comfortable with them getting into an app.  

The GoC can't use GoogleMaps, but this may be an option for the city.  Other than OpenLayers, what other simpler mapping options do you see?  OpenLayers can be (in fact should be for performance) built for the specific purpose that it's being used for.  I haven't done performance testing on it though.  

There are still accessibility challenges with OpenLayers 2.12, but it's a better starting point than the last code I saw as part of WET.

**Comment by StephenOTT** [comment]
The bigger question is the integration of GIS type data into a drupal environment.  
Are we providing only a front end or a GIS backend as well.
Front end being the js to view a map from a different data source or are we going to provide the spatial information into the database?  If we are getting into database territory, we should be looking at the Geoserver, PostGIS.  We can provide a great front end, but how the data is being stored creates a bottleneck very quickly when users will want slightly more advanced spatial functions beyond displaying content on a map.  Spatial queries (even simple ones) creates a bottleneck.

CartoDB is a interesting option and it open source.  Minimizes learning curve for end user to produce map with spatial query support.

nice write up on PostGIS and geoserver: http://www.geops.de/blog/64-spatial-data-and-drupal-7

**Comment by mgifford** [comment]
Very interesting.  Did you have a chance to look at this Drupal distribution - http://cartaro.org

That being said, let's start with some baby steps and work up to something that could perhaps compare.

I added Geoserver & PostGIS btw.

**Comment by sylus** [comment]
I just took a look at the distribution and how it is assembled, if we indeed wanted to go this way wouldn't be difficult to have it as an app. :)

The info file for this app would have just the following dependencies along with a corresponding make file:

```
; Contrib modules
projects[feeds][version] = 2.x-dev
projects[feeds][subdir]  = contrib
projects[geoserver][version] = 1.x-dev
projects[geoserver][subdir]  = contrib
projects[job_scheduler][version] = 2.x-dev
projects[job_scheduler][subdir] = contrib
projects[nodetype_access][version] = 1.0-beta4
projects[nodetype_access][subdir]  = contrib
projects[nodetype_access][patch][] = http://drupal.org/files/nodetype_access-fix_empty_types-1426702-3.patch
projects[ole][version] = 1.x-dev
projects[ole][subdir]  = contrib
projects[openlayers][version] = 2.x-dev
projects[openlayers][subdir]  = contrib
projects[postgis][version] = 1.x-dev
projects[postgis][subdir]  = contrib

; Libraries
libraries[ole][download][type] = file
libraries[ole][download][url]  = https://github.com/geops/ole/tarball/master
libraries[ole][download][subtree]     = client
libraries[openlayers][download][type] = file
libraries[openlayers][download][url]  = http://openlayers.org/download/OpenLayers-2.12.tar.gz
```

We'd also have to have our own functionality like frontmap + cartaro_demo

**Comment by StephenOTT** [comment]
I looked over cartaro a few weeks ago. Was interesting but the complexity remains with having to work with the opengeo stack.  

Is interesting but would you see us using PostGIS sync or moving from mysql to postgres as the base db?

**Comment by sylus** [comment]
I do love postgres but don't think we would (at least at STC) be moving to it particularly because some of the more recent improvements in MySQL 5.6 as well as other factors. Your right though as I don't think we would be able to use postgis. Although it does seem postgres works really well for spatial queries though haven't done too much research on this.

**Comment by StephenOTT** [comment]
For that reason a cartodb like solution is an attractive option.  There is
also the postgis sync module

On 2012-09-09, at 4:01 PM, William H notifications@github.com wrote:

I do love postgres but don't think we would (at least at STC) be moving to
it particularly because some of the more recent improvements in MySQL 5.6
as well as other factors. Your right though as I don't think we would be
able to use postgis.

—
Reply to this email directly or view it on
GitHubhttps://github.com/wet-boew/wet-boew-drupal/issues/361#issuecomment-8408615.

**Comment by mgifford** [comment]
I'm not going to add the OpenLayers Editor to the list, but pretty neat stuff - http://drupal.org/project/ole

**Comment by StephenOTT** [comment]
Also good to add LocalSolr

http://wiki.apache.org/solr/LocalSolr

**Comment by mgifford** [comment]
Is that different than http://drupal.org/project/openlayers_solr - looking at the description it seems like it might be included.

**Comment by StephenOTT** [comment]
My understanding is that the openlayers_solr modular provides integration between solr and drupal for spatial searches.  But unclear that LocalSolr is installed as part of this module

**Comment by StephenOTT** [comment]
@mgifford 
An interesting project to monitor and possible leverage from:
OpenLayers Locator: http://drupal.org/project/ol_locator

**Comment by StephenOTT** [comment]
Another OpenLayers module to add to the list:
http://drupal.org/project/openlayers_proximity

**Comment by mgifford** [comment]
Some discussion about the future of OpenLayers going on here: http://drupal.org/node/1331410

**Comment by sylus** [comment]
Cleaning up some old issues. :)
