### ISSUE TITLE
Can't enable WetKit Security Features

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#363]
I enabled this feature from eng/admin/structure/features

And immediately got:

Fatal error: Cannot redeclare wetkit_defaults_create_password_policy() in /Users/mike/shared/htdocs/wet-boew-drupal/profiles/wetkit/modules/apps/wetkit_web_usability/wetkit_security/wetkit_security.module on line 19

Best to remove this and add it as an app or something.

**Comment by sylus** [comment]
This module has been removed as well as wetkit_web_usability has been renamed to wetkit_wetboew for more clarity. Your git repo is out of sync by a little bit. Try the latest we now have awesome search api integration :)

**Comment by mgifford** [comment]
So if I do:
drush make --no-gitinfofile --working-copy https://raw.github.com/wet-boew/wet-boew-drupal/master/build-wetkit.make .

in the sub-directory then this should all get fixed up, right?  Any feature that's been outdated should be removed.

If so then it's still there from this morning and also from 10 minutes ago.  If not, how do I make sure that I've got the latest versions?  I must be missing something.

I think wetkit_wetboew sorta sounds like a nasty disease.  Not sure it adds clarity, but I will be less likely to try it.

**Comment by sylus** [comment]
Hmm drush make only replaces files it knows about not preexisting files, so it looks like you have both wetkit_wetboew  and wetkit_web_usability. Not sure how we can get around this :S

Yeah the naming is that of wet's library: wet-boew so using that convention as the library is loaded inside of wetkit_wetboew using libraries api. Am open to a better name though.
