### ISSUE TITLE
 Drupal Pre-Built gives 404 error

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew-drupal#37]
The link in the README.md file for Drupal Pre-Built is broken... 404 error for https://github.com/sylus/wet-boew-drupal-compiled.  I've got to install on a machine without Internet access so the apps don't work.

P.S. Installed on Linux with PostgreSQL last night at home and worked fine.

**Comment by sylus** [comment]
Hey yeah I have been meaning to do this. Ideally will push an initial build out after the weekend once some remaining issues are resolved. Ideally I am hoping though that most people will still build their own repo here as the other one will only be updated monthly.

**Comment by RobJohnston** [comment]
Any other ideal on how one could run the drush make command on a connected computer, move the files to the disconnected computer, and still get the apps portion?  It's just that last part that's needed.

**Comment by sylus** [comment]
The apps are local ones they should install regardless of an outside connection.

Are you referring to the apps (only one so far) housed on the webexp external server? If this is the case there is a process to manually download the app and add a manifest.app file.

Can you let me know a bit more of some problems your running into?

**Comment by RobJohnston** [comment]
The step that is failing is on "Install apps for WetKit (local)".  The error is:
<code><pre>
    Warning: file_put_contents(temporary://fil52AD.tmp) [function.file-put-contents]: failed to open stream: "DrupalTemporaryStreamWrapper::stream_open" call failed in file_unmanaged_save_data() (line 1900 of D:\internet\dmz_drupal\includes\file.inc).
    The file could not be created.
    Notice: Undefined property: stdClass::$uri in file_save() (line 570 of D:\internet\dmz_drupal\includes\file.inc).
    Notice: Undefined property: stdClass::$uri in file_entity_file_presave() (line 14 of D:\internet\dmz_drupal\profiles\webexp\modules\contrib\file_entity\file_entity.file.inc).
    Warning: file_put_contents(temporary://fil52AE.tmp) [function.file-put-contents]: failed to open stream: "DrupalTemporaryStreamWrapper::stream_open" call failed in file_unmanaged_save_data() (line 1900 of D:\internet\dmz_drupal\includes\file.inc).
    The file could not be created.
    Notice: Undefined property: stdClass::$uri in file_save() (line 570 of D:\internet\dmz_drupal\includes\file.inc).
    Notice: Undefined property: stdClass::$uri in file_entity_file_presave() (line 14 of D:\internet\dmz_drupal\profiles\webexp\modules\contrib\file_entity\file_entity.file.inc).

Error

Unable to connect to Apps Server.
</pre></code>

I'm doing this on IIS6, so <code>sudo chmod -R 777 sites/all/modules</code> isn't going to do anything, but I've made that directory writable and given the IUSR_MachineName account has full control.  I believe that's equivalent, so I assume that a network connection is necessary to get past this point.

**Comment by sylus** [comment]
Hmm rather annoying lol. I do have a kind of hack solution you could do to make this work though not ideal but would provide a temporary stopgap. If you removed the app specific code in webexp.profile I believe just comment out lines 60 and 66-68 the apps tasks will not be called.

You will then have to go into webexp.info and add the apps to the bottom of the file as modules which they also are. What this is basically doing is telling drupal to loads the apps as modules instead completely bypassing the app functionality. This wouldnt work for apps that have additional dependencies (apps solve this use case) but none of the local apps have this problem as all dependencies for each of them are already present. You just need to add the following apps to bottom of .info file as dependencies.

dependencies[] = wetkit_admin
dependencies[] = wetkit_core
dependencies[] = wetkit_demo
dependencies[] = wetkit_images
dependencies[] = wetkit_magic
dependencies[] = wetkit_pages
dependencies[] = wetkit_theme
dependencies[] = wetkit_users
dependencies[] = wetkit_widgets
dependencies[] = wetkit_wysiwyg
dependencies[] = wetkit_language
dependencies[] = wetkit_web_usability

You definitely don't need to have an internet connection to install the local apps as I have tested this but I can see something is for sure going on here. Let me ponder this over the weekend and verify again no network connection is needed. 

IMPORTANT: Have you tried adding proxy information in settings.php to get through the firewall and see if it does work when there is an internet connection? That would be a useful step in debugging this.

**Comment by RobJohnston** [comment]
For our set-up, the development, testing, and staging servers are not able to connect to the Internet in any way, not even through a proxy.  In the coming week(s) we'll be changing to develop on a normal workstation so we'll be able to see when Drupal core or modules need updating.  I tried your suggestion and ended with a different error.  After the weekend I'll try again from scratch to make sure I'm not missing a step and let you know what happens.

**Comment by sylus** [comment]
If you got a different error it could be because some dependencies are missing when the apps (modules) are loaded. When you add them to the .info file not everything is fully installed so likely could be a result of that. It seems we should probably focus on the first error with apps operating normally. I'll play around this weekend to make sure they don't require a network connection. A wild guess I am thinking is could be related to this patch http://drupal.org/node/1561652 where one of the lines in the patch states:

if ($install_state['interactive'] || is_writable(drupal_realpath('sites/all/modules')))

Can you add a watchdog statement to this?

**Comment by RobJohnston** [comment]
I tried putting a watchdog statement on either side of that line and got nothing in the watchdog table.  Let's assume I was doing that wrong.

The situation is a bit more interesting today.  I've got a local development environment so I have a connection to the internet (can use drush to update modules for another site), but I get a similar error at the same place--after clicking the "Continue" button on the "Enable apps support" screen.  Here's the error this time for comparison:
<code><pre>
•Warning: file_put_contents(temporary://fil4167.tmp) [function.file-put-contents]: failed to open stream: "DrupalTemporaryStreamWrapper::stream_open" call failed in file_unmanaged_save_data() (line 1900 of C:\inetpub\wwwroot\dmz_drupal\includes\file.inc).
•The file could not be created.
•Strict warning: Creating default object from empty value in apps_retrieve_app_image() (line 280 of C:\inetpub\wwwroot\dmz_drupal\profiles\wetkit\modules\contrib\apps\apps.manifest.inc).
•Notice: Undefined property: stdClass::$uri in file_save() (line 570 of C:\inetpub\wwwroot\dmz_drupal\includes\file.inc).
•Notice: Undefined property: stdClass::$uri in file_entity_file_presave() (line 14 of C:\inetpub\wwwroot\dmz_drupal\profiles\wetkit\modules\contrib\file_entity\file_entity.file.inc).
•Warning: file_put_contents(temporary://fil41D5.tmp) [function.file-put-contents]: failed to open stream: "DrupalTemporaryStreamWrapper::stream_open" call failed in file_unmanaged_save_data() (line 1900 of C:\inetpub\wwwroot\dmz_drupal\includes\file.inc).
•The file could not be created.
•Strict warning: Creating default object from empty value in apps_retrieve_app_image() (line 280 of C:\inetpub\wwwroot\dmz_drupal\profiles\wetkit\modules\contrib\apps\apps.manifest.inc).
•Notice: Undefined property: stdClass::$uri in file_save() (line 570 of C:\inetpub\wwwroot\dmz_drupal\includes\file.inc).
•Notice: Undefined property: stdClass::$uri in file_entity_file_presave() (line 14 of C:\inetpub\wwwroot\dmz_drupal\profiles\wetkit\modules\contrib\file_entity\file_entity.file.inc).
Error
Unable to connect to Apps Server.
Click "Continue" to finish the installation. 
You can either fix your internet connection and try the installation again or install apps later from the apps config page.
</pre><code>

Tried this from home running Linux with Apache and PostgreSQL no problem.  Here at work it's Windows with IIS and MS SQL Server.  Any more insight? Network routing issue, maybe?

**Comment by eleclerc** [comment]
> •Warning: file_put_contents(temporary://fil4167.tmp) [function.file-put-contents]: failed to open stream: "DrupalTemporaryStreamWrapper::stream_open" call failed in file_unmanaged_save_data() (line 1900 of C:\inetpub\wwwroot\dmz_drupal\includes\file.inc).

This usually happen when the webserver have permissions issue with `sites/default/files` and subfolders

**Comment by RobJohnston** [comment]
Grrr... I even knew that, but the previous screen only mentioned permissions to sites/all/modules and the "Unable to connect to Apps Server" really threw me off.  I've given the IUSR_MachineName account full control to the sites/default/files folder and have passed through this issue.  Rookie mistake... I hang my head in shame.  Thanks @eleclerc!

**Comment by eleclerc** [comment]
Just in case somebody get the same error on Linux/OSX, might also be due to a permission issue on the /tmp folder, or more specifically, to the folders defined on the settings page on admin/config/media/file-system.

**Comment by RobJohnston** [comment]
And on Windows, even with IUSR_MachineName having full control on the /sites/default folder I still had to manually create the /sites/default/files/tmp directory to get everything smoothly installed.

**Comment by sylus** [comment]
Closing this issue as everything looks resolved. The pre-built will be put up shortly as wanted to have a good stable rel for it.
