### ISSUE TITLE
Meta Tabbed Interface tweaks

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#375]
Meta for tabbed interface cleanup/tweaks.

**Comment by StephenOTT** [comment]
@sylus 
Is work still being done on tabbed interface?
Class styles are not having an effect

**Comment by StephenOTT** [comment]
Ability to customize the transition speed between images is a desired option.
Provides more flexible use options/use cases for tabbed interface

**Comment by mxlav** [comment]
I've been poking around trying to figure out how to slow down the transition cycle in the tabbed interface.

Is there a way to do this?

**Comment by sylus** [comment]
The whole tabbed interface is being reworked so would rather file issues against the new functionality.
