### ISSUE TITLE
Translation workflow problem

### ISSUE THREAD

**Issue by MichaelClift** [wet-boew/wet-boew-drupal#380]
The translation workflow isn't working.  The following is the error message:

Warning: call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in entity_translation_node_tab_access() (line 72 of F:\xampp\htdocs\profiles\wetkit\modules\contrib\entity_translation\entity_translation.node.inc).

**Comment by sylus** [comment]
The translation is working this is a problem with entity translation being not enabled for nodes only for fieldable panel panes and entity translation expects it would be working on the node. Working on a patch but should not break any functionality other then an annoying error.

**Comment by sylus** [comment]
Keeping open so I don't forget to clean up this message.

**Comment by sylus** [comment]
Fixed!

**Comment by MichaelClift** [comment]
When will this be committed?

**Comment by sylus** [comment]
The fix is basically that Entity Translation is disabled as it is causing too many problems. I have a few patches kicking the can at some of the larger problems with Entity Translation but won't be released till can be further tested by greater drupal community.

All you should have to do is disable Entity Translation. If the problem still persists go to configuration -> entity translation -> and select node and click save. Then again disable entity translation.

**Comment by uottawa-wcms** [comment]
@sylus Just wanted to make sure you saw my post on drupal.org re: this issue. I think I tracked it down and a potential fix for them. I encountered it today as well. 

http://drupal.org/node/1437976

**Comment by sylus** [comment]
Hey @uottawa-wcms we so have to talk more I was going through the exact same steps! ^_^

There is another problem with entity_translation in how it overrides page manager making it impossible to override the node_edit screen (again related to this callback) and I think the page_manage_node_edit_disabled variable.

Your fix would get rid of this problem but can only enable entity translation once the other problem is fixed as well (created an issue on d.o). Then there is some more work to do on fieldable_panel_panes.

I was going to set up a monthly developer meeting (probably at a pub or something) hopefully you would be game! :)

**Comment by uottawa-wcms** [comment]
That would be awesome :).

**Comment by sylus** [comment]
Hey @uottawa-wcms can I get your contact details. ie Phone Number. There will likely be some times I'd like to give you a shout :)

**Comment by uottawa-wcms** [comment]
Sure - email is rturnbul@uottawa.ca, extension here is 7512.
