### ISSUE TITLE
Unable to patch

### ISSUE THREAD

**Issue by MikeBourgeau** [wet-boew/wet-boew-drupal#386]
I am unable to patch!!! I am using a Drush 5.4 on a Windows 7 machine. Everything is downloading but it is not patching. Also I can't find the drupal_wet folder that it is supposed to create when you do the drush make command
drush make --prepare-install --no-gitinfofile --working-copy https://raw.github.com/wet-boew/wet-boew-drupal/master/build-wetkit.make drupal_wet

Thanks

Mike

**Comment by joejoseph00** [comment]
@MikeBourgeau everything is patching using Linux right now using this script http://wet.7pro.ca/sites/wet.7pro.ca/files/wet_drush_sh.txt

Sorry, I haven't used windows to do this  :(   Must be a configuration problem, or version issue with the tools.  Can you try doing this:

drush make --debug --prepare-install --no-gitinfofile --working-copy https://raw.github.com/wet-boew/wet-boew-drupal/master/build-wetkit.make drupal_wet

this makes it run in --debug mode, you'll see more messages that way.  Show the error message.  Is it just an http connection issue again? or , what is the error message when you run in debug mode.

**Comment by sylus** [comment]
This could be any number of things, is git installed? Is drush properly configured? Are you running your commands through msysgit.

Without more information it is hard to say what the problem is.

The virtualbox preconfigured install can't come fast enough lol

**Comment by sylus** [comment]
I am about 30 - 45 mins from releasing an update documentation on installation it might help.

**Comment by StephenOTT** [comment]
@sylus 
Thanks Sylus.  The problems seem to be with windows machines.  
Any mac users having issues?

**Comment by joejoseph00** [comment]
I think Mike had a problem finding a working git client for windows.  He's on Windows 7, I've never used Windows 7

**Comment by mxlav** [comment]
I tried both W7 and Mac machines at home. W7 gave me errors if I recall, but no errors on my macbook. So i didn't bother debugging the W7 issues.

**Comment by sylus** [comment]
I use a window machines at my work at STC along with a few other developers. However this is Windows Vista. I bet it is because people are installing drush 5.7 which has a known windows bug.

**Comment by joejoseph00** [comment]
Mike says he's using using a Drush 5.4 on a Windows 7 box.

5.7 (or was it 5.6) gave us trouble on Linux too because we're still on php 5.2, we had to downgrade to Drush 5.4 which is what we're now using.

**Comment by MikeBourgeau** [comment]
I have Git installed 1.7.11 and I have the Drush 5.4…5.7 is not working!!! I run the command with Drush command prompt.

**Comment by StephenOTT** [comment]
Let's talk tomorrow morning and I will send you a pre packaged zip file
that will get you started so you can get past the git/drush issues.

**Comment by sylus** [comment]
Can you paste your drush debug? As @StephenOTT mentioned he can send you off a pre packaged zip. If really needed I can make a copy of the full build on another repo. 

I have been hesitant before as it won't be always be up to date but seems like at this point would be beneficial for people.

**Comment by StephenOTT** [comment]
@sylus  are your new instructions ready to go?  btw nice wiki updates :)

@sylus give me a ring tomorrow and lets chat about dev meetup on 25th.  some options might be able to give you.

**Comment by StephenOTT** [comment]
@MikeBourgeau 
Okay i skipped the morning as i am sure i will be on the phone with other issues.
See link for zipped package: https://www.dropbox.com/s/v9e0bpbzt7xu7gn/drupal_wet_09112012.zip

Unzip and point acquia dev desktop (settings>sites>import) to the drupal wet_09112012 folder.

Make sure to set the settings of the import to create a new database and in the url for localhost add a 1 after localhost so it reads "localhost1" (without quotes).  press okay and browser will launch to run browser based instal.

**Comment by MikeBourgeau** [comment]
Thanks guys for the effort. I will give the zip file a try. I also have a buddy who will built me a Linux machine and with the help of Joseph I will be able to get it going. Also last night I tried it with a XP machine and got no result then tried it with my friends MAC and it got it done beautifully…like a charm.

I will ask my boss if I can buy a MAC hi hi hi  : )

Thanks….I will let you know how the zip package does.

Michel Bourgeau

**Comment by MikeBourgeau** [comment]
The zip package worked great!!!!  Thanks Stephen  : )  
I can now work...yeah!!!!

Thanks to Stephen

**Comment by jfbourgon** [comment]
I came to the exact same problem recently. The cause was related to my git install (using msysgit 1.8). Only the git/cmd folder was appended to my system %path% variable. The folder git/bin where patch.exe is located was not incuded. Adding it explicitly to %path% variable both fixes the patch appliance and final copy from temp folder to target location.

**Comment by sylus** [comment]
Thanks for the feedback!
