### ISSUE TITLE
Error Message - Lost Admin menus

### ISSUE THREAD

**Issue by lpgascon** [wet-boew/wet-boew-drupal#387]
After adding a Column in the Admin_Content_Node View i now always get an error message on every administration page i go to.

Error message
Notice: Trying to get property of non-object in user_access() (line 798 of D:\Ampps\www\wettest\modules\user\user.module).

I've also lost the Content menu item from the main menu. If i go there manualy (/admin/content/) i get an error : you are not Authorized to access this page

Anyone knows how i can fix this? 

I've tried Clearing the Cache but maybe i'm missing a step

Thanks in advance

LouisG

**Comment by sylus** [comment]
I assume you were modifying a view? You can just simply revert it and everything should be good again. Please reopen if did not fix and post an exact set of steps to reproduce.

**Comment by lpgascon** [comment]
I did try to undo what i did with no success... I'll try to backup the database and do a fresh install.

Thanks
