### ISSUE TITLE
(META) University of Ottawa Contrib Modules

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#389]
Issue is used to reference the adoption of a suite of Ottawa University Modules located at: https://github.com/uottawa-wcms

After talking with the University they are committed to supporting and maintaining these modules as well as providing a more agnostic namespace and integration with our distro etc. The current plan is to have a monthly developer meeting where a lot of the planning for this can happen. Basically though what will happen is that Ottawa University will host their modules inside of their own repo and they can be included as part of the WetKit build out.

The benefits are two-fold in that Ottawa U can get the experience from us and we can get the experience from Ottawa U who have a significant amount of quality developers!!! It should be noted that the modules from Ottawa U won't be part of core but will and should be extremely easy to add. The developer meetings will focus on a lot of this.

Current modules for adoption:

1) Dual Language Editor
2) Enhanced Migration

**Comment by StephenOTT** [comment]
Something to discuss at the upcoming working group meeting?

**Comment by thriuin** [comment]
Absolutely. This is a very good response to the request raised in issue #86.

**Comment by StephenOTT** [comment]
Okay lets make sure to bring it up on the 25th
