### ISSUE TITLE
NEEDS REVIEW: Ariadne cookbook created for wet-boew-drupal profile

### ISSUE THREAD

**Issue by patcon** [wet-boew/wet-boew-drupal#390]
Created the "glue" cookbook to get wet-boew-drupal running on ariadne. Feel free to take it for a spin and provide any feedback. (Might want to up the VM memory from the default 1GB if you've got the system resources -- check Ariadne README for further details)

https://github.com/patcon/ariadne-wet-boew-drupal

PS, I'd recommend pulling the newest tagged release (ie. pull on master branch)

**Comment by sylus** [comment]
OMG you are awesome and totally made my night :) Will test this out first thing tomorrow morning!

**Comment by sylus** [comment]
Hey @patcon will the minor change in the build re: #388 affect this? It hasn't been committed yet but will soon.

**Comment by patcon** [comment]
Nope, won't affect it :) Actually it would make it more stable. I'd recommend removing all external URL's like that from makefiles ASAP, as it hurts build reproducibility and our ability to move toward continuous deployment.

The Ariande cokbook currently builds the head of `master` branch each time it's run, which is necessarily the same branch that you have in `build-wetkit.make`. If we adopt [some scripting like our scripts here](https://github.com/myplanetdigital/secondlevel-rerun-modules/blob/develop/2ndlevel/commands/build/default.sh#L37), then it will be possible to build any previous commit revision (tag/branch/hash), but atm we're confined to what `build-wetkit.make` dictates.

**Comment by patcon** [comment]
Note: In that script snippet through the link, `develop` is our main branch, but you would be swapping out `master`. I could make this pluggable if you wanted to fork our scripts so we'd be improving them together.

**Comment by patcon** [comment]
//cc @mgifford

now that you're all set up, you're totally me go-to guy :)

**Comment by mgifford** [comment]
I'll give that a go, but just realized now that this is a new project for ariadne-wet-boew-drupal.  Thanks.

**Comment by sylus** [comment]
This is working now so closing.
