### ISSUE TITLE
Version control all scripts with project and use rerun scripting framework

### ISSUE THREAD

**Issue by patcon** [wet-boew/wet-boew-drupal#394]
As alluded to in #388, I recommend we use the rerun framework:
https://github.com/dtolabs/rerun

Basically support standardization and modularization of fully-doc'd scripts :)

Also, I suggest we may want to follow the i18n bash scripting techniques laid out in this Linux Journal article:
http://www.linuxjournal.com/content/internationalizing-those-bash-scripts

Just as one example of how it could be done (we can obviously adopt our own conventions):
http://github.com/myplanetdigital/2ndleveldeep

**Comment by joejoseph00** [comment]
subscribing

Will have to try this http://www.linuxjournal.com/content/internationalizing-those-bash-scripts
asap.

**Comment by sylus** [comment]
Dupe of #400
