### ISSUE TITLE
img max-width 100% breaks map displays - gmap, getlocations, openlayers

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#398]
Gotta rewrite the SASS to avoid this problem with max-width:100% & mapping tools.  See:
  http://drupal.org/node/1297980#comment-5081820

Jeff's got some good recommendations, but they are being overwritten by global.base.scss

Trying to get this to work with OpenLayers.

**Comment by mgifford** [comment]
Exceptions probably needed to be added to:

wetkit/modules/apps/wetkit_images/wetkit_images.css
wetkit/themes/wetkit_adaptivetheme/css/global.base.css 

Also, why is there an add in here to:
/\* Ethan Marcotte - http://front.ie/l8rJaA */

**Comment by mgifford** [comment]
Similarly, there's some padding added to images that needs to be overridden.  

.openlayers-map img {
  margin-left: 0px;
}

Not sure where the best place in the theme is to put this.

**Comment by d-shields** [comment]
Regarding the margin-left for the openlayers maps, I've added what's required to cityott-adaptivetheme-custom.css

**Comment by sylus** [comment]
Hmm not sure the best way to fix this. The global.base.scss was from AdaptiveTheme and I am sure there is good reasons why Jeff Burnz added that code, will have to talk to him first before removing.

**Comment by sylus** [comment]
I looked into this and the max-width of 100% needs to be assigned for images to be properly responsive.

You can apply an image-actual class for the images and that will make them respect their original widths.

However I will add the following by default to our custom sass file:

``` scss
/* Override max-width 100% for map displays */
.gmap,
.view-gmap,
.openlayers-map,
#getlocations_map_canvas {
  img { max-width: none; }
}
```

**Comment by mgifford** [comment]
That's great, thanks!
