### ISSUE TITLE
App for Slideshow?

### ISSUE THREAD

**Issue by uottawa-wcms** [wet-boew/wet-boew-drupal#399]
@sylus are you making an app available for slideshows or do you have a recommendation? We were looking at using FlexSlider and a few other things, but if WET is going to have something that we can fully theme, we'll use the same thing :)

**Comment by StephenOTT** [comment]
Tabbed interface?

**Comment by uottawa-wcms** [comment]
The last mockup I saw needed to have an image (of a certain size), title text, descriptive text, and link for each slide, and offer Pause/Start, Next, Prev controls, and a X of Y counter for how many slides there are. We would need to be able to theme the entire look of it, and then integrate it into a Panel custom page.

**Comment by StephenOTT** [comment]
Would just have to change the css?

**Comment by mgifford** [comment]
There was an implementation earlier that had a built in slider. I don't see the initial slideshow now.  The tabs are pretty powerful now:

http://wet-boew.github.com/wet-boew/demos/tabs/tabs-eng.html

But don't see how they are built into the Drupal Distro at the moment.  Maybe I need to just update what I'm using.

**Comment by sylus** [comment]
Believe this was answered with my latest meeting with Robert? For the View based Tabbed Interface please see #431. Planning to bring it in as soon as possible :)

**Comment by mgifford** [comment]
Yup. Thanks!
