### ISSUE TITLE
Git Workflow

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#4]
This new repository of wet-boew-drupal will be using a github-flow.

It is encouraged that all contributors wishing to collaborate will also using this workflow.

The workflow is discussed in detail here: http://scottchacon.com/2011/08/31/github-flow.html

Ultimately github-flow relies on forking a repository and sending a pull request for each change.

**Comment by eleclerc** [comment]
thanks for sharing, this is really a must-read article
