### ISSUE TITLE
Legal issues

### ISSUE THREAD

**Issue by eleclerc** [wet-boew/wet-boew-drupal#412]
Some agency will have a hard time adopting the distro without these missing legal-ish pieces:
- A licence file (otherwise, that would be illegal for anybody but the author to distribute a project build with this variant. Trying to help consultants here)
- Releases being tagged so version number can be specified in S.O.W.

**Comment by sylus** [comment]
Hey @eleclerc I don't know much about this but definitely can follow your advice on this. I assumed we just inherited from the WET license. Should I copy that into our repo?

**Comment by eleclerc** [comment]
Seems like a safe and easy solution, I'd be happy with that  ;)

**Comment by sylus** [comment]
Added :) Please reopen as needed
