### ISSUE TITLE
Updating an installation

### ISSUE THREAD

**Issue by MichaelClift** [wet-boew/wet-boew-drupal#417]
With the changes to the build procedure, does the update procedure change?

Currently it says to use the following command:

Command: drush make --no-gitinfofile --working-copy https://raw.github.com/wet-boew/wet-boew-drupal/master/build-wetkit.make .

Should it be a two step process?  Something like

Change to your  profiles/wetkit directory
Command: git pull

Change to your installation directory

Command: drush make --no-gitinfofile --working-copy --working-copy [path to]/profiles/wetkit/build-wetkit.make .

**Comment by sylus** [comment]
Hey @MichaelClift the documentation should be updated. Your correct it involves technically 3 steps:

1) git pull (to fetch the updates for profiles/wetkit directory)
2) drush make ... (to rebuilt the file system in sites/all/modules for all contrib)
3) drush updatedb (for any database schema updates)

As of yesterday we are no longer removing any modules or changing the file system (see rename from apps to modules) so the above steps should work as of today. We might be adding modules in the future but this would involve discussion with everyone. However the updatedb would fix this should a module be added.

I'll try to update the docs soon and mention all of this.

Note: If on the off chance a module has been shown to cause problems or security concerns we will endeavour to create a hook_update_n in our install profile that will fix the database should it have to be removed.

**Comment by sylus** [comment]
Cleaning up some old issues. :)
