### ISSUE TITLE
Nav Current Problem appearing again

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#419]
Hey @pjackson28,

I know your crazy busy but looking at http://wet.openplus.ca can you immediately see why the nav-current is being applied in the mega menu?

I solved this problem a week ago. I know it is something I must have done but cant immediately see the problem. The markup looks pretty close except for a few classes.

**Comment by pjackson28** [comment]
@sylus I think I found the problem. It looks like it's the suppression of the files in the URL that are tricking the script (also the PE object is a little greedy when it comes to URL matching). I've tweaked the matching algorithm to take this into account. I've pushed the updated PE file to the repository. Take a fresh copy and see if it addresses your issue.

**Comment by sylus** [comment]
Thanks @pjackson28 your so awesome :) Will test out first thing in the morning :)

**Comment by sylus** [comment]
Fixed!
