### ISSUE TITLE
Enabling Wetkit Slider causes major failure

### ISSUE THREAD

**Issue by dsamojlenko** [wet-boew/wet-boew-drupal#42]
On a clean install, enabling the Wetkit Slider module causes a major failure.  I just get a bunch of error messages (below) and can't do anything at all.  Had to go into the database to disable the module again and everything is back to normal.

Error
Error message
The specified file profiles/webexp/themes/wetkit_adaptivetheme/images/slider01.png could not be copied, because no file by that name exists. Please check that you supplied the correct filename.
The specified file profiles/webexp/themes/wetkit_adaptivetheme/images/slider02.png could not be copied, because no file by that name exists. Please check that you supplied the correct filename.
Notice: Undefined index: fid in file_field_presave() (line 219 of /var/www/drupal/modules/file/file.field.inc).
Warning: array_flip(): Can only flip STRING and INTEGER values! in DrupalDefaultEntityController->load() (line 178 of /var/www/drupal/includes/entity.inc).
Notice: Trying to get property of non-object in file_field_presave() (line 220 of /var/www/drupal/modules/file/file.field.inc).
Notice: Undefined property: stdClass::$uri in file_save() (line 570 of /var/www/drupal/includes/file.inc).
Notice: Undefined property: stdClass::$uri in file_entity_file_presave() (line 14 of /var/www/drupal/profiles/webexp/modules/contrib/file_entity/file_entity.file.inc).
Notice: Undefined index: fid in image_field_presave() (line 236 of /var/www/drupal/modules/image/image.field.inc).
Warning: array_flip(): Can only flip STRING and INTEGER values! in DrupalDefaultEntityController->load() (line 178 of /var/www/drupal/includes/entity.inc).
Notice: Trying to get property of non-object in image_field_presave() (line 236 of /var/www/drupal/modules/image/image.field.inc).
Notice: Undefined property: stdClass::$fid in file_usage_add() (line 654 of /var/www/drupal/includes/file.inc).
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'fid' cannot be null: INSERT INTO {file_usage} (fid, module, type, id, count) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4); Array ( [:db_insert_placeholder_0] => [:db_insert_placeholder_1] => file [:db_insert_placeholder_2] => node [:db_insert_placeholder_3] => 10 [:db_insert_placeholder_4] => 1 ) in file_usage_add() (line 661 of /var/www/drupal/includes/file.inc).
The website encountered an unexpected error. Please try again later.

**Comment by sylus** [comment]
WetKit Slider is not yet ready for WET v3.0 as WET itself has not finished works on the Tabs Worker. Till this is added this feature is broken. I will remove to minimize confusion.

**Comment by sylus** [comment]
Actually I think I can try to get this in over the weekend will post progress here ^_^

**Comment by StephenOTT** [comment]
Looking forward to seeing this feature activated again.  Just ran into the same issue.  Enabled the feature and the site crashed

**Comment by sylus** [comment]
WetKit Slider has been fixed and is now working, you can add it using the panels ipe under views.... Work is still needed to make it look good in panels ipe but when added and page refreshed everything works.

**Comment by StephenOTT** [comment]
great.  Will test it out when i get a chance.
