### ISSUE TITLE
Handling Redirects/Broken Links

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#420]
So we all have this problem.... We want to move our site over to a new system, in this case drupal, and we are changing our URL structure.  In the case of the City of Ottawa we are drastically changing our URL structure.

You may have a Bilingual url, unilingual URL with a language indicator, or separate english and french URLs.  If you change your url structure you are going to have to deal with redirects.

Many may use htaccess to create a series of 301 and 302 redirects. In some cases you use pattern matching or hard code the redirect.

But what do you do when you are dealing with 1000 pages, 10,000 pages, 100,000 pages, or even a million pages of content?  Management says there cannot be any "broken links".... Bookmarks must remain in tract.... How do you manage so many redirects?

What have people been doing?

We have been kicking around a bunch of ideas and best practices.... None of which are very appealing.
Then we started talking about 404 Search with Solr.  If you don't know the feature, this allows your to use part of the url as a search query to provide you with potential matching pages.  Using the keyword in the url as the search parameter.  Sounds fine but this only works if you have keywords that make sense, and you are not rearranging too much content.  Furthermore you are not taking the user through a seamless transition, they are taken to a search results page..... 

I can hear us all saying "But if can set a confidence match and take them directly to the best/top search result".  Yes you are right... But you can only trust that result if your keywords make sense from your url and your site is fairly small.  If you have a lot of similar content with similar url keywords you are screwed.

So here is the idea @sylus and I are kicking around and want some thought on.  When data is imported into drupal, a field is used to capture the old URL of the page.  This means that all of your content that comes from your current site would have a field along with it that has the historical URL.  In the City of Ottawa's case we have 2 URLs, the main user readable URL and a permalink.  So both of these URLs are passed into their own individual fields along with the body.  Then using Search 404, Search API, and the Solr confidence match, when someone uses one of the URLs that are in the Historical URL field or the Historical Permalink Field, Search 404 will take the user directly to the new content.  100% confidence that they are taken to the correct page and no search results page.  Furthermore you could assign multiple historical urls to a single node allowing multiple urls to go to a single new content page.

At first review, this looks to be VERY manageable.  Can be something we import with Feeds.  Mass updates can be preformed very quickly and could scale very well.

So it is too good to be true?  Anyone see some issues with this?
Know of anyone that is already doing this?

**Comment by thriuin** [comment]
When I first implemented this idea at StatCan, I was using it to link English and French content, and it has worked very well so far for that purpose because our content is consistantly organized. I am definitely intrigued by your and @sylus 's idea to re-use it with search and to archive changing links.

**Comment by mgifford** [comment]
As described by Stephen, we've used http://drupal.org/project/Search404 in the past but haven't played with some of the neat extensions to tie it into Solr search.

Running the site through http://drupal.org/project/linkchecker is also good.  Just to check that the content doesn't have links in it that aren't broken.

Another good option to consider is http://drupal.org/project/redirect or http://drupal.org/project/globalredirect

But I think the path of putting the old URLs into a field that isn't displayed is pretty hacky.

Some thoughts on other processes:
http://www.outlier.com/thinktank/tags/change

RewriteEngine On
RewriteRule ^contact_us.html$ http://www.mydomain.ca/contact_us [R=301]
RewriteRule ^myoldpage.html$ http://www.mydomain.ca/mynewpage [R=301,L] 

But ya, if you've got hundreds you'd definitely want to write a PHP script or something to write out the text or simply use something like - http://www.geoffmanning.com/technology/generate-301-redirects-in-excel/

When it comes to server load you want to fix the problem as early as possible.  10,000 hard coded redirects in Apache are going to be way easier (both immediately & in the long term) than 10k Solr queries (that get called every time someone hits the site).

You've got a list of the current domains (that are being phased out).  You've also got a list of the current 404 pages of the existing site.  That's a great starting point.  If you ensure that all of those are redirected in Apache properly you're going to deal with most people's problems.

Broken links are constantly being created.  Even when you fix all of these you're going to need to be proactively looking to see that bad URL's are addressed.  They could be anything from simple typos that are happening all the time:
 http://www.mydomain.ca/i_put_in_an_extra_period..html

to bad links that are just garbage:
   http://www.mydomain.ca/C;OAIEUFOIVMWER

to efforts to penetrate your site's security:
  http://www.mydomain.ca/users.php?action=delete&user=XXXX&_wpnonce=XXXXXXX

So you need a good plan to deal with 404's.    

Compiling a list of active 404's now and on a weekly basis till the site launches could be good.  Just to ensure that you've got a sense of what some of the existing problems are.  

The site can be good, but no site is perfect.

**Comment by sylus** [comment]
Sagely advice from @mgifford ^_^ 

I have to admit still curious bout trying the Search404 method but pretty much all of mike's advice is sound and well thought out.

Looks like redirects are the way to go :S :P

Very interesting issue though. I still wish there was a better way as I know STC itself will have about 100,000 and more pages to worry about for this. Time to bring out the regex!

Boourns indeed.

**Comment by StephenOTT** [comment]
There is a balance that needs to be reached between server load and content/system custodian.

Agree on the server load concern, my thinking on this is if the maintenance on redirects becomes to a point where it is literally cheaper to pay for additional server load capabilities, it becomes a calculated increase.

This can become especially important for sites that continue restructure content.  If redirects can become a seamless integrated feature of content management that content contributors can accomplish that is a huge win and removal of tedious task.  Redirects are typically identified by content custodians, and they should be the ones able to resolve the issues them selves.  (Obviously governance and restriction capabilities are required, but the principal remains the same).

On keeping the old URLs in fields... Where there is a relevant use case is the continual reporting on the old structure of the site compared to the new structure of a website.  For large websites with multiple multi-diciplinary stakeholders involved in the content there would be a reporting need to show where the old content now sits in the new structure, where old URLs point too, and continued consolidation or ROT analysis of content produce reporting requirements.  If these fields are not in the db and on the apache side we have to move to excel reporting and multiple tracking mechanisms.  One source of truth, without the need to export, manipulate and massage into a workable report is most desirable.

**Comment by mgifford** [comment]
For migration purposes it totally makes sense to have that old URL field associated with the data.  It's an easy thing to do at the time of migration and there really is no downside in bringing over that data with the migration.  It might be something you'd want to delete after a while simply because it isn't needed.  It's not something that should be a big piece of a 404 strategy in my opinion.

After launch admins will be able to add multiple alias' to the same node and change/delete the alias' according to their own needs.  Some of the redirect modules I pointed to can help, but there should not be a problem moving forward with your team being able to restructure the paths. Future changes can be more easily taken care of by Drupal.  You might want to go through and clean that up semi-regularly and bring stuff into Apache redirects, but that would be optional.

**Comment by StephenOTT** [comment]
Agree on the alias strategy.

So the question would come down to how long one would keep the old urls in fields for?  1 month, 6 months, 1 year.

**Comment by joel-osc** [comment]
There is another option we used on CTA where you create a panel page which replaces your page_not_found and have the panel page takes the old page url, parses it and then send it into a view which displays a link to the correct page. Add some preamble about the site changing and needing to update your bookmark and voila. Minimal administration, done directly in Drupal and no overhead.

**Comment by mgifford** [comment]
@StephenOTT I'd say you could comfortably keep them for a year.  Until they become a pain.

@joel-osc Nice. That prompts the user to fix the problem at the source (the bookmark or link).  Possibly much nicer for many commonly bookmarked URLs.

I think we are getting close here to defining what we want.  Then there's the hard work of actually turning it into a reality.

**Comment by patcon** [comment]
EDIT: haha ok should have read the above more clearly. The solution below isn't really automated, and would use something like [Redirect module](http://drupal.org/project/redirect)

I've heard that it's a good approach if resources are limited to get ahold of the Google Analytics data and say "we're going to get any page in the 99.9% of our pageviews mapped to the new site" (or any arbitrary # that feels right). Then you'dre not hitting the point of diminishing returns putting effort into linking pages that are likely not going to disappoint anyone :)

Might also want to look at data on peak periods, in case there's a seasonally active apge that might have a lot of links (relevant to lots of gov sites, I'm sure).

**Comment by colans** [comment]
I'm a fan of the RedirectPermanent directives.  As described above, either use a module for this, or stick it in your Apache/Nginx config directly.  A year makes sense to me as well.  I like this idea because you don't need to maintain old links on your site permanently, only for a transition phase.  At the end of that, you're left with a cruft-free site. @joel-osc came up with a great enhancement to this, but again, I wouldn't want to be maintaining it in the long term, just for a year or some other fixed amount of time.

If Management wants to store these permanently, you can store the list(s) off-line.  And for link checking, yes, I agree, make sure that you're periodically running Link Checker or some such thing.  (It's really a separate issue though.)
