### ISSUE TITLE
First Working Group Meeting Today (September 25th, 2012)

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#430]
Just a reminder to those who signed up our first Working Group Meeting is Today.

For information please see: https://github.com/wet-boew/wet-boew-drupal/wiki/WxT-Drupal-Working-Group

**Comment by MaddyDaigle** [comment]
I was just wondering who it was that was discussing the VM solution for Drupal at the meeting (sitting near the project near Will and Laurent ).  Would it be possible to get his contact information? Thank you!

**Comment by sinkinsona** [comment]
@MaddyDaigle that would be @patcon from myplanetdigital.com.

**Comment by patcon** [comment]
heyoooo! :)

Feel free to open a meta discussion issue in a project queue if it's publicly relevant, or tweet me, or email me:
http://github.com/wet-boew/wet-boew-drupal/issues
http://github.com/myplanetdigital/ariadne/issues/
https://twitter.com/patconnolly
patrick@myplanetdigital.com

**Comment by StephenOTT** [comment]
What is left for the VM work?  Have some significant interest in getting this up and running asap.

**Comment by StephenOTT** [comment]
Draft Minutes have been posted
https://github.com/wet-boew/wet-boew-drupal/wiki/WxT-Drupal-Working-Group

**Comment by patcon** [comment]
Awesome! Thanks man. I might suggest using the "Downloads" section of either the wet-boew-drupal or wet-boew repos going forward -- might be simpler for non-technical people to help with minutes :)
https://skitch.com/patccon/eafg3/wet-boew-wet-boew-drupal

EDIT: Unless we want to version the drafts and make PR's possible, which I just realized it pretty cool too! So maybe I retract that suggestion

Having said that, if we really want to push it with this version-control-everything-related-to-the-project approach, I could submit a PR to convert the minutes into a more version-control friendly format like markdown, and we could use prose.io to allow editing and viewing? (Won't see full feature-set on pdfs/docx files)
http://prose.io/#wet-boew/wet-boew-attachments/tree/master/Working%20Groups/Drupal%20Variant/Meetings/September%2025%202012/Minutes

Prose is an open source project, so leveraging it seems in line with our goals and motivations
http://github.com/prose/prose

Tangential, but interesting :)
/cc @developmentseed

**Comment by StephenOTT** [comment]
Oh right!!!  Good thinking, did not even cross my mind!   Will make change

On 2012-10-08, at 11:43 AM, Patrick Connolly notifications@github.com
wrote:

Awesome! Thanks man. I might suggest using the "Downloads" section of
either the wet-boew-drupal or wet-boew repos going forward -- might be
simpler for non-technical people to help with minutes :)
https://skitch.com/patccon/eafg3/wet-boew-wet-boew-drupal

—
Reply to this email directly or view it on
GitHubhttps://github.com/wet-boew/wet-boew-drupal/issues/430#issuecomment-9229951.

**Comment by patcon** [comment]
Oops. I have a poor habit of editing posts after sending, so check github (not just notification email) for the full story

And minor note: spaces in file/directory-names can be a little awkward. If it's all the same, I might suggest we avoid them in favor of underscores/hyphens in our repos :)

**Comment by StephenOTT** [comment]
10-4.

On 2012-10-08, at 12:03 PM, Patrick Connolly notifications@github.com
wrote:

Oops. I have a poor habit of editing posts after sending, so check github
(not just notification email) for the full story

And minor note: spaces in file/directory-names can be a little awkward. If
it's all the same, I might suggest we avoid them in favor of
underscores/hyphens in our repos :)

—
Reply to this email directly or view it on
GitHubhttps://github.com/wet-boew/wet-boew-drupal/issues/430#issuecomment-9230653.
