### ISSUE TITLE
View with tabbed interface..

### ISSUE THREAD

**Issue by MaddyDaigle** [wet-boew/wet-boew-drupal#431]
Hello,

I was just wondering if the tabbed interface can be used in conjunction with a view or if there will be support for that in the future. For example: I'd like to have a list of article content based on current node taxonomy which is easy to do.. but I'd like to display that in a tabbed interface.  I may just be missing something though.

Thanks you in advance! :)

**Comment by StephenOTT** [comment]
Good idea.  Would be a good modification to the current tabbed interface.
Be able to associate the view fields to the tabbed interface fields.  Image, Title, alt test, description, etc.

**Comment by MaddyDaigle** [comment]
I developed a bit of a potential solution for this.  I created a view tpl.php file that displays a view in the proper format for a tabbed interface. I created a view called "tabbed interface" which uses this file as its theme. I haven't tested it in Drupal WET yet however, just a basic Drupal install.  I'd like to be able to modify the pager in the view so that it's used for the tabs, but I haven't figured out how to do that yet.

**Comment by sylus** [comment]
Hey @MaddyDaigle I do have code for this that was done with a content type and a rewrite on the views.tpl and view--field.tpl that accomplished what you need. We did ultimately go the fieldable panel pane route. But your correct it would be nice to autogenerate a tabbed interface based on the content as well... I'll bring the code back in at earliest chance I get. Likely  within the week.

**Comment by MaddyDaigle** [comment]
Thanks! :)

**Comment by sylus** [comment]
Looks for this in the next day or two with the addition of WetKit Views which has some custom row style plugins. A issue will be opened to announce the addition.

**Comment by mgifford** [comment]
Any updates?  Fine to close, when there's a link to some documentation.

**Comment by sylus** [comment]
Closing as tabbed interface is out atm.
