### ISSUE TITLE
Drupal Variant links - documentation

### ISSUE THREAD

**Issue by mxlav** [wet-boew/wet-boew-drupal#433]
http://wet-boew.github.com/wet-boew/demos/index-eng.html

the links under Drupal variant are broken

Drupal variant
•Drupal variant - English example
•Drupal variant - French example

**Comment by mxlav** [comment]
I have a huge form in my webapp and the clients needs to do a lot of scrolling to get to the end and I am trying to make it look shorter so I tried using form-inline mentioned here http://wet-boew.github.com/wet-boew/demos/grids/grid-form-eng.html#inline on a DS div within my manage fields custom css field. 

I also used background-light to brighten it up a little. the grey works fine but the inline didn't work.

Other than venturing in theming, how can i change the display to have some fields side by side vs one above the other?

**Comment by sylus** [comment]
Hey @mxlav the links have been fixed, though the installation of Drupal needs to be redone as there is permission bugs. But links do work.

As for your form issue might I suggest the WebForm http://drupal.org/project/webform module? And using its build in page functionality so you can have a multi page ajax form?

This should likely be a separate issue if you have more questions.
