### ISSUE TITLE
September 25, 2012 - Working Group - Photos

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#435]
Hi everyone,

I know some of you who attended the Step 25, 2012 working group meeting were taking some photos and video.  If you have photos or video could you please upload and provide a link so we can aggregate the content and centrally post the information on the wiki?

Thanks

**Comment by colans** [comment]
I think I saw @dergachev with a camera.

**Comment by StephenOTT** [comment]
@dergachev  Any photos?

**Comment by dergachev** [comment]
Hey folks, had a busy couple of weeks, and I'm still learning how github notifications work.

https://www.dropbox.com/sh/nacf9cfbwhhqzze/qaYNl5zSQY (contains full-size photos)

The lighting in the room was hard to photograph in, but at least the subjects were very animated. ;)
https://www.dropbox.com/sh/nacf9cfbwhhqzze/qaYNl5zSQY#f:IMG_6589.JPG

**Comment by StephenOTT** [comment]
Photos downloaded and added to github
