### ISSUE TITLE
Selenium Integration

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#44]
Ala http://seleniumhq.org/ I would love to get some automated browser testing working for this distribution as think it would greatly improve the quality of the code when new updates come in. Firefox has a plugin for it that will directly map user based actions on Drupal. Pretty easy to setup too.

The good news is that our Travis (Continous Integration) build works with Selenium. So could run the tests on every commit. See support for this at: http://about.travis-ci.org/docs/user/gui-and-headless-browsers/

I have to admit I don't really have the time now to implement this but it is on my radar. If anyone is willing to take a further look into this would be appreciated!

**Comment by mgifford** [comment]
I added it here, but probably should have added it here instead:
https://github.com/wet-boew/wet-boew/issues/57#issuecomment-6815052

**Comment by sylus** [comment]
As per #57 I have added basic selenium + casperjs testing. We may not need both of these frameworks but curently they both look to fill a niche.

Selenium: currently tests by logging in as administrator and logging out
CasperJS: checks that there are three headlines on the front page

Now that the initial framework around these libraries is added it is time to add some tests. Selenium being the easiest as it just records your actions and creates the files for you!

**Comment by sylus** [comment]
Selenium has been integrated but I had to remove the installation test so right now we only have logging in and logging out selenium test. Selenium + the Firefox Recorder only works on regular pages and not when Ajax is used. Due to this the installation test, fails on the modules installation page as the selenium recorder never took this page into account. IMHO this is a huge problem with selenium. I do believe the Web Driver fixes this and will look into https://github.com/facebook/php-webdriver

**Comment by csedev** [comment]
For automated regression testing, I'd recommend IBM Rational Functional Tester.  There's a bit of a learning curve, but it does provide a powerful data-driven regression testing environment.  The price is a bit steep, but if there is interest, I can reach out to IBM and see if they would be willing to share a floating license to be used on this project.   

Keep in mind the time commitment to maintaining the automated tests.  For every 1 day of development, you may find you are creating 2-3 days of testing efforts.  You might want to wait until development slows down before investing too much time.

**Comment by nschonni** [comment]
Besides the price issue about Functional Tester, there is also the issue of where it would be installed. Selenium is supported by Travis-CI, but I don't know if AT would requires its own hardware.

**Comment by StephenOTT** [comment]
This has been resolved with Saucelabs.com
