### ISSUE TITLE
Ajax error 200 when trying to change Entity Selection Mode

### ISSUE THREAD

**Issue by OTTGuy** [wet-boew/wet-boew-drupal#440]
When creating or editing an Entity Reference field for a content type, switching the Entity Selection Mode from Simple to Views, or back from Views to Simple, generates this Ajax 200 error.  This error happens with all 4 Widget Type choices and not just with the first 2 Autocomplete types listed.

Debugging information follows.
Path: /eng/system/ajax
StatusText:Parsererror
ResponseText:
Fatal error:Class
EntityReference_SelectionHandler_Views contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (EntityReference_SelectionHandler::validateAutocompleteInput in 
C:\Documents and Settings...
\sites\all\modules\contrib\entityreference\plugins\selection\EntityReference_SelectionHandler_Views.class.php on line 150.

**Comment by joel-osc** [comment]
Think this is a known issue with a patch: http://drupal.org/node/1608358

**Comment by OTTGuy** [comment]
Thanks joel, I needed that patch.
