### ISSUE TITLE
Update TinyMCE to 3.5.7

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#442]
Panopoly has updated their version of TinyMCE to 3.5.7

This is a placeholder issue so don't forget to update our version as well.

+libraries[tinymce][download][url] = https://github.com/downloads/tinymce/tinymce/tinymce_3.5.7.zip
+libraries[tinymce][patch][1561882] = http://drupal.org/files/1561882-cirkuit-theme-tinymce-3.5.7.patch

**Comment by sylus** [comment]
This was recently done at https://github.com/sylus/tinymce-wetkit/commit/cecd802bc4d74ca032158d68ba0f53f2deac41dd

New makes will update to using this.

@joejoseph00 just so you are aware ^_^

**Comment by joejoseph00** [comment]
@sylus,  I see , you're working after supper :+1: 
Has anyone regression tested this new version of TinyMCE against the custom plugins?  Just wondering.  

Good to know that it's gone to 3.5.7, this way if we have problems we'll know a bit about where to start troubleshooting.

Thanks.
