### ISSUE TITLE
Search field displaying incorrectly

### ISSUE THREAD

**Issue by pjackson28** [wet-boew/wet-boew-drupal#447]
The search field at http://wet.openplus.ca/eng is displaying incorrectly. By default the input field and submit button are on different lines causing the search to overlap the Canada wordmark. In addition, tabbing to the search field causes the search area to expand upwards (revealing two radio buttons with no labels and a "close link") which is then overlapped by the GC nav bar (top black bar).

**Comment by sylus** [comment]
Was a problem with the Installation and permissions will fix over the weekend ^_^
