### ISSUE TITLE
Fixed parent item in menu blocks

### ISSUE THREAD

**Issue by eimhin** [wet-boew/wet-boew-drupal#450]
Hello,

The  "fixed parent item" setting doesn't seem to be working when adding a menu pane to a panels layout. (ie. the WET: Mega Menu tree).  When I save the settings the menu just reverts to the root level, instead of being relative to the fixed parent setting. The other settings (starting point, active menu link) work as expected. I get the same issue whether I'm using the IPE or Panopoly admin. 

On the other hand, the setting works if I make a new menu block  (structure >> add new menu block) and then insert it into a panels layout as a standard block pane (miscellaneous tab). I get the same result but it requires pre-creating all the fixed parent menus.

Maybe this is an incompatability with the menu blocks module and panelizer. Is anyone else experiencing this issue?

Thanks

**Comment by sylus** [comment]
Will take a look :) Thanks @eimhin really happy to have you in the code :)

**Comment by sylus** [comment]
Hazaa this was fixed upstream by the amazing @populist :) I am bringing in his recent updates right now but if you would like to see the issue: http://drupal.org/node/1802098

**Comment by sylus** [comment]
Looks fixed can you verify this by updating codebase? :) Please reopen if problem persists :)
