### ISSUE TITLE
Suggest and Vote for Wxt Drupal Working Group Agenda Items

### ISSUE THREAD

**Issue by sinkinsona** [wet-boew/wet-boew-drupal#453]
We want to here the agenda items that the community would like to have discussed at our WxT Drupal Working Group meetings. Request agenda items  by visiting this wiki page https://github.com/wet-boew/wet-boew-drupal/wiki/Suggest-and-Vote-for-Agenda-Items and editing the page. Add a new item and or vote by adding 1 to the item you would like tabled. We will commit to addressing at least the highest voted item at the next re-occurring meeting and maybe more..

**Comment by sinkinsona** [comment]
We are planning our next WxT Drupal working group meeting this week and we will be finalizing the agenda.  Visit the link above to add items you would like discussed or add a comment to this issue.

**Comment by StephenOTT** [comment]
Suggest Pull Requests.  What needs to be updated, changed.
Would be a good demo, and documentation.

**Comment by StephenOTT** [comment]
Mentions for new people in the signup list
@jamessauve
@Pacoup
@theadbo
@bmiller72ca
@strinh
@jamesson
@ericvong

**Comment by StephenOTT** [comment]
Would also like to add the topic of responsive images.
http://drupal.org/project/resp_img
http://drupal.org/project/responsive_images

WET has a way to handle this.  But it is another one of those questions about when do you use the WET Core feature or override the core feature with something that a Drupal module will handle better and provide a administration interface.

Focus is not on the two modules above, but more the direction for responsive image support in the distro as a administration/configuration feature.

**Comment by pjackson28** [comment]
WET core has something through grids (essentially scaling to the container) but looking forward it will adopt whatever ends up being implemented for responsive images for the HTML5 spec.

There are two competing visions right now for implementing responsive images, the picture element (W3C community) and the srcset attribute (WHATWG). Once it is clear that one has been chosen over the other then WET core will work to implement a polyfill to allow it to be used before widespread browser adoption. Currently there are competing proposals for both approaches for inclusion as HTML5 extensions and Chrome has a test build with picture support but no decision has been made at this point by the HTML working group. You can read more here: http://www.w3.org/community/respimg/

If you need to implement something in the interim then I would suggest making it as easy as possible to transition to whatever will be the way forward for responsive images in HTML5 (once they make up their minds). It may be worthwhile implementing an interim polyfill approach for the picture element and building a module that supports that but to make it easy to switch over to srcset if that ends up winning out. I believe there is a picture polyfill out there already (may need some refining). Ideally the polyfill would be integrated into WET core and then could be leveraged within the Drupal variant like you've leveraged the other polyfills.

**Comment by StephenOTT** [comment]
Agenda has been set for November 16 meeting #486
