### ISSUE TITLE
Finalize a project name

### ISSUE THREAD

**Issue by colans** [wet-boew/wet-boew-drupal#454]
As a follow-up to the project-name discussion as the committee meeting, here is the issue to discuss.

After thinking more about this, maybe we should come up with a succinct self-identifying name rather than a long description as we have now, "Web Experience Toolkit - Drupal Variant".  Other Drupal distributions are doing this exactly, such as [Spark](http://drupal.org/project/spark) for example.  Perhaps the creative folks in the crowd could help develop such a name?

A good reason for doing this is that most folks (outside of the federal government, generally, but inside as well) have no idea what the Web Experience Toolkit is.  We can get away from confusing them.

Thoughts?

**Comment by sinkinsona** [comment]
@colans I would says that the name Web Experience Toolkit (WET) is well recognized within the federal government but not as much for people not in the public sector.  In gov hearing that a project is part of WET is a positive thing as WET is well know in the GOC for producing accessible, usable and interoperable solutions.  Actually my clients at stats often say use a WET solution if one exists.  Maybe we could just go with Web Experience Toolkit Drupal or WET Drupal for short and lose the Variant part.
