### ISSUE TITLE
Enabling External Electronic Archives - App Needed

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#456]
Stemming from a meeting with the University of Ottawa yesterday I wanted to touch on managing electronic archives.  It ties sorta into:
https://github.com/wet-boew/wet-boew-drupal/issues/198

But it's really a lot bigger than this.  The biggest discussion I've seen about providing a reliable electronic archives (other than just a zip of the whole site) has been pushed by @Silona in:
  http://silona.org/category/citability/

It's about two years old but efforts by the NY Senate to implement this (for Drupal) are things that possibly @GraylinKim might be able to fill us in on.  The main site for this effort is:
   http://citability.org/

There was a wiki on building this in Drupal that was started here:
  http://citability.pbworks.com/w/page/7506680/Drupal

There seem to be some interesting projects by folks like @anarchivist that might be able to be brought into this too.

In anycase, we need to have some sort of strategy to preserve content in a static state in an increasingly dynamic world.  Some relevant links:
  http://archive.org/about/faqs.php
  https://en.wikipedia.org/wiki/Web_archiving

**Comment by GraylinKim** [comment]
I'm not exactly sure what you are talking about re: the NYSenate efforts @mgifford. I've only been with the Senate for a year and work on [nysenate/OpenLegislation](github.com/nysenate/OpenLegislation) and various internal [software systems](github.com/nysenate).

I believe @rtblair would be more knowledgeable about any Drupal efforts past or present.

**Comment by mgifford** [comment]
Sorry @GraylinKim it's stuff that I heard was being developed.  Possibly through Andrew Hoppin.  So it's safe to assume that the NY Senate isn't actively working on a digital archive management strategy.  Would be interesting to know if folks at the Whitehouse are.....

Thanks for your quick response.

**Comment by sylus** [comment]
Cleaning up some old issues. :)
