### ISSUE TITLE
(Meta) Working Group Minutes

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#459]
This is a meta issue for Working group minutes.  Discuss minutes, changes, updated, corrections, etc.

Minutes will be draft for 1 week from date of posting.  After the week if no changes have been made, minutes will become final.

**Comment by StephenOTT** [comment]
September 25 Draft Minutes have been posted.
https://github.com/wet-boew/wet-boew-drupal/wiki/WxT-Drupal-Working-Group

They will be draft until October 12, 2012.  You have 1 week to review and comment as needed.

Thanks

**Comment by sylus** [comment]
I added a PDF format for those who would have problems using .doc ^_^

**Comment by colans** [comment]
Is there a particular reason the minutes weren't written as a wiki page?  I'm not sure why we would need to bother with attachments at all.

**Comment by StephenOTT** [comment]
Document was already in word from the person who took the minutes, and I had not had the time to transfer.  @patcon helped us out and converted to .md.
See link for markdown version
https://github.com/wet-boew/wet-boew-attachments/blob/master/Working%20Groups/Drupal%20Variant/Meetings/September%2025%202012/Minutes/WET%20Drupal%20Variant%20Working%20Group%20Meeting-Sept%2025%202012-Minutes-DRAFT%20v1.md

**Comment by StephenOTT** [comment]
September 25 Draft Minutes are final

**Comment by patcon** [comment]
Thanks Stephen! Yeah... The nerd in me liked markdown in a repo, but maybe wiki format is best going forward? At the next meeting we could even just nominate someone to pop it open and take notes in the wiki right in the meeting?

**Comment by StephenOTT** [comment]
Minutes and Presentation have been posted for the January 25 2013 meeting:
https://github.com/wet-boew/wet-boew-attachments/tree/master/Working%20Groups/Drupal%20Variant/Meetings/January%2025%202013

**Comment by StephenOTT** [comment]
This issue stays open all the time for Minutes

**Comment by sylus** [comment]
This hasn't been updated and I'd rather post minutes in our website that is being launched either today or tomorrow. So closing!
