### ISSUE TITLE
Development Mode for JS + CSS WET Files

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#46]
A few people have suggested it would be nice to switch to development for the files loaded from WET as they come minified.

**Comment by eleclerc** [comment]
I just want add my vote on this issue. if my understanding is correct, Drupal core can minify the file for a production website anyway

**Comment by sylus** [comment]
This is now done, though will have to check if the correct way and not a performance issue:

Properly Library Integration using new libraries 2.x -> This now gives us support for source (unminified) or default (minified) WET-BOEW JS. This can be set in admin/config/wetkit_web_usability/settings
