### ISSUE TITLE
SEO App - Everyone wants to be found!

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#460]
Thinking about this, I think we could probably leverage this other distro's work in this area:
http://drupal.org/project/debut_seo

Would still be a good idea to review if there's anything specific that needs to be added to this app for bilingual environments.

**Comment by sylus** [comment]
The app is very minimal doesn't do too much other then an info + makefile including some modules.

Though the only modules we are missing are globalredirect and xmlsitemap. We could add them as an seo module but not sure what the best way would be.

**Comment by mgifford** [comment]
I hadn't evaluated debut_seo, but could be a useful starting point.

Another good module is:
http://drupal.org/project/seo_checklist

**Comment by sylus** [comment]
Cleaning up some old issues. :)
