### ISSUE TITLE
Atom Syndication

### ISSUE THREAD

**Issue by sinkinsona** [wet-boew/wet-boew-drupal#461]
In support to the GOC Standard on Web Interoperability (http://www.tbs-sct.gc.ca/pol/doc-eng.aspx?section=text&id=25875) web feeds are to be available in the Atom Syndication Format specification (http://tools.ietf.org/html/rfc4287).  Currently the distro does not have any modules to provide this functionality.

Looks like the following modules are available to provide Atom functionality:

This mod exist http://drupal.org/project/atom but is in beta.  Looks like it needs to be patched for xml:lang support.

Another option would be http://drupal.org/project/views_atom but it looks like this module is most useful when used in conjunction with the http://drupal.org/project/feeds_atom.  Both are in dev.

based on downloads 6,756  http://drupal.org/project/atom seems to be the most popular.

I am going to evalute and let you know my findings.  Any recommendations, suggestions from the community are always welcome :)

**Comment by thriuin** [comment]
Neither module is heavily used, but the views_atom module offers more much more flexibility to define the content of your feeds. It was developed for use with feeds_atom, but there is no requirement to use it with feeds_atom - it will create an atom feed.  

If you do use views_atom, please note there is a bug that prevents it working with newer versions of the Feeds module (http://drupal.org/node/1632362) - I submitted a patch for this some time ago http://drupal.org/files/views_atom-Update_feeds_item_table_name-1632362-1.patch. I've used it quite successfully, so far, with developing our solution for content staging.

**Comment by colans** [comment]
As you'd want to control the contents of your feed with Views, I'd recommend picking a module that has support for it.

**Comment by sinkinsona** [comment]
@thriuin and @colans based on my evaluations http://drupal.org/project/views_atom works great and with views.  Unless I hear otherwise I will submit the pull request and close this issue.
