### ISSUE TITLE
Language of Parts

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#465]
This is an important part of WCAG & an even more important part of the GoC.  Let's make sure we've got some folks looking at it in Core:
- [Drupal Issues](http://drupal.org/project/issues/search/drupal?issue_tags=language%20of%20parts)
- [Discussion on GDO](http://groups.drupal.org/node/145894)

**Comment by sylus** [comment]
Closing this as can be handled as part of the larger discussion in #296

**Comment by mgifford** [comment]
I'd like to leave this here as a separate issue.  Partly because it isn't solved in Drupal 8.  There are some approaches we can consider, but as any bilingual organization needing to deal with internationalization, this is huge.  

It's not going to be solved (I don't think) in an Accessibility App as it comes down to how we choose to deal with string translation.  It's going to take some serious investment in Drupal 8 or Drupal 9 to fix this.  Ultimately it's going to be something that is going to have to be monitored & possibly spearheaded by government institutions that need to deliver bilingual websites.

I see the Accessibility App as something that can be thrown together now with best practices & enhancements based on Drupal 7. 

So yes, this is bigger than the D7 Distro, but pretty critical to getting this to meet WCAG 2.0 AA.

**Comment by sylus** [comment]
Fair point add Working Group label to it as merits discussion in that forum as well.
