### ISSUE TITLE
Access control solution: Alternatives to Workbench

### ISSUE THREAD

**Issue by patcon** [wet-boew/wet-boew-drupal#467]
Forked from #445

Maybe we could discuss what those alternatives might be, and post a few links. I'll try to dig into some other mainstream profiles later to see how they decided to tackle access control.

**Comment by sylus** [comment]
I think @joel-osc has a pretty good handle on an access control model. /cc

**Comment by sylus** [comment]
Workbench is in as no real other alternatives.

**Comment by patcon** [comment]
:+1:
