### ISSUE TITLE
Stylesheet Question - IE8 - content always staying at 960px

### ISSUE THREAD

**Issue by mxlav** [wet-boew/wet-boew-drupal#468]
Two part question:
1. 
   I've been mostly working in Firefox locally, but need to make sure everything looks ok on IE8 since that's what the entire agency uses.

I noticed that on Firefox the content stretches to the edges using 1200px, but in IE, even if I stretch the display on two screens, it always remains at 960px.

Is this an IE limitation or is there additional markup I could use?

2.
I have a style sheet in my subtheme folder and while testing in Firefox, the changes I make are rendered in the browser, but when I check in IE they don't come up. If I go play around the the theme-ie-min.css file, I can get my changes showing, but I know I shouldn't be playing in the core files...why is IE not seeing my css within my sub-theme?

**Comment by mxlav** [comment]
I had a moment right after I hit the post button :-)

So I added a line in my theme.info file

stylesheets-conditional[lte IE 8][all][] = css/myfilename.css

and it is now overriding the ie-min file

Still need info for question 1 though.

**Comment by LaurentGoderre** [comment]
Regarding question #1, older versions of IE don't support media query so responsive design doesn't work on it. More recent version such as IE9 and 10 should support it.

**Comment by LaurentGoderre** [comment]
Regarding you question number 2, the way it is set up is that IE loads its own set of stylesheet and all the borwsers load another one. The IE specific ones are basically the stylesheets for every browser with some IE specific fix.

**Comment by mxlav** [comment]
thanks for the clarification!

**Comment by sinkinsona** [comment]
Questions have been answered so closing issue.  Re-open should further clarification be needed.
