### ISSUE TITLE
Beans & Entity Translation

### ISSUE THREAD

**Issue by uottawa-wcms** [wet-boew/wet-boew-drupal#469]
@sylus wanted to leave you this note, in case you run into the same issues.

I had to replace the entity_translation module that came with wetkit with the -alpha2 version from drupal.org, in order to get beans to work. If I didn't, the fields for beans would not display if they were set to be translated.

Not sure if you guys customized it or if it's a bug in their dev branch - wanted to check first before I posted to d.o as a bug, as well as let you know the fix in case you were wrestling with it.

Cheers,
Rob

**Comment by sylus** [comment]
Cleaning up some old issues. :) and using both of this :)
