### ISSUE TITLE
Improve Form Validation

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#470]
There is definitely room for improvement with form validation in Drupal 7.

Thoughts on D8 approaches:
http://groups.drupal.org/node/209513

Current concerns with HTML5 & D8:
http://drupal.org/node/1797438

Possible improvements through (with a bit of work):
http://drupal.org/project/clientside_validation

Neat JS example:
https://github.com/fnagel/jQuery-Accessible-RIA

Example of WET form:
http://wet-boew.github.com/wet-boew/demos/formvalid/formvalid-eng.html

Best practice suggested by @pjackson28
- JS validation first
- HTML5 validation for no-JS
- finally rudimentary server-side validation

**Comment by sylus** [comment]
Yeah this finally needs to get some love will start working on it ^_^

**Comment by mgifford** [comment]
That's great.  If we can worth through the model that Paul outlined, we might be able to get it into Drupal 8.  Time's running out on that though so would be good to put up a patch that can provide a best practice. We can then backport it to Drupal 7 WET.
