### ISSUE TITLE
Page addresses, accented characters, and transliteration

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew-drupal#474]
Does anyone know the standard for page addresses as it relates to non-ascii characters?  

The reason I ask is if I create a page in Drupal called "Senate Reform" and the French page is then titled "Réforme du Sénat", the page name will be http://mysite.gc.ca/content/réforme-du-sénat, with the accented characters in the URL.  Is this allowable now?  The old CLF pages have examples with page names including /francais/ but I found no pointer to a standard that said the '&ccedil;' should become a 'c', for example.

There is an option under /admin/config/search/path/settings called "Reduce strings to letters and numbers" which, when checked, will replace anything not in the ASCII-96 set with a dash, so the page address becomes http://mysite.gc.ca/content/r-forme-du-s-nat.

There is also a transliteration module (not included with this Wxt install profile) that will change the page address to http://mysite.gc.ca/content/reforme-du-senat.  I'd recommend inclusion of this module.  Any thoughts?

**Comment by StephenOTT** [comment]
We are using the transliteration module.  

If I remember right I think it was a missed module.

@sylus can you confirm?

**Comment by theadbo** [comment]
[We](https://buyandsell.gc.ca) use the transliteration module as well.

**Comment by jamessauve** [comment]
What rules do you use? Is there a standard?  As Rob said, right now most upper ascii are being set to a dash (-), but not all.  Fancy apostrophes (pasted in from MS Word) for instance and em dashes.  

We have a pretty good idea what we plan to do, but if there is an existing standard, we'd surely follow that rather than re-invent the wheel.

**Comment by theadbo** [comment]
Sorry for the overly brief response earlier. We flatten all accented characters to the basic letters, é becomes e, ç becomes c etc. Apostrophes become dashes so S'inscrire becomes s-inscrire. I don't believe we're following any kind of standard.

**Comment by jamessauve** [comment]
That's pretty much exactly what we were planning.  Thanks.

**Comment by sylus** [comment]
Added the transliteration module :)
