### ISSUE TITLE
CMS Comparison by RCMP?

### ISSUE THREAD

**Issue by Pacoup** [wet-boew/wet-boew-drupal#475]
I know there's been talks of having RCMP's comparison done on various CMS up on the Wiki, but I just searched for it and couldn't find it.

Is this already available somewhere?

We're going through our own decision process on whether to use Drupal and we'd greatly appreciate previously done comparison efforts; especially one done with the GoC in mind.

**Comment by StephenOTT** [comment]
Hey pat

This is one of the action items from the past Drupal working group.  I am working to determine if the document is ready to be posted on Github.  Will get back to you shortly

**Comment by sinkinsona** [comment]
I know that @jeffdavidgordon team from RCMP had done an evaluation and we could share that document with you + sounds like @StephenOTT might be converting the document to mark down for posting on wiki.  One thing to keep in mind for the GOC is that TBS Information Management is recommending Drupal or Interwoven as a guideline for WCMS.  If you have access to GCPedia (internal to GOC ) you can find the recommendation and requirements that have been defined by the WCMS tiger team.

**Comment by StephenOTT** [comment]
Sent email to Chris to confirm if information can be shared/ready to be shared.

**Comment by MaddyDaigle** [comment]
I can send the documentation to whomever might need it as well.  Just flip me an e-mail.

**Comment by mxlav** [comment]
can you sen me a copy please.

marc.lavictoire@cbsa-asfc.gc.ca

**Comment by MaddyDaigle** [comment]
I've actually just added it to the wiki, if that's okay.  The documentation is located here: https://github.com/wet-boew/wet-boew-drupal/wiki/WCMS-Comparison
Keep in mind that this was written before WET Drupal took off.  It might be beneficial to add what's already been accomplished by the variant in that document as well.

**Comment by StephenOTT** [comment]
Closing as this has been posted
