### ISSUE TITLE
Metadata Dublin Core

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#478]
Dublin Core appears to be falling to the wayside as a metadata standard.

Should we be moving to another standard?

**Comment by thriuin** [comment]
HTML 5 Microdata combined with the vocabularies described on http://schema.org are an emerging standards that get lots of buzz. There is, of course, a module for that: http://drupal.org/project/microdata, but it seems to be a work in progress.

I think it is a little premature to dismiss Dublin Core altogether. While there lots of academic interest in more advanced semantic technologies, I don't think there is either widespread concensus or adoption of any single new standard.

**Comment by colans** [comment]
There's an upstream discussion on implementing DC (and its issues) over at [Add new meta tag: Dublin Core](http://drupal.org/node/1491616).  To my knowledge, it's still needed by the feds.

**Comment by thriuin** [comment]
Correct. As per TBS standards that @StephenOTT references in the other issue #174, all GoC sites will still need to provide basic Dublin Core support for now. Non-GoC entities of course don't have to follow this standard, but support for DC still needs to be included in the core WxT-Variant for the time being.

**Comment by sylus** [comment]
Marking this as postponed until there is a clear defined standard.
