### ISSUE TITLE
Building an App, and publishing it to an App server

### ISSUE THREAD

**Issue by joejoseph00** [wet-boew/wet-boew-drupal#487]
Placemarker for developer notes on building an app, and publishing it to an app server.

Start with a feature, or multiple features turn it/them into an app.  

App standards (draft)
http://groups.drupal.org/open-app-standard/oas

How to build an app:
http://products.phase2technology.com/display/commondocumentation/How+to+Build+an+App

**Comment by sylus** [comment]
Cleaning up some old issues. :)
