### ISSUE TITLE
Distro update

### ISSUE THREAD

**Issue by joejoseph00** [wet-boew/wet-boew-drupal#488]
I performed a distro update today and got this message:

Include file missing: drupal-org-core.make                       [error]
Include file missing: drupal-org.make                                [error]
drupal-7.16 downloaded.                                                       [ok]

Should I ignore the missing include file?  

When I ran the updatedb command, it said:  
No database updates required                      [success]
Finished performing updates                         [ok]

**Comment by sylus** [comment]
No something must have went wrong. You are not supposed to lose those files. Makes me wonder what else was lost. Did you do both a git clone and a drush make?

**Comment by joejoseph00** [comment]
Hi @sylus, correction, git clone?  that I believe is done during install.  I followed step 1, 2 , 3 of update.  Step 1 is Switch (cd) to your working Drupal Directory. (distro directory) Step 2 is run drush make, I also just re-tried on another server, same thing, drush said those two make files were missing.  However they are actually sitting there in the profiles/wetkit folder.

Note: both Drupal installs I tested this on (two different servers) had the wetkit distro installed my user's public_html  folder using the userdir directive and userdir mod.  I don't see why that would make a difference though.

I've tested the update on recent distro installs using
git  1.7.3.4 on OpenSuse 11.4
php 5.3.5 (open suse 11.4)
drush version 5.4

and on Novell SLES SP1
git 1.7.x
php 5.2.x
drush 5.4

Here's the exact message from step 2 of the update procedure:

@www:~/public_html/aidedisplaysuite> drush make --no-gitinfofile --working-copy https://raw.github.com/wet-boew/wet-boew-drupal/master/build-wetkit.make .
Include file missing: drupal-org-core.make                                                                                    [error]
Include file missing: drupal-org.make                                                                                         [error]
drupal-7.16 downloaded.                                                                                                       [ok]

Step 3 (updatedb) said there were no db updates to perform, then gave a success message.

So I'm concerned about the missing make files.  I actually checked, and those files are there;

see:
find ~/public_html/aidedisplaysuite -name drupal-org-core.make
it finds it here:
~/public_html/aidedisplaysuite/profiles/wetkit/drupal-org-core.make

I also found the other file in the same folder.  

As you can see, I instantiated the drush make command from the drupal install dir, (root of drupal install dir)
in this case aidedisplaysuite

**Comment by joejoseph00** [comment]
I updated the last comment

**Comment by sylus** [comment]
Ah your doing a full build and not a relative one. You shouldn't use the full url anymore but rather the local build-wetkit.make sorry didn't see this earlier.

**Comment by joejoseph00** [comment]
ok, so we should update step 2 on the project home page https://github.com/wet-boew/wet-boew-drupal ?

Step 2
To quickly update an existing site using the Drush command line, change to the directory where Drupal was installed and enter this command.

Command: drush make --no-gitinfofile --working-copy https://raw.github.com/wet-boew/wet-boew-drupal/master/build-wetkit.make .

to 
Step 2
To quickly update an existing site using the Drush command line, change to the directory where Drupal was installed and enter this command.

Command: drush make --no-gitinfofile --working-copy profiles/build-wetkit.make .

?

**Comment by joejoseph00** [comment]
Hi @sylus, have you actually ran the update procedure on the homepage of https://github.com/wet-boew/wet-boew-drupal
?
This is what happens on my test box:
user@server:~/public_html/wetboew> drush make --no-gitinfofile --working-copy https://raw.github.com/wet-boew/wet-boew-drupal/master/build-wetkit.make .
Include file missing: drupal-org-core.make  [error]
Include file missing: drupal-org.make         [error]
drupal-7.16 downloaded.                           [ok]

See step 2 in "update" on the page https://github.com/wet-boew/wet-boew-drupal,

SO, I tried THIS instead:
drush make --no-gitinfofile --working-copy profiles/wetkit/build-wetkit.make .

but it just re-downloads drupal 7.15, but isn't the point of updating to go to drupal 7.16?  Or is panopoly still on 7.15?

I also noticed three errors when doing this using profiles/wetkit/build-wetkit.make :
Unable to clone tinymce from https://github.com/sylus/tinymce-wetkit.git.                   [error]
Unable to clone markitup from https://github.com/sylus/markitup-wetkit.git.                 [error]
Unable to clone wet-boew from https://github.com/wet-boew/wet-boew.git.                     [error]

Can you please enlighten me on the update procedure?  Perhaps I'm missing something totally obvious.

**Comment by sylus** [comment]
Cleaning up some old issues. :) (This is answered on the README now)
