### ISSUE TITLE
SQLSTATE[23000] error 

### ISSUE THREAD

**Issue by aminophenol** [wet-boew/wet-boew-drupal#489]
Thanks in adance!

I got this error at the end of the wetkit installation:
SQLSTATE[23000]: [Microsoft][SQL Server Native Client 11.0][SQL Server]Cannot insert duplicate key row in object 'dbo.file_managed' with unique index 'uri_unique'.  

Tried also MySQL and got a similar message:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'uri' 

Here's my installation steps:
1. unzip drupal zip into a windows directory, added SQL Server drivers
2. at root of drupal, git clone https://github.com/wet-boew/wet-boew-drupal.git profiles/wetkit; 
3. at root of drupal, drush make --prepare-install --no-gitinfofile --working-copy profiles/wetkit/build-wetkit.make --yes
4. copy profiles/wetkit/ to root of drupal directory 
5. at root of drupal, drush make --no-gitinfofile --working-copy https://raw.github.com/wet-boew/wet-boew-drupal/master/build-wetkit.make .
6. run http://domain/install.php (- installation profile = Web Experience Toolkit )

Installation would run ok until the end.  Below is the complete error message at the end.

An AJAX HTTP error occurred.HTTP Result Code: 200Debugging information follows.
Path: http://van-v-web/install.php?profile=wetkit&locale=en&id=1&op=do
StatusText: OKResponseText: Home | Drupal
@import url("http://van-v-web/modules/system/system.theme.css?mcb84o");
@import url("http://van-v-web/modules/system/system.messages.css?mcb84o");
@import url("http://van-v-web/modules/system/system.menus.css?mcb84o");
@import url("http://van-v-web/modules/system/system.base.css?mcb84o");
@import url("http://van-v-web/sites/all/modules/contrib/jquery_update/replace/ui/themes/base/minified/jquery.ui.core.min.css?mcb84o");
@import url("http://van-v-web/sites/all/modules/contrib/jquery_update/replace/ui/themes/base/minified/jquery.ui.accordion.min.css?mcb84o");
@import url("http://van-v-web/sites/all/modules/contrib/date/date_api/date.css?mcb84o");
@import url("http://van-v-web/sites/all/modules/contrib/date/date_popup/themes/datepicker.1.7.css?mcb84o");
@import url("http://van-v-web/sites/all/modules/contrib/fences/field.css?mcb84o");
@import url("http://van-v-web/modules/node/node.css?mcb84o");
@import url("http://van-v-web/sites/all/modules/panopoly/panopoly_admin/panopoly-admin.css?mcb84o");
@import url("http://van-v-web/sites/all/modules/panopoly/panopoly_core/css/panopoly-fonts.css?mcb84o");
@import url("http://van-v-web/sites/all/modules/panopoly/panopoly_core/css/panopoly-modal.css?mcb84o");
@import url("http://van-v-web/sites/all/modules/panopoly/panopoly_core/css/panopoly-dropbutton.css?mcb84o");
@import url("http://van-v-web/sites/all/modules/panopoly/panopoly_magic/panopoly-magic.css?mcb84o");
@import url("http://van-v-web/sites/all/modules/panopoly/panopoly_theme/css/panopoly-featured.css?mcb84o");
@import url("http://van-v-web/sites/all/modules/panopoly/panopoly_theme/css/panopoly-accordian.css?mcb84o");
@import url("http://van-v-web/sites/all/modules/panopoly/panopoly_widgets/panopoly-widgets.css?mcb84o");
@import url("http://van-v-web/modules/search/search.css?mcb84o");
@import url("http://van-v-web/modules/user/user.css?mcb84o");
@import url("http://van-v-web/profiles/wetkit/modules/custom/wetkit_demo/wetkit_demo.css?mcb84o");
@import url("http://van-v-web/profiles/wetkit/modules/custom/wetkit_widgets/wetkit-tabbed-interface.css?mcb84o");
@import url("http://van-v-web/profiles/wetkit/modules/custom/wetkit_wysiwyg/wetkit-wysiwyg.css?mcb84o");
@import url("http://van-v-web/sites/all/modules/contrib/views/css/views.css?mcb84o");
@import url("http://van-v-web/modules/system/system.admin.css?mcb84o");
@import url("http://van-v-web/modules/system/system.maintenance.css?mcb84o");
@import url("http://van-v-web/sites/all/modules/contrib/ctools/css/ctools.css?mcb84o");
@import url("http://van-v-web/sites/all/modules/contrib/panels/css/panels.css?mcb84o");
@import url("http://van-v-web/themes/seven/reset.css?mcb84o");
@import url("http://van-v-web/themes/seven/style.css?mcb84o");
@import url("http://van-v-web/sites/all/modules/panopoly/panopoly_images/panopoly-images.css?mcb84o");
Home  
Installation tasksChoose profileChoose languageVerify requirementsSet up databaseInstall profileConfigure siteChoose a themeImport French LanguageFinished  
Status messageCustom Search enabled. Don't forget to set permissions.
Refreshed 2 strings for the enabled modules.
Refreshed 8 strings for the enabled modules.
To use menu blocks, find the "Add menu block" link on the administer blocks page.
Password policy module successfully installed. Please review the available configuration settings.
Reset language for all terms.Warning message
The image resize filter has been installed. Before this does anything, the image resize filter needs to be added to one or more text formats. Visit the text format administration to set up this filter.
Error messageThe file could not be created.The file could not be created.
The file could not be created.The file could not be created.
The file could not be created.The file could not be created.
The file could not be created.The file could not be created.
SQLSTATE[23000]: [Microsoft][SQL Server Native Client 11.0][SQL Server]Cannot insert duplicate key row in object 'dbo.file_managed' with unique index 'uri_unique'.    

99%Completed 133 of 134.
Installed WetKit WET-BOEW module.

Tried also MySQL and got a similar message:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'uri'

**Comment by RobJohnston** [comment]
I've had problems on Windows and the line "The file could not be created" sounds familiar.  I had to manually create the "tmp" directory (/sites/all/files/tmp or /sites/subsite1/files/tmp).  Once it's created the installation can put the .htaccess file into it, but can't seem to create the directory.  

As an aside, this location is specified on the /admin/config/media/file-system page that you'll see once you get Drupal installed.

**Comment by aminophenol** [comment]
That fixed it!

My temp file location happens to be at C:\Windows\Temp.  I gave "Everyone"
Write access to it  (as IUSR or Network service wouldn't work)
and .htaccess was created there at the end.

Thank you very much!

**Comment by sylus** [comment]
Thanks @RobJohnston :) closing issue.
