### ISSUE TITLE
Panelizer question

### ISSUE THREAD

**Issue by mxlav** [wet-boew/wet-boew-drupal#492]
How does Panelizer filter the available items to use/display (in the left hand bar)? For example you will get defferent choices on a landing pages, or in the panel editor, or mini panels on a content type such a basic page.

The reason I ask is I am trying to add <page messages> to two places i noticed it was missing
1. landing pages
2. when editing a content type (Node add/edit form panel)

The only place I found the <page messages> was under <Page elements, Status Messages>, but this tab is not available from the two items listed above.

**Comment by sylus** [comment]
Awesome documentation can be found here: http://drupal.org/node/1704334

Panelizer specifically can be explained by: 

It is probably best to think of Panelizer as a kind of Page Manager for entities. Like Page Manager it allows you to set the renderer, layout and content for each entity type however Panelizer takes things to the next level. Now the layout and content for individual entities can be customized. Want to add a video to a specific node or a list of related content to a taxonomy term? Panelizer says: NO BIG DEAL.

Entities can be panelized in the Panelizer configuration. Panelizing entities is highly encouraged for your Panopoly App. Make sure that you select both "panelize" and "provide default panel" for your entity and all its view modes.

**Comment by mxlav** [comment]
OK so by going in Structure--Panels--Settings--Panel Pages--Allowed Other Content, and I was able to select "Status messages" for both my landing page and the add/eddit panel.

Note: I would think you would want the messages displayed by default on the add/eddit panel, so that any validation errors when entering content is displayed? In any case closing.

**Comment by sylus** [comment]
You are correct this should be there by default reopening till next commit

**Comment by nadinecz** [comment]
This might very well fall into the “ok…what’d I do wrong category…”

Thanks to the above, I can now add the status message to the node edit/add panel variant.  But, that wasn’t enough to get messages to display.

I had to change the page—panels-internet.tpl.php files to print the messages (this got me the drupal generated validation errors on the form).    

So the question(s)
-   Is this the correct way to “fix” this?  (note, that I`ll move it to my subtheme if I need to persist it).
-   If not, what did I miss?  :)

**Comment by nadinecz** [comment]
So further testing shows (for me) that adding the status message on the panel had absolutely no effect...

I know the panel variant is being "invoked" - other changes made are taking effect.

**Comment by sylus** [comment]
Will be pushing code within an hour or two with the fix :) You shouldnt need to use the template to print the message array as that will force the status messages outside of the panel context. This is perfectly fine to do but now it will be duplicated for the panel layout that u have added status messages to.

**Comment by sylus** [comment]
Hmm although I am wondering if makes sense to remove from panels and just write messages in the template so is always present above a panels layout. Thoughts @nadinecz?

**Comment by nadinecz** [comment]
I favor the the template route, done once and no one needs to hunt for it :)
