### ISSUE TITLE
Upgrading from an older version of WET..formating issues

### ISSUE THREAD

**Issue by mxlav** [wet-boew/wet-boew-drupal#493]
So I had a prototype app running on an older version of WET still using zen responsive theme. Decided to port it to a fresh install of WET3 using features, mostly to bring over my HUGE content types.

The issue I am having is that on the old version, when viewing saved content, it was displaying 
   bold Label : data 
and it was displaying in line as per specified in the content type.

Now everything is coming in as H4 labels, which then makes a carriage returns so the inline display doesn't work.

I assume that this is related to fences being part of the newest build, but I can't remove fences as it is linked to the WET-BOEW module.

If I chose from the WRAPPER MARKUP , no markup or div, it removes the H4 label, but then it's just plain text, not bolded, and still not inline. Most of the the other options in the list are prety specific to lists, or headers.

How do I go back to simple Bold label with inline value?? :S

**Comment by mxlav** [comment]
Still trying to figure this out...so far what i've been able to determine is that the following styling is not being picked up in the new site

<pre><code>
.field .field-label {
    font-weight: bold;
}
.field-label-inline .field-label, .field-label-inline .field-items {
    float: left;
}
</code></pre>

**Comment by sylus** [comment]
Hmm @mxlav are you able to give me a ring? 

I am definitely able to help you with the upgrade but need to see what is going on? Maybe can do a remote desktop session or something.

**Comment by mxlav** [comment]
Sure thing...i don't have your number, but you should have mine.

**Comment by mxlav** [comment]
@sylus sent you some screen shots

**Comment by sylus** [comment]
http://code.google.com/p/msysgit/downloads/detail?name=Git-1.7.11-preview20120710.exe&can=2&q=

**Comment by sylus** [comment]
svn checkout http://svn.github.com/wet-boew/wet-boew.git

**Comment by mxlav** [comment]
```
<div class="field-label"> Emergency Fix Type: </div>
<div class="field field-name-field-emergency-fix-type field-type-list-text field-label-inline inline view-mode-full"> Incident </div>
```

**Comment by mxlav** [comment]
@sylus , when we spoke last time did you say you were going to fix the WET template or that I should sub theme on my end? I can't recall...

**Comment by mxlav** [comment]
@sylus 

Brought in the CSS, no changes for inline.

When I look at the css with firebug and compare it to a regular (non WET) Drupal site, I notice that there is no styling being loaded

Styling from non WET site

```
.field-label-inline .field-label, .field-label-inline .field-items {
    float: left;
}
.field .field-label {
    font-weight: bold;
}
.node .content {
    font-size: 1.071em;
}
body, body.overlay {
    color: #3B3B3B;
}
body, #site-slogan, .ui-widget, .comment-form label {
    font-family: Georgia,"Times New Roman",Times,serif;
}
body {
    font-size: 87.5%;
    line-height: 1.5;
    word-wrap: break-word;
}
```

Styling from WET site, which doesn't have the field label styling

```
textarea, input, body {
    font-family: Verdana,Arial,Helvetica,sans-serif;
    font-size: 80%;
}
body {
    font-size: 80%;
}
body {
    font-size: 13px;
    line-height: 1.5em;
}
```

Note, trying to get this back how it was, i ended up in field--fences-div.tpl.php, playing around in there and I changed it to this (moving the $classes up top and wrapping both label and field; this fixed the inline and the bold label...for a few fields....

```
<div class="<?php print $classes; ?>"<?php print $attributes; ?>>
    <?php if ($element['#label_display'] == 'inline'): ?>
      <span class="field-label"<?php print $title_attributes; ?>>
        <?php print $label; ?>:
      </span>
    <?php elseif ($element['#label_display'] == 'above'): ?>
      <h3 class="field-label"<?php print $title_attributes; ?>>
        <?php print $label; ?>
      </h3>
    <?php endif; ?>

    <?php foreach ($items as $delta => $item): ?>
        <?php print render($item); ?>
    <?php endforeach; ?>
</div>
```

I noticed that Terms of Reference is staying a '''H2''' with '''<ul>''' even when inline is specified

**Comment by mxlav** [comment]
@sylus ... so out of curiosity(/frustration), I went ahead and removed the dependency to fences in the WET-BOEW module, then turned off fences and things go back in line, even for terms of reference.

Questions...what am I braking in WET-BOEW by turning off fences?

**Comment by sylus** [comment]
Nothing at all just more markup gets rendered in Drupal. I might remove it myself if causing problems
