### ISSUE TITLE
Panels & Language Context Bug

### ISSUE THREAD

**Issue by uottawa-wcms** [wet-boew/wet-boew-drupal#494]
I was talking with Joel last week and he mentioned that he's had issues with panes disappearing in the in-place editor (the panes that are not being displayed as a result of the context are disappearing).

Anyone hear anything else about this and have a specific bug report I can follow to get this fixed?

**Comment by joel-osc** [comment]
This is the issue I mentioned: http://drupal.org/node/1069744

**Comment by uottawa-wcms** [comment]
thanks @joel-osc :). They wanted me to stay on top of it, that's all.
