### ISSUE TITLE
Request for Feedback: Separate widget configuration from Panels

### ISSUE THREAD

**Issue by uottawa-wcms** [wet-boew/wet-boew-drupal#495]
So we've been discussing here a new module that might be of interest to the WET-BOEW drupal team and I'd like to get some feedback from you on it.

We feel that, because the IPE is currently non-functional for Panels and the Panels back-end is very complex, it would be useful to provide an interface for users with a less-technical background (ie content editors) to be able to modify the settings of widgets without having to traverse the panels interface.

First question, is this something that Fieldable Panel Panes will solve? It looks like FPP provides a non-Panels administrative interface. If this is simple enough to use (and the widgets can be connected to a panels pane), then that would be good enough.

If not, we were looking at creating something that has a top level admin item called Widgets that lets you create new instances of widgets (and perhaps categorize them using tags). It would then also allow you to plug specific instances into a panels pane. 

The end goal of this is for all of the content of any panel page to be editable without touching panels (and without using the IPE). Only if you wanted to add new items or removing existing items, you would have to touch anything directly related to Panels.

Any thoughts on if this is what FPP will do when the issues around it are fixed and if it would be useful to code this other module in the meantime? It seems like it would be really simple to create a wrapper pane to load another pane and to even provide some kind of dual-language interface to creating wrappers.

**Comment by colans** [comment]
What's "IPE"?

**Comment by sylus** [comment]
IPE is the in place editor for panels.

Just wanted to clarify that I don't see how the IPE is non functional? It only has one bug that I know of that has a patch for it.

However for your larger point I guess a streamlined and simple interface for the widgets perhaps using hook_apps_app_info wouldn't be a bad idea.

As for your first question I think a top level admin item might be the better way to go.

**Comment by kavinay** [comment]
I do agree that IPE is more complex than what I'd want most of my lay users accessing. However, adding FPP to the mix may not solve what in our experience has usually boiled down to a use case and training issue.

If the user needs to frequently customize page layout and contents, they're not just a content editor. They're effectively a webmaster as their ability to manipulate the display is quite powerful (and hazardous! :D ). Such power will require these users to be vetted and trained regarding use of the panel interface or any other solution you provide them. In the end, you still have to put the responsibility on them to understand the rights you've granted them.

Maybe FPP could smooth out some issues, but I think just about any user who's given the ability to customize a page cannot be considered a non-technical use case. Once they're worried about more than only content, these users have assumed a technical role where IPE is warranted and FPP may just be an additional layer of complexity for developers to manage.

**Comment by ottawadeveloper** [comment]
We are mostly looking at the use case of users who need to edit the content in Panels without changing the layout. It seems a pain to have to train people on Panels when all they need to do is change the slides for a slideshow or update a contact number. By abstracting the content from Panels, we can let content editors worry about content and let developers worry about layout.

**Comment by kavinay** [comment]
Agreed, the slide system is painful to lay users. How would FPP make it easier?

BTW, I assumed content like a contact number would be editable anyway. The content editor just needs to access the node where the copy resides, right? Do you mean that boilerplate stuff like that is inserted by hand via panes/views instead? If so, I can see your dilemma now: I wouldn't trust my users with such a right in the production environment either.

@sylus How did you guys picture a content editor setting slides for example? This has worried me a bit as I don't want it to be a developer level task either. Is panels fine-grained enough that we're expected to setup permissions for limited IPE use by a content editor who needs to control arbitrary aspects of the display?

**Comment by sylus** [comment]
Hey @kavinay there is a recent addition to the base distro that offers this granularity of permissions. Please see the issue here: http://drupal.org/node/1813562

There are two ways I would picture a content editor settings slides one using the IPE, the other using the FPP admin area. Of course am open to a more usuable alternative. ^_^

**Comment by ottawadeveloper** [comment]
Agreed, it's only this inline content editing that causes problems, and only because the IPE wasn't available. I saw the IPE patch is out, so I'm going to apply that and discuss if we still need an alternative for editing content that is stored inside of panel widgets.

FPP is still very useful to have, since it exposes them as entities and makes them more translatable (instead of using context). Also, it means that when we get around to making the dual-language editor support entity translation, we can have FPP in side-by-side mode.

**Comment by sylus** [comment]
Yeah though still needs to see why FPP Translatable Patch isn't working :( I know it is something to do with base path and wildcard just haven't been able to isolate.

**Comment by ottawadeveloper** [comment]
:D I'm really looking forward to it, even if it means I have to retrain everyone here on how to build panels widgets.
