### ISSUE TITLE
Unable to use revision information log

### ISSUE THREAD

**Issue by kavinay** [wet-boew/wet-boew-drupal#496]
Hi there,

The revision system in WET seems to be working fine, however I can't seem to get the  _"Revision log message"_ form working in the Node Add/Edit page variant. I've tried to add it to the Sidebar panel via Form Content -> Node form revision log message. However, when a user goes to the add content page, he will only see the _"Revision Information"_ heading and nothing else in that section.

Also, it appears it was a conscious decision to exclude the _"Node being edited" node form revision log_ from the default add/edit content interface. Is there a reason why this was dropped? Will activating this ability to record revision notes interfere with another part wetkit's approach?

Thanks,

Kavin

**Comment by sylus** [comment]
Taking a look right now :)

**Comment by sylus** [comment]
Hey @kavinay,

Looked into this. I think we removed this to minimize the clutter but you are correct you should be able to add it. I have filed an issue with our base distro: http://drupal.org/node/1824256

As soon as a fix is in place will let you know :)

Thanks for the issue!

**Comment by kavinay** [comment]
Great, thanks for the quick response @sylus!

Is there a wiki or doc somewhere that logs what default functionality the team has decided to remove/alter? I find I'm having a tough time telling when functionality just doesn't work or if wetkit or panopoly simply decided to use a different model to accomplish a similar job.

**Comment by sylus** [comment]
Hey the revision code has been added so this should now be fixed.

I will try to find time to map out what functionality was modified around the node add/edit screen.

I think it is mostly pretty minimal stuff. Will post back here.

**Comment by sylus** [comment]
I took further look into this and I think there is most of the standard node add / edit page in place now after the revision was added as well as the tabs (primary and second) on the node edit screen.

We now have our panels page of higher precedence above panopoly_admin so any further customizations can be done there.

Larger additions related to this panels page will likely be needed when the ERS vs Workbench decision is made :)

Please reopen issue if other elements are needed and panopoly unassigns. I search for all unset declarations in panopoly_admin and I think it is only author and revision_information which are moved.
