### ISSUE TITLE
Enhanced Token Browser Doesn't Seem to Work

### ISSUE THREAD

**Issue by thriuin** [wet-boew/wet-boew-drupal#501]
It seems like the distro is trying to provide its own token browser, which is displayed when editing a field that supports tokens and you click on "Browse available tokens.". The browser displays a list of static groups that claims to be clickable or expandable, but is not. Maybe this is a problem with Panopoly, but if there is no fix, can this be disabled?

**Comment by sylus** [comment]
I would bet this is a problem with jquery 1.7?

**Comment by sylus** [comment]
Hey @thriuin I edited the primary image and the browse tokens page is expandable for me but I think you are referring to a different area. Can you point to the page you are experiencing the problem?

**Comment by thriuin** [comment]
This happened in the Rules admin screen. I didn't see any bugs in the Rules issue queue related to this, so it could very well be a jquery issue or some other minor incompatibility issue. In any event, it's not a big deal - I opened this issue just for a reference.

**Comment by sylus** [comment]
Looks fixed now :)
