### ISSUE TITLE
Responsive Panels

### ISSUE THREAD

**Issue by ottawadeveloper** [wet-boew/wet-boew-drupal#502]
I've been looking at responsive panels and it seems like I only have two options (that perhaps I can combine)
1. Use media queries to display: none; the elements I don't want shown at some break-points. The downside to this is the mark-up still gets loaded. We want to cut down on the markup as well (duplicate content is larger and, if I remember right, has a negative SEO impact as it triggers some of Google's spam filters).
2. Use Browscap and Context to hide certain elements from the output at certain resolutions. However, this seems to only target device-by-device. It wouldn't give different outputs for landscape vs portrait or for different desktop resolutions.

Anyone have any better ideas? The goal would be to connect our media-query breakpoints into Panels so that Panels knows not to display those elements at all (no HTML markup, etc) at certain breakpoints.

If there aren't any, does anybody have any input on how we could best add this functionality to Panels? I was imagining something like the following:
1. Add a configuration setting to Panels panes that lets you specify which break point they appear at.
2. If they are not set to appear everywhere, a small chunk of AJAX is used to load the widget (perhaps the entire panel region?), if the break-point matches (or does nothing if the break-point doesn't match). 
3. When the window resizes past a break-point, the AJAX is called again to rerender the panes as needed.
4. To support our media-query approach, we're going to also be adding some custom Javascript code that allows for easier handling of having different JS functions called depending on break-point and easier creation of transition functions that are invoked when changing break-points between loads.

**Comment by sylus** [comment]
Will need time to go through this but definitely an important topic to discuss.

This is one feature being worked on for a mobile visibility button just so you are aware: http://drupal.org/node/1762864 ^_^

**Comment by ottawadeveloper** [comment]
That's very cool. It's definitely important to get that in there.

One of the problems with using the IPE in conjunction with multi-lingual interfaces and responsive designs that might hide mobile-only pieces on desktop sites is that you need to have the pane visible (I think) in order to be able to edit it. Which means you need to change languages to edit English/French (something we've been trying to avoid but maybe it works better for you guys?) and you need to switch to a tablet or something to edit the mobile version with. Hopefully this can address that last part :D.

I did some really cool work today on this (just like 30 minutes for a rough first prototype): http://ottawadeveloper.com/reslib/reslib-test.html

If you look at the source of the page, you can see that the button is only tied to one function - what behaviour is attached to that function changes depending on your screen resolution. This was looking at addressing my fourth point and could be really useful for you guys, if WET-BOEW in general needs widgets to behave differently at different breakpoints. It means you can take out the breakpoint specific code and simply write different methods, then attach them transparently to a single function call. I was also playing around with a cleaner way of doing triggers, because other developers are looking at doing transitions between mobile states (instead of instant snaps). Many possibilities I feel.

Hopefully I'll get more work done on it soon and a chance to play with adding settings to panels to leverage this and some AJAX code.

**Comment by sylus** [comment]
Cleaning up some old issues. :)
