### ISSUE TITLE
WET Lightbox integration

### ISSUE THREAD

**Issue by bmiller72ca** [wet-boew/wet-boew-drupal#505]
The WET documentation indicates it uses the ColorBox approach for which there is a Drupal Module to be used for implementing.

http://drupal.org/project/colorbox

Has anyone done any work with this module yet? We will be doing some testing in this area here at the university, hopefully will have some feedback.

**Comment by sylus** [comment]
Hey @bmiller72ca ^_^

We just directly use the ColorBox implementation from WET by using a custom formatter to append the right markup that WET expects for the lightbox to appear.

As this works haven't considered implementing the Colorbox module? Was their additional functionality that is needed?

**Comment by bmiller72ca** [comment]
Ok I think I understand the concept behind the formatter append, and I can see how we do not want to layer multiple implementations. 

Is there any documentation on the custom formatter, or can you provide some to point us in the right direction.

**Comment by sylus** [comment]
If you go to the following link you can see custom formatters that other people made. Also a screencast into how they are built :)

http://customformatters.com/

This is actually one of my fav modules :)

**Comment by mgifford** [comment]
Just adding onto this, https://drupal.org/project/custom_formatters isn't part of the Drupal WET & there still isn't any documentation on how to use WET's 

Adding some issues here about Drupal WET integration:
https://github.com/wet-boew/wet-boew-drupal/issues/284
https://github.com/wet-boew/wet-boew-drupal/issues/552

And some other links about Colorbox vs Lightbox:
https://github.com/wet-boew/wet-boew/issues/1856

And re-opening this as there's got to be someplace to start documenting this.

**Comment by sylus** [comment]
Closing old issue. If there are specific problems please file a new one with an explicit problem being stated.

**Comment by mgifford** [comment]
I'd prefer if it stayed open until there was a link going to the documentation for this issue. The specific problem is that there still is nowhere near enough documentation posted.
