### ISSUE TITLE
Install WxT Drupal on a Shared Hosting environment

### ISSUE THREAD

**Issue by duboisp** [wet-boew/wet-boew-drupal#508]
Hi,

Did you have or planned to have documentation on how the WxT Drupal can be installed on a shared hosting environment ?

Thanks

:-)

**Comment by ApplebyT** [comment]
I am also interested in how to accomplish this. As a volunteer I'm redoing a website for a local non-profit and it needs to be bilingual, and is hosted on a shared hosting environment. I'd like to use the base WxT Drupal and features so that I don't have to reinvent the wheel.

**Comment by sylus** [comment]
Cleaning up some old issues. :) This distro can definitely run on shared hosting but personally won't have the time to write documentation on it and I think the specs on the shared hosting would still have to be rather high at least 512MB for memory_limit.
