### ISSUE TITLE
Stop using default template for maintenance page

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#511]
The maintenance page needs some work as right now we are using a default one.

**Comment by ssari** [comment]
I'm getting strange messages after I put the server (wetkit rc1) in maintenance mode.
@sylus 
Is this issue related?
Is there any solution yet?

In the server I have Acquia, I wasn't enable to turn off the maintenance mode.


< id="main-content">

**Comment by sylus** [comment]
This has been fixed with Omega :)
