### ISSUE TITLE
Notification: Addition of Nodequeue Module

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#512]
I have seen this module used to great effect by @joel-osc at the City of Ottawa and think there a more then a few use cases for the module to be included with some cool default implementations.

Just making an issue so if people have valid points against the addition this can be taken into account.

@joel-osc, @mgifford @thriuin @sinkinsona @StephenOTT

**Comment by thriuin** [comment]
No problem.
