### ISSUE TITLE
Notification: Addition of Field Collection Module

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#513]
This module is too useful to leave out and has been used to great effect particularly with fields being dependent on other fields.

**Comment by MikeDucharme** [comment]
Great news. Translation support for field collections has been spotty though. Has the latest version been tested for i18n?

**Comment by sylus** [comment]
It is being used in the wild with the upcoming City of Ottawa website. @joel-osc can you comment on problems with i18n before the addition of this module?

**Comment by joel-osc** [comment]
Patch is available for translation - http://drupal.org/node/1316162, tested cleanly for use.

**Comment by MikeDucharme** [comment]
and note that the latest dev of Entity API must be installed (as of Oct 31)

**Comment by nadinecz** [comment]
@sylus Can Field Collection Table (http://drupal.org/project/field_collection_table) be considered/added as well?    This is probably not the right way to go about requesting that :)
