### ISSUE TITLE
Organic Groups error

### ISSUE THREAD

**Issue by MaddyDaigle** [wet-boew/wet-boew-drupal#514]
Hello,

Just wanted to let everyone know that I'm getting an error when I install the OG module on WET Drupal. When you try and create group content the following error occures: 

<pre>Fatal error: Unsupported operand types in C:\xampp\htdocs\drupal\modules\field\modules\options\options.module on line 99</pre>

Has anyone run into this issue?  If yes, is there a solution out there?

**Comment by sylus** [comment]
Hmm well we don't include OG as part of WetKit Drupal but have successfully installed it before. I can take a look in a few days for other people who are going to try this.

**Comment by MaddyDaigle** [comment]
That would be great! Thanks. :)

**Comment by MaddyDaigle** [comment]
We actually solved the issue!  Organic groups messes up when both og and i18n_fields are installed.  So the following patch can be applied to i18n_fields to fix the issue:

http://drupal.org/node/1788748

**Comment by sylus** [comment]
I think the patch is still in flux so won't add it yet, but people can easily find this issue should they have the same problem.
