### ISSUE TITLE
Open Atrium going Panopoly!

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#515]
Thought I would share this awesome news with people here.

Open Atrium the go to Intranet in a box is being ported to Drupal 7 and using Panopoly as its base.

Panopoly will no doubt look forward to a lot of improvements by this amazing team being assembled to built on top of it.

http://www.agileapproach.com/blog-entry/moving-forward-open-atrium-20

**Comment by sylus** [comment]
@sinkinsona @thriuin @StephenOTT @uottawa-wcms

**Comment by StephenOTT** [comment]
:+1:

**Comment by openplus** [comment]
I got plans for this!
FYI: don't bother with RedHen. at least not yet.
