### ISSUE TITLE
Theme developer module

### ISSUE THREAD

**Issue by mxlav** [wet-boew/wet-boew-drupal#518]
If I install the module on a basic Drupal site all is working normal, when I install the module on a WET-BOEW-Drupal site, the API works, it displays the template info, calls etc, but the variable array is  always NULL at the bottom of the API.

Not sure what WET module is conflicting with the Theme developer to loose the vars array? Curious to see if anybody else has this issue?

**Comment by sylus** [comment]
Hmm I have used devel_themer in the past with no problems, there could have been a regression, when I get time can take a look at this.

If you have any more information to provide please post here as will speed up a solution ^_^

**Comment by mxlav** [comment]
The problems seems to be intermittent..sometime i see the values but most of the times they are NULL.

**Comment by sylus** [comment]
I can't seem to replicate this problem anymore on latest dev builds so looks fixed. @mxlav can you confirm?

**Comment by mxlav** [comment]
I've been having issues with this module and tend to leave it off. I keep getting out of memory errors.

**Comment by sylus** [comment]
Closing this issue as is mostly related to devel themer.
