### ISSUE TITLE
Make sure all external links have rel="external"

### ISSUE THREAD

**Issue by pjackson28** [wet-boew/wet-boew-drupal#520]
There were a lot of external links in WET core that did not have rel="external" so make rel="external" is added to each of your external links in your variant. This is part of the HTML5 spec and required by the Standard on Web Interoperability.

**Comment by uottawa-wcms** [comment]
Would it be useful to override the theme_link template to automatically append rel="external" to all links that are not Drupal-bound links? Would handle all the cases automatically that are not in content (and perhaps IMCE can be taught to add them automatically or a formatter put in place for it?)

**Comment by sylus** [comment]
Yeah we could use theme_link template but I worry about the extra computational costs of it detecting for every link in the drupal system whether it is is external or not.

**Comment by uottawa-wcms** [comment]
It seems like it would be a relatively small cost, like

if (substr($link, 0, 7) == 'http://' || substr($link, 0, 8) == 'https://')

Plus, most people should have heavy front-end caching in place anyways, which means those links will be generated infrequently.

**Comment by uottawa-wcms** [comment]
Or url_is_external, but it has preg_match, so maybe it is slow.

**Comment by uottawa-wcms** [comment]
In case anyone is wondering, url_is_external benchmarks at about 8.46ms per execution on my non-server system under XAMPP.

**Comment by uottawa-wcms** [comment]
8.46ms for external links or 0.76ms for Drupal links
