### ISSUE TITLE
Entity vs Content Translation

### ISSUE THREAD

**Issue by uottawa-wcms** [wet-boew/wet-boew-drupal#521]
@sylus do you guys want to weigh in on this? We're in the middle of rebuilding the dual-language editor to be more robust and handle all entity-based forms (which has required some Robert magic but that's okay). Wondering if it's worth adding support in this new module for content translation or if we should just support entity translation (leveraging the title module to support multi-lingual titles, a field-based version of path auto and a custom module to update the menu settings to be multilingual).

**Comment by joel-osc** [comment]
After using Entity Translation on a recent project I absolutely believe that this is the path forward. I think it would be best to not worry about content translation and focus on entity translation. At a field level you could offer tabs at the top of each translatable field for each language available which opens up a modal window for content translation. A translator could move the modal window to a second monitor and have two full screen version going at the same time - which is a dream come true for people in this role. This solution would also scale well in other countries which have the need to support more than two languages.

**Comment by uottawa-wcms** [comment]
@joel-osc I really like that idea, as an alternative for literal side-by-side editing. Right now we're focusing on a two-column, one-form dual editing experience (so every field can be seen side-by-side with it's counterpart without having to scroll two windows), but I think a modal experience is better for when you are not using this side-by-side experience (as opposed to the current experience of the Translate tab or a drop-down to change the current language you are editing.

**Comment by sylus** [comment]
Cleaning up some old issues. :) Going ET all the way!
