### ISSUE TITLE
metatag vs metatags_quick

### ISSUE THREAD

**Issue by uottawa-wcms** [wet-boew/wet-boew-drupal#528]
I'm wondering if there was a reason metatag was chosen over metatags_quick. metatags_quick is fully based on Field API (and thus is fully compatible with entity translation and a dual-language approach to it). Metatag appears to be hacking the field API (their "field" is a blank, non-language specific placeholder that triggers form_alter to write a field into the "appropriate" place later) and is going to be difficult to work into a dual-language approach (likely I'll have to recode their form alter). Metatag provides a lot more functionality out of the box than metatags_quick but it seems like the cost is pretty high, and that they're going to run into issues with Drupal 8 without a rewrite.

Anyone have any thoughts?

PS: Is anyone else as eager for translatable entity properties as I am?

**Comment by sylus** [comment]
Hmm might have to disagree on this one (could be persuaded), I have tried both and have found metatag to be far more extensible and less problems in general. Also the fact Acquia is behind this module makes it a safer bet for government.

Could be convinced to switch sometime down the line but can't see it in the near future.

Could you file an issue with your concerns to the metatag module? They might have more information on rationale for architecture design then I. ^_^

Would be interested in their feedback.

In an unrelated matter just today added a rough migration support for metatags: http://drupal.org/node/1284756

Anyone offer opinions? @mgifford @joel-osc

**Comment by mgifford** [comment]
metatags_quick was only ever supposed to be a bridge.  It's grown into more than that but metatags is just a really powerful tool.  Certainly if you want things like Dublin Core & integrated taxonomy support it's important.

Also, always useful to look at critical mass:
http://drupal.org/project/usage/metatag
http://drupal.org/project/usage/metatags_quick

**Comment by uottawa-wcms** [comment]
Cool - we ended up hacking metatag in anyways since others pointed out that even if we aren't using DC or anything except the title override and the description (and maybe some of the opengraph stuff eventually), GoC certainly is and metatags_quick didn't look like a useful way of supporting DC.

@sylus their front page says they didn't use field/entities because they want the "flexibility" that not using it provides, so it looks like they've already considered it. I would hope they reconsider this come Drupal 8, since it looks like everyone else will be moving away from custom altering the node edit form into properties.
