### ISSUE TITLE
AJAX HTTP error on "Install profile" step with MS SQL Server.

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew-drupal#53]
I was on my way to give you more info about issue #37 and started from scratch, using drush make to get the latest version after pull request #52, but I ran into a new error near the end of the "Install profile" step.  Here it is (I've just changed the name of the site to something more generic and added CRLFs for readability):

<code><pre>
An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. 
Path: http://dr.maint.internal.net/install.php?profile=webexp&locale=en&id=1&op=do StatusText: OK ResponseText: Home | Drupal 
@import url("http://dr.maint.internal.net/modules/system/system.messages.css?0"); 
@import url("http://dr.maint.internal.net/modules/system/system.base.css?0"); 
@import url("http://dr.maint.internal.net/modules/system/system.theme.css?0"); 
@import url("http://dr.maint.internal.net/modules/system/system.menus.css?0"); 
@import url("http://dr.maint.internal.net/profiles/webexp/modules/contrib/date/date_api/date.css?0"); 
@import url("http://dr.maint.internal.net/profiles/webexp/modules/contrib/date/date_popup/themes/datepicker.1.7.css?0"); 
@import url("http://dr.maint.internal.net/modules/field/theme/field.css?0"); 
@import url("http://dr.maint.internal.net/modules/node/node.css?0"); 
@import url("http://dr.maint.internal.net/modules/search/search.css?0"); 
@import url("http://dr.maint.internal.net/modules/user/user.css?0"); 
@import url("http://dr.maint.internal.net/profiles/webexp/modules/contrib/views/css/views.css?0"); 
@import url("http://dr.maint.internal.net/profiles/webexp/modules/contrib/caption_filter/caption-filter.css?0"); 
@import url("http://dr.maint.internal.net/modules/system/system.admin.css?0"); 
@import url("http://dr.maint.internal.net/modules/system/system.maintenance.css?0"); 
@import url("http://dr.maint.internal.net/profiles/webexp/modules/contrib/ctools/css/ctools.css?0"); 
@import url("http://dr.maint.internal.net/profiles/webexp/modules/contrib/panels/css/panels.css?0"); 
@import url("http://dr.maint.internal.net/themes/seven/reset.css?0"); 
@import url("http://dr.maint.internal.net/themes/seven/style.css?0"); 
Home Installation tasks
Choose profile(done)
Choose language(done)Verify requirements(done)
Set up database(done)Install profile(active)
Configure siteImport French LanguageEnable apps supportInstall apps for WetKit (local)
Choose a themeFinished! 
Warning message The Date API requires that you set up the site timezone and first day of week settings and the date format settings to function correctly. 
The image resize filter has been installed. Before this does anything, the image resize filter needs to be added to one or more text formats. Visit the text format administration to set up this filter. 
Status message A Display Suite code text format has been created. 
Refreshed 2 strings for the enabled modules. 
Refreshed 8 strings for the enabled modules. 
To use menu blocks, find the "Add menu block" link on the administer blocks page. 
Password policy module successfully installed. Please review the available configuration settings. 
SQLSTATE[42000]: [Microsoft][SQL Server Native Client 10.0][SQL Server]Incorrect syntax near the keyword 'current'. 
</pre></code>

I've done this twice now with the same error.  Installing on MS SQL Server, obviously.

**Comment by sylus** [comment]
Are you able to try the install using drush si? and append the --debug to it?

**Comment by RobJohnston** [comment]
If I was installing on MySQL I would be able to, but I don't see a way to get it on MS SQL due to the "--db-url=mysql://<username>:<password>@<domain>:<port>/<database>" part of the command.

**Comment by RobJohnston** [comment]
Seems like "current" is a reserved work in MS SQL.  See http://drupal.org/node/1260112.

**Comment by sylus** [comment]
Hey @robjohnston you indeed found the error give me about 20 mins and I will add the patch to the build

**Comment by sylus** [comment]
Patch Committed give it a go now! :)

**Comment by RobJohnston** [comment]
Yes, got past the error. The patch worked.  Thanks.
