### ISSUE TITLE
wysiwyg for priorities

### ISSUE THREAD

**Issue by jomuji** [wet-boew/wet-boew-drupal#534]
Hi, i'm trying to change the priority boxes images, threw  the wysiwig, on blocks. it seems to have a problem with the popup for inserting images.

anybody knows something about this ? should i update the wysiwig? if yes how ?

regards.

**Comment by sylus** [comment]
Yeah this was a bug that was recently updated in wetkit_wetboew as we removing the the jquery ui theme. This jquery ui theme causes some issues with JQMobile when logged into Drupal.

However for now the logic has been replaced so the theme is included when logged in: https://github.com/wet-boew/wet-boew-drupal/commit/72f2a4a83c7aacc0e4c173efc8fdffba91168214#L1L169

**Comment by jomuji** [comment]
great then, thanks a lot
