### ISSUE TITLE
Build script/profile ?

### ISSUE THREAD

**Issue by joejoseph00** [wet-boew/wet-boew-drupal#535]
@sylus, any idea what happened to the buildout procedure?  it's no longer working.

**git clone https://github.com/wet-boew/wet-boew-drupal.git profiles/wetkit;**
Initialized empty Git repository in /home/USERNAME/public_html/SITENAME/profiles/wetkit/.git/
**fatal:** https://github.com/wet-boew/wet-boew-drupal.git/info/refs download error - **The requested URL returned error: 403**

**Comment by sylus** [comment]
GitHub could have been done when you attempted? Works fine for me
