### ISSUE TITLE
Missing "Date modified:" field for panelized pages

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew-drupal#541]
Related to Issue #196, the "Date Modified:" field does show on a non-panelized page but not on a panelized page (or landing page).  This is an element mandated by the Standards on Web Usability.

**Comment by RobJohnston** [comment]
Actually, the other date format in #196 is incorrect.  It shows a form like "Monday, 19/11/2012" and according to section 1.6 of http://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=24227&section=text#secE.1, it should be "2012-11-19".  Also, it should be the date the node was changed, not created.  Something like this:
<code>
          &lt;dl id="gcwu-date-mod" role="contentinfo"&gt;
            &lt;dt>&lt;?php print t('Date modified:'); ?>&lt;/dt&gt;
            &lt;dd>&lt;span>&lt;time&gt;&lt;?php print format_date($node->changed, 'custom', 'Y-m-d'); ?>&lt;/time>&lt;/span&gt;&lt;/dd&gt;
          &lt;/dl&gt;
</code>
Not positive where to put it, but I'm thinking under line 205 of page--panels.tpl.php.

**Comment by sylus** [comment]
Hey @RobJohnston I am able to fix the panelized page for nodes as am able to get the date variable. However for a panelized page composed of multiple panes not sure how I would go about getting the date.

Would the date be when the whole panel was saved or an individual pane?

**Comment by RobJohnston** [comment]
Hmmm, don't know.  I was looking at the default content provided on installation so I hadn't thought of the panel of panes.  Anybody else have an opinion?  

I didn't know that the dates for saving the panels and panes would be available in the DB.  The date of the latest modification of any of the panes might be another option, if possible.

I think that the date the content was changed is what's important and the date of any formatting or layout changes matters not at all.

**Comment by sylus** [comment]
Think latest pull request addresses the crux of this issue. Pure panels layout will require more consideration. ^_^

Just waiting for Travis to say good to merge.

**Comment by sylus** [comment]
Fixed!
