### ISSUE TITLE
Displaying block in panelized content

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#542]
This post describes an issue I had and the solution I found in case someone needs it.

I was able to add a block (in particular QuickTab block) using panalizer option in a panelized content type (for example, basic page), but I couldn’t do it in a specific page/content.

Because all Default settings are checked in “Admin>Structure>Content Types>Basic Page>Panelizer>Allowed content”, I thought, wrongly, it would allow blocks in each content.

The block appeared in “Home>My Content Type>Content>Add Content – Miscellaneous” when in “Admin>Structure>Panels>Settings>Panel Pages>” I selected “New Block” and/or select the block in “Allowed Block content”.

This is a nice article about the panelizer module - Creating Specialized Layouts with Panelizer, http://drupalwatchdog.com/2/1/panelizer-layouts

**Comment by sylus** [comment]
Thanks for the useful post, this will likely need to be added to the documentation, tagging appropriately.
