### ISSUE TITLE
Exporting, importing Wetkit default panel display 

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#543]
I would like to create a panel display from one of the “Wetkit default panel displays” preserving the styling classes and IDs.

It seems that exporting and importing layout is the best option. Is there any option to export specific Wetkit default layout?

**Comment by sylus** [comment]
Yup you should be using features quite extensively to tailor your site to the unique requirements you have.

Admin path is at: /admin/structure/features

**Comment by ssari** [comment]
I have implemented a workaround solution based this video: 
Creating a Custom Panels Layout in Drupal 7 - Metal Toad Media (http://www.youtube.com/watch?v=gmX2jnH9Kdg)

I modified wetkit_adaptivetheme.info file adding my layout under "Responsive Panels - Standard layout", and I copied one of the custom panels (xx\wetkit\profiles\wetkit\themes\wetkit_adaptivetheme\custom_panels) and modified the respectives files (.css and .php).

Not sure, if I'll lose this configuration when the wetkit will be updated !!! It would be better to have custom_panels folder under /sites/my_site/files/

Hopefully, we'll progress with the Panopoly configuration and find other solution.

**Comment by sylus** [comment]
Cleaning up some old issues. :)
