### ISSUE TITLE
Bad value wb-cont page-title for attribute id on element h1

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew-drupal#546]
Non-panelized pages have an h1 ID attribute with a space in its name, which validator.w3.org doesn't like:

<blockquote>Bad value wb-cont page-title for attribute id on element h1: An ID must not contain whitespace.</blockquote>

The original looks like this:
<code>
 &lt;h1 id="wb-cont page-title"&gt;
</code>

I believe this is only contained in page--internet.tpl.php and page--intranet.tpl.php.  The panelized page only has this:
<code>
  &lt;h1 id="wb-cont"&gt;
</code>

Don't know what the best change is... only "wb-cont" or "web-cont-page-title" or something else.

**Comment by sylus** [comment]
Good catch addressing by removing page-title ^_^

**Comment by sylus** [comment]
Fixed!
