### ISSUE TITLE
Format settings in Custom: WetKit Lightbox

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#552]
Would it possible to select my own image style instead of the existing ones: thumbnail, medium, large, panopoly_image_quarter, panopoly_image_half, panopoly_image_full ?

**Comment by sylus** [comment]
You could manually add your own image style to wetkit_wetboew.custom_formatters.inc but future updates would make this modification disappear. Might be an initial solution for now.

I will look into a way to make this logic more abstract and extendable.
