### ISSUE TITLE
Enabling Alt and Title fields when using Media file selector

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#553]
Would it be possible to add Alt and Title fields when using the widget type: Media file selector as it is with the Image widget ?

**Comment by sylus** [comment]
There is a patch that was just rbtc will try to include it today

**Comment by sylus** [comment]
Part 1 has been added, still have to make file_entity work with the media upload widget.

**Comment by ssari** [comment]
Thanks @sylus 
Do you still planing to publish the Wetkit beta version this week, as you mentioned in the last WG meeting?

**Comment by sylus** [comment]
Will do my best!
