### ISSUE TITLE
Permissions for WetKit menu

### ISSUE THREAD

**Issue by uottawa-wcms** [wet-boew/wet-boew-drupal#560]
@sylus For the WetKit menu, since it's all about Panels layouts and such, it seems like it would make more sense to tie it into something Panels related, it's own permission or maybe "administer site configuration" rather than "access administration pages" (which is necessary to see any of the admin pages). Right now, we can't remove this menu for any user who we also want to be able to see other top-level items (like Content) and there are sure to be cases out there where people want to have users who can add content and such from the admin toolbar without also showing them this menu.

**Comment by sylus** [comment]
Makes sense will try to get around to this soon ^_^

**Comment by sylus** [comment]
Cleaning up some old issues. :) (permissions have been added)
