### ISSUE TITLE
Install Profile with Panopoly

### ISSUE THREAD

**Issue by uottawa-wcms** [wet-boew/wet-boew-drupal#566]
Hi @sylus,

I've been working on debugging this, but I wanted to see if you had any insights.

I'm trying to create our own install profile, leveraging the WetKit-Drupal modules but with our own tweaks. It's still in it's infancy (I'm just trying to get all the right modules enabled on install) but I'm running into a problem.

When installing Panopoly Core (and WetKit Pages and possibly other Panopoly/WetKit modules), I get a PDO exception about column "module" cannot be null.

I've tracked this issue down to the hook_modules_enabled on those modules, specifically the calls to grant permissions. For some reason, the panelizer taxonomy_term breadcrumbs permissions are not present when these hooks are called (possibly other ones). I can't locate these objects (the terms) in the database either after the error, so I suspect they are simply not being imported on install. 

I am using the versions of panopoly_\* and wetkit_\* that come with the latest version of wetkit (as of Nov 23, 2012 at least), though I've copied them into my own repo so I can work with a consistent (and slightly tweaked for dependencies and make files) version of them. I've also replaced all the modules with latest stable + your patches, since we needed to do this in a number of places anyways - we needed latest dev of entity and diff to support Entity CRUD UI and latest stable (unpatched) of entity_translation to support Bean.

Any ideas why this might be failing? If you want to take a look in more detail, you can look at http://github.com/uottawa-wcms/omega - this is the Vagrant/Puppet/Drush Make release we've been working on (the drush make file is messy, my apologies - I've been working on just making it work, not making it pretty :D). The vagrant build is also in error at the moment, so you'll have to set it up through ADD or something for the moment.

You can install it simply by:

```
{make a directory for your install and change into it}
git clone https://github.com/uottawa-wcms/omega.git ./
cd webroot
drush make -y ./uottawa-build-static.make
```

I've been testing browser-based installs, not sure if the drush si works better or not (most of our users will be using browser-based installs).

**Comment by sylus** [comment]
I have encountered that error before it is because Panopoly is using defaultconfig and was a problem with order of install. 

This has been quasi fixed at: http://drupal.org/node/1837312

For Panopoly you should really be just directly pulling them straight from the source at a specified SHA and do patches for any customizations you need. For the WetKIt modules I have no problem updating to latest versions if they are stable and don't cause regressions. Can even have another branch for this so you don't have to maintain your own set of modules. Perhaps at some point we should talk about abstracting some of the WET modules even further so we can have a shared base. For instance maybe WetKit i18n should have a different name that we can both pull from. I don't know just throwing ideas out there :)

It is my hope that over the next few weeks or so that WetKit aligns closer to you guys. :) We will be adding Draggable Views, Nodequeue and Field Collection as well.

I love that you are using Vagrant and have a setup going. A shame though you didn't choose Chef over Puppet though! Ruby is DevOps!

**Comment by uottawa-wcms** [comment]
Awesome. I was excited when @joel-osc showed me Nodequeue, though we haven't done anything with it yet - my work has been heavily focused on the new entity-based DLE (which I'm very excited for). I just checked with Bryan, if you wanted to come by, say, Thursday afternoon and we can talk about the distribution (and I can show you some of the latest work we've been doing and talk about the direction we're going in), that would be awesome. 

I'm trying a fresh install with the latest RC3 versions of Panopoly and I'll see if I can figure out how to take theirs automatically - the problem is, I don't want their profile (I just want the modules so I can load them into my profile) and I don't want their make files to run, since they override my own versions (and this causes other things to break oddly).

**Comment by uottawa-wcms** [comment]
Nope, fails with latest RC3 from Panopoly as well. I checked the code and it does have the fix discussed in 1837312 (which is #5 - adding the permissions to hook_modules_enabled, which is where the code is failing) even in my previous builds, so it appears to be unrelated to 1837312. 

I checked the database immediately after install and, as far as I can see, there is a vocabulary installed called panopoly_categories so that's fine.

It's only the "breadcrumbs" that's failing. When I look in PanelizerEntityDefault.class.php (from Panelizer), I see permission definitions for overview, content, context, layout and settings (and defaults and choice), but I don't see one for breadcrumbs...

And it looks like that might be the issue. I'm not applying any of the patches to Panelizer that Panopoly wants, including http://drupal.org/files/1655296-panelizer-allow-breadcrumb-tabs-40.patch which looks like it adds the breadcrumbs permission that I'm missing.

Let me try rolling that Panelizer update into my distro and see if that fixes it....

**Comment by sylus** [comment]
Yeah you don't have to take their profile (WetKit doesn't) just the modules which we do in our drupal.org-core.make. As for there make files you can just patch them to refer to the versions you would want. For instance WetKit can't use simplified menu admin which at some point was in a make so we just patched it to remove.

**Comment by uottawa-wcms** [comment]
Good to know - when I have this working, I think I'll look at creating patches to only take what I need. I assume that's as simple as cloning their project and git rm the files I don't want, then create a diff that I can store with my make and apply?

**Comment by sylus** [comment]
Exactly :)

**Comment by sylus** [comment]
Sadly can't meet this week but will try for next week. I really want to make sure we align with you guys as close as possible because your building some great stuff :) Ultimately saves work on my end lol! 

Just need to solve this Bean problem!

**Comment by uottawa-wcms** [comment]
Absolutely. Let me know - my schedule is getting full of Xmas things here. I am busy the afternoon of the 4th and maybe the 6th (I am unsure if Sang will cancel his meeting or not on the 6th, but if that works better for you, I can probably talk him into it).
