### ISSUE TITLE
TinyMCE to be updated

### ISSUE THREAD

**Issue by joejoseph00** [wet-boew/wet-boew-drupal#567]
CTA is going to be providing some updates to TinyMCE

The work will be done by Mike B.  I'll try to gather the specs and post them in as much detail as possible.  We'll fork the wetboew distro version of TinyMCE and will do pull requests so the changes can be merged.

Timeframe for this is probably from now through December.

I will provide the updated spec documentation for TinyMCE outlining what the features do and what the new changes are.

**Comment by joejoseph00** [comment]
We'll handle upgrading the core package to 3.5.8 if it hasn't already been done.  We'll do regression testing on this as well.

**Comment by StephenOTT** [comment]
Are these major upgrades?

**Comment by joejoseph00** [comment]
Hi Stephen, thanks for the question.  I'd say some minor upgrades with some feature enhancements.  Here's the latest note from the developer (Mike B)

> I’ve made a few other improvements since then (August), plus the core package is now up to 3.5.8 and has a few >compliance improvements (e.g. TFOOT was being placed in the wrong location).

I'll try to get some additional details about what our group is cooking.  If the City of Ottawa has any feedback or feature requests feel free to post them here so that I can pass the info off to the developer.

**Comment by joejoseph00** [comment]
just found out that one of the key people in this project is in the hospital having emergency surgery so that's why I don't have more details about it.

**Comment by sylus** [comment]
Thanks for the information @joejoseph00 I will likely be updating to 3.5.8 from 3.5.7 shortly to assist.

**Comment by sylus** [comment]
Hey @joejoseph00 TinyMCE has been updated to 3.5.8 as well as lots of other improvements please see #580

**Comment by joejoseph00** [comment]
Super!  We'll test it and work on the updated version asap.  As I get details about the planned updates I'll post them here.

> > > William H notifications@github.com 2012-12-03 12:00 >>>

Hey @joejoseph00 TinyMCE has been updated to 3.5.8 as well as lots of other improvements please see #580

**Comment by sylus** [comment]
Going to close this for now but please reopen when works resumes :)

**Comment by joejoseph00** [comment]
Hi @sylus , what was the last version of wetboew drupal to include TinyMCE?  I'd like to grab it?  I heard it's no longer included with the distro.  We're still paying Mike to work on it and we just got a request from another agency looking for the html cleanup module.  I also have to fix our Intranet version to support the updated branding and fixed bilingual support that you kindly repaired (with the translations I provided).  I thought Drupal could support more than one wysiwyg editor at the time so I was a bit surprised to hear that it was removed , was there a compatibility issue between CK and Tiny preventing them both from being included ?  I'm not against CK, I've heard great things however for some reason our users here seem to absolutely love the html cleanup modules that Mike created and a few other key features specific to their wcag requirements and accessibility requirements.

**Comment by sylus** [comment]
Hey @joejoseph00 not sure where you heard it was removed? The plan is to ultimately move to ckeditor but only when it has feature parity with TinyMCE. All versions of WET Drupal still use TinyMCE

Ultimately during the install we may ask which editor a user prefers. I don't see it being removed anytime soon.

**Comment by joejoseph00** [comment]
ah ok, sorry, please delete thread then.  my bad.

> > > William H notifications@github.com 2013-02-25 09:28 >>>

Hey @joejoseph00 not sure where you heard it was removed? The plan is to ultimately move to ckeditor but only when it has feature parity with TinyMCE. All versions of WET Drupal still use TinyMCE
