### ISSUE TITLE
Missing Workbench Moderation module

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#569]
Distro used to have Workbench and Rules modules to perform content moderation. The version installed in mid of November doesn't have Workbench/Workbench Moderation modules.

Is there any other option to replace them ? 

Although, it isn't a priority now, this feature is great for us. 

Thanks in advance.

**Comment by sylus** [comment]
We removed this as haven't settled on an official workflow solution (though looks like Workbench will be it). However until a decision was made didn't want to dictate a workflow.

You can of course add the module yourself for the time being ^_^
