### ISSUE TITLE
Configuring Bilingual URLs

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#570]
When creating a basic page the URL <magically generated>, the ENG and FRA permalink are respectivelly http://host-name/eng/content/node-title and http://host-name/fra/content/node-title. 
However, the last should write "contenu" instead "content.

I configured "Patterns" in URL Aliases (/admin/config/search/path/patterns) to obtain the French URL:
http://host-name/fra/contenu/node-title. Likewise to other content types. It worked well.

Now, I wonder if  there is any other option to do it. Perhaps, the French URL could be set, for basic page, in one of the related language modules.

**Comment by sylus** [comment]
Ah I can fix this give me a day or so :)

**Comment by sylus** [comment]
This has been fixed by use of a custom token.
