### ISSUE TITLE
Updating a node that is already published

### ISSUE THREAD

**Issue by wcms-ottawa** [wet-boew/wet-boew-drupal#572]
Hello,

I am wondering if there has been any discussion around allowing users to work on a node that is already published without effecting the published node. Meaning a user could be revising a published node and save it in draft state while users make the necessary changes and preview it etc. 

The way my current build works is something like: create draft -> publish -> unpublish -> delete, etc. What if we wanted: create draft -> publish -> edit -> preview->edit->publish changes, etc. Perhaps I am missing something and this is already available.

I expect we could go ahead and add 1 or more existing modules such as workflow but I was curious to see if others had this requirement and potentially adding it if it is not already in the distro or in the works.

Thanks

**Comment by ssari** [comment]
I believe you are refering to moderation what we also want to implement.
Please, check Willian's answer about Workbench moderation.
https://github.com/wet-boew/wet-boew-drupal/issues/569

**Comment by wcms-ottawa** [comment]
Thanks ssari

**Comment by sylus** [comment]
Workbench Moderation is in though will need to update to address #645
