### ISSUE TITLE
Possibly old bug but discovered today

### ISSUE THREAD

**Issue by uottawa-wcms** [wet-boew/wet-boew-drupal#573]
This is from a WetKit clone we did back in August, so it may be already fixed by now.

In modules/custom/wetkit_wetboew/wetkit_wetboew.install you have the function wetkit_defaults_create_password_policy().

In modules/apps/wetkit_web_usability/wetkit_security/wetkit_security.module you have the same function.

Enabling both of these modules (which somehow happened on this site, not sure if it's supposed to happen) and installing a new module causes the .install file to be included as well (really not sure why, but it's happening) and then the obvious conflict and crash (during module installation, post-module being enabled in the system table but before the install hook is called to create the schema).

If not already fixed, it seems like it would be better to either centralize this definition into an include or name these two slightly differently to prevent any clashes from ever occurring.

**Comment by sylus** [comment]
wetkit_web_usability is no longer a module we have so definitely out of date, please look at our master branch :)
