### ISSUE TITLE
Unable to clone markitup

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#576]
I just got this error when installing :

Unable to clone markitup from https://github.com/sylus/markitup-wetkit.git.                  [error]

and other erros in drush:

Command site-install needs a higher bootstrap level to run - you will need invoke drush      [error]

from a more functional Drupal environment to run this command.
The drush command 'si wetkit wetkit_wetboew_selection_form.theme=wetkit_adaptivetheme'       [error]

could not be executed.
A Drupal installation directory could not be found                                           [error]

Any suggestion?

**Comment by Pacoup** [comment]
This is possibly and most likely due to the partial system outages GitHub is currently experiencing. I suggest you try again when the system status is all green.

<a href="https://status.github.com/">GitHub System Status page</a>

**Comment by ssari** [comment]
Thanks. After all it's Friday.
