### ISSUE TITLE
WetKit Web Usability Page

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#582]
In a fresh install a status message appears: 
" Please proceed to the WetKit Web Usability Page to configure additional settings. "
with link to  /admin/config/wetkit_wetboew/settings.  Actuallty is displays only options of the /admin/config/ .

Do we still need this configuration?

Thanks.

**Comment by sylus** [comment]
Yeah this needs to be changed :)

**Comment by sylus** [comment]
Fixed with better messages :)
