### ISSUE TITLE
Could not locate file_entity version 7.x-7.x-2.0-unstable7

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#583]
When installing a new version, I got a warning:
Could not locate file_entity version 7.x-7.x-2.0-unstable7, will try to download latest recommended or supported release. 

Apparenttly, everything is ok.  Is there anything to concern about?

Thanks.

**Comment by sylus** [comment]
It will still resolve to the latest recommended. I will file an issue upstream for this :)

**Comment by Phr34ks0w** [comment]
Hi @sylus , I also get the subject issue. 

 Could not locate file_entity version 7.x-7.x-2.0-unstable7, will try to download latest recommended or        [warning]
supported release.

Thanks

**Comment by sylus** [comment]
Fixed!
