### ISSUE TITLE
WYSIWYG Filter and HTML5 Support

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#584]
Took a bit of work but believe WYSIWYG Filter now fully supports HTML5.

Was hoping could get a review going to see if any elements / attributes missed.

Here is a simple description:

http://www.tinymce.com/wiki.php/Configuration:valid_elements

a) valid_elements: Are the only elements + attributes that are allowed to be pasted in TinyMCE
b) rule_valid_classes: Are the only classes allowed to be entered (we are allowing all classes by using a\* -> z_)
c) rule_valid_ids: Are the only classes allowed to be entered (we are allowing all id's by using a_ -> z*)

So is there any additional elements missed after reviewing: 

https://github.com/sylus/wet-boew-drupal/blob/33a0f5f5c29b7d2ef734388c160ea829258d78d8/modules/custom/wetkit_wysiwyg/wetkit_wysiwyg.features.filter.inc#L38-124

@StephenOTT, @joel-osc, @joejoseph00, @pjackson28, @uottawa-wcms 

I have tested the Filter by directly pasting from WET Documentation (almost have a migration for it ready to push soon too) and everything seems to work and nothing stripped out.

**Comment by sylus** [comment]
Eventually I realize we should limit the classes and ids but for now think being open with them is the best option to minimize confusion.

**Comment by StephenOTT** [comment]
Woot   :+1:

**Comment by uottawa-wcms** [comment]
I think allowing for developers to easily configure the acceptable elements (especially classes and IDs) would be useful, since I know we'll likely be looking at using our own IDs (in line with our own templates). I'm going to pass this list on to the designers here to make sure it meets everything we need but if it's full HTML5 support, it should be fine.

**Comment by mankev** [comment]
Please see my comments posted as an issue on wet-boew/wet-boew. This editor is also being used by some of the shops using TeamSite and other CMSs. There may be an opportunity for collaboration.
