### ISSUE TITLE
Error: Undefined index: fieldable_panels_panes_path

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#597]
I got the following error message when adding panes (tabbed interface, image, video) in a new version installed Dec 3rd.

Error message
Notice: Undefined index: fieldable_panels_panes_path in fieldable_panels_panes_entity_edit_form_submit() (line 953 of D:....\sites\all\modules\contrib\fieldable_panels_panes\fieldable_panels_panes.module).

**Comment by sylus** [comment]
Yeah I am aware of this doesn't cause any functional issues but is being worked on.

**Comment by sylus** [comment]
Fixed!
