### ISSUE TITLE
Contextual Mega Menu

### ISSUE THREAD

**Issue by eimhin** [wet-boew/wet-boew-drupal#612]
I'm working with Organic Groups in WET Drupal and I'd like to configure the mega menu to contextually display group-specific menus instead of the "main-menu" (WET: Mega Menu) which it's currently fixed on. I'd rather not override the menu preprocessing that's currently implemented by the Wetkit Adaptive Theme, but is there somewhere in the theme include files that I should look at to include this functionality?  The new menus should behave in the exact same way as the current mega menu.

Thanks for any advice!

**Comment by sylus** [comment]
Hey @eimhin can you not just take over control of the Mega Menu and add the additional menus you require? Can you elaborate further on what you need? ^_^

**Comment by MaddyDaigle** [comment]
We need to have a series of separate mega menus in different menu blocks that will completely replace the default mega menu based on the OG group node the user is currently on.  So essentially "main-menu" is going to have to change.  We're just curious where we'd replace the main-menu with another menu block based on context if there's support for this,or if we'd have to write custom code to do this.  I was able to kind of get it to work by modifying the wetkit_menu_blocks-1 array to point to a different menu block.. but it wasn't displaying properly.

**Comment by Tikka** [comment]
This is also something we will have to do here.

**Comment by openplus** [comment]
We have similar issues... but with WET-JQM, I think we'll be running into some catch 22 elements.
@sylus I spoke to Laurent about this... and think I might have a few ideas to test... which will be tricky (so talk Thursday when we see each other).

**Comment by sylus** [comment]
This has been completely fixed with the use of WetKit Menu + Mini Panels
