### ISSUE TITLE
Class array bug in wetkit_language.module

### ISSUE THREAD

**Issue by uottawa-wcms** [wet-boew/wet-boew-drupal#613]
In wetkit_language.module, line 120, the 'class' property of $attributes should be an array (eg array('link')) instead of just the text - see http://api.drupal.org/api/drupal/includes%21common.inc/function/l/7. Not sure why it hasn't broken until now, but it's causing an issue for our distro.

**Comment by sylus** [comment]
Thanks will fix this ASAP today

**Comment by sylus** [comment]
Just waiting for Travis. As an aside did you happen to look at Bean @uottawa-wcms you guys must have the same problem with it doubling install time when using drush si.

**Comment by uottawa-wcms** [comment]
Haven't had a chance - I've been working on the Vagrant build. We've been using browser-based installs anyways pretty exclusively anyways, since we're adding a lot of setting options to the install profile.

**Comment by sylus** [comment]
Have u switched to using chef instead of puppet? Librarian is awesome, the vagrant-ariadne github project is a really decent base @patcon

Does not matter so much but we r gonna roll with chef vagrant. It can be a duel! :)

Yay treating this issue like irc

**Comment by uottawa-wcms** [comment]
Just ran a quick test - clean drupal, standard install profile, timed it "as is", then with "bean" only, then with "bean_admin_ui" and "bean_uuid" as well. Vanilla install is 47 seconds, bean install is 56 seconds, all three bean modules is exactly 60 seconds. So it doesn't look like a problem with bean itself, it must be how bean is talking to another module. Can you run drush si --verbose and see which module it's hanging up on? 

I kind of want to switch to Chef, it looks more powerful, but I have a lot of priorities so I don't really have time to update to Chef sadly. Unless you guys have a base LAMP Chef package that we can apply to CentOS? 

Is Chef significantly faster than Puppet? It's taking 20-45 minutes to provision from a clean base box (most of which is package installs). We were looking at rolling our own base box that comes pre-provisioned just so we can avoid that time investment every time it runs. We've also noticed significant slow-downs when working through Vagrant - the web-based installer takes about about 30-45 minutes to complete (it spends 10-15 seconds installing each module and there are 140 modules).

**Comment by sylus** [comment]
Hmm yeah I think it is bean interacting with other modules I only get slow down after bean is already enabled can share the logs.

Chef is comparable but in my opinion more inuitive, particularly because it leverages Ruby DSL and has a fantastic community on GitHub. For your base box have you guys looked into VeeWee? https://github.com/jedi4ever/veewee

As for slowdowns with vagrant have you added alot of the relevant performance options (cpucount, memorysize, shared folders etc) in the VagrantFile?

**Comment by uottawa-wcms** [comment]
I haven't - it's very basic. The main one I looked at was :nfs but it doesn't work on our macs out of the box and it doesn't work on Windows at all. I think most of my problem is that I'm on Windows - the emulation provided by cygwin is notably slower in nearly every major operation (drush make is 2-3 times slower on my system than the macs here).
