### ISSUE TITLE
Drupal Solution Stack to address performance and scallability

### ISSUE THREAD

**Issue by mankev** [wet-boew/wet-boew-drupal#617]
This may be a bit off topic for this project, but I believe it needs to be addressed somewhere. A question about performance, scalability and load balancing was brought up during the presentation on Tuesday in Gatineau, and it is bound to come up again. Providing a pre-baked solution that can be easily deployed anywhere in the GOC will go a long way in helping Drupal as a CMS gain acceptance in the GOC. We are currently evaluating Drupal for our Proactive Disclosure requirements, but are hesitant because our costs to deploy even a simple stack are very high. A pre-baked certified solution stack would help defer a large part of these costs.

@stylus I spoke to you after the meeting about a video I saw. Here is the link: http://sf2010.drupal.org/conference/sessions/performance-testing-economist-online-using-grinder.html

When I speak of a Solution Stack I mean tested hardware, and software solution(s), and rubber stamp (TRA, TDD, documentation etc) to roll out anywhere in the GOC. This would be a challenging effort to say the least, especially the rubber stamp.

**Comment by sylus** [comment]
We have an approved stack (TRA). Ideally i'd like to replicate this stack using Chef + Vagrant for ease of use amongst developers and enhanced portability. 

I'll bring this up at work tomorrow and see what we can do.

**Comment by mankev** [comment]
Great, this is a good starting point, however I doubt if I approached my infrastructure provider they would happily install it. I will need more information because even the simplest of things can become a huge undertaking.  An image would be a great way to go, but this requires a standard platform across GOC. However, since this solution resides in the DMZ it could be hosted by anywhere in the GOC, eliminating the requirement for a standard platform across the GOC, and may be another option. 

I would like to compare environments, but would rather do this offline.

**Comment by sylus** [comment]
Cleaning up some old issues. :)
