### ISSUE TITLE
Error: uncaught exception thrown while handling exception

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#620]
After the updates #619, the installation went well, but not able to login, see error message bellow.

Our system runs PHP 5.3.16, it should be ok.
I checked all system variables required for PHP and MySql
        max_execution_time120,  realpath_cache_size   1M,   max_input_time  120
        innodb_flush_log_at_trx_commit  2,     max_allowed_packet  96

Original
PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away: SELECT filename FROM {registry} WHERE name = :name AND type = :type; Array ( [:name] =&gt; linkit_profiles_ui [:type] =&gt; interface ) in _registry_check_code() (line 3077 of D:\Xxxxx\includes\bootstrap.inc).

Additional
PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away: SELECT ml._, m._, ml.weight AS link_weight FROM {menu_links} ml LEFT OUTER JOIN {menu_router} m ON m.path = ml.router_path WHERE (ml.link_path IN (:db_condition_placeholder_0)) ; Array ( [:db_condition_placeholder_0] =&gt; demo ) in menu_link_get_preferred() (line 2492 of D:\Xxxxx\includes\menu.inc).

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in D:\Xxxxx\includes\database\database.inc:2139 Stack trace: #0 D:\Xxxxx\includes\database\database.inc(2139): PDOStatement->execute(Array) #1 D:\Xxxxx\includes\database\database.inc(664): DatabaseStatementBase->execute(Array, Array) #2 D:\Xxxxx\includes\database\database.inc(2318): DatabaseConnection->query('SELECT expire, ...', Array, Array) #3 D:\Xxxxx\includes\lock.inc(167): db_query('SELECT expire, ...', Array) #4 D:\Xxxxx\includes\lock.inc(146): lock_may_be_available('schema:runtime:...') #5 D:\Xxxxx\includes\bootstrap.inc(420): lock_acquire('schema:runtime:...') #6 D:\Xxxxx\includes\bootstrap.inc(442): DrupalCacheArray->set(Array) #7 [internal function]: DrupalCacheArray->__destruct() #8 {main} thrown in D:\Xxxxx\includes\database\database.inc on line 2139

**Comment by sylus** [comment]
Your settings appear correct aside from memory limit which on initial install should be set to at least 256M (you can then proceed to specify 192M.

With the correct memory limit does the install proceed?

**Comment by ssari** [comment]
I tryed memory_limit = 220M, 256 and 512, with no success.

Drush was updated to 5.8.

Please note the installation seems ok. 

I'm able to navigate the wetkit template, an additional error message is displayed in the frontpage: 

Notice: Undefined index: menu-wet-mid-footer in menu_tree_build()...

However, when we try to login with the drupal admin account the PDO exception is still appearing after the login. 

So I wonder if I need other PHP extension ( these are already enabled):
php_bz2.dll
php_com_dotnet.dll
php_curl.dll
php_gd2.dll
php_mbstring.dll
php_mysql.dll
php_mysqli.dll
php_pdo_mysql.dll
php_pdo_sqlite.dll
php_sqlite.dll
php_sqlite3.dll

I installed the wetkit yesterday morning on this server with no errors (before the distro update), so it might be something related to the last update.

Thanks in advance for your help.

**Comment by sylus** [comment]
Hmm we have been installing a few servers today with no problems. Also Travis has reported no errors so am inclined to think this is a problem with your configuraiton.

Is your mod_rewrite enabled for the server? Additionally perhaps your vhost is not properly configured.

**Comment by ssari** [comment]
Ufa!!! Done.
After reinstalling the AMP stack, and change Mysql parameters in my.ini fiel:
max_allowed_packet = 40M
*_buffer_size = 20M
in addition the ones required in the documentation.
innodb_flush_log_at_trx_commit = 2
max_allowed_packet = 96M

**Comment by MikeDucharme** [comment]
I had only to update max_allowed_packet size (set to 96M as well) in mysql's my.cnf file.
