### ISSUE TITLE
Drush 5.8 Requirement

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#622]
Just wanted to alert the community. The build out now requires Drush 5.8 as a minimum.

This is kind of a disruptive change. However have been pushing the awesome D.O community to incorporate translations during the Drush Make phase.

With Drush 5.8 when we do the build out the po files are now downloaded as well which allows upon initial install to have a greater degree of translation support.

Additionally Drush 5.8 has added performance improvements for compilation in Windows based environments so figure an added bonus as well.

An updated windows installer for drush (5.8) has been posted at: http://drush.ws/drush_windows_installer

Process is as simple as reinstalling with this version if you are using Windows.

**Comment by MikeDucharme** [comment]
Is there a link to D.O discussing incorporated translations in drush make? I'd like to follow.

**Comment by sylus** [comment]
Hey @MikeDucharme this is the only issue I know about: http://drupal.org/node/1543774

Also you have been added to the variant members :)

**Comment by MikeDucharme** [comment]
I saw that! Thanks. I'll be coming out to monthly meetups for sure.
