### ISSUE TITLE
Video Player

### ISSUE THREAD

**Issue by lpgascon** [wet-boew/wet-boew-drupal#634]
Hi guys,

We were wondering if there is any plan/timeline for the implementation of the Video Player module for the Drupal WetKit? This is one of our priorities for implementation and would like to get an idea when we can expect something? 

Appreciated

Louis

**Comment by sylus** [comment]
Hmm I have a half baked implementation at the moment which I can release on another branch for evaluation?

As for a stable release all depends on solving some of the few remaining high level issues. I can try to aim for before January?

Certainly would probably be the most useful widget to have.

**Comment by lpgascon** [comment]
Whatever can be done about it is very appreciated. As long as there is a plan to work on this sooner than later.
(Would be sad to see this fall on the back burner) We were just finding it strange that an image of the video player has been sitting on the main page of the distribution and we don't see anywhere why it is not functionnal or when it will be released.

Thanks again

**Comment by sylus** [comment]
Hey @lpgascon keep in mind you can still use raw markup for any of the WET widgets that are not implemented. So the Video Player would work this way as well. However definitely understand a more turn key solution would be beneficial. I have a lot on my plate this weekend, but will at least try to get a rough implementation out of the door.

**Comment by LaurentGoderre** [comment]
Hey @sylus, I haven't developed in Drupal in a while but maybe you have another WET implementation that's done I can reuse that to create the multimedia player. The biggest task I guess is creating the content type for HTML captions.

**Comment by ssari** [comment]
Thanks @sylus  and @LaurentGoderre. All efforts are appreciated, and we'll try to help as much we can.

**Comment by sylus** [comment]
This works now straight in the WYSIWYG media button!

**Comment by LaurentGoderre** [comment]
@sylus I guess we can close this and open other issues seperatly can't we?

**Comment by sylus** [comment]
Woot agreed sorry took me a while to get this one but working great now!

**Comment by mgifford** [comment]
Ok, so you click on the "Add media" button in CKEditor `<span id="cke_55_label" class="cke_button_label cke_button__media_label">Add media</span>`

Then upload a .mov file and it doesn't come up embeded in Laurent's Video player. 

Either the short description you gave 5 months ago is misleading or something's changed since it was written.

![screen shot 2013-07-08 at 6 56 40 pm](https://f.cloud.github.com/assets/116832/765137/2edefc0c-e822-11e2-8516-36732fc7d061.png)

So if there's another way to present video with WET I'm looking forward to seeing it.

**Comment by pjackson28** [comment]
There is likely a compatibility issue with the format you are using as .mov is a QuickTime format. Here is the compatible formats section from the player documentation:

Compatible Formats

Video: MPEG4(H264+AAC), WebM(VP8)
Audio: MP3, Ogg Vorbis
Captions: TTML, HTML5 Data

(https://github.com/wet-boew/wet-boew/wiki/Multimedia-player#compatible-formats)

**Comment by mgifford** [comment]
Would be useful if there was a warning of some point when folks are uploading a .mov to alert folks that it won't work with the video player.

However, even using the demo.mp4 which came with the distro (or a .m4v file that I uploaded after testing locally), it still isn't working. Some screenshots of the wysiwyg & published page.

![screen shot 2013-07-09 at 11 29 24 am](https://f.cloud.github.com/assets/116832/769027/8db60b14-e8ac-11e2-8646-e27230b4e77a.png)

![screen shot 2013-07-09 at 11 29 47 am](https://f.cloud.github.com/assets/116832/769029/93492b4c-e8ac-11e2-80a4-3dd980ff8aad.png)

**Comment by LaurentGoderre** [comment]
Do you have a live example?

**Comment by mgifford** [comment]
I sent you the link to our testing server as a DM. As I said there, it's likely an issue on the Drupal side.  Either in the documentation or code. Just a matter of trying to track down how it should be done & making sure it's clearly documented so that we can track down when it doesn't work as expected.

**Comment by sylus** [comment]
Closing this as workflow can be adjusted by just removing mov from the list of allowed file extensions.
