### ISSUE TITLE
Missing Page Title and Tabs

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#636]
How can I add “Page Title” and “Tabs” to a panel in a new content type as it is in the “Basic Page” content type?

The only option available in the “Page Content” category is “Node Title” or “Field Title” (when Automatic Field Replacement is enabled).  These options require style configuration.

Am I missing any configuration in this new version?

Thanks,

**Comment by sylus** [comment]
If you go to:

admin/structure/panels/settings/panel-page

Are the checkboxes for those elements unchecked?

**Comment by ssari** [comment]
Yes, I check "Page Title" and Tab in "Allowed Other content" (admin/structure/panels/settings/panel-page).

I should be enough to have the category "Page element" in the "Add content to Content" view. I am missing as well the category Miscelaneous.

Is there any place to set the categories to be showed in the panes?

or How to add entities in here admin/panopoly/panes?

**Comment by ssari** [comment]
Althought, I disabled the  "Automatic Field Replacement", the  “Field Title” (machine name title_field) is still appearing in the new content types.

And, it seems caching Panelize information , even after 1) Delete the content type, 2) Flush All in Drupal, 3) Clean the browser, and 4)Restart the server. Crazy!!!

Actually, I could delete the  Panelize information FROM`wetkit`.`panelizer_defaults` in the database.

**Comment by sylus** [comment]
Hey @ssari would it be possible to have a step by step procedure of what you are trying to do and your anticipated result?

**Comment by ssari** [comment]
When adding a new panelized content type (admin/structure/types/manage/my-content-type)
STEPS:
1)  Title is in the “Manage fields” with Field Type = Node module element, by default
2)  Title is not showed in “Manage display” – Default, by default
3)  Title is not showed in admin/config/content/panelizer/node/my_content_type.page_manager/content
        3.1) allowed content  allowed content and layout as standard Panels pages
        3.2) Full Page override
                (a) Settings --> In-Place-Editor and CSS-ID: page-page
                (b) Contexts  --> (nada)
               (c)  Layout --> Wetkit – 2 column for example
                        (i) Custom:Center pane --> Top region 
               (d)  Content
                         (i)    This node” Body and “This node”-->Top region

Adding Page:Title in the Content region (or whatever). 
Pressing the gear button the “Add content to Content” admin view is showed.
1)  The possible options are “Form Content” and Page Content”, and only Node:Title is in the last option.
2)  Note that “Page Element” and “Miscellaneous” are not there.

The same thing happened after configuring Panels (/admin/structure/panels/settings/panel-page), that is checking the options “Page tittle” and “Tabs” in “Allowed other content” 

My guess, we need to have “Page Element” in the “Add content to Content” admin view, but I couldn’t find where I should set this.

Please note that, it has happened in the last versions, the ones I have installed in the middle of November are ok.

Thank you for your support.

**Comment by ssari** [comment]
Good news about the Beta1 version   #668 @sylus, and I want be sure this issue about "Page Title" and "Page Tabs" will be covered.
Digging down the code I found out that the wetkit_pages custom module (\wetkit1\profiles\wetkit\modules\custom\wetkit_pages) define this two panes in wetkit_pages.panelizer.inc: (   $pane->type = 'page_title'; and   $pane->type = 'page_tabs';).
When creating a new panelized content tye using the UI, I believe we are using other module, perhaps  the panapoly_core module ((sites\all\modules\panopoly\panopoly_core\panopoly_core.panelizer.inc), in which these panes are not defined.
Please, have a look on this for me.

**Comment by ssari** [comment]
This issue is not appearing in the version installed last Friday (11/1/13), so I guess it is fixed; however I didn't realize what was wrong.  Any how, I will close this issue.
