### ISSUE TITLE
French Translations are not being downloaded during build/drush make command in step 4 of the instructions.

### ISSUE THREAD

**Issue by Ozinold** [wet-boew/wet-boew-drupal#637]
Here's one of many warnings:

<code>

> > panopoly_magic cloned from http://git.drupal.org/project/panopoly_magic.git.                                                                 [ok]
> > Checked out revision 27071ae.                                                                                                                [ok]
> > Unable to download translations for panopoly_magic: fr                                                                                       [warning]
> > </code>

**Comment by sylus** [comment]
This is expected as not all modules have translations defined for them. We are working for translations for all of the panopoly modules atm though.

The l10n_client can then be used for all remaining translations (appears at the bottom on french screen)
