### ISSUE TITLE
HTML5 with Drupal form elements?

### ISSUE THREAD

**Issue by mxlav** [wet-boew/wet-boew-drupal#640]
I've managed to get html tag via the hook_form_alter such as adding placeholder, or pattern, but It seems is there should be an easier way to accomplish this via manage fields on the content type.

I was wondering if you guys knew of a a module to accomplish this?

I've seen some posts about people patching Drupal 8 core fields to do this, but what do we have for Drupal 7?

**Comment by sylus** [comment]
I think http://drupal.org/project/html5_tools along with http://drupal.org/project/elements solves many of these problems, just haven't had the change to evaluate them for inclusion but would greatly welcome feedback on if they solved many of these problems and caused minimal regressions in the build.

**Comment by mxlav** [comment]
I'll give it a try.

**Comment by mxlav** [comment]
I started playing a little with HTML5 attributes, but when I found out they didn't work in IE8, then I decided not to spend anymore time on this at the moment since any HTML5 validation wouldn't work here at work.
