### ISSUE TITLE
Handler views - node could not be added

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#645]
The following message appears in admin/workbench.
It seems not affecting the system.

Debug:
'Handler views_handler_field_node_revision tried to add additional_field language but node could not be added!'
in views_handler_field->add_additional_fields() (line 142 of c:\xxx\wetkit\sites\all\modules\contrib\views\handlers\views_handler_field.inc).

**Comment by nadinecz** [comment]
Just adding some data points....

Not using the latest wet-drupal, not using workbench.

But.

I got the exact same debug message.  I was trying to show all the revision of a node (Views 7.x-3.5).   

Including having added this patch http://drupal.org/node/1754354, and this one http://drupal.org/files/views_1827602_5_content_revision_description.patch (but further testing showed that the patches had nothing to do with it.  

I did have a relationship to the original node content and the revision user.... <-- something in here (I think) was causing it to 'freak out'. I've had to put it aside for now, as it's annoying, but not critical...

It's an issue I have open to get back to, watching this in case you have any luck.  I'll post back if I find anything.
