### ISSUE TITLE
Panels support for workflow

### ISSUE THREAD

**Issue by joel-osc** [wet-boew/wet-boew-drupal#648]
Anyone using the workflow module with WET may be interested in applying this patch: http://drupal.org/node/1511694#comment-6855398 that I submitted last night . It will allow you to add the workflow form to any node edit panel region independent of the base form.

**Comment by sylus** [comment]
Code looks awesome.

Would like to bring this in but quick questions for @joel-osc 

Does this mean workflow is mutually exclusive from workbench? If we use one do we need the other?

**Comment by sylus** [comment]
Cleaning up some old issues. :)
