### ISSUE TITLE
problems with sub theme

### ISSUE THREAD

**Issue by mxlav** [wet-boew/wet-boew-drupal#654]
I did a clean install from yesterdays build, and copied a working subtheme from a previous install and the styling is not loading. I'm getting the following in the apache log

Wed Dec 19 09:20:36 2012] [error] [client 7.28.132.76] File does not exist: E:/Sites/profiles, referer: http://7.28.135.50/drupal_wet2/eng
[Wed Dec 19 09:21:06 2012] [error] [client 7.28.132.76] File does not exist: E:/Sites/misc, referer: http://7.28.135.50/drupal_wet2/eng/admin/structure/taxonomy/overall_status/add
[Wed Dec 19 09:27:02 2012] [error] [client 7.28.130.42] File does not exist: E:/Sites/misc, referer: http://7.28.135.50/drupal_wet2/eng/admin/appearance/settings/cbsa_adaptivetheme

I also tried to create a new subtheme with the same results, all the wetkit styling is not coming in.

**Comment by nadinecz** [comment]
Update.   The error messages in the apache error.log go away when we remove the minister box (this is unrelated to the sub-theme issue @mxlav  & I are experiencing). 

Current:   Still unable to get the sub-theme to work properly.   Note:  we do have this working in previous copy.   Work continues.

**Comment by sylus** [comment]
If you switch to the wetkit adaptivetheme does everything work as expected?

**Comment by mxlav** [comment]
yes, the wetkit theme is displaying ok on its own, our sub theme is currently only extending it without any customisation (atm)

this is the info file (located in E:\Sites\drupal_wet2\sites\all\themes\cbsa_adaptivetheme)

;----------// Theme Information

  name        = CBSA WetKit Adaptive Theme
  description = Desc here....
  core        = 7.x
  base theme  = wetkit_adaptivetheme

;----------// Stylesheets

  ; Web Usability Theme - Custom CSS
  stylesheets[all][]  = css/cbsa-adaptivetheme-custom.css

;----------// Regions

  regions[sidebar_first]  = Sidebar first
  regions[sidebar_second] = Sidebar second
  regions[content]        = Main Content
  regions[highlighted]    = Highlighted
  regions[content_aside]  = Aside
  regions[footer]         = Footer
  regions[leaderboard]    = Leaderboard
  regions[header]         = Header
  regions[mega_menu]      = Mega Menu
  regions[help]           = Help
  regions[page_top]       = Page top
  regions[page_bottom]    = Page bottom

We've extended the wetkit theme in the past with no issue, not sure what is going on now?

**Comment by sylus** [comment]
I don't suppose you can send me the sub theme? Sorry but I don't have enough information to go on atm.

**Comment by mxlav** [comment]
I think i emailed it at your work email :S...the mail server was giving me all kinds of errors with zip and php files..

**Comment by nadinecz** [comment]
More data points.
1. Switched the "Debug Subtheme" option on - showed that we were missing 
   - release     = 7.x-3.x..... in the info file.   Added it.   Now says we're good to go; however, the same css loading issue persists.
2.  I know the subtheme is being loaded....

**Comment by mxlav** [comment]
i just built a fresh install at home on the macbook, same issue...something smells fishy.

Has anyone else attempted to subtheme wetkit recently?

**Comment by sylus** [comment]
I have a rough idea of what this could be but haven't had a chance to check out yet. If you take a look here: https://github.com/wet-boew/wet-boew-drupal/blob/master/modules/custom/wetkit_wetboew/wetkit_wetboew.strongarm.inc#L142-476

You see we export the adaptivetheme settings. My guess is these trump the new subtheme.

Can confirm more tomorrow as reserving time for this.

**Comment by sylus** [comment]
Actually I can spend some time on this now. Can I be a bother and ask you to send your theme to my email addy? sylus1984@gmail.com?

**Comment by mxlav** [comment]
ok sent you the one from home, which is pretty much the same basic empty theme

**Comment by sylus** [comment]
I found the problem.

If you look here: https://github.com/wet-boew/wet-boew-drupal/blob/master/modules/custom/wetkit_wetboew/wetkit_wetboew.module#L329

You see we are setting the WET-BOEW library explicitly if we are using the wetkit_adaptivetheme but since a subtheme is being used this won't work since wetkit_adaptivetheme is no longer the main theme.

I think something like this would fix it:

``` php
  if (($theme == 'wetkit_adaptivetheme') || (($theme == variable_get($subtheme)) {
```

Where the variable_get can be specified inside one of the config form for wetkit_wetboew.

As a temporary workaround and to verify this is the problem can you write (in Line 329):

``` php
  if (($theme == 'wetkit_adaptivetheme') || (($theme == 'your theme name')) {
```

If this works before I resort to using a variable get I'd like to detect a subtheme of wetkit_adaptivetheme automatically so people wouldn't have to use a config form.

**Comment by sylus** [comment]
@mxlav and @nadinecz did this fix your problem?

**Comment by mxlav** [comment]
@sylus works like a charm. I can live the workaround.

thanks for the help.

**Comment by sylus** [comment]
I will work on this and commit some code that detects the subteme so you won't have to modify core. WIll notify here when done.

**Comment by sylus** [comment]
Thinking this will fix the sub theme problems :)
