### ISSUE TITLE
Ajax error when trying to Preview a custom layout in Panels. "Managing Custum Layouts" -> "Adding Flexible Layout"

### ISSUE THREAD

**Issue by Ozinold** [wet-boew/wet-boew-drupal#656]
An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /eng/admin/structure/panels/layouts/add-flexible
StatusText: OK

ResponseText: 
Add a new layout | Web Experience Toolkit
*/-->
Skip to main content
HomeAdministrationStructurePanelsLayoutsAdd flexible layout
My account
Log out
Français
Add a new layout  
Add to Default shortcuts  
Error message
Name field is required.
Administrative title 
&nbsp;
This will appear in the administrative interface to easily identify it.
Name *
The unique ID for this layout.
Administrative description 
Category 
What category this layout should appear in. If left blank the category will be "Miscellaneous".
CanvasCanvas settings
Add column to left
Add column to right
ColumnColumn settings
Add row to top
Add row to bottom
RowRow settings
Add region to left
Add region to right
RegionRegion settings
Remove region
CenterCustom: Lorem IpsumLorem Ipsum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam egestas congue nibh, vel dictum ante posuere vitae. Cras gravida massa tempor metus eleifend sed elementum tortor scelerisque. Vivamus egestas, tortor quis luctus tristique, sem velit adipiscing risus, et tempus enim felis in massa. Morbi viverra, nisl quis rhoncus imperdiet, turpis massa vestibulum turpis, egestas faucibus nibh metus vel nunc. In hac habitasse platea dictumst. Nunc sit amet nisi quis ipsum tincidunt semper. Donec ac urna enim, et placerat arcu. Morbi eu laoreet justo. Nullam nec velit eu neque mattis pulvinar sed non libero. Sed sed vulputate erat. Fusce sit amet dui nibh.  
Live preview

![Screenshot from 2012-12-19 13:55:38](https://f.cloud.github.com/assets/2808857/22731/6b80c12a-4a0e-11e2-9b3e-6c15124a2b9a.png)

**Comment by Ozinold** [comment]
I kinda figured out why it happens. It's when the Administrative title is left blank. It's not a mandatory field so it should throw some sort of exception when the Administrative title is left blank.

**Comment by sylus** [comment]
We don't really use flexible layout for this distribution as we need to have specific layouts to work with WET. It is actually almost as quick to make custom panel layouts. Either way this issue is likely upstream.
