### ISSUE TITLE
Working Group Meeting - January 25, 2013 1:00pm to 4:00pm

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#664]
We are looking to have the January working group meeting At Ottawa City Hall on January 25, 2013.

If anyone has a issue with this date please post below.  If we do not hear back from anyone in the next day or so we will post the invite.

Thanks

Update: Date changed from Jan 24 to Jan 25

**Comment by StephenOTT** [comment]
Looking to move the date to the Friday, January 25, 2012.  Please let me know if anyone has issues with this?

**Comment by StephenOTT** [comment]
Moving Date from Jan 24 to Jan 25

**Comment by sinkinsona** [comment]
Just sent out meeting invitation for next WxT Drupal Working that will be held at at Ottawa City Hall - Colonel By Room - 2nd Floor South end of building on January 25, 2013, 1:00pm to 3:30pm.  If you did not receive an invite and wanted to participate just let me know.

**Comment by StephenOTT** [comment]
Need to post Agenda. @sinkinsona 

I would like to add the topic of Caching to the agenda topics

**Comment by sinkinsona** [comment]
@StephenOTT Should be able to post it tomorrow.

I have received a couple of agenda items requests but if anyone has other items they would like to discuss just let me know.

**Comment by sinkinsona** [comment]
Please find below the proposed agenda for the next WxT Drupal Working meting that will be held at at Ottawa City Hall - Colonel By Room - 2nd Floor South end of building on January 25, 2013, 1:00pm to 3:30pm.
1. Introductions
2. Drupal Camp Ottawa discussion
3. Project updates
   - City of Ottawa launch
   - StatCan upcoming launch
   - Opin Software inc
   - Other
4. Debrief on Acquia meeting with TBS
   - RFI and RFP
5. Distro Updates and new features
6. Caching (memcache , Varnish configurations)
7. Increasing Collaboration
8. Feature request
9. Open discussion
10. Next Meeting
11. Round table / closing remarks

**Comment by dergachev** [comment]
Thanks to everyone for coming! Here are my meeting notes: https://gist.github.com/4637572

Sorry about the mistakes.

**Comment by xmacinfo** [comment]
I was one of the folks coming from Montréal. Thank you all for organizing these meetings.

Thank you, Alex, for the notes. These notes are complete and very good!

**Comment by StephenOTT** [comment]
Great meeting everyone.

Minutes and Presentation are posted: https://github.com/wet-boew/wet-boew-attachments/tree/master/Working%20Groups/Drupal%20Variant/Meetings/January%2025%202013

Make sure to clone the repo if you want the presentation as the Presentation is too big to be downloaded through the Github weblayer
