### ISSUE TITLE
Australia's Drupal 7 aGov Distro

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#665]
http://agov.com.au

http://drupal.org/project/agov

Demo Site: http://demo.agov.com.au

Can be installed easily by downloading the zip: http://ftp.drupal.org/files/projects/agov-7.x-1.0-beta3-core.zip
Unzip and import with Acquia Dev Desktop 

Has anyone taken a look?  Evaluated?

**Comment by StephenOTT** [comment]
@mgifford @openplus @sylus @sinkinsona

**Comment by StephenOTT** [comment]
@sylus make sure to check out their installer UI.
Some nice additions.
Optional Example Content install

**Comment by StephenOTT** [comment]
PreviousNext the company that developed the distribution created a WCAG validator Service and Scheduler modules.
The WCAG modules are included in the distro

May be a interesting model to duplicate

**Comment by ssari** [comment]
Nice integration in aGov distribution. Thanks for sharing @StephenOTT.
The UI installation with variable checking will be great for the new adopters.
Features such as WCAG module would be great for future additions, perhaps for the Beta 2 version :-)

**Comment by StephenOTT** [comment]
Would be great if people could test it out and see what could be adopted from the distro.

There are some distinctly different choices made in the distro and some very similar choice for modules.  

Would be a great comparison as it is a distro that is going for a market that is very similar to WET-BOEW Drupal

**Comment by ssari** [comment]
Agree. I installed it, and I'll be testing it through the week.

**Comment by mgifford** [comment]
Definitely worth checking out the aGov distro they built in the Quail code that I mentioned earlier into the project:
https://drupal.org/project/agov

Anyone know anything about the OpenHamilton initiative here:
http://datapublic.org/about
https://drupal.org/project/datapublic

**Comment by StephenOTT** [comment]
@mgifford could probably reach out over MISA if you like

**Comment by mgifford** [comment]
I'm in touch with folks from Previous/Next who are building it.  Not sure who MISA is but think it's usually beneficial to expand the network and encourage folks to start collaborating more.
