### ISSUE TITLE
theming comments

### ISSUE THREAD

**Issue by mxlav** [wet-boew/wet-boew-drupal#666]
I've been playing with comment.tlp.php and comment-wrapper.tpl.php, in order to use the WET comment-module style. By changing the comments to be a li instead of articles, and with some css teaks I've managed to make it work.

One thing I haven't been able to get to work yet is making the delete|edit|reply links to be buttons instead of links. The closest I got was adding the following code to preprocess_comment:

function cbsa_adaptivetheme_preprocess_comment(&$vars){
    $vars['content']['links']['#attributes']['class'][] = " button";
}

This adds the class to the wrapping UL tag, and just makes all three a big button. What I need it either at the LI tag level or the a tag.

Any ideas where/how I can do this?

**Comment by sylus** [comment]
Oh this is a great idea! Haven't had a chance to take a look at this but let me take a look tomorrow and will get back to you :)

**Comment by sylus** [comment]
Some comment theming will be added with the new wetkit_community module being added shortly.
