### ISSUE TITLE
Rendering Alt and Title attributes with Media File Selector 

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#667]
Following Issue #553
The system doesn't render the image's attributes (Alt and Title) when using:
FIELD TYPE:     Image
WIDGET:         Media file selector
Display FORMAT: Image

Alternatively, I could use  Display FORMAT: Rendered file, but it doesn't allow customized Image style.

Looking the database for the field_myimage, in the table `field_data_field_myimage` the entries 
field_myimage_alt and field_myimage_title are NULL while in the tables field_file_image_alt_text_value and field_file_image_title_text_value the values are assigned.

I wonder if there is any way to fix it in order to use media browser and image style features.

Thanks.

**Comment by sylus** [comment]
Sorry for not getting back there is a site launch happening soon so have been preoccupied. I think this has been fixed when using the WYSIWYG but haven't checked it on the field type. Seems like another prime reason to have unit testing :) I will take a look! 

Thanks for catching this!

**Comment by sylus** [comment]
So I looked into this and it appears you have to use the field type File instead of image for this to work.

**Comment by ssari** [comment]
I was refering to Field Type : Image, but it was fixed in RC1.
Sorry @sylus, I forgot to close this.
