### ISSUE TITLE
fyi -- drupal camp ottawa !!

### ISSUE THREAD

**Issue by mxlav** [wet-boew/wet-boew-drupal#669]
http://drupalcampottawa.com/

**Comment by StephenOTT** [comment]
Some Image-Actual / Responsive image issues with the sponsor images at the bottom :)
Ottawa.ca has some of the same issues 

![snap](https://f.cloud.github.com/assets/1994838/57846/7ce8807a-5b5b-11e2-966d-7cb5395a8bff.jpg)

**Comment by liquidcms** [comment]
whoo hoo! the site is up!!

and issue tracker for this on GitHub; cool (as my emails don't seem to get through to OpenPlus).. couple comments/suggestions for the site:
- can we open up the admin access to the Camp organizers?
- can we get the sponsors list updated - i have been trying to get LiquidCMS added for a few days now?
- i see Stephen's issue posted above has been fixed: first fix still had issues in that logos didn't appear correctly in most browsers; they now work in FF and IE which is good - can you can check out the home page in IE? the Camp logo is messed up (IE8)  - yes, i am sure all of you use MAC's; but 99% of the GoC uses IE (ughhh!!)
- is there a GitHub repo for this site? if you add one we can fix some of the left over IE or other css issues

thanks for getting this up.

**Comment by liquidcms** [comment]
oh yes, and i guess seconding what Stephen said; responsiveness doesn't seem to work; but not sure how important that is at this late stage.

**Comment by liquidcms** [comment]
i guess FR side of site could use some work; anyone able to do some translation work?

**Comment by xmacinfo** [comment]
I can help a bit with the French translation, here and there. Can you create an account for me?

I plan to go to your camp for the first time.

**Comment by liquidcms** [comment]
looks like a site bug list was started here: https://docs.google.com/document/d/1ZNgOzFhVDs2_OmhTnKJnp9Gy23hcEm9PGGXRmhyTMJI/edit

**Comment by minorOffense** [comment]
If you request access to the doc I can give you edit rights.

**Comment by sylus** [comment]
See #714
