### ISSUE TITLE
Sharing and Contributing comments for Group

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#672]
Something that was posted on the OpenCounter Distro (https://github.com/codeforamerica/opencounter#readme)

![snap](https://f.cloud.github.com/assets/1994838/57850/a93722ee-5b5b-11e2-808c-93a53d461f7e.jpg)

What do you guys think for adopting the same text?

**Comment by mgifford** [comment]
Great suggestion to add to the distro's README.md

I like being explicit about "the ask".  We need them to be part of the community and there are a few ways that folks can do this.

I guess it's a matter of forking the code & making a pull request.

**Comment by sylus** [comment]
We now have a contributing.md file.
