### ISSUE TITLE
HTML5 Validation Error in Book Module 

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#673]
I got the following error message when validating the HTML pages rendered by the Book Module.

Line 15, Column 71: Bad value up for attribute rel on element link: Not an absolute IRI. The string up is not a registered keyword or absolute URL.
<link rel="up" href="/eng/content/xxxxxxxxxxx" />

The value “up” is no longer available in the tag link for HTML5 (http://www.w3schools.com/html5/att_link_rel.asp).

I modified the book.module file replacing “up” by “ stylesheet”, and it worked. 

Since it’s no appropriated modify the core module, I would like to know if there is any other solution besides redirecting the issue to Drupal 7 Book Group (http://groups.drupal.org/node/237838).

……………………………….original
if ($book_link['plid'] && $parent = book_link_load($book_link['plid'])) {
      $parent_href = url($parent['href']);
      drupal_add_html_head_link(array('rel' => 'up', 'href' => $parent_href));
      $variables['parent_url'] = $parent_href;
      $variables['parent_title'] = check_plain($parent['title']);
    }
………………………………….modified
if ($book_link['plid'] && $parent = book_link_load($book_link['plid'])) {
      $parent_href = url($parent['href']);
      drupal_add_html_head_link(array('rel' => 'stylesheet', 'href' => $parent_href));
      $variables['parent_url'] = $parent_href;
      $variables['parent_title'] = check_plain($parent['title']);

**Comment by sylus** [comment]
Hmm would probably file an issue on Drupal.org for this ^_^
