### ISSUE TITLE
Drupal Wetkit installation error

### ISSUE THREAD

**Issue by Tikka** [wet-boew/wet-boew-drupal#674]
In step 4 on https://github.com/wet-boew/wet-boew-drupal/blob/master/README.md

I am able to run:
git clone https://github.com/wet-boew/wet-boew-drupal.git profiles/wetkit;

The second part of the step:
drush make --prepare-install --no-gitinfofile --working-copy profiles/wetkit/build-wetkit.make --yes

fails with this error (truncated):

http://solr-php-client.googlecode.com/files/SolrPhpClient.r60.2011-05-04.zip.
querypath cloned from https://github.com/technosophos/querypath.git.        [ok]
Checked out revision 2320739.                                               [ok]
wet-boew cloned from https://github.com/wet-boew/wet-boew.git.              [ok]
Unable to checkout revision 570555b                                      [error]
Source directory                                                         [error]
C:/Users/TIKKA~1.CCH/AppData/Local/Temp/make_tmp_1358182345_50f437c94f293/**buil
d**/sites/default\default.settings.php
is not readable or does not exist.
chmod(): No such file or directory make.utilities.inc:372              [warning]

This command was executed from DOCROOT.

Thanks, T

**Comment by ssari** [comment]
Hi Tikka,

I just did an instalation with no errors, only warnings (translations)

You may check if the user (C:/Users/TIKKA) has Administrative rights.

**Comment by Tikka** [comment]
Hi ssari,

The user has full admin rights. A couple of weeks before this, the installation was run successfully. Do you have any hints, other than the rights issue, to get around this problem?

Thank you.

**Comment by ssari** [comment]
You may check permissions for C:/Users/TIKKA~1.CCH/AppData/Local/Temp/..
It is used as temporary folder, and the error message is saying it is not readable or does not exist.

**Comment by Tikka** [comment]
The temp folder has full permission for every user authorized on the computer. Does special permission need to be set? As an aside, this command worked about 2 weeks before the Christmas holiday, on the same computer.

Thank you for pointing out the translation warnings. I forgot to mention that. I did understand about those warnings, based previous on a comment in the wiki, 

I've tried the installation again. The temp folder exists, and I can watch files being added to it while the installation is running. Things are being checked out successfully in the installation

Truncated excerpt from installation:
tinymce cloned from https://github.com/sylus/tinymce-wetkit.git.            [ok]
Checked out revision ef85a05.                                               [ok]
markitup cloned from https://github.com/sylus/markitup-wetkit.git.          [ok]
Checked out revision 4b77626.                                               [ok]

The folder make_tmp_1358266667_50f5812b8d65e was created, and then removed from the temp folder. The error report for this installation run reports correctly that : make_tmp_1358266667_50f5812b8d65e as being not available, which is reasonable, because it get's deleted.

C:/Users/TIKKA~1.CCH/AppData/Local/Temp/make_tmp_1358266667_50f5812b8d65e/**buil
d**/sites/default\default.settings.php
is not readable or does not exist.
chmod(): No such file or directory make.utilities.inc:372              [warning]

**Comment by ssari** [comment]
Strange!
I usually not use the extra parameters to build, only:
                                      drush make --prepare-install profiles/wetkit/build-wetkit.make --yes
Just double checking. Have you changed the recommended parameters for PHP and MySQL?
Which operational system and stack you are using?

**Comment by MikeDucharme** [comment]
Can you try running the command as sudo just to be sure that there are no permissions issues?

<code>sudo drush make --prepare-install --no-gitinfofile --working-copy profiles/wetkit/build-wetkit.make --yes</code>

**Comment by Tikka** [comment]
Hi ssari,

Yes it is strange. Since everything else in the installation seems to work., I believe the source of the error is this:

wet-boew cloned from https://github.com/wet-boew/wet-boew.git.
Unable to checkout revision 570555b [error]

PHP and MySQL have been setup as indicated in the installation instructions. The recommended versions of acquial drupal, git and drush were installed. Win 7 in this instance. This error can be repeated on other systems.

A colleague in my office had the same problem late last year (November, December?) He said it was resolved quickly by someone, and he cannot remember who or when. We are trying to rollback to a previous version - which worked for him.

Hi Mike: that was a good hint, but it did not work. Just for fun, I can see files being added/deleted from this temp folder as the installation progresses. sudo generates an error on my system. As copied from the git bash window.
$ sudo drush make --prepare-install --no-gitinfofile --working-copy profiles/we
tkit/build-wetkit.make --yes
sh.exe": sudo: command not found

**Comment by ssari** [comment]
Again checking!
Have you update Drush 5.8 or higher and Git 1.7.10 or higher ?
We had some issues using unappropriated version.
I installed the Wetkit wit Win 7 and AMPPS.

**Comment by Tikka** [comment]
H ssari,

Yes - drush 5.8, and git 1.7.10. I think we can close this issue, since MikeDucharme is having the same error. See issue 676.

**Comment by sylus** [comment]
Fixed now!
