### ISSUE TITLE
On IIS and MySQL

### ISSUE THREAD

**Issue by elaberge74** [wet-boew/wet-boew-drupal#675]
Does anyone has been installed it on IIS and MySQL ?

If yes, someone have something like a step by step ?

Merci

**Comment by sylus** [comment]
I know of some people that have done this, will send them an email. Asking if have the time to do a write up.

**Comment by StephenOTT** [comment]
Would be great if we can post on the Wiki

**Comment by dsamojlenko** [comment]
We have it running on IIS and MySQL and we didn't really have to do anything special to get things working.  Feel free to get in touch with any specific questions though.

**Comment by sylus** [comment]
Closing this for now as a fair amount of documentation on the interwebs ^_^
