### ISSUE TITLE
Do you rely on gh-pages demos from wet core or only the source and built files

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew-drupal#679]
hey @sylus, if the demos were to change, would that affect you?

**Comment by Tikka** [comment]
We have removed all of those pages.

**Comment by sylus** [comment]
Those files are used for an optional migration script to import them into drupal. Where are u thinking of putting them?

**Comment by LaurentGoderre** [comment]
We are looking at major changes to the demos folder but gh-pages shouldn't be affect, still wanted to give you a heads up.

**Comment by sylus** [comment]
Hey @LaurentGoderre will likely give you a call today about this have a few questions!
