### ISSUE TITLE
500 error on fresh install

### ISSUE THREAD

**Issue by dsamojlenko** [wet-boew/wet-boew-drupal#680]
Just did a fresh install from the repo and I'm getting a 500 error.  Here's what's in the log:

PHP Parse error:  syntax error, unexpected T_FUNCTION, expecting ')' in [...] /profiles/wetkit/modules/custom/wetkit_migrate/migrations/wetkit_migrate_link.inc on line 65

**Comment by MikeDucharme** [comment]
Did this occur during the drush make build or during a new site installation (via Drupal UI)?

Can you also provide some environment details? (drush, database, os versions)

**Comment by sylus** [comment]
It looks like you are running php5.2. I think this module requires u to have php5.3.

I know the offending line and will try to rewrite the code to make it 5.2 compliant.

**Comment by dsamojlenko** [comment]
you're right, we're running 5.2 ... stuck on it for now unfortunately.  I just removed the module - doesn't seem critical?

**Comment by sylus** [comment]
This has been fixed should work in php 5.2 now
