### ISSUE TITLE
wet-boew versions and wet-boew-drupal stable

### ISSUE THREAD

**Issue by Pacoup** [wet-boew/wet-boew-drupal#683]
How do I know/determine what version of the wet-boew my wet-boew-drupal install is using?

And how do I know what release I have / how to use a stable or a development version of the wet-boew-drupal distro. Right now it seems as if there's only a master branch in development and no "stable" releases.

**Comment by ssari** [comment]
According to #668  we are close to have the Beta1 version.
As far I understood, @sylus is working to provide a version, stable is possible with version control.
Come to this Friday meeting #664 to get more information.
Cheers,

**Comment by sylus** [comment]
RC1 is landing in a day or so to coincide with some of the StatsCan launches. Almost there!

**Comment by Pacoup** [comment]
Any details on what version of the wet-boew toolkit itself the Drupal distro is targetting? Any way to customize this (e.g. test with a beta version of wet-boew, etc.)?

**Comment by sylus** [comment]
#704
