### ISSUE TITLE
Search404 page not fully translatable to French

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew-drupal#684]
Type in a URL that doesn't exist, such as /wetkit and you'll see a page titled "Page not found" with search results below.  Now toggle to the French and you'll land on /fra/search404 and the title "Page not found" will still be displayed in English.

Now go to /admin/config/search/search404 and apparently you can set the "Custom Page Title" for English and French but no matter what you type, it will save for both English AND French.  Same for "Custom Page Text"... only one value gets saved for both languages.

**Comment by sylus** [comment]
This was solved for city of ottawa let me dig up the code and will post a commit shortly :)

**Comment by StephenOTT** [comment]
Could we get a post of the description for the fix during the commit  ?

**Comment by joejoseph00** [comment]
@sylus, just wondering if this commit was done, if so, you could close this issue as resolved.

Quoting your message "This was solved for city of ottawa let me dig up the code and will post a commit shortly :)"

**Comment by StephenOTT** [comment]
@joejoseph00 @sylus I think this was a global text overwrite that was done.... / String replace

@joel-osc any thoughts?

**Comment by sylus** [comment]
K the problem here is in search404_install:

variable_set('search404_page_title', 'Page not found');

So need to convert this into a multilingual variable.

**Comment by sylus** [comment]
Yeah apparently in search404_page search404 calls:

variable_get('search404_page_title', t('Page not found'));

But was initially set in search404_install as:

variable_set('search404_page_title', 'Page not found');

Notice that was initially set without t string. If you delete the variable search404_page_title then everything works when it is recreated.

**Comment by sylus** [comment]
http://drupal.org/node/1953556

**Comment by sylus** [comment]
Fixed upstream.
