### ISSUE TITLE
Changes to the core gh-pages

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew-drupal#688]
Hey @sylus I was inspecting the core build and discovered that post build script to update gh-pages is not behaving as expected and the rebase is actually going all the way to before the script was updating the branch. This causes our builds on master to be significantly longer and they keep getting longer.

I will change the approach (testing locally). The changes should not change the history but the history after the change might be a bit different.

Just a heads up

**Comment by sylus** [comment]
Thanks for the heads up @LaurentGoderre.
