### ISSUE TITLE
Title Settings - clarification

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#691]
The issues we had with page:title and page:tabs need some clarification, specially about the tittle settings (admin/config/content/title).

In a fresh version (28/01) these are the challenges:

By default the Title field is displayed as title, but it doesn’t appear in the “Manage display” options.

If Title is replaced with a field instance, the configuration is changed:
• Label:              Title
• Machine name:   title_field
• Field Type:         Text
• Widget          Text field
• Operations      edit/delete
In this case Title appears hidden in the “Manage display” window. 
Considering Title as an important element of the page, its confirmation is changed:
• Field:              Title
• Label:              <Hidden>
• Format:         Default

When panelizing the new content type, the allowed content and layouts are used as standard Panels pages.

After setting CSS ID and choosing the pages layout, the following panes are created:
• “This node” Title 
• “This node” Body 
• “This node” links 
// the menu options are hidden

These settings allow us to create new content where the Title does have the wet-boew format.

Going back to the panels, removing the “This node” Title, and adding Page title element, the title is displayed as it should be.

Similarly, the “page tabs” may be added to make easy the editing process.

It worked, but there are couple open questions:
1.  Do I need configure  “ Title settings”  in this process?
/admin/config/content/title
2.  Since we use the same content and layouts of the standard Panels pages, why the new content type doesn’t have by default these features (page title, page tabs) ?

**Comment by sylus** [comment]
Cleaning up some old issues. :) Please re-open if still a problem.
