### ISSUE TITLE
Permalink permission for Editor role

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#703]
Does someone know which permission (admin/people/permissions) is associated with Permalink field in the content type, for instance, Basic Page (node/add/wetkit-page)?

When using the Administrator role the field appears in the new content, but not for the Editor role.

 I tried several combinations with no luck.

Thanks,

**Comment by sylus** [comment]
I believe the permission you want is: Path -> Create and edit URL aliases

**Comment by ssari** [comment]
Thanks @sylus. I worked perfect.
