### ISSUE TITLE
Is the build still relying on gh-pages?

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew-drupal#706]

**Comment by sylus** [comment]
Nope this is our current pull from wet-boew

libraries[wet-boew][download][type] = git
libraries[wet-boew][download][branch] = v3.0-dist
libraries[wet-boew][download][revision] = d33e42
libraries[wet-boew][download][url] = https://github.com/wet-boew/wet-boew.git

**Comment by nschonni** [comment]
wouldn't a git submodule make more sense?

**Comment by sylus** [comment]
Drupal relies on Drush Make to accomplish the build out all external libraries should be called using this specification. A large part because the library has to be placed in /sites/all/libraries which is only created during the build out and subsequent installation.

**Comment by nschonni** [comment]
Fair enough, I've never used Drush (or Drupal). Is a tag easier to use than the branch/revision combo?

**Comment by LaurentGoderre** [comment]
Ok thanks! I will switch our gh-pages to not keep the history.
