### ISSUE TITLE
HTML video caption

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#707]
Any suggestion of tools to create a HTML video caption?

As far as I could go from using YouTube Subtitler and CaptionTube is a STR format.

Perhaps @LaurentGoderre  has a recommendation for us!

Thanks all.

**Comment by LaurentGoderre** [comment]
Any TTML caption files can easily by turned into HTML captions by taking the TTML captions and grouping them in paragraphs tags.

@sylus is there a content type in the Drupal distro to create the HTML captions?

**Comment by sylus** [comment]
Nope just a field to upload them. Would be neat to attempt but probably won't have the time for this particular feature. Anyone is welcome to do a pull request.

Basically what I do for creating a HTML video caption is just finding an example and manually editing the html. It doesn't take too long and is pretty straightforward.

**Comment by ssari** [comment]
Thanks @LaurentGoderre and @sylus.
I'll keep looking for solutions.
Cheers.
