### ISSUE TITLE
Regression of Issue #85? Theme disappears upon visiting admin section.

### ISSUE THREAD

**Issue by jmk1ng** [wet-boew/wet-boew-drupal#708]
Just did a fresh install today, and this one cropped up on me. The behavior is pretty much identical to ticket #85 

Installed via the web interface, got an error on the last step:

Notice: Undefined index: translations in EntityTranslationDefaultHandler->getTranslationsKey() (line 1405 of [...]\sites\all\modules\contrib\entity_translation\includes\translation.handler.inc).

Loaded up the site, and the theme showed correctly. Went into the admin section and the theme disappeared - both wetkit_rubik and wetkit_adaptivetheme are gone.

**Comment by sylus** [comment]
I know what is causing this but thought putting the bean installation code in a separate install_task would fix the issue. I had this working when the logic was present in hook_init.

This error doesn't occur when doing a drush si.

Thanks for letting me know i'll be sure to resolve this before rc1 release on Thurs.

**Comment by sylus** [comment]
This should now be fixed. I just tested the browser installation again and looks good :)
