### ISSUE TITLE
Tabbed interfaces break JS when browser resized

### ISSUE THREAD

**Issue by jmk1ng** [wet-boew/wet-boew-drupal#709]
Javascript Error:
Uncaught ReferenceError: ResizeEvents is not defined. Line 194 in pe-ap-min.js (when de-minified by Chrome Inspector)

I can't reproduce this error with the vanilla wet template, so I'm thinking it must be an issue with the Drupal variant (or at least exacerbated by the Drupal variant). I've isolated the problem to Tabbed Interfaces specifically.

To reproduce:
1. Clean install of wetkit profile using the wetkit_adaptivetheme theme
2. Add a tabbed interface pane to the homepage (I added 2 slides with images)
3. Resize the browser to handset width (triggering the JS error above)
4. Resize the browser back to desktop width (mobile UI persists)

I noticed @sylus brought up this problem in the core wet issue queue here: https://github.com/wet-boew/wet-boew/issues/791 However, it seems this problem isn't isolated to Ottawa.ca as it's reproducible with a vanilla wet-boew-drupal install.

**Comment by sylus** [comment]
Ah this was fixed for City of Ottawa but didn't bring the fix over. Will do that tomorrow!
