### ISSUE TITLE
Please Register for Drupal Camp Ottawa

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#714]
It's time now to register for - http://www.drupalcampottawa.com/

Please encourage curious people in different government departments to sign up.

It will be a great learning opportunity and an opportunity to network with others who have been using Drupal.

Robin, Mat, Chris & I gave a good plug on the radio this morning & hope that provides a surge of registration.  The sessions are really shaping up!

**Comment by StephenOTT** [comment]
@mgifford lets hear more about the plug?

**Comment by xmacinfo** [comment]
I would need an admin account to fix the French side! Possible?

**Comment by manumilou** [comment]
I also could help for french translation.
