### ISSUE TITLE
Array to string conversion in module_implements() Notice

### ISSUE THREAD

**Issue by TheDuke13** [wet-boew/wet-boew-drupal#715]
Hi all,

I'm currently working on a sanbox environment (setup last Thursday) and have this Notice/Error that keeps coming up when I edit a content block on the home page using the visual interface from panopoly:
_Notice: Array to string conversion in module_implements() (line 709 of /var/www/html/includes/module.inc). It loops this notice then shows the content._

I was wondering if this is a known issue or if someone would have a quick fix?

Let me know if you need any details specific to the context

**Comment by sylus** [comment]
I don't see this error on current builds are you able to verify?

**Comment by sylus** [comment]
Closing as haven't been able to reproduce on latest but please reopen if problem persists!
