### ISSUE TITLE
Interest in code sprint for Dual language Editor?

### ISSUE THREAD

**Issue by strinh** [wet-boew/wet-boew-drupal#722]
Is there any interest out there from developers in participating in a code sprint to get DLE finished and pulled into WET?  We've been hearing through the grape vine (Sylus) that there's pent-up demand for it and this was the best we could come up with to get it finished.

If you are interested, what would be the best date? (we were thinking early March).

**Comment by jamessauve** [comment]
YES!

**Comment by sylus** [comment]
Very excited about this code sprint :) Going to be awesome to get the DLE in!

**Comment by danielwashbrook** [comment]
Sounds like a great idea! Did anything come about with this? Is there a starting point we'd be working from or is this from scratch?

**Comment by joejoseph00** [comment]
Here's a couple of debugging tricks I used recently that might help out this code sprint.  
https://github.com/wet-boew/wet-boew-drupal/wiki/D%C3%A9bogage-des-requ%C3%AAtes-sql-avec-tcpdump
https://github.com/wet-boew/wet-boew-drupal/wiki/D%C3%A9bogage-en-d%C3%A9voilant-les-communications-entre-apache-et-drupal

Is this code sprint still in the todo list? 
Is there a date/time for the sprint?  I'd like to sneak out for a sprint.

**Comment by danielwashbrook** [comment]
I may have a client who's interested in contributing some of my time to this project. But I'm over on the west coast so physically being involved will be tough.

strace is a great suggestion! 

It seems like there might be two versions of this module floating around. One that's wrapped in the ottawa distro and the other is a feature that's about 6 months old. Does anyone have suggestions on which we should development against?

**Comment by strinh** [comment]
Hey everyone, sorry I've been silently absent.  Yes, it is still going on, but after the working group meeting last week, we've decided to switch  gears and go with secure syndication instead, something that is actually a little bit closer to fruition.  If you are interested, please let me know and I will add you to the invite.  If you don't get an invitation, please remind me!

Scheduled for April 5th at the University of Ottawa:

Code sprint for Secure Syndication / Synchronization

Activities
Development
-   Syndicating menus – 1 Developer
-   Syndicating files – 1 Developer
-   Syndicating panels – 1 Developer
  Documentation – 1 Documenter
  Enhancements – Remaining resources
  Testing – 1 Tester (Manual testing)

Total people needed 5.  Many more are welcome and can help with enhancements or we can try extreme programming by pairing people up.

Expected sprinter requirements:
-   Drupal development
-   Drupal patch creation
-   OO development
-   Access to GitHub
-   Knowledge of Acquia developer desktop
-   Your own laptop with Drush, GIT, preferred IDE (Netbeans) and Drupal Dev Desktop installed

Get prepared:

GitHub Source -
https://github.com/uottawa-wcms/secsyn
Download and familiarize yourself with the code please!

We are using Acquia Developer Desktop -
https://www.acquia.com/products-services/dev-desktop

• Read any documentation posted ahead of the sprint.
• Participate in any discussions ahead of the sprint.
• Contact sprint organizers and let them know you plan to participate.
• Read up on relevant issues in the GitHub issue queue.
• If you're not already familiar with it, learn how to apply patches. See http://drupal.org/patch/apply. This will be needed for testing.

Location:

University of Ottawa
1 Nicholas Suite 720J

Questions?  Call me at 613-562-5800 x 2836

**Comment by strinh** [comment]
Hey everyone, just a reminder that this is tomorrow afternoon.  I haven't heard anything from anyone yet (could be that the timing is real bad) but if you are interested, please let me know.  We have everything set up and ready to go and have 3 developers from uOttawa participating in the sprint.

**Comment by sylus** [comment]
I'd like to participate but am under the gun for actually having our deploy implementation live tomorrow. Is most of the work tomorrow related to content staging? I actually think we got this issue mostly solved please see: https://github.com/wet-boew/wet-boew-drupal/issues/820

I have support for most Drupal entities and everything is working great.

Where does Services + UUID + Deploy fall short to warrant another deploy implementation?

I think the only feature we still have to integrate is the encrypt module.

At the very least for sec syn should have an interface similar to ours:

![Deployment Interface Filled](https://f.cloud.github.com/assets/984304/337019/f279b6be-9cbb-11e2-8128-53e0a06cf960.png)

**Comment by joejoseph00** [comment]
@strinh   @sylus is a code machine!  So does that mean there's no need for a code sprint for this?  Or is there still going to be a code sprint to do other work?  I brought my laptop today.

**Comment by strinh** [comment]
Hey Joe, there's still a need.  We will be comparing notes next week with @sylus and worst case, there might be a merging of projects.  See you ... in like 2 minutes!

**Comment by joejoseph00** [comment]
I needed to find the notes I created on debugging , but the wiki is gone! :(

**Comment by joejoseph00** [comment]
I even tried the wayback machine, all I could see is the link and title of the link
https://github.com/wet-boew/wet-boew-drupal/wiki/Debugging-queries-with-tcpdump

Debugging

Debugging queries with tcpdump \* NEW
Debugging apache with strace \* NEW
