### ISSUE TITLE
Not able to change layout in a new content type

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#737]
In a today install and in admin/config/content/panelizer/node/my-content-type.page_manager/layout, the only  available layout is “Flexible”, althought the allowed content and layout are the same as standard Panels pages.

What going on?

**Comment by sylus** [comment]
It appears I was a little overzealous with some CSS settings. I will be doing a RC1a bug fix release in a day or so as Drupal.org has mentioned a few other fixes.

For now remove these lines in your code and flush all caches:

https://github.com/wet-boew/wet-boew-drupal/blob/master/modules/custom/wetkit_layouts/css/wetkit_layouts.css#L9-11

This should let you be able to switch categories. I think that is the problem?

**Comment by sylus** [comment]
Let me know if that fixed it and I push the fix right away.

**Comment by ssari** [comment]
It worked. Thank you.

**Comment by sylus** [comment]
Keeping open till fix is in place

**Comment by sylus** [comment]
Fix in v7.x-1.0-rc1-hotfix1
