### ISSUE TITLE
Notice: Undefined index: menu-wet-mid-footer

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#738]
I just got the following error message in a fresh install:

Error message
Notice: Undefined index: menu-wet-mid-footer in menu_tree_build() 
(line 304 of ...\profiles\wetkit\modules\contrib\menu_block\menu_block.module).

**Comment by sylus** [comment]
This occurs sporadically and goes away with a drush cache clear. Looks like a dependency install problem.

**Comment by sylus** [comment]
I don't see this error in the last few builds I have tried. Closing for now but please reopen if issue persists.
