### ISSUE TITLE
Problems with wetkit_migrate

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#739]
The links under “Example Pages” are mismatched. 

This is not a big deal just a head up in case the Migrate team did not noticed. 

The file migrate_default_content.xml seems fine, perhaps something wrong in migrate_default_content.inc. 

 I wish to be more helpful, but I’m still working to understand the Migrate module’s functionality.

**Comment by sylus** [comment]
Fix in v7.x-1.0-rc1-hotfix1
