### ISSUE TITLE
MultiSite Question

### ISSUE THREAD

**Issue by pclatney** [wet-boew/wet-boew-drupal#744]
We'd like to setup a multisite config with two sites using the WET distribution. So two databases but both sites using the the WET profile. Has anyone done this, any issues?

**Comment by RobJohnston** [comment]
I haven't done it with RC1, but have with a slightly older version (don't expect a difference).  Currently there are eight sites on our development sever sharing the same code but with different database.  See also issue #397.

**Comment by pclatney** [comment]
Thanks Rob

**Comment by sylus** [comment]
Stats is doing this with RC1 for about 5 sites now and no problems ^_^ We also use the deploy module as a content staging solution.

**Comment by pclatney** [comment]
Thanks sylus and Rob. I installed 3 sites and they seem to work fine. I am wondering what the best approach is for theming with a multisite config. We'll have slight differences in our design and need site specific CSS but other than that the sites are pretty much the same. What are your teams doing?

**Comment by RobJohnston** [comment]
@pclatney, We had the same situation here, in that a couple sites needed something just a little different or had site-specific CSS.  Sylus is really more of an expert, but I started here:  https://drupal.org/node/225125.  It seemed like a light-weight solution (in that it didn't require many new files).
