### ISSUE TITLE
Disable all multi-lingual options / build without French language support?

### ISSUE THREAD

**Issue by 3dluvr** [wet-boew/wet-boew-drupal#749]
This might sound counter to what this project's goals might be about, but not everyone has a bilingual requirements (ie. provincial and municipal levels) so I wonder is there a way to build a distribution without French language support?

At a first glance it seems that turning modules off post-install is not an ideal solution as some still linger and other integrations might be broken.

Perhaps a build switch or some configuration option that can do this would be great, or any other suggestion how can this be done would be appreciated.

**Comment by joejoseph00** [comment]
Why would you use this distribution if you didn't want multilingual?  Just use Drupal out of the box, it's a lot simpler, you can choose your language at installation time.  This Drupal distribution is all about bi-lingual/multilingual support.  If you want unilingual, stick to some other distribution.

**Comment by joejoseph00** [comment]
This distribution is well-suited for countries like Belgium, Switzerland, Canadas federal government, New Brunswick, certain parts of Ontario, Quebec, the European Union, the United Nations, the US Government (spanish/english) and other jurisdictions.  If you want unilingual English, check out the australian drupal distribution or some other distro, might be a good choice.

**Comment by 3dluvr** [comment]
Reason being is that this distribution has the accessibility compliance built in which is a requirement for the (municipal level) organization I work for. As we are not mandated to have bilingual services (English/French) it would only be creating additional overhead and could possibly affect the site's performance.

Obviously I could gut it out and/or take modules and patch things together, but I feel that might be a disservice to all the developers who have spent their time putting it together into a working package. And I really do not wish to invent hot water again...

**Comment by dwoods** [comment]
I work for a university in BC, and we started building an internal Drupal distribution based on Panopoly, and then started to look at this project as something we could possibly gain a lot from (and hopefully give some back to).  We would be developing a custom theme, but most of our ~250 sites that this would be deployed on do not require or want multilingual support.  Some sites, however, would want it (International programs), so solid multilingual support is beneficial, as long as it can be turned off (ie. I don't want /eng displayed in URLs for English-only sites).

I've tried disabling all i18n-related modules, but hit a dead end with some of the dependencies.

In the description of the project: 

"Development has been tailored for organizations that need to comply with standards for accessibility and bilingualism OR that simply need a distribution that allows them to get up and running quickly using a carefully curated selection of modules that can support common enterprise business requirements."

Aside from the accessibility standards compliance we require, we definitely fall onto the latter side of the OR.

I'm wondering if perhaps I'm barking up the wrong tree here, and asking for trouble by trying to utilitze WxT Drupal for a non-government website?

Any advice would be appreciated :)

**Comment by joejoseph00** [comment]
@3dluvr , there's a drupal camp tomorrow at the social sciences building UOttawa, the top Drupalers of the nation will be there today and tomorow.  keynote by Dries , you can have your questions answered there.

**Comment by 3dluvr** [comment]
Unfortunately, I found out about the camp too late to be able to attend... :(

Although, my question is directed to the developers of WET-Drupal specifically as I am hoping that this would be something doable without too much effort (ie. a configuration switch during build process?).

**Comment by sylus** [comment]
As the US is also interested in the work we are going to work on making the language requirements optional.

**Comment by joejoseph00** [comment]
As with any open-source, anyone can fork and do whatever they want.  But if they remove i18n it could create serious challenges pulling anything usefull from those forks.  

> > > William H notifications@github.com 2013-02-23 12:42 >>>

As the US is also interested in the work we are going to work on making the language requirements optional.

**Comment by 3dluvr** [comment]
@sylus I don't mean to be a pest, just wondering if you have any timeframes for when could this be addressed?

I am in the midst of a project where I'd like to use WET-Drupal but have a fairly fixed deadline in June so kinda short on time...

**Comment by sylus** [comment]
Hey sorry for the super late response. This is definitely on our roadmap but I can't see it being pushed along in the forseeable future.

**Comment by 3dluvr** [comment]
@sylus 

Thanks for the reply. I guess I'll have to find another solution in the mean time.

**Comment by sylus** [comment]
Closing this for now as don't see this on the horizon anytime soon.
