### ISSUE TITLE
Drupal.org - WET is now Live

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#751]
http://drupal.org/project/wet

**Comment by nrc-cnrc-web** [comment]
Congrats to @sylus (and everyone else who worked on this).

**Comment by ssari** [comment]
Bravo!!! Congratulations all people involved specially @sylus.

**Comment by xmacinfo** [comment]
Congratulations! Don't forget to promote a release for other to start downloading from Drupal.org and use the d.o. infrastructure to automatically build the WET distribution!

**Comment by DanMorand** [comment]
Any chance we'll see the release published on drupal.org today? We'd like to have it available for team members who've got the Acquia desktop dev installed and need to begin working on our WET-Drupal migration.

**Comment by StephenOTT** [comment]
@sinkinsona

**Comment by sinkinsona** [comment]
@DanMorand this is being worked on and should be available soon enough.  This being said you can still git clone and drush make / si to get up and going right away with distro.

**Comment by sinkinsona** [comment]
@DanMorand Just did a drush make of rc1 tonight and can share via dropbox if this helps you get started.

**Comment by DanMorand** [comment]
Thanks, if we end up needing that I'll get in touch. This is more so that team members (publishers for the most part) who are using the Acquia stack have a simple way to get WxT set up.

**Comment by StephenOTT** [comment]
@DanMorand the file @sinkinsona built can be directly imported in Dev Desktop.  (Settings>Sites>Import)

So its the perfect file for team members in the mean time.

**Comment by DanMorand** [comment]
Sounds good.  @sinkinsona can you post a link here for dropbox?

**Comment by sinkinsona** [comment]
@DanMorand if you provide me with your email I can share it with you.  You can post it here or click on my profile and send it to my email

**Comment by openplus** [comment]
@DanMorand  Did you ever get up and running?

**Comment by DanMorand** [comment]
@openplus I'm just getting my Dropbox account upgraded so I can download the distro as one package  - not much room on the free account.
