### ISSUE TITLE
Versioning strategies for sites based off wet-boew-drupal

### ISSUE THREAD

**Issue by jmk1ng** [wet-boew/wet-boew-drupal#752]
Just curious if there's a current best practice defined for sites based off the wet-boew-drupal install profile in terms of versioning, or if anyone else in the community has come up with a scheme internally that works for them that they'd like to share.

We were considering building off the wet-boew-drupal versioning scheme with something like 7.x pre-rc1 1.0. Our site is currently based off a pre-RC version, and the 1.0 would represent our implementation's specific version.

We also noticed that you went with a 7.x instead of actually referencing the version of core the install profile builds off of. We're about to do some core updates, and thought it might be useful to tag our versions with the version of core we're currently running. Is there an argument against that?

cc @sylus, @StephenOTT

**Comment by StephenOTT** [comment]
@sylus @sinkinsona 
Any comments you can provide??
