### ISSUE TITLE
Extending Wetkit Layouts 

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#753]
Since I couldn’t find a solution to export WetKit panel layout (issue #543), I extended the existing in wetkit\profiles\wetkit\themes\wetkit_adaptivetheme and declared in wetkit_adaptivetheme.info
  ; Panels Module layouts
  plugins[panels][layouts] = custom_panels

It seems that WetKit-rc1 no longer implement Panels Module layouts in the wetkit_adaptativetheme module. Instead, a new module wetkit_layouts (name = WetKit Panel Layouts) is developed with layouts defined in profiles\wetkit\modules\custom\wetkit_layouts\plugins\layouts. The layout names also changed (Implements core hooks for agov_layouts!!!)  :-(

Here is the question:
In this new structure, where should I declare my_layout when defining it in: 
1)  profiles\wetkit\modules\custom\wetkit_layouts\plugins\layouts\my_layout, or
2)  sites\all\modules\custom\my_module\pluging\layout

Thanks in advance.

**Comment by ssari** [comment]
Never mind. I found a workaround.
Thanks.

**Comment by Tikka** [comment]
What did you do? This was an interesting issue.

**Comment by ssari** [comment]
I copied person layout and rebuilt my template, which is available to be selected in admin/structure/panels/settings/panel-page.
However, it is not working properly and I got this message:

Warning: include(xx\wetkit/profiles/wetkit/modules/custom/wetkit_layouts/plugins/layouts/my-layout/my-layout.tpl.php) [function.include]: failed to open stream: No such file or directory in theme_render_template() (line 1495 of wetkit\includes\theme.inc).

So I'll review the template, and reopen the issue in case someone could help us.

**Comment by Tikka** [comment]
Thank you. Good to know this, and I am bookmarking this for later use @ssari

**Comment by sylus** [comment]
If you wish to add your own layouts I would do the following:

a) Create your own module (basing it off of wetkit_layouts). Be sure to declare ctools layout dependency:
https://github.com/wet-boew/wet-boew-drupal/blob/master/modules/custom/wetkit_layouts/wetkit_layouts.module#L11-15
b) Add whatever new layouts you want inside of plugins/layouts (just base it off of the examples in wetkit_layouts/plugins/layouts)
c) One you have your new layouts created flush the theme_registry and it should have been created.

To learn more bout ctools layouts go here: http://drupal.org/node/495654 

The above article describes how to use ctools layouts at length. ^_^
