### ISSUE TITLE
Permission issue: Translating taxonomy terms in localized vocabulary

### ISSUE THREAD

**Issue by eimhin** [wet-boew/wet-boew-drupal#754]
I'm running the latest build of WxT Drupal (Feb 14th) and receiving an access denied msg when I try to translate taxonomy terms in a localized vocabulary. I'm logged in as User 1, all multilingual modules are enabled, and translation permissions set. No additional third-party modules used beyond those included with WxT.

Set to localize translation mode. I'm using "Wetkit Categories" vocabulary as an example:
![localize](https://f.cloud.github.com/assets/1537226/181354/76efec32-7c4c-11e2-9456-cfa63fefa28f.gif)

Adding a term, click "Save and translate" :
![add-term](https://f.cloud.github.com/assets/1537226/181356/7df371b6-7c4c-11e2-9f93-c38e58bcecb4.gif)

The result:
![access-denied](https://f.cloud.github.com/assets/1537226/181357/8dbd7f10-7c4c-11e2-9a42-8cf7d06b1f01.gif)

I run into the same issue on multiple dev environments. 
Can anyone else reproduce this?

**Comment by RobJohnston** [comment]
Yes, I can reproduce it with that taxonomy and a new one just made up (with or without a descripton), but I have to change the editor to "Plain text" or else I'll also get a warning stating: 

"The string taxonomy:term:4302:description for textgroup taxonomy is not allowed for translation because of its text format".

**Comment by eimhin** [comment]
Hi Rob,
We got the same warning about the description field. In your multilingual settings, click on the strings tab and check off all text formats to make them translatable.

![trans-text-formats](https://f.cloud.github.com/assets/1537226/182365/d8ee7ada-7c6e-11e2-901d-1c28a68bb41f.gif)

**Comment by sylus** [comment]
Hey at the DrupalCamp session on Saturday there is a code sprint. I'd love to hear any issues that are experienced and we can fix them together!

**Comment by MaddyDaigle** [comment]
I was able to kind of fix this.  First of all, taxonomy needs to be checked under the Entity translation page in Configuration which it is not by default.  Localized taxonomy on it's own doesn't seem to work if Entity translation isn't enabled anymore,  there is no translate tab and an access denied issue is displayed as Eimhin depicted above.  Unfortunately I haven't been able to figure out why this is happening yet. Once this is done, if you try and translate a taxonomy term there is still a problem:  the taxonomy title is not translatable (under "operations" in the translate taxonomy page you will see "No translatable fields".) Just go into that vocabulary > Manage fields. Modify the name field for taxonomy by clicking "replace under operations".  This will replace it with a text field and should fix the issue.

**Comment by MaddyDaigle** [comment]
Just wondering:  Should we move on with using entity translation for taxonomy or is this actually a bug that needs to be fixed?  Is it the intent of Drupal WET to just use entity translation now?

**Comment by Tikka** [comment]
Thank you for this @MaddyDaigle.

**Comment by sylus** [comment]
Yeah thinking lets just enable Taxonomy for ET as we are slowly letting ET take over everything. Next up is node translation once the use case has been confirmed via Health

**Comment by auxonic** [comment]
Glad to find this discussion.. strange default settings in the current version related to taxonomies.  I've a solid background in Drupal but just started on a project based around WET.

I had to turn on Entity translations for Taxonomies.  The taxonomies are set to "No multilingual options" which seems to have the same effect as the normal "localize" options.  I then added a field and that allowed me to translate the taxonomy item without getting the permission error.

**Comment by WebBeest** [comment]
I've had the same problem with this error (not with this distribution btw); with entity_translation enabled, the access is defined by "entity_translation_tab_access"; this states that the source of the taxonomy term can't be LANGUAGE_NONE. That was the problem for me.
