### ISSUE TITLE
Page Manager Layouts issue

### ISSUE THREAD

**Issue by MaddyDaigle** [wet-boew/wet-boew-drupal#759]
Just thought I'd point this out since I haven't been able to figure out why this is occurring.
I'm trying to create a new panel variant under the node_view page.  When I get to the Choose Layout section of the configuration, I only get "AT Responsive Panels - 1 column" as an option.  There is no way to toggle through categories.

https://github.com/MaddyDaigle/Wiki_Images/raw/master/page-manager-issue.png

I tested this on simplytest.me (not sure which version of wet-drupal is on there) and it seems to work.. so I'm unsure if it's been recently fixed or a recent bug.

**Comment by sylus** [comment]
This has been fixed recently it actually is a css style setting form item categories to display:none

**Comment by MaddyDaigle** [comment]
Ahhhh thanks! :)
