### ISSUE TITLE
Sauce Labs Integration + Travis

### ISSUE THREAD

**Issue by patcon** [wet-boew/wet-boew-drupal#760]
@sylus Couldn't find any mention of this in the queues, but I thought you showed me a working version of the sauce labs interface -- just can't find it now :)

**Comment by patcon** [comment]
(For anyone else reading this, followup with Wil indicated that he hadn't actually got it working yet.)

Juuuuust got it working earlier tonight:
https://github.com/myplanetdigital/drupal-skeletor/blob/master/.travis.yml
https://travis-ci.org/myplanetdigital/drupal-skeletor/builds/5488826
https://saucelabs.com/tests/17612018c0804de38aca8ca0e7864159

The test fails, as I was just using the tests from the demo, but it still served the page from travis.

I'm going to be working at creating a travis cookbook that makes sauce-connect setup much simpler than it is now, if the maintainers think it's worthwhile:
https://github.com/travis-ci/travis-cookbooks/tree/master/ci_environment

cc: @michaelklishin @loicfrering @joshk @roidrage

**Comment by joshk** [comment]
Can you hold off for a day, I have been talking to saucelabs about this and have some great news to share. 

I'm out and about tonight, but will update this ticket a little later when I am back. 

High 5 

Josh

**Comment by patcon** [comment]
woooo! :+1:

EDIT: Oh hey... Guessing this is related :)
https://gist.github.com/santiycr/5139565#file-sauce_connect_setup-sh-L9-L11

**Comment by nschonni** [comment]
This might help too http://sauceio.com/index.php/2013/03/building-a-ci-system-using-selenium-builder-github-travis-and-sauce-labs/

**Comment by StephenOTT** [comment]
Did anything come of this?

**Comment by roidrage** [comment]
@StephenOTT sorry for not keeping this up-to-date. This is probably what came out of all this: http://about.travis-ci.org/docs/user/addons/#Sauce-Connect

**Comment by sylus** [comment]
Thinking this is not going to happen, willing to take a PR but for now closing.
