### ISSUE TITLE
can't create custom beans 

### ISSUE THREAD

**Issue by mxlav** [wet-boew/wet-boew-drupal#761]
1. Created a new block type, no fields 
2. go to content/blocks/add, enter stuff, save

get error

Fatal error: Allowed memory size of 205520896 bytes exhausted (tried to allocate 261900 bytes) in /Sites/rc1/includes/common.inc on line 120

trying to edit or delete the block afterward will generate the same error

**Comment by sylus** [comment]
I think your memory_limit is only 196MB.

Increasing it to 256MB should fix this problem.

You should be fine at 196MB but guess something is up. I will take a look at this with xhprof in coming weeks.
