### ISSUE TITLE
Best practices for WxT-Drupal regarding custom CSS and custom HTML

### ISSUE THREAD

**Issue by nrc-cnrc-web** [wet-boew/wet-boew-drupal#764]
Hi,

Please forgive my lack of knowledge (complete Drupal noob), but I was wondering with regards to WxT-Drupal specifically:
1. Is there a ideal way to include a link to a custom stylesheet in all pages of a site?
2. Is there an ideal way to customize the HTML output that is generated by Panels?

I've read about ways to do each of these, but was hoping for advice from someone using this distro who has actually implemented customizations in either/both of these areas.

Cheers!

**Comment by mxlav** [comment]
I've been defining any new css via a subtheme, takes about 3 minutes to setup once you get the hang of it

http://drupal.org/node/225125

point your subtheme to base theme  = wetkit_adaptivetheme and define your css within your sub theme folder

**Comment by nrc-cnrc-web** [comment]
That was not one of the ways I'd read about to define new CSS, and it sounds much easier and safer to do.
Thank you kindly!  :-)

**Comment by mxlav** [comment]
This is the best way to do it if you don't want to modify the wetkit theme, to avoid conflicts when WET changes.

Once you've sub-themed, you can look at using custom templates if you want to customize the html.

**Comment by nrc-cnrc-web** [comment]
Sick! Man, I've got _lots_ to learn!
That's exactly what I wanted to do (avoid conflicts).
Thanks again!!
