### ISSUE TITLE
Add scrutinizer-ci support for static code analysis

### ISSUE THREAD

**Issue by patcon** [wet-boew/wet-boew-drupal#774]
Just heard about this tonight. Still playin around with it.
https://scrutinizer-ci.com

**Comment by patcon** [comment]
Whoa. Cool! Apparently it can _submit_ pull requests with coding style fixes :)

**Comment by sylus** [comment]
Oh that is awesome. Is there a repo you can point me to that your testing this out with? Will definitely include this!

**Comment by patcon** [comment]
Right on. Just added the simplest of files, and haven't toyed with it past that -- I don't think it's working for me yet :)
https://github.com/myplanetdigital/drupal-skeletor/blob/master/.scrutinizer.yml
https://scrutinizer-ci.com/g/myplanetdigital/drupal-skeletor/inspections

If you go to the site's main page, there's a rolling list of the analysis runs that have completed, so I'd check those out. And no badges yet, as far as I can tell :(

**Comment by jakoch** [comment]
The badges arrived https://scrutinizer-ci.com/blog/badges-for-your-repositories
Code Quality Metrics, too :)

**Comment by sylus** [comment]
Woot added and using scrutinizr for our code commits.
