### ISSUE TITLE
Question: Wxt-Drupal and the Subscriptions module

### ISSUE THREAD

**Issue by nrc-cnrc-web** [wet-boew/wet-boew-drupal#775]
Hi. This is very likely a lack of understanding on my part, but I'm trying to get the Subscriptions module working and I've been unable to, so I was hoping someone here might have a suggestion or 2. I've followed the instructions to set it up, but the "Subscribe" options that are supposed to appear do not.

I've tried the module with a fresh install of Acquia Drupal (not this distro) and the options show up at the bottom of each page. Is there something in this distro that is suppressing the display of the Subscribe options? Or perhaps an option in this distro that must be enabled/disabled, which doesn't exist in Acquia Drupal?

**Comment by joel-osc** [comment]
Can you provide more information about your config? I would be interested in knowing whether or not you have added the subscriptions form in panels and whether or not your Acqui test was a panelled node.

**Comment by nrc-cnrc-web** [comment]
Acquia site: I did pretty much nothing. I installed the module itself and the mail_edit module (because it's required) and enabled them both. I left the default config settings as-is. Panels module was not installed.

Wxt-Drupal site: I did the same as above, and also went into Blocks and enabled the Subscriptions interface for the Main content section. I then went into Panelizer (which is where, I just realized, my problem may lie) and added the "Subscriptions interface" block to my content (right between "node content" and "node updated").

However, I just noticed that the settings are not being saved. I found it odd that in Panelizer I now have to add content to the "Top (conditional)" section and then move it to the Content section (because the gear is locked in the content section). But that might explain at least part of my troubles?

**Comment by sylus** [comment]
Hmm not sure panelizer is the route you want to go for this. Panelizer is for unique layouts for each page. It looks like you just want to use panels itself if I understand correctly.

Please refer to this documentation for the difference between panelizer and panels and when to use each. (Steps 1-5): http://drupal.org/node/1704266

**Comment by nrc-cnrc-web** [comment]
Fantastic - thanks very much for that!
