### ISSUE TITLE
Megamenu misbehaving

### ISSUE THREAD

**Issue by nrc-cnrc-web** [wet-boew/wet-boew-drupal#776]
Hi,

We are experiencing some strangeness with the mega menu. If we create a new page and add a menu link (with <Mega Menu> as the parent), then create another new page with a menu link (using the previous page we just created as the parent), it puts the link to the last page in the wrong part of the mega menu (ie: it ends up a child of another section). It also adds an extra ul tag in front of itself, so the display is off and the page doesn't validate.

Has anyone else noticed this happening?

**Comment by sylus** [comment]
Could be a dupe of #771

However I haven't had any problems with mega menu so not sure what is going on.

Can you attach some pictures and a step by step guide of how to reproduce.

Really want to get these menu issues fixed once and for all :P

**Comment by nrc-cnrc-web** [comment]
Don't think it's a dupe. And for sure - I'll write up exactly what I did, with some screen caps and post back here this afternoon.

**Comment by nrc-cnrc-web** [comment]
OK, so I created a new basic page called "Forum test". I opted to add a menu link during creation, and set it to be a child of "Home". I then created another basic page called "Test", and created a menu link again with "Home" as the parent.

This image shows the result of that. Seems the mega menu doesn't associate those links with the correct parent (while they are fine in the secondary navigation).

![megamenu-vs-secnav](https://f.cloud.github.com/assets/2982689/233862/ff2aae0a-8761-11e2-99aa-db372e911972.jpg)

**Comment by Phr34ks0w** [comment]
This issue is also happening with my 4 Drupal WxT instance running on my Win2k8 server. I also have a call open #758 for a similar issue with the mega menu.

I have notice that if I create from scratch a new parent item with children, the children will display under another parent. But if I rename an existing demo template parent or child to whatever I want, it will behave properly.

I don't know if this helps a bit or make things worst, but that's what's going on in my case. Very similar anyway.
Thanks

**Comment by dlanglois** [comment]
We are hoping to launch a new website next week that uses the latest WetKit distro, and this issue is a huge showstopper for us.We would really appreciate a prompt resolution. Thank you.

**Comment by sylus** [comment]
Have enough to go on now will take a look at this tonight. Thanks for the detailed walkthrough it definitely assists.

**Comment by sylus** [comment]
Able to reproduce and know where the code is failing. Will do my best to fix as soon as possible.

**Comment by dlanglois** [comment]
Thank you very much. We will test it as soon as you have a fix.

**Comment by sylus** [comment]
Hey I have this fixed and will release RC2 over the weekend. I basically had to rewrite the whole mega menu system but think should fix most of the problems.

Documentation on how to use will also be forthcoming this weekend.

On Monday I'd appreciate a review once RC2 is released.

**Comment by dlanglois** [comment]
That's great news! We will review it on Monday for sure. Thank you for your help!

**Comment by nrc-cnrc-web** [comment]
Hi.

@dlanglois has updated those files at our end, but there now seems to be a problem with the mega menu in IE. Screen cap below. If you need a screen cap of the mega menu link administration page as well, I will try to get that for you tomorrow.

![conceirge-mega-menu](https://f.cloud.github.com/assets/2982689/250485/9971eae0-8b4b-11e2-925e-ae1a1fc635ca.jpg)

**Comment by sylus** [comment]
Hey this is working now but steps need to be done for the upgrade. As a quick test can you boot up a fresh install and evaluate? Once you confirm it works I will release RC2.

The upgrade itself also requires documentation as you need to make "fake" menu items to make it work using <span> and <group> as evidenced by the new build. There is also a button in wetkit wetboew settings that allows you to recreate the menu.

**Comment by nrc-cnrc-web** [comment]
Thank you kindly! I will download and install it this morning, and let you know.

What do you mean by "fake" menu items?

**Comment by nrc-cnrc-web** [comment]
Fresh install, with 2 pages added: 1 (Test) is child of Mega Menu, other is child of Test.
Browser is IE 9.0.8112 on 64-bit Windows 7 Pro SP1 workstation.

![wxt-drupal-pre-rc2](https://f.cloud.github.com/assets/2982689/255494/1c18825c-8c0e-11e2-8cbf-1e46f9ff55e7.jpg)

**Comment by sylus** [comment]
On initial install did the menu look proper and only when you added the menu items did it break?

I am thinking you are not leveraging the 'group' and 'separator' menu items.

Unfortunately these special menu items have to be added manually based on certain conditions to prevent the menu from going bonkers.

Just let me know if initial install looked good and I can explain how the megamenu should be structured.

**Comment by nrc-cnrc-web** [comment]
After a fresh install (but before adding any menu items) it worked. It was after I added items that it didn't.

I added the menu items during content creation, not from the mega menu administration page. I'll do a fresh install on my laptop at home tonight and try it out using the "span" and "group" separators that are there, and will post back with the results later tonight.

Thanks!

**Comment by nrc-cnrc-web** [comment]
Sounds good, thanks. I think I have an idea how they are supposed to work, as I had to build something to do this for our CMS (TeamSite). But I won't say no to guidance, especially when it comes to Drupal!  :-)

**Comment by nrc-cnrc-web** [comment]
Tried it with the separators and it worked great. The display issues in IE 9 are gone. The HTML validated as well. Thanks again!

![mega-menu](https://f.cloud.github.com/assets/2982689/257149/2ff538da-8c48-11e2-818f-b60033b06430.jpg)

![mega-menu-admin](https://f.cloud.github.com/assets/2982689/257150/34acf3a4-8c48-11e2-8161-1cc4df4091e4.jpg)

**Comment by Phr34ks0w** [comment]
Hi  @nrc-cnrc-web, I'm curious, what did you specify behind the span item? 

Hi @sylus , are you saying to create the menu items with the mega menu admin and not from the add new content > add menu item?

Thanks

**Comment by nrc-cnrc-web** [comment]
The span item's path should be `<separator>`.

I think, since the spans are required for the layout of the mega menu, as long as you have them in place before you add your content you should still be able to add a link during content creation, as they'll appear in the drop-down.

**Comment by Phr34ks0w** [comment]
OK, thanks, I will try this.

I have an off topic question. How do one modify the "Sub Site Name" label on the Intranet theme? I know how to modify the main site name in the site information admin section but I don't see anything anywhere for the Sub Site name and I have search everywhere. Again, sorry for the off topic question.

Thanks

**Comment by sylus** [comment]
Hey for no links you can also use <nolink> in the path and will only render without the ahref though I think I need to do more testing wth this. As for the menu in the node add page I hope to extend it so can take an option to include span if needed.

As for changing the sitename go to: Appeareance -> WetKit AdaptiveTheme -> Intranet Settings and change it there.

**Comment by nrc-cnrc-web** [comment]
One problem we just noticed here: if you create a page and link it to a 3rd level menu item, its parents do not show up in the breadcrumb. Is there a setting to configure the breadcrumb to display the ancestors? Or is this a bug?

If you'd like me to close this ticket and start a new one pertaining to breadcrumb only, please let me know.

**Comment by mxlav** [comment]
Probably need to use Path Breadcrumbs. It has a UI similar to Panels.

**Comment by sylus** [comment]
Yeah this is a use case for path breadcrumbs (which is the coolest module ever) take a look at the node view.

**Comment by nrc-cnrc-web** [comment]
Thanks guys! From what I've read about it (including a feature request for path breadcrumbs: http://drupal.org/node/1823030), seems it's not able to create a breadcrumb based on the node's place within the menu. I'll do some reading and playing around to figure out how to make it do what I want.

Since breadcrumbs are to be set up to be handled during implementation phase (and not OOTB), they are not an issue and I'm closing this ticket. All questions have been answered and the mega menu is working great now.

Thanks again. Cheers!

**Comment by sylus** [comment]
You can create a custom token for menus and that will be found by path breadcrumbs as a solution ^_^

**Comment by nrc-cnrc-web** [comment]
Thanks for the tip! I'll give that a whirl.   :-)

**Comment by sylus** [comment]
If you have the time can open a ticket for the path breadcrumb + menus issue. I know someone working on that problem at the very moment. @joel-osc
