### ISSUE TITLE
Drupal WET Working Group Meeting - March 22, 2013, 1 to 4pm

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#778]
next working group meeting on March 22, 2013 1 to 4pm.

More details to come

**Comment by StephenOTT** [comment]
Next working group meeting is being Scheduled for March 22, 2013 - 1pm to 4pm, at Ottawa City Hall in the Colonel By Room (Second Floor, south end of building - Across from the stairs).

**There will be Webex and Teleconference available for anyone that cannot attend in person**

If you would like to see a agenda item discussed please post it below

I have also sent out a Meeting Invite, if you would like to receive this please email me at stephen.russett@ottawa.ca and I would be happy to forward you the invite.

### Webex and Teleconf Details:

Meeting Number: 735 039 804
Meeting Password: Drupal

https://cityofottawa.webex.com/cityofottawa/j.php?J=735039804&PW=NMGNjNzY4YzUz

Teleconference information:
Call-in toll-free number: 1-8667979099  (Canada)
Call-in number: 1-6137875142  (Canada)
Attendee access code: 436 898 7

### Agenda:

May not occur in this order.
1. Drupal.org Distro update
2. Drupal Camp Review
3. Web Renewal
4. Joint GTech Nomination for WET-Drupal (Joint with Who? WET and Drupal WET?)
5. Deployment
6. Use Case/Demo of Tool (Lee Hunter)

Mentioning everyone that has signed up at the Events Page:
https://github.com/wet-boew/wet-boew-drupal/wiki/WxT-Drupal-Working-Group

@sinkinsona
@StephenOTT
@csedev
@openplus
@thriuin
@sylus
@jeffdavidgordon
@leehunter
@dsamojlenko
@kavinay
@sboots
@eleclerc
@joejoseph00
@finweb
@liquidcms
@wilroboly
@colans
@mgifford
@lmichaud
@PatGilbert
@patcon
@Michel-Gendron
@wolkyd
@dergachev
@mxlav
@ericvong
@jamesson
@strinh
@bmiller72ca
@theadbo
@Pacoup
@jamessauve
@erarcham
@ssari
@marcmcd
@eimhin
@MaddyDaigle
@gleger
@nadinecz
@minorOffense
@crawleyde

**Comment by StephenOTT** [comment]
Retyping the follow because fo a typo
@minorOffense
@crawleyde

**Comment by StephenOTT** [comment]
@sboots
@eleclerc
@joejoseph00
@finweb
@liquidcms
@wilroboly
@colans
@mgifford
@lmichaud
@PatGilbert

**Comment by StephenOTT** [comment]
@patcon
@Michel-Gendron
@wolkyd
@dergachev
@mxlav
@ericvong
@jamesson
@strinh
@bmiller72ca
@theadbo
@Pacoup

**Comment by StephenOTT** [comment]
@jamessauve
@erarcham
@ssari
@marcmcd
@eimhin
@MaddyDaigle
@gleger
@nadinecz
@minorOffense
@crawleyde

**Comment by StephenOTT** [comment]
@wolkyd

**Comment by StephenOTT** [comment]
There will be Webex and Teleconference available

**Comment by StephenOTT** [comment]
Updated post above with a Webex and Telecof details

**Comment by StephenOTT** [comment]
Updated with Agenda information

**Comment by StephenOTT** [comment]
@xmacinfo
@nrc-cnrc-web
@kvantomme

Added new names that were posted to Signup wiki for working group

**Comment by sylus** [comment]
Closing this as is a old issue and easier to use wiki.drupalwxt.org to provide meeting information.
