### ISSUE TITLE
Thoughts on the Asset Module??

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#781]
http://drupal.org/project/asset

**Comment by StephenOTT** [comment]
@sylus @joel-osc @mgifford

**Comment by mgifford** [comment]
More info is always useful.  We haven't looked at it, but if you look at the stats of current installs:
Reported installs: 335 sites currently report using this module. 
Downloads: 12,096

and compare it with http://drupal.org/project/media

**Comment by sylus** [comment]
Looks like an interesting module for sure, but would need to be extensively tested. File Entity which is similar and driven by API first has 276,000 compared to 12,000
