### ISSUE TITLE
Mega menu still not working in IE8 or 9 after fresh install from master

### ISSUE THREAD

**Issue by Phr34ks0w** [wet-boew/wet-boew-drupal#782]
Don't want to rain on your parade but the mega menu is still not working properly for me in IE8 or 9. This is after a fresh install from last night's cloned master (15/03/2013). BUT, it looks perfect in FF19 (Firefox). Am I doing something wrong?!?!? 

See pics...

![admin_menu](https://f.cloud.github.com/assets/2170704/264005/c9112fee-8d81-11e2-8c09-32dbfbdf754a.JPG)
![IE8_menu](https://f.cloud.github.com/assets/2170704/264008/d2f812ac-8d81-11e2-8199-02417a28cc93.JPG)

**Comment by Phr34ks0w** [comment]
Also, I have noticed that the menu parents click event will change from what specified in the menu admin settings to /eng# (all of them).

Ex:
If we look at the screenshot example in my previous message, the parents menu items "Home", "Chief Administrator" and "Courts" all point to /eng# in the browser (IE and FF). If I look at the settings, for example, the "Home" path is set to &lt;front&gt;, the "Chief Admin." is pointing to node/7 and "Courts" is pointing to node/9. But, they finally all point to e.g. http://server_name:8084/eng#. 

![parent_links](https://f.cloud.github.com/assets/2170704/264219/c4d8aa1e-8d87-11e2-9a94-450c65a860ee.JPG)

**Comment by sylus** [comment]
Your megamenu is not configured properly. Spans should be part of every section but I don't see it for your first tab. Can you do a fresh install and show me without touching the megamenu that it isn't working?

**Comment by Phr34ks0w** [comment]
Ok, so to put this clear, this is how it should look in the menu layout:

Home (e.g. path = http://drupal.org or &lt;front&gt; )

&gt;span (e.g. path = &lt;separator&gt;)
&gt;&gt;Welcome (e.g. path = http://drupal.org or &lt;front&gt; )
&gt;&gt;&gt;About Site (e.g. path = http://drupal.org or. node/41)

&gt;span (path = &lt;separator&gt;)
&gt;&gt;News (e.g. http://news_page.html or node/23)
&gt;&gt;&gt;Today's news (http://drupal.org or node/15)
&gt;&gt;&gt;Yesterday's news (http://drupal.org or node/25)

Courts (e.g. path = http://drupal.org or node/66 )

&gt;span (e.g. path = &lt;separator&gt;)
&gt;&gt;Federal Court of Appeal (e.g. path = http://drupal.org or node/44 )
&gt;&gt;&gt;Judges (e.g. path = http://drupal.org or node/33 )
etc etc

Should I be worried about the weight option when creating a new parent or child object?

**Comment by Phr34ks0w** [comment]
Ok, I did a fresh install and it seems to be code 18 error (problem is 18 inch in front of the screen ;0) ) I must be breaking it when creating/altering the menu. I guess I need some training on how to setup and manage the Drupal menu system. Because it's working fine in both IE8-9 and FF.

Like I said in my previous message (above), should it be laid out like that?

Automatically, the span &lt;separator&gt;  tells Drupal that this is a section or block of links like &lt;ul&gt; with a bunch of &lt;li&gt; within?

So I taken that it's normal that the parent main menu items are setup with &#35; sign? They are not meant for clicking but just hovering to open up and show the sub items?

Thanks

**Comment by Phr34ks0w** [comment]
Why is the &lt;group&gt; only use in the Drupal WCMS section and nowhere else in the entire mega menu?

My logic tells me that &lt;group&gt; tells Drupal that this is a group of objects but why is it not use everywhere in the demo menu? Or Am I mistaken? That &lt;group&gt; doesn't mean what I think it means.

Sorry if I sound so noob, but I don't know Drupal that welll except for the bits and pieces of trial and error in the last 2-3 months.

Thanks

**Comment by nrc-cnrc-web** [comment]
If you put your menu together as you listed it in your post from 2 hours ago, it will not work, and will look like this:

![mega-menu-1](https://f.cloud.github.com/assets/2982689/264940/a48c75b0-8da0-11e2-8733-6401a5ecfaa3.jpg)

![mega-menu-admin-1](https://f.cloud.github.com/assets/2982689/264941/a77bd806-8da0-11e2-855d-f5d556cd00b8.jpg)

I would recommend trying something more like this:

![mega-menu-2](https://f.cloud.github.com/assets/2982689/265001/a4607aae-8da1-11e2-8168-533d9d44012f.jpg)

![mega-menu-admin-2](https://f.cloud.github.com/assets/2982689/265002/aa5e9418-8da1-11e2-84e2-8d1e19e2debe.jpg)

**Comment by nrc-cnrc-web** [comment]
IMO, unless you are required to have that "Home" button in your topnav and leftnav, I'd remove it completely. The breadcrumb and the site name both link to Home anyways.

I'd create the menu like this (just a suggestion though); note the use of group to output "About site" as a "top-level" item, thus correctly display as the same level as "News":

![mega-menu-suggestion](https://f.cloud.github.com/assets/2982689/265124/754fa844-8da5-11e2-9c62-c3842f0621b4.jpg)

![mega-menu-admin-suggestion](https://f.cloud.github.com/assets/2982689/265125/795a64f6-8da5-11e2-90b2-19c7d7bb5268.jpg)

**Comment by Phr34ks0w** [comment]
Yea, I finally understand the layout system now. I'm changing the menu in my new testing Drupal instance as we speak (sorta) and it's looking mighty fine ;) Thank you

The only thing now is... like I said earlier, are the main or parent items suppose to be clickable?  

"<em>So I taken that it's normal that the parent main menu items are setup with # sign? They are not meant for clicking but just hovering to open up and show the sub items?</em>"

![parent_links](https://f.cloud.github.com/assets/2170704/265122/72711a40-8da5-11e2-87c5-a3d0a3a400cb.JPG)

**Comment by nrc-cnrc-web** [comment]
No, those items are not supposed to go anywhere when you click them. A hover/click/keypress to activate them should expand/collapse the menu; the link to the top-level page is at the bottom ("Chief Administrator - Main Page").

**Comment by Phr34ks0w** [comment]
ok, that's what I wanted to hear. Thank you

Everything is fine then :)

Closing call
