### ISSUE TITLE
Getting Path breadcrumbs to work with menus

### ISSUE THREAD

**Issue by nrc-cnrc-web** [wet-boew/wet-boew-drupal#783]
As mentioned in #776, ticket opened to address the issue of getting Path breadcrumbs to work with menus.

**Comment by mrochette** [comment]
Got Path breadcrumbs to work with the menus.  Had to tweak the selection rules to include the URL path of the parent categories

Home > Administration > Structure Path breadcrumbs > Selection Rules
String: URL path    Current path type is one of "YourPathsHere"
