### ISSUE TITLE
Broken Media Widget

### ISSUE THREAD

**Issue by pclatney** [wet-boew/wet-boew-drupal#784]
Has anyone experienced problems with the media upload widget when using it from the WYSIWYG editor? The layout is broken and I can't upload files or select files from the library.

![broken_media_widget](https://f.cloud.github.com/assets/2363196/265089/8911df74-8da4-11e2-9afa-5644fe286141.gif)

**Comment by sylus** [comment]
This looks like jQuery UI is not being properly loaded.

Unfortunately I am not able to reproduce but could be because have fixed this problem unintentionally. Likely RC2 when it is released will fix this problem for u.

**Comment by MikeDucharme** [comment]
I'm experiencing a similar problem. @sylus What is "RC2". Is it "Release Candidate 2"? If so, how does that fit into your naming conventions since we're currently at 7.x-1.x?

_EDIT_ Nevermind. Found the tags:

```
$ git tag
v7.x-1.0-rc1
v7.x-1.0-rc1-hotfix1
```

**Comment by sylus** [comment]
Closing old issues.
