### ISSUE TITLE
WET v3.1 new Feature Branch

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#790]
Wanted to keep everyone aware that work has been nearly done in supporting the new version of WET v3.1. For anyone that is curious and particularly for people who don't want government branding please take a look.

All of the work is being done currently on the feature-wet-v3.1 branch and integrates with the WET 3.1 library. Two new themes have been added WET and BASE.

You will have to use the feature-wet-v3.1 branch and change the build-wetkit.make with the latest revision from that branch to get this to work.

**Comment by sylus** [comment]
http://sandbox.openplus.ca/

**Comment by sylus** [comment]
Steps to test:

a) git clone -b feature-wet-v3.1 https://github.com/wet-boew/wet-boew-drupal.git
b) edit build-wetkit.make and replace master with latest revision sha for feature-wet-v3.1 branch:
projects[wetkit][download][revision] = 6c0f9335f6cda574a6520775206380ff04e35595
c) continue normal build process specified in readme.md

**Comment by sylus** [comment]
@pjackson28 @LaurentGoderre 

I noticed a few minor things on sandbox.openplus.ca

Should I open a new ticket or wait till a new release for wet v3.1 in case were fixed? We are currently using:  
v3.1.0-b2-dist

**Comment by pjackson28** [comment]
You should first try to reproduce on the live working examples. If you can still reproduce then please open one or more tickets.
