### ISSUE TITLE
NGINX + PHP-FPM + MySQL + APC  words of advice?

### ISSUE THREAD

**Issue by TheDuke13** [wet-boew/wet-boew-drupal#797]
Hi all,

Thought I'd drop in and see if anyone out there is using a similar stack (NGINX + PHP-FPM + MySQL + APC), and if so: 

Would you have any suggestions on optimizations we should be looking at? We've worked out a nginx config using this: http://wiki.nginx.org/Drupal

Now we're looking around to see if anyone has any words of wisdom to share.

Thanks!

Carl

**Comment by sylus** [comment]
You could check out the high performance group on D.O.
