### ISSUE TITLE
Departmental Theme Redistribution

### ISSUE THREAD

**Issue by irwink** [wet-boew/wet-boew-drupal#799]
Is there or will there be documentation describing how a departmental theme can be packaged and redistributed within a department ?  

In PWGSC my team takes the WET template package for static sites and adds in the common departmental navigation elements (e.g. Site title, mega menu, site footer links) then packages it up for use by all sites and applications within the department.  We also take care of packaging a particular version of the WET template release (e.g. 3.0.5).

We would have to do a similar function for the Drupal-WET based sites, we need to control the exact Durpal-WET version and add in the departmental navigation elements.  Once we do this, which is something I would expect many departments would also have to do, how could this be redistributed within the department.  All the existing installation and setup instructions use github as the source repository.

**Comment by sylus** [comment]
I would just create a subtheme for wetkit adaptivetheme and make your changes in that theme. This was done with Health Canada that had particular customizations they needed.
