### ISSUE TITLE
Toggle Display of Site Name broken?

### ISSUE THREAD

**Issue by d-shields** [wet-boew/wet-boew-drupal#801]
From what I can tell in page--panels--wet.tpl.php, the logic is there to toggle the $site_name from the UI, but it doesn't seem to work when Site Name is unchecked.
The $site_slogan toggle works perfectly and the code looks much the same, so I'm not sure what the issue could be.
It does work if I hack in an if statement for $hide_site_name, but I don't think that should be required - should it?

**Comment by sylus** [comment]
Can you submit a pull request for the code improvement? :)
