### ISSUE TITLE
Wetkit Tabbed Interface - problems to change style

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#807]
I couldn't change the style in a tabbed interface of the Wetkit rc1 version. The "pane style" admin view doesn't allow me to select any of the settings, consequently it doesn't go next to select the styles.

The same is happening in a fresh install of the Wetkit (master), but not in the feature-wet-v3.1 version, please see the image attached.

How can I fix it in my implementation of the Wetkit 7.x-1.0-rc1 ?

Thanks.

![tabbed-inteface-style](https://f.cloud.github.com/assets/1461809/317520/4ed9d538-9875-11e2-915a-7f62fb28c2cd.png)

**Comment by sylus** [comment]
Closing as has been refactored.
