### ISSUE TITLE
Notice: Create New Bean blocks should have a replaced Title Field

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#809]
Reference to: http://drupal.org/node/1954126

If you create a new Bean block type and do not replace the title field with a entity field you will get a fatal memory error.

Following the instructions in: http://drupal.org/node/1954126 will resolve the issue.

This should be known to anyone that is create Bean block types.

**Comment by mxlav** [comment]
Cool, I also had encountered this (in this issue ticket https://github.com/wet-boew/wet-boew-drupal/issues/761) ...but you did better research than I did :-)

**Comment by sylus** [comment]
Fixed upsteam.
