### ISSUE TITLE
Wetkit Demo content still present after disabling the module.

### ISSUE THREAD

**Issue by MikeDucharme** [wet-boew/wet-boew-drupal#813]
I wanted to wipe out the demo content so I disabled the wetkit_demo module but all of the menu items and blocks are still present.

Branch: remotes/origin/feature-wet-v3.1

**Comment by RobJohnston** [comment]
I've been away for a while and I'm guessing here, but I think that you should have disabled the wetkit_migrate module, as this is what brings in content near the end of the installation.

**Comment by sylus** [comment]
You shouldn't really disable wetkit_demo although it wouldn't hurt I don't think. If you wanted to remove the default content and menu items (currently only megamenu) you can just rollback the migrate scripts @ http://wxt-drupal:8082/eng/admin/content/migrate

Unfortunately there is no logic to roll back the default beans.

**Comment by RobJohnston** [comment]
@sylus, for what it's worth, I'm doing concurrent installs right now on mysql and postgresql and I just noticed that the postgres Web install doesn't have the "Import Content" stage after the "Import French Language" step.  I don't plan on investigating this... just thought I'd mention it to you somewhere and here seems (almost) appropriate.

**Comment by sylus** [comment]
This has been fixed and wetkit demo has now a flag to enable it by default during drush si.
