### ISSUE TITLE
open stream: No such file or directory in wetkit_install_tasks_alter() (line 75 of

### ISSUE THREAD

**Issue by alar2** [wet-boew/wet-boew-drupal#817]
Hi wet-boew-drupal, This is my first post. :) I was able to get through the Linux install without too many hiccups. My Windows XP experience was failure. In an attempt to use windows I tried again on my own clean Windows 7 install by following:  
https://github.com/wet-boew/wet-boew-drupal/wiki/Download%2C-Installation%2C-and-Update

I updated the bit about you must use Drush 5.4 (I'll clean up my notes once I have success!), but now I'm having issues at the very last step.

Trouble may have started when the install couldn't find the php\pear library. Do I only have to update my PATH. There is a PEAR under 
$ which php
/c/Program Files (x86)/Drush/Php/
Would that be the one installed by the Acquia Dev Desktop?
Unfortunately I'm not very comfortable in windows, or with panopoly.

Did something else fail to get initialized in a previous step she wonders? Seriously I had a hard time figuring out whether this documentation was for a single or a multi-site install. I'm sure it's supposed to make it simple but there are important pieces missing in the description IMHO.

Any help much appreciated :)

---

Starting Drupal installation. This takes a few seconds ...                  [ok]

WD php: Warning: include_once(C:\Users\allison\Sites\drupal_wet):      [warning]

failed to open stream: Permission denied in
_drupal_theme_initialize() (line 208 of
C:\Users\allison\Sites\drupal_wet\includes\theme.inc).
WD php: Warning: include_once(): Failed opening                        [warning]

'c:/Users/allison/Sites/drupal_wet/' for inclusion
(include_path='.;C:\php\pear') in _drupal_theme_initialize() (line
208 of C:\Users\allison\Sites\drupal_wet\includes\theme.inc).
WD php: Warning: require_once(/panopoly_core.profile.inc): failed to   [warning]

open stream: No such file or directory in
wetkit_install_tasks_alter() (line 75 of
C:\Users\allison\Sites\drupal_wet\profiles\wetkit\wetkit.profile).
Drush command terminated abnormally due to an unrecoverable error.       [error]

---

Cheers,
Allison

**Comment by alar2** [comment]
Do I even need PEAR? Has nobody else suffered on a clean WIndows 7 install?
What is the best Windows flavour for wet-boew-drupal?

**Comment by StephenOTT** [comment]
@alar2 how did you install GIt and Drush on your pc?

**Comment by alar2** [comment]
Hi StephenOTT,
I used https://github.com/wet-boew/wet-boew-drupal/wiki/Download%2C-Installation%2C-and-Update

and I always take notes....

Acquia on Windows 7

## Installation location

Stack location: C:\Program Files (x86)\acquia-drupal
Site location:  C:\Users\allison\Sites\acquia-drupal

## Port settings

Apache:       8082
MySQL:        33066

## Drupal settings

Site name:    My Acquia Drupal Site
Username:     admin
E-mail:       yyyyyy@xxxxxx.com

Thousands of free modules make Drupal even better .....  waiting....

For your safety windows has blocked bits of MySQL and Apache. <-- Allow access :P

---

Update your $PATH Environment Variable to add the following location:

C:\Program Files\acquia-drupal\mysql\bin;
C:\Program Files (x86)\acquia-drupal

C:\Program Files (x86)\acquia-drupal\mysql\bin

%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\

Update local host. Open notepad right click run as administrator

Update apache

<VirtualHost *>
  ServerName drupal_wet
  DocumentRoot "C:\personnalLocalFolder\Desktop\Sites\drupal_wet"
  <Directory "C:\LocalFolder\Desktop\Sites\drupal_wet">
    Options Indexes FollowSymLinks ExecCGI
    AllowOverride All
   Order allow,deny
    Allow from all
  </Directory>
</VirtualHost>

<VirtualHost *>
  ServerName drupal_wet
  DocumentRoot "C:\Users\allison\Sites\drupal_wet"
  <Directory "C:\Users\allison\Sites\drupal_wet">
    Options Indexes FollowSymLinks ExecCGI
    AllowOverride All
   Order allow,deny
    Allow from all
  </Directory>
</VirtualHost>

 Download and install Drush 

Alternatively, the latest Drush installation instructions on Drupal.org for Windows can also be used. Older versions of the Drush source code are available from http://drupal.org/node/97249/release. At this time, on Windows you must still use version 5.4 of the Drush module. 

***\* Out of date above ******

*****\* Updated below *******

https://github.com/wet-boew/wet-boew-drupal/issues/622

Just wanted to alert the community. The build out now requires Drush 5.8 as a minimum.

This is kind of a disruptive change. However have been pushing the awesome D.O community to incorporate translations during the Drush Make phase.

With Drush 5.8 when we do the build out the po files are now downloaded as well which allows upon initial install to have a greater degree of translation support.

Additionally Drush 5.8 has added performance improvements for compilation in Windows based environments so figure an added bonus as well.

An updated windows installer for drush (5.8) has been posted at: http://drush.ws/drush_windows_installer

Process is as simple as reinstalling with this version if you are using Windows.

alar2 - I added updates to: https://github.com/wet-boew/wet-boew-drupal/wiki/Download,-Installation,-and-Update

Must verify.

 Download and install Git 

http://code.google.com/p/msysgit/downloads/detail?name=Git-1.8.1.2-preview20130201.exe&can=2&q=full+installer+official+git

C:\Program Files (x86)\Git

Git Bash only. Good enough for me ;)  \* crosses fingies *
- commit Unix style line endings

Build and launch the WetKit Drupal Distribution

 Build the complete Drupal installation software profile in your Web Server DOCROOT using the following commands at the Git Bash command prompt. The DOCROOT will be C:\personnalLocalFolder\Desktop\Sites\drupal_wet. Note: you may have to create the directory "drupal_wet" first.

Launch git bash - not GUI

C:\Users\allison\Sites\drupal_wet

$ pwd
/c/Users/allison/Sites

$ ls -l
total 4
drwxr-xr-x   31 allison  Administ     8192 Apr  2 19:22 acquia-drupal
drwxr-xr-x    2 allison  Administ        0 Apr  2 20:36 drupal_wet

---

Any and all help appreciated. Like I said, I need to present a clean process, and I'm willing to help update documentation for fools like me that make improper assumptions! ;)

Cheers,
Allison

**Comment by arothmel** [comment]
@StephenOTT - I used the guide "Download, Installation, and Update"

https://github.com/wet-boew/wet-boew-drupal/wiki/Download%2C-Installation%2C-and-Update

Is there a better Guide?

Thanks,
Allison

**Comment by StephenOTT** [comment]
@alar2 @arothmel are you installing this on your local desktop using Acquia Dev Desktop?

**Comment by StephenOTT** [comment]
> Is there a better Guide?

That is the "super detailed" guide.  But if you are just installing on your local system you can pretty much skip all those steps.

Also please check out: https://github.com/wet-boew/ariadne-wet-boew-drupal

@alar2 @arothmel email me at stephen.russett AT ottawa.ca and we can get you set up.

**Comment by arothmel** [comment]
@StephenOTT  I tried replying last night from home. Two messages above. 

Yes Acquia Dev Desktop on a Virtual Box running Windows 7.
The reason I want the detailed guide is I have to deploy it to the development server as well. 

Thanks!
I looked at  ariadne-wet-boew-drupal it requires Ruby :(

**Comment by StephenOTT** [comment]
Is Ruby a no go?

**Comment by alar2** [comment]
@StephenOTT  - Thanks again. Ruby was not in the plans. I am familiar with Drupal, my learning curve here is the wet-boew-drupal project. 
I was able to install on Linux now I need a windows version!!!
I'm not looking for the easiest way but if Ruby is the BEST way then....

**Comment by StephenOTT** [comment]
Needed ruby knowledge should be fairly limited.  

If you can use the https://github.com/wet-boew/ariadne-wet-boew-drupal it would be the best as it is designed to be a completely reproducible environment that has everything you need.

That way if you run into trouble, others can easily install the exact environment and troubleshoot.

The originla dev, was looking to duplicate the Acquia dev cloud config

**Comment by alar2** [comment]
Thanks Stephen,
I'll look in to the c:\php\pear on Windows 7 issue as well because I think that is the main problem with the long method.

**Comment by StephenOTT** [comment]
We can get you some support for the Ariadne if you like?

What website are you working on?

**Comment by StephenOTT** [comment]
Assume you did some googling? http://blog.stuartherbert.com/php/2012/05/10/getting-pear-working-on-windows-7/

**Comment by alar2** [comment]
---

w00t!!!

Gee how difficult was that on Windows 7? In retrospect I didn't have enough background in Windows 7 admin rights....

---

After fixing the pear problem...

---

WARNING!  The include_path defined in the currently used php.ini does not
contain the PEAR PHP directory you just specified:
<C:\Program Files (x86)\acquia-drupal\php5_3\pear>
If the specified directory is also not in the include_path used by
your scripts, you will have problems getting any PEAR packages working.

Would you like to alter php.ini <C:\Program Files (x86)\acquia-drupal\php5_3\php
.ini>? [Y/n] : Y

---

And altering db access in MySQL - don't ask ;)
When in doubt edit settings.php 

---

Attempt # x

c:\Users\allison\Sites\drupal_wet>drush si wetkit wetkit_wetboew_selection_form.
theme=wetkit_adaptivetheme --sites-subdir=drupal_wet --db-url=mysql://drupaluser
:drupal@localhost:33066/wetkit_db --account-name=admin --account-pass=WetKit@201
2 --account-mail=admin@example.com --site-mail=admin@example.com --site-name="We
b Experience Toolkit"
You are about to CREATE  the 'wetkit_db' database. Do you want to continue? (y/n
): y
Starting Drupal installation. This takes a few seconds ...                  [ok]

Processed 6 (6 created, 0 updated, 0 failed, 0 ignored) in 1.9 sec   [completed]

(185/min) - done with 'WetKitMigrateDefaultContent'
Processed 2 (2 created, 0 updated, 0 failed, 0 ignored) in 0.4 sec   [completed]

(329/min) - done with 'WetKitMigrateMegaMenu'
Processed 80 (80 created, 0 updated, 0 failed, 0 ignored) in 4.2 sec [completed]

(1152/min) - done with 'WetKitMigrateMegaMenuLinks'
Installation complete.  User name: admin  User password: WetKit@2012        [ok]

w00t!!!

---

Gee how difficult was that on Windows 7? In retrospect I didn't have enough background in Windows 7 admin rights....

---

Web Experience Toolkit
Search
Search website
Site Menu

```
Home(open the submenu with the enter key and close with the escape key)
Drupal WCMS(open the submenu with the enter key and close with the escape key)
GitHub(open the submenu with the enter key and close with the escape key)
Example Pages(open the submenu with the enter key and close with the escape key)
```

Status message

```
Thank you for installing the WxT-Drupal Variant for the Web Experience Toolkit. You may login at the following page: User Login
```

Warning message

```
For more information please be sure to read the online Documentation
```

Headlines

```
WetKit Features

Drupal is open source software maintained and developed by a community of 630,000+ users and developers. It's distributed under the terms of the GNU General Public License (or "GPL"), which means anyone is free to download it and share it with others. This open development model means that people are constantly working to make sure Drupal is a cutting-edge platform that supports the...

WetKit Collaboration

A major goal of the WetKit Drupal Variant is to enable and encourage collaboration on various activities involving the Web Experience Toolkit and in particular the Drupal platform.This project is always looking for contributors in a wide array of areas. If you are designer or developer then we could use your help!We believe the real strength behind this distribution should be the community...

WetKit Demo

Web Experience Toolkit (WET) includes reusable components for building and maintaining innovative Web sites that are accessible, usable, and interoperable. These reusable components are open source software and free for use by departments and external Web communities. The toolkit complies with the new Standards on Web Accessibility and Web Usability; the toolkit will also ease compliance with the...
```

Videos
undefined

Current position: 00:00:00

Total time: --:--:--

Playback percentage:
Web Experience Toolkit Video

This section is for video related content. Often this is the best place to introduce your department or organization.

```
Multimedia Help
Transcripts and Alternative Formats
```

Priorities

```
Image 1
```

**Comment by sylus** [comment]
Closing old issue please reopen if problem persists.
