### ISSUE TITLE
WetKit Deployment + WetKit Deployment Service Module

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#820]
After a lot of work content staging is now working and the following entities are supported for deployment (content staging):

1) Nodes (Content) and associated entities attach to them (taxonomy etc)
2) Beans
3) Files
4) Taxonomy
5) Comments
6) Users

Fixes have been introduced for files in wysiwyg and for panelizer to be deployed as well.

This module requires a steep learning curve though and will need to be tailored per department requirements and if you use additional modules like field_collection etc. However most of the hard work is done!

This module heavily relies on the immense power and deployment framework provided by:

1) Services
2) UUID (the most powerful of friends)
3) Deploy

Plan is to in the future offer Encrypt as an addition to the deployment plan.

The modules use the following relationship:

wetkit_deployment: client
wetkit_deployment_service: server

A single interface has been created for deployment using views + panels and custom ctools plugins for deployment and queue api.

![Deployment Interface](https://f.cloud.github.com/assets/984304/336895/b9623702-9cb6-11e2-9dd7-47fdf87e410c.png)

And with actual items in the queue:

![Deployment Interface Filled](https://f.cloud.github.com/assets/984304/337019/f279b6be-9cbb-11e2-8128-53e0a06cf960.png)

The staging area is per user and the deployment area shows all deployment plans currently in the queue ready for publishing the server.

More work needs to be done with this module and improvements upstream to deploy but definitely a great first step in content staging.

Soon a panel page and functionality will be integrated for: 

http://drupal.org/project/configuration

So we can have both content staging + configuration deployment.

**Comment by sylus** [comment]
@StephenOTT @joel-osc @joejoseph00 @mgifford @strinh

**Comment by mgifford** [comment]
Excellent work. We're definitely going to have to try this out!

**Comment by StephenOTT** [comment]
Providing a Block that can be placed at the node level to send to Deploy quque would be helpful as part of the user workflow

**Comment by sylus** [comment]
@maddydaigle

**Comment by sylus** [comment]
This is working and has been tested at Stats, so closing! :)

**Comment by MaddyDaigle** [comment]
Awesome! Thanks WIll. :)

**Comment by mgifford** [comment]
Curious if there has been any wok to add Encrypt  functionality.

I'm not clear if Wetkit Deploy does above and beyond the contrib Deploy module. 

Also, WetKit Deployment requires: Bean UUID (disabled), Bean (enabled), Entity API (enabled), Chaos tools (enabled), Universally Unique ID (enabled), Deployment (enabled), Entity Dependency API (enabled), Deployment UI (disabled), Page manager (enabled), Quicktabs (missing), Rules (disabled), Entity tokens (enabled), UUID Path (disabled), Views content panes (enabled), Views (enabled), Workbench Moderation (enabled)

WetKit Deployment Service Requires: Bean UUID (disabled), Bean (enabled), Entity API (enabled), Chaos tools (enabled), Universally Unique ID (enabled), Rest_server (missing), Services (missing), UUID Path (disabled), UUID Services (disabled)

But Quicktabs isn't in the profile.  I don't think that Deploy is part of the build either, but I had downloaded that. The REST_Server & Services also isn't there by default.

Configuration module also needs Xautoload to work.

So, for clarification when you say client/server you mean staging/production:

wetkit_deployment: client   => Staging
wetkit_deployment_service: server  => Production

Right?

And it seems pretty clear that one shouldn't install wetkit deployment & wetkit deployment service on the same server. But nice to see it doesn't blow up if you do. 

Taking a look at the deployment page eng/admin/dashboard/deployment I think there's a CSS issue:

![screen shot 2013-07-08 at 1 00 06 pm](https://f.cloud.github.com/assets/116832/762783/ebc55844-e7ef-11e2-8a04-39c5769113fe.png)

That's with just WetKit Deployment & the caches cleared.

But ultimately I'm posting here as we need more documentation on this.  How is it different from:
  https://drupal.org/node/1195682

Knowing why you build the wetkit module and how it's different would be very useful.

**Comment by mgifford** [comment]
I'm going to re-open this as it shouldn't be considered closed if there isn't documentation.  That could be in a new issue, but it's critical for being able to use the code.  Just knowing it works at Stats isn't sufficient.

**Comment by sylus** [comment]
The readme for wetkit_deployment says you have to perform a make fot both wetkit_deployment and wetkit_deployment_service. As some dependencies are not immediately downloaded with the distro as not everyone will need to use deployment.

If you don't do that make and try to get the dependencies yourself your gonna have a rough time.

We now have a new documentation person at stats but is likely going to be a few weeks if not months before she gets up to speed to write documentation on deployment.

**Comment by mgifford** [comment]
So from profiles/wetkit/modules/custom/wetkit_deployment/README.md

> This module isn't enabled by default
> Client: Please run the following drush make in profiles/wetkit directory:
>     drush make --no-core --contrib-destination=. modules/custom/wetkit_deployment/wetkit_deployment.make
> Server: Please run the following drush make in profiles/wetkit directory:
>     drush make --no-core --contrib-destination=. modules/custom/wetkit_deployment/wetkit_deployment_service/wetkit_deployment_service.make
> Enable!

So for clarification do I need to do a whole new build for this, or just do the build of wetkit_deployment.make & wetkit_deployment_service.make

From your comments it sounds like I'm going to have to disable these modules, remove them from sites/all/modules and then try this again. 

Good to know you've now got a documentation person.

**Comment by sylus** [comment]
No you don't need to do a new build at all just an in place one following exactly the instructions. And yeah should help

**Comment by mgifford** [comment]
So I got this error when running wetkit_deployment.make

> > Checked out revision 5cc4fc2.                                                                                                                                [ok]
> >  deploy patched with deploy-1604938_1.patch.                                                                                                                  [ok]
> > Unable to patch deploy with deploy_allow_revision_id-1948186-2.patch.                                                                                        [error]

I'm not sure what the problem with https://drupal.org/node/1948186 is.

**Comment by mgifford** [comment]
I should also add that after running this entity_dependency is nowhere to be found in profiles/wetkit

grepping for the text doesn't show up anything.

**Comment by sylus** [comment]
I have done a feature-deployment and checked with travis and everything appear to be in order?

**Comment by mgifford** [comment]
We forced it and it seemed to be fine.

Looking at the docs again:
- Client: Please run the following drush make in profiles/wetkit directory:
  drush make --no-core --contrib-destination=. modules/custom/wetkit_deployment/wetkit_deployment.make
- Server: Please run the following drush make in profiles/wetkit directory:
  drush make --no-core --contrib-destination=. modules/custom/wetkit_deployment/wetkit_deployment_service/wetkit_deployment_service.make

Also useful to tell folks  that "Make new site in the current directory? (y/n): y" isn't actually going to build a new site.

I'm assuming that there is no reason that we couldn't run both drush make scripts on the same code base.  

We generally use git for managing code/versions rather than drush make. Will, I know you like to build up from drush make and there's good reasons for that, but it's not always the right solution.

And the client/server is confusing..  Probably it should be staging/production when the site goes live.  Mind you we're right now wanting the content to be created on staging and then pushed back to our development environment. 

Also, useful to compare to methods like:
  drush rsync @dev @staging 
  drush sql-sync @dev @staging

Here's a link going into a bit more detail about how to deal with this via Drush.
http://drupal.stackexchange.com/questions/11535/how-to-set-drush-sql-sync-not-to-clone-users-between-dev-and-staging

**Comment by sylus** [comment]
Updated the whole suite of deployment modules and reflected a better naming methodology.

**Comment by mgifford** [comment]
Is there documentation posted yet?

**Comment by Pacoup** [comment]
It's not immediately obvious what this is but it sounds like what I think it is... Is this a tool to have a staging server for content review; i.e. a separate server/domain where pages can be sent as staging for review.

If the question is not obvious, here's our current workflow at CIHR with OpenText WebSolutions which we're replacing with Drupal:

<ol>
<li><strong>Edit and save page</strong></li>
<li><strong>Publish page to dev/stage/prod</strong><br>
Publishing to dev, stage or prod renders the page as static HTML and sends it to either dev.cihr.ca/pageID, stage.cihr.ca/pageID or cihr.ca/pageID.<br>
dev and stage are only accessible internally (Intranet), so we use stage to send non-final pages for review to clients (internal content authors and owners)</li>
</ol>

Is this “content staging” in wetkit the same thing?

**Comment by sylus** [comment]
Yes this is exactly what you think it is. Using Web Services + JSON to deploy content from a content staging server. All it requires is line of site + session based authentication restricted by IP.

Currently we have Node, Menus, Files, Comments, Users, and Beans deployed by the click of a checkbox. Also There is a bulk exporter.

**Comment by Pacoup** [comment]
Wow, that's really fantastic. Now we don't even have to imagine a complex LDAP / Active Directory solution to replace our traditional content review workflow.

Can this be integrated in a publishing step (I assume this what you meant by checkbox, as in checkbox in a publishing step)?
