### ISSUE TITLE
Automated paths are getting "/content/" injected even though it is not defined in patterns.

### ISSUE THREAD

**Issue by MikeDucharme** [wet-boew/wet-boew-drupal#826]
Default Path Pattern (default setting - all others are blank):
[node:bilingual_pathauto_prefix]/[node:title]

New "Page" with "Test Page" as title generates:
/eng/content/test-page

If I drop the language token, it works as expected:
New page: /eng/test-page

Is the "bilingual_pathauto_prefix" token simply the "content/contenu" text?

**Comment by joel-osc** [comment]
Best to just check the code:

desktop:/var/www/wet/profiles/wetkit/modules$ grep -r bilingual_pathauto_prefix .
./custom/wetkit_core/wetkit_core.strongarm.inc:    'token-node:bilingual_pathauto_prefix' => 'token-node:bilingual_pathauto_prefix',
./custom/wetkit_language/wetkit_language.strongarm.inc:  $strongarm->value = '[node:bilingual_pathauto_prefix]/[node:title]';
./custom/wetkit_language/wetkit_language.tokens.inc:  $info['tokens']['node']['bilingual_pathauto_prefix'] = array(
./custom/wetkit_language/wetkit_language.tokens.inc:        case 'bilingual_pathauto_prefix':

function wetkit_language_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();
  $sanitize = !empty($options['sanitize']);

  // Node tokens.
  if ($type == 'node' && !empty($data['node'])) {
    $node = $data['node'];

```
foreach ($tokens as $name => $original) {
  switch ($name) {
    case 'bilingual_pathauto_prefix':
      if ($node->language == 'fr') {
        $value = 'contenu';
      }
      else {
        $value = 'content';
      }
      $replacements[$original] = $sanitize ? filter_xss($value) : $value;
      break;
  }
}
```

  }

  return $replacements;
}

So yes.
