### ISSUE TITLE
Can't edit user account on /user page

### ISSUE THREAD

**Issue by MikeDucharme** [wet-boew/wet-boew-drupal#827]
There is no "Edit" tab on user pages (example.com/user) like in Drupal core so users (including user/1) are locked out of managing their account details, changing passwords, etc.

**Comment by d-shields** [comment]
This seems to be easily fixed by adding the 'Tabs' pane under Page Elements. 
However, one does not seem to be able to save the default user page, but rather only update one user page at a time. 
I've run into the same issues with Basic Page. Surely, we're missing a step here?

**Comment by joel-osc** [comment]
Defaults are here: eng/admin/config/content/panelizer

**Comment by d-shields** [comment]
@joel-osc - I think you just saved my life :-)

**Comment by joel-osc** [comment]
Yeah, that menu is in a very, very odd place but powerful when you find it.

**Comment by MikeDucharme** [comment]
I'm concerned about how many "core" Drupal features like this are disabled by default. New distribution users who are familiar with Drupal (like me) can become confused when expected functionality has been removed and it is not clear how to get that functionality back. Are choices like this part of a ux strategy or documented anywhere?

**Comment by joel-osc** [comment]
This is panels and panelizer and not really a WET thing. I would recommend spending some time to just look over the  WET modules to understand the delineation between what WET does and what Panopoly, Panelizer and base Panels does. WET doesn't do too much that is invasive, panopoly (panopoly_admin) is a bit more invasive and a good one to have a look at. It sounds like a lot of your frustration is panels / panelizer related for which there is a lot of info on the web. Also, it might help you to play around with panels on a base install of Drupal (non-wet) and then add panolopy or just panelizer and then you will see where each comes into play.

**Comment by StephenOTT** [comment]
@MikeDucharme Could you start a wiki page of these items and we can add to it as we find some of these issues?

**Comment by MikeDucharme** [comment]
Thanks for the info @joel-osc . It's certainly difficult to know whether something is wet-related or panopoly/panelizer/panels related. I think that's a good idea @StephenOTT - I'll do that. I'd also like to see us work on documenting each custom wet module so the delineations are more clear.
