### ISSUE TITLE
Enabling "Display author and date information." has no effect.

### ISSUE THREAD

**Issue by MikeDucharme** [wet-boew/wet-boew-drupal#828]
I enabled "Display author and date information." in the Publishing Options at 

```
/eng/admin/structure/types/manage/wetkit_page
```

 but the author is not displayed. I notice that the "Date Modified" is displayed even with this setting disabled.

I'm not sure what the best course of action is - author and date should probably be separate settings in Drupal core anyways.

**Comment by d-shields** [comment]
From what I understand, the Date Modified that you see is a custom panel pane added by default.

**Comment by RobJohnston** [comment]
Might relate to issue #541.  "Date Modified" may be required according to the "Standard on Web Usability" linked from that issue.

**Comment by sylus** [comment]
Yeah these are displayed (or not) in: http://wxt-drupal:8082/eng/admin/structure/pages/edit/node_view based on the content type. Basically just panels workflow.
