### ISSUE TITLE
Disabling "Prepend breadcrumbs with a home link by default" as no effect (Wetkit Breadcrumbs)

### ISSUE THREAD

**Issue by MikeDucharme** [wet-boew/wet-boew-drupal#829]
I wanted to disable the "Home" link in the breadcrumb but it is still displayed after unchecking this option at:

```
/eng/admin/panopoly/wetkit_settings/wetkit_breadcrumbs
```

I flushed caches a few times thinking it might be cached.

**Comment by sylus** [comment]
I will have to take a further look but I think this is a conflict between AdaptiveTheme + Path Breadcrumbs.

**Comment by sylus** [comment]
So I looked into this and this is more of an upstream issue as in wetkit_settings we are merely using functions the path_breadcrumbs module.

It says right below the checkbox that:

This value does not changes current breadcrumbs navigation. It is just set default value for new path breadcrumbs.

So will have to be fixed upstream in path_breadcrumbs issue queue.

**Comment by sylus** [comment]
Closing this issue as is only related to path breadcrumbs.

**Comment by mgifford** [comment]
Having a text list of enabled modules in each RC would be useful.  I don't even know if path_breadcrumbs is being used any more.  

If it is, it would be useful to put in the link to the upstream issue.  It does really help issues move ahead if there are links.  Even between different projects (say between d8 & ckeditor) having links between the issue queues is useful.  Simply saying it has to be dealt with upstream doesn't generally git the bug fixed.

Why would "only related to path breadcrumbs" be a reason to close this issue?

**Comment by sylus** [comment]
The reason is this is an upstream issue. Fix the problem straight in path breadcrumbs. I plainly stated this 2 comments up.

There is no upstream issue created. I encourage you to file one.
