### ISSUE TITLE
Mobile NavBar disappeared

### ISSUE THREAD

**Issue by d-shields** [wet-boew/wet-boew-drupal#830]
This is definitely not a bug, but a configuration question..
As we try to get more acquainted with the distro, I've played with a lot of the configuration, pushed a lot of buttons and tweaked a lot of settings - almost all in the UI. 
I can't figure out what I've done wrong, but somewhere in my messing about, I've disabled the mobile navbar. It's not in the source code, though the wet-boew js file that handles this is being loaded.  
I have 2 sites running off the same code base - 1 works, the other doesn't.. 
Has anyone come across this?

**Comment by d-shields** [comment]
I've tracked this down to i18n.
When I disable the French language here: admin/config/regional/language , I lose the mobile navbar. 
I'll try to figure out what's happening with this.

**Comment by sylus** [comment]
What do you mean by mobile navbar lol? The one that WET loads?

**Comment by d-shields** [comment]
Yep - this part: 
![Screen-Shot-2013-04-05-at-2 45 56-PM](https://f.cloud.github.com/assets/1577088/345402/5dc55584-9e21-11e2-9616-0ddaf0daf3f9.png)

**Comment by sylus** [comment]
Oh I know what is doing this check in the theme for wetkit under template--preprocess.inc and you will see logic to append the french link. I think I am not guarding against something correctly.
