### ISSUE TITLE
Mobile Menu Items

### ISSUE THREAD

**Issue by d-shields** [wet-boew/wet-boew-drupal#831]
From what I can see, the only way to edit the mobile menu is to edit this file: 
/wetkit/profiles/wetkit/modules/custom/wetkit_wetboew/wetkit_wetboew.menus.inc

Is that the case for now, @sylus, that the menu items have to be hard-coded into this .inc file?

**Comment by sylus** [comment]
Nope now with menu mini panels on the scene this file will soon be deleted.

Additionally you can still create / delete menu items in the interface?

Can you be a bit more descriptive?

**Comment by d-shields** [comment]
I can try.
I figured the pop-up menu was a regular drupal menu, but couldn't find it in the ui, so grepped through files, it seemed that the only place I could find any relevant strings was in that /inc file.

Does that help?

**Comment by d-shields** [comment]
this seems to work fine now.
who knows what my problem was before?!
