### ISSUE TITLE
How to edit field featured_status

### ISSUE THREAD

**Issue by d-shields** [wet-boew/wet-boew-drupal#832]
Hey @sylus, I've been trying to figure out how the featured_status field works.
I understand that populist made a decision to drop our the promote to front page and sticky options from drupal core. Is this supposed to serve the same sort of function? 
If so, how does it work? I can't seem to see it on the node edit page, either with the panels page enabled or disabled.
If not, could you please explain the functionality of this featured_status field?

**Comment by sylus** [comment]
I think this would make more sense to ask this question in Panopoly closing this issue.
