### ISSUE TITLE
Language Neutral Beans

### ISSUE THREAD

**Issue by d-shields** [wet-boew/wet-boew-drupal#834]
Is it possible to create language-neutral beans?
If so, how would I go about doing that?

**Comment by StephenOTT** [comment]
@d-shields did you create a new Block Type?

**Comment by d-shields** [comment]
@StephenOTT - tried that, but I don't see an option for language at /admin/structure/block-types/add

**Comment by StephenOTT** [comment]
It is part of the Entity Translation config:
/eng/admin/config/regional/entity_translation

![Screen Shot 2013-04-07 at 4 24 07 PM](https://f.cloud.github.com/assets/1994838/349399/230a7c84-9fc1-11e2-95e3-8aafcaf67154.png)

Once you uncheck the Hide Lang Selector you are good to go:

![Screen Shot 2013-04-07 at 4 24 42 PM](https://f.cloud.github.com/assets/1994838/349401/41ca9050-9fc1-11e2-8e7d-6e702b14f88c.png)

**Comment by StephenOTT** [comment]
May be good to have the language selection part of the default Distro config.

**Comment by d-shields** [comment]
thanks, @StephenOTT! 
I would definitely agree that this be available by default.

**Comment by sylus** [comment]
I guess there is a case for this. At the government we are not allowed to use Language Neutral hence why we disabled that option. However for others can see the benefit. Will get to this soon. Unless anyone wants to do a pull request!

**Comment by sylus** [comment]
Fixed!
