### ISSUE TITLE
Responsive Tabbed Interface

### ISSUE THREAD

**Issue by d-shields** [wet-boew/wet-boew-drupal#835]
When I pass the breakpoints on browser width that for the page to reload as a "tablet" layout, the "active" class is no longer included in the markup, so I end up with no items being displayed

`<div id="tabs1_2" class="tabs-content-pad active" tabindex="-1" role="tabpanel" aria-hidden="true" aria-labelledby="tabs1_2-link" style="display: block; min-height: 348px;">`

becomes

`<div id="tabs1_2" class="tabs-content-pad ">`

What am I doing wrong here, @sylus?

**Comment by StephenOTT** [comment]
Updated the post from @d-shields as GFM was not being used around the html code.

when showing code you need to use:
![Screen Shot 2013-04-07 at 4 27 33 PM](https://f.cloud.github.com/assets/1994838/349405/9b33a726-9fc1-11e2-99db-1ae5b5f6a10b.png)

**Comment by d-shields** [comment]
thanks
