### ISSUE TITLE
Willing to update documentation in exchange for support

### ISSUE THREAD

**Issue by alar2** [wet-boew/wet-boew-drupal#838]
My interest in wet-boew-drupal is rather recent; I rarely let an install issue get the best of me. But in this case I want to keep my process clean and avoid work-arounds. If any of you experienced wet-boew-drupal experts could help me with I think an almost successful install of wet-boew-drupal on a clean Windows 7; I'll gratefully update the "Windows Detailed Installation Steps with Acquia Dev Desktop" instructions!
Please refer to issue #817
## Many thanks!!!

Allison
BTW: If it makes any difference it's a Windows 7 Virtual Box. Thx!

**Comment by alar2** [comment]
It was the php\pear issue. Windows permissions settings did not allow PHPs PEAR to be installed. I did update the documentation for "https://github.com/wet-boew/wet-boew-drupal/wiki/Download%2C-Installation%2C-and-Update" to include this little hiccup. :zap:

**Comment by sylus** [comment]
Closing old issues.

**Comment by mgifford** [comment]
I don't believe that running Windows as a webserver is every a good idea.  That being said, I've written up a document to help install WET on Windows.  The thread is here:
  https://github.com/wet-boew/wet-boew-drupal/issues/947

Could definitely use your input Allison.
