### ISSUE TITLE
RC2 Release date?

### ISSUE THREAD

**Issue by nrc-cnrc-web** [wet-boew/wet-boew-drupal#840]
Hi. Just wondering if there's a specific date set for the RC2 release? Thanks!  :-)

**Comment by sylus** [comment]
I would assume at the very latest by early next week! Will needs lots of testers when this happens though! :)

**Comment by xmacinfo** [comment]
Speaking about testers, any plan to properly package WET using drupal.org packaging scripts? That would make it easier for testers to download and install the WET distribution.

No releases have been created yet on Drupal.org.

https://drupal.org/project/wet

**Comment by nrc-cnrc-web** [comment]
Cool beans! Thanks for the update, @sylus. Count me among those testers.  :-)
