### ISSUE TITLE
Generating PDFs

### ISSUE THREAD

**Issue by mxlav** [wet-boew/wet-boew-drupal#843]
I've been playing around with generating PDF docs for a view output and/or a node.

**Test#1**
Installed http://drupal.org/project/print with https://code.google.com/p/dompdf/
**Results**, Html output OK; PDF clocking, not generating doc, not seeing any errors.

After some research, Suspecting some css somewhere in WETKIT is causing grief to the tool. Switched my theme to bartik and PDF doc is generated without any problems.

**Test#2**
Used http://www.tcpdf.org/ instead of dompdf.
**Results**, PDF is generated, but ALL styling is stripped out. Did some research and other people have encountered this issue and there are several ways recommended to fix this. But this tool supposedly doesn't play well with newer css.

Ideally I would like to be able to use the tool that works with the latest css like dompdf.
1. Has anyone else encoutered the bug with WETKIT and dompdf?
2. or is there a better way to generate pdf than what I am attempting to do?

**Comment by MikeDucharme** [comment]
I've had a lot of success with [Views PDF](http://drupal.org/project/views_pdf) which works with tcpdf.

There is a limited amount of styling available in the UI but you can override the output for every field when using the PDF Fields output style and changing the settings per field. Here's a snipped for a custom formatted image field that is rendered as a background image for a printable certificate:

 **PHP Code Before Output** (field setting in views)

```
// set a full pdf background image with no margin or padding
// My field containing the path to my image is $row->field_field_certificate_image[0]['rendered']['#item']['uri']);
// get the current page break margin from tcpdf
$bMargin = $this->getBreakMargin();
// get current auto-page-break mode from tcpdf
$auto_page_break = $this->getAutoPageBreak();
// disable auto-page-break to force only a single page to be generated
$this->SetAutoPageBreak(false, 0);
// set background image
$img_file = $row->field_field_certificate_image[0]['rendered']['#item']['uri'];
// set the image to cover the entire pdf stage (see the tcpdf api for arguments list)
$this->Image($img_file, 0, 0, 297, 210, '', '', '', false, 300, '', false, false, 0);
// restore auto-page-break status
$this->SetAutoPageBreak($auto_page_break, $bMargin);
// set the starting point for the page content
$this->setPageMark();
```

This may be overly complex for your use case as the default settings available in the UI may be enough for you.

**Comment by mxlav** [comment]
thanks @MikeDucharme , I haven't looked at Views PDF module yet since it was limited to views, but I might.

Update on the bad WETKIT css. I've been attempting to strip-out bits and pieces of WETKIT styling in the code to at least get a file generated.

```
$patterns = array();
 $patterns[0] = '!<style>@import.*?profiles/wetkit.*?</style>!';
 $patterns[1] = '!@import url.*?profiles/wetkit.*?mkzll5\\"\\);!';
  $patterns[2] = '!<script.*?wetkit.*?</script>!';
  $patterns[3] = '!<noscript><link rel="stylesheet" href.*?profiles/wetkit.*?</noscript>!';
  $patterns[4] = '!<link type=\\"text/css\\" rel=\\"stylesheet\\".*?profiles/wetkit.*? media=\\"all\\" />!';

  $html = preg_replace($patterns, '', $html);
```

Ends up the bad CSS is in the IE specific CSS. Adding the code above resulted in a pdf being generated..not very nice looking one mind you, but still, at least it generated. I then re-add them one by one starting from the top and the pdf was generated until only pattern[4] remained. Adding pattern[4] back in the mix = no pdf. 

...

**Comment by StephenOTT** [comment]
@mxlav What is your use case/user story that has views being a limit?

**Comment by mxlav** [comment]
On my side, I don't have a use to case to only using views. 
But from a quick glance to the **Views PDF** module page, it appears that it's implementation is limited to views, vs the **Print** module which can be used at any level in Drupal (Nodes, ContentTypes, Views etc..)

**Comment by StephenOTT** [comment]
Okay.

I was just thinking in my head you could use a contextual filter to process the node id and use the view to output the same node view.  But Print module looks nice

**Comment by sylus** [comment]
Closing old issues.
