### ISSUE TITLE
Media browser unable to upload alternative format video

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#846]
I created a field to upload alternative format of the mp4 videos.
BTW, wetkit 7x-1.0-rc1

When uploading other than mp4 format, preferable wmv, the admin tab doesn't show the radio options: video and wetkit video, and nothing else can be done. See the picture.

Actually, the files are beeing upload and the db updated, but nothing is showed in the content type.

Can someone help me to fix it?

![video upload issue](https://f.cloud.github.com/assets/1461809/364416/f521dfc8-a21e-11e2-900e-8dc752da085e.png)

**Comment by sylus** [comment]
You will need to add wmv mimetype inside the file type for this to be added. File Entity requires knowledge of the mime type beforehand in order to do its magic :)

**Comment by ssari** [comment]
Thank you @sylus, but unfortunately we couldn’t see the magic. 

The mimes were configured.
-   wetkit\includes, file.mimetypes.inc
              338 => 'video/x-ms-wmv',
             341 => 'video/x-msvideo',
             'wmv' => 338,
             'avi' => 341,
-   acquia\apache\conf, mime.types:
           video/x-ms-wmv wmv
          video/x-msvideo avi

It’s a strange behavior.
-   wmv - the file browser plugin doesn’t show the radio options, and doesn’t display the file name, although it upload the file 
-   avi - the file browser plugin doesn’t show the radio options, display directly the file name. The file is uploaded but I can’t edit to add description.

Is there other venue to justify this unexpected behavior when using the “Media file selector” widget?

Alternatively, using the File widget, the video file is upload and file name + extension is display; however it’s not possible to change the name or add “title” or “alt” to the link.

**Comment by sylus** [comment]
Can you try this patch?

http://drupal.org/node/1836266#comment-7219888

**Comment by ssari** [comment]
We replicated the Production site to test it.
Using Git with two different commands I got error. Not sure which command I should use.
Also error when testing the patch on Simply.me.  Please see the pictures.
Did it work in your system?
![issue_file_entity_patch-t2](https://f.cloud.github.com/assets/1461809/399483/81586520-a873-11e2-8add-dc62899a8ca3.png)
![issue_file_entity_patch-t1](https://f.cloud.github.com/assets/1461809/399486/89f993d4-a873-11e2-9700-15da0f23d752.png)

**Comment by RobJohnston** [comment]
@ssari , I think that it would be "patch -p1 file_entity_variables-1836266-27.patch" executed from the directory where the file_entity.info and file_entity.variable.inc files are located... the "p1" to strip out the leading "a/" and "b/" from the file locations.

**Comment by sylus** [comment]
This is baked in now by default.
