### ISSUE TITLE
Fresh Installation - Theme disappears(?) after clicking on any admin menu

### ISSUE THREAD

**Issue by MichaelClift** [wet-boew/wet-boew-drupal#85]
After clicking on any admin menu item, the clf3 theme disappears and errors are displayed:

Notice: Undefined index: highlighted in include() (line 124 of F:\xampp\htdocs\modules\system\page.tpl.php).
Notice: Undefined index: sidebar_first in include() (line 136 of F:\xampp\htdocs\modules\system\page.tpl.php).
Notice: Undefined index: sidebar_second in include() (line 142 of F:\xampp\htdocs\modules\system\page.tpl.php).
Notice: Undefined index: wetkit_adaptivetheme in drupal_theme_initialize() (line 100 of F:\xampp\htdocs\includes\theme.inc).
Notice: Trying to get property of non-object in _drupal_theme_initialize() (line 145 of F:\xampp\htdocs\includes\theme.inc).
Notice: Undefined index: wetkit_adaptivetheme in drupal_theme_initialize() (line 100 of F:\xampp\htdocs\includes\theme.inc).
Notice: Trying to get property of non-object in _drupal_theme_initialize() (line 145 of F:\xampp\htdocs\includes\theme.inc).
Notice: Trying to get property of non-object in _theme_load_registry() (line 334 of F:\xampp\htdocs\includes\theme.inc).
Notice: Undefined index: wetkit_adaptivetheme in theme_get_setting() (line 1332 of F:\xampp\htdocs\includes\theme.inc).
Notice: Trying to get property of non-object in theme_get_setting() (line 1369 of F:\xampp\htdocs\includes\theme.inc).
Notice: Trying to get property of non-object in theme_get_setting() (line 1379 of F:\xampp\htdocs\includes\theme.inc).

Any ideas?

**Comment by RobJohnston** [comment]
I was just about to submit this same bug.  I noticed it when clicking the "Apps" menu.  Breaks the whole site.

**Comment by sylus** [comment]
Hey yeah I noticed this as well am working on it right now... Strange thing is works with drush si... Will likely take me a few hours to track this down. Will report here as soon as possible.

To minimize these issues in the future, will need some sort of automation testing for browser based install

**Comment by openplus** [comment]
Last ran OK for me on the 6th June (Again... Drush make + front-ent browser install)... but dying since.

**Comment by RobJohnston** [comment]
Looks like I did a manual install at home on the night of the 9th that worked OK.  May or may not be related, but I don't see any default content on the front page since this started happening.  The "Headlines", "Videos", and "Priorities" titles are there, along with the "more" link, but that's it for me.

**Comment by thriuin** [comment]
Same here, except it was in the morning of the 9th.

**Comment by sylus** [comment]
Yeah I have traced the bug to the last week, expect a fix soon. After that I will focus on testing the browser install with xfvb and selenium so this doesn't happen again.

**Comment by sylus** [comment]
So everyone knows I have tracked the bug to the addition of the .po files for the apps in a commit 5 days ago. Doing a git reset 6f15561 --hard makes the site work again in graphical install.

Based on this knowledge I will have a fix soon prolly in next hour or so!

**Comment by sylus** [comment]
All fixed up!
