### ISSUE TITLE
University of Ottawa (Contrib Modules)

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#86]
Hey all,

I had some exciting news that I just couldn't wait to share. As some of you know Ottawa University has been participating in working alongside this distribution. I just came from a meeting with them today to see the progress they have been making.

In short I was amazed. They have developed a total of 6 modules and each of them offer some pretty amazing functionality. The two that most impressed me were the enhanced migration interface and the french language integration improvements. To be clear when I say improvements I mean improvements! The french language has been so seamlessly integrated in drupal it is quite possibly the best work I have seen in this work space.

Anyways they are committed to collaborating and will be sharing this code shortly so look for even more improvements coming through the pipeline. There of course will be no base architecture changes as these are all just value added improvements.

All in all collaboration is starting to happen and I couldn't be happier!

Exciting!!!

**Comment by mgifford** [comment]
It was a really nice to see their tools. The work on Migration & bilingual content editing both rock.  Oh ya, then there was the multi-site issue tracker..  Great stuff!

**Comment by thriuin** [comment]
Perhaps this is a good candidate for an App or two,

**Comment by StephenOTT** [comment]
Any slides or presentation files you can share?

**Comment by sylus** [comment]
Closing this for now.

**Comment by sylus** [comment]
I am not sure about this. I have evaluated Ottawa U's code and in its current state I can't bring it into the distro as I think it would cause maintenance problems down the line. Given that the only reason you would not like workbench is it breaks side by side I am not sure that is enough of a reason as the workflows it provides are pretty nice. Although I could be persuaded to take out workbench as ERS or WorkFlow + Revision could fulfilll the requirements. I admit workbench has a few peculiarities but I would need to have a solution that provides much the same thing as a replacement.

I would prefer when EntityTranslation is fully supported that we devote time then on the side by side editor.

For a side by side editor functionality has your translation dept evaluated: http://drupal.org/project/tmgmt?

**Comment by thriuin** [comment]
For what it's worth, StatCan's internal clients have not expressed any interest in Workbench (the opposite, if anything) and we probably won't use it. I like the idea of dropping it from the distro - if someone needs this solution, they can include it themselves or it could be 'appified'. However, I have to agree completely that it is not appropriate to integrate the UOttawa editor for all the reasons that @sylus indicated.

**Comment by joejoseph00** [comment]
Hi guys, sorry for those messages, please delete them.  That was an internal memo.

As for this issue, it's not my call.

**Comment by joejoseph00** [comment]
I'll mention this http://drupal.org/project/tmgmt and see what they say.

**Comment by sylus** [comment]
Also @joejoseph00 if they do want Ottawa U's side by side or something similar. If it gets built and tested of course I will add it in. I am just saying in its current form I don't think it is maintainable and I don't have the time to fix it atm.
If CTA does and passes testing I'll def bring it in.

**Comment by sylus** [comment]
Alright talked about it a bit and I can remove workbench ^_^

**Comment by sylus** [comment]
Also @joejoseph00 Entity Translation does still have some minor problems with Node but does work great for full fledged entities :)

**Comment by sylus** [comment]
Let me know what CTA thinks about the module I sent and if they still want a side by side editor (even though we would have to repeat work twice for entity trans once it is stable for nodes) I can start some work on it basing off of Ott U

**Comment by joejoseph00** [comment]
What impresses me with the UOttawa side-by-side, is that it can be enabled based on content type, it does not have to be used with all content types, just the selected ones.  It also works perfectly in both french and/or english mode, something our D6 side-by-side didn't do (it doesn't work in french).  They're also uptaking the WETBOEW version of TinyMCE into it.  It's also using the forms api, everything is happening through the forms API before the add content page loads, so it's Kosher using D7 forms api.  

Our D6 side-by-side only works on one content type in one language instead of both , the UOttawa side-by-side is in D7 already, so thanks to this we no longer have to upgrade our existing side-by-side interface from D6.

**Comment by sylus** [comment]
At @joejoseph00 does this mean you used their module successfully internally without a problem? Last time I looked it added a fair amount of additional tabes and was directly taking over control of revisions.

**Comment by joejoseph00** [comment]
We did some pilot tests of it here a few weeks ago and it was working.  We also just had a meeting with UOttawa yesterday and they demo'd some of their new stuff , the side-by-side, and their migration module.  citt-tcce.gc.ca was there too.

**Comment by joejoseph00** [comment]
The tables are probably required for logging which content types are to be used with the side-by-side, not sure what else they're storing, maybe other config settings.  As for revisions, I'd have to run another pilot test to have a look and see what happens as I don't think we looked at that.  We might still have it running.  I could have another look.

**Comment by sylus** [comment]
I have seen this module in action as well and it works great but the key thing is they have an awesome developer (Robert) to fix any problems that would arise. I worry that since it looks like it is far reaching in a few areas that it could have unintended consequences and be a burden to maintain. You will notice that all of my modules are very straightforward and based on ctools and for further protection alot of them gathered upstream from Panopoly which has its own set of peer review.

Ideally I would have to sit with Robert (the amazing developer at Ottawa U) and we could work this out together. I only think it would take an hour or two for me to content and bring the module in. If problems did arise with it though I doubt I would be the one performing bug fixes.

**Comment by joejoseph00** [comment]
If he hasn't done so already, I'm sure if we asked for a cleanup he could quickly remove some debug or experimental stuff he may have left in there during dev.

It's tough to get any code published on Drupal.org, in fact lots of these maintainers don't answer e-mails for months.  At least with Robert, we know where he works.

As for Panopoly, I don't know much about it other than what I've heard about here.

**Comment by sylus** [comment]
Hey @joejoseph00 I just talked to Ottawa University about all this and I think we have a solution for this. Not sure if I should write it up here or file a Meta Issue?

**Comment by thriuin** [comment]
While I agree that UOttawa has done some interesting work and some departments may want to take advantage of it, the fact is that we are one week from our first formal release. We simply DO NOT have the time, nor can we take the risk of introducing such a big change right now. 

Longer term, a lot of work and thought went to into the choice of Panopoly for its useability, its broader community support, and its close ties to the Drupal 8 initiative. 

Having said that, if CTA and others want to invest the effort into creating an app or modules that offer an alternative editing experience based on the work done by UOttawa, that would be most welcome, but I can't see it being part of the 'core' WET Drupal variant in the near future. That certainly doesn't prevent it from being made available.

This is probably a discussion that is best left for the working group.

**Comment by sylus** [comment]
There has been some discussion with Ottawa University on this and a solution is at hand, please proceed to #389

**Comment by joejoseph00** [comment]
Just to clarify to the Drupal Ottawa community, one of the most important features of our D6 site is the side-by-side entry form interface, ours works perfectly as designed and has never failed outside of design specifications as it works as per design specs.
