### ISSUE TITLE
Webinar: Exploring Canada's Web Experience Toolkit

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#865]
General information about WET

http://www.howto.gov/training/classes/canada-web-experience-toolkit

Format: Webinar
Date:   Wednesday, April 17, 2013
Time:   1:30–2:30 PM ET
Fee:    Free
Presenters: Paul Jackson, Government of Canada
Description
Ever wish all federal government websites were run on common components that are accessible and secure? The Government of Canada has taken this unique approach to Web management and built a platform of standards-compliant (W3C and WCAG) components that its agencies use to build and maintain their sites. Each website can apply unique themes to control its look and feel, but the themes all run on top of these common components, ensuring their sites are accessible and secure. The reusable components of the Web Experience Toolkit (WET) are open source software and free for use by departments and external Web communities. 
Join us for a special presentation by Paul Jackson, from the Treasury Board of Canada Secretariat (Canada’s counterpart to OMB), who will provide an overview of WET, and discuss how it’s revolutionized the way the Government of Canada manages its digital properties.  
What You'll Learn 
During the webinar you'll learn:
What's in the Web Experience Toolkit
Why and how it was built
What benefits/outcomes the Canadian government has seen since implementing the toolkit
Considerations for U.S. Web managers 
Who Should Attend
Anyone interested in learning what is happening across international governments.
About the Presenter
Paul Jackson is the project lead and one of the lead developers for Canada's Web Experience Toolkit. In 2009, he established the framework for open collaborative development within the Government of Canada that evolved into the Web Experience Toolkit project. He further built upon that success by leading the effort in 2012 to move the project to GitHub as a public open source project to enable collaboration across jurisdictions and private organizations. He has also co-developed several standards for the Government of Canada including the Standards on Web Accessibility, Web Usability and Web Interoperability as well as the newly released Standard on Optimizing Websites and Applications for Mobile Devices.

**Comment by StephenOTT** [comment]
@pjackson28
