### ISSUE TITLE
Lots of warning messages and one segmentation fault

### ISSUE THREAD

**Issue by joejoseph00** [wet-boew/wet-boew-drupal#867]
@sylus 
I just deployed the latest from the master repo and got various warnings and 
one "Segmentation fault".  I did some investigation about the warnings, apparently modules that are in dev (not beta or release) most often do not have a .po file available online.  This explains the warning messages, however I'm not sure why I'm getting a segmentation fault when the build is trying to apply a patch for l10n_client.module_0.patch

Is anyone else getting this segmentation fault ?

I'm using   git version 1.7.12.4
                drush version 5.8
                php version 5.3.8

the segmentation fault occurs when git apply is called

Unable to download translations for wetkit: fr                        [warning]
Unable to download translations for panopoly_users: fr                [warning]
Unable to download translations for panopoly_magic: fr                [warning]
Unable to download translations for panopoly_widgets: fr              [warning]
Unable to download translations for panopoly_admin: fr                [warning]
Unable to download translations for panopoly_theme: fr                [warning]
Unable to download translations for panopoly_images: fr               [warning]
Unable to download translations for panopoly_core: fr                 [warning]
Unable to download translations for tao: fr                           [warning]
Unable to download translations for path_breadcrumbs: fr              [warning]
Unable to download translations for rubik: fr                                                         

Unable to download translations for workbench: fr                     [warning]
Unable to download translations for workbench_moderation: fr          [warning]
Unable to download translations for views_atom: fr                    [warning]

Unable to download translations for linkchecker: fr                   [warning]

Unable to download translations for fences: fr                        [warning]
Unable to download translations for diff: fr                          [warning]
Unable to download translations for better_formats: fr                [warning]
Unable to download translations for advanced_help: fr                 [warning]
Unable to download translations for metatag: fr                       [warning]

Unable to download translations for bean_panels: fr                   [warning]
Unable to download translations for bean: fr                          [warning]
Unable to download translations for variable: fr                      [warning]
Unable to download translations for migrate: fr                       [warning]

> > sh: line 1: 26395 Segmentation fault      GIT_WORK_TREE=. git apply --check -p1 /tmp/make_tmp_1366132137_516d85a99d7c1/l10n_client.module_0.patch --verbose 2>&1

Unable to download translations for i18n_panels: fr                   [warning]
Unable to download translations for i18nviews: fr                     [warning]

Unable to download translations for title: fr                         [warning]
Unable to download translations for entity_translation: fr            [warning]
Unable to download translations for search_api_db: fr                 [warning]
Unable to download translations for search_api_solr: fr               [warning]
Unable to download translations for facetapi: fr                      [warning]
Unable to download translations for caption_filter: fr                [warning]
Unable to download translations for search_api: fr                    [warning]
Unable to download translations for image_resize_filter: fr           [warning]
Unable to download translations for linkit: fr                        [warning]
Unable to download translations for wysiwyg_filter: fr                [warning]
Unable to download translations for wysiwyg: fr                       [warning]

**Comment by sylus** [comment]
This is now fixed! Can you try again, please reopen if problem persists
