### ISSUE TITLE
Alt Tags & Media Module

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#87]
Until this issue gets closed in the media module, this is going to remain a critical problem with the distro - http://drupal.org/node/1307054

If you have a chance, please test this so that it can be marked RTBC in Drupal's issue queue.

**Comment by sylus** [comment]
Added the two relevant patches to file_entity and media... Everything looks good but will likely require keeping this issue open till more testing can be done. However patches are in and functional.

**Comment by sylus** [comment]
Thinking this can be closed? Everything seems to work for alt tags :)
