### ISSUE TITLE
Search language toggle

### ISSUE THREAD

**Issue by MaddyDaigle** [wet-boew/wet-boew-drupal#874]
Hello,

We are using a fairly recent copy of WET Drupal (about a month ago was when we updated).  The value of the search button is not translated in French. I've been looking around in the code for where that value is set and I also looked in admin/config/search/custom_search/results but I can't find where to set the language or the option to set it.  String translation also isn't giving me any luck as it is not showing up to be translated.  Any help would be much appreciated, as this is the last thing keeping us from going live (we hope!)

Thanks!

Maddy

**Comment by RobJohnston** [comment]
Agreed it's a problem.  My install from 2 days ago doesn't translate the search button either.

**Comment by sylus** [comment]
I think you may need to manually update custom search module: http://drupal.org/node/731212/commits

http://drupal.org/node/1365874
http://drupal.org/node/1905356

Perhaps one of these issues? I'll take a further look tonight and try to track down where this was fixed.

**Comment by MaddyDaigle** [comment]
Great!  Thank you so much for pointing me in the right direction.  I'll look into this today. :)

**Comment by pclatney** [comment]
I was able to get this to work by going to Custom Search 1 block structure/block/manage/custom_search_blocks/1/configure and saving it. Then under Translate Interface I added the translation to this string custom_search:common:1:blocks_1_submit_text which wasn't there initially.

Hope that helps

**Comment by StephenOTT** [comment]
@MaddyDaigle can we close or still need more info?

**Comment by sylus** [comment]
This is for sure fixed, so closing :)
