### ISSUE TITLE
How to integrate the Splash page in the WetKit

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#878]
I couldn’t get in the issue #280 if the WetKit has a solution for the splash page, and I couldn’t find any option for that. 

Hey! @sylus, how did you implement it in the StatsCan?

My first idea was to modify the html.tpl.php template adding the following condition, but I’m not sure where $splash should be defined. 
    <?php if ($splash) ?>
            <?php print $page_splash; ?>
        <?php else; ?>
            <?php print $page_top; ?>
            <?php print $page; ?>
            <?php print $page_bottom; ?>
    <?php endif; ?>

I also tried the Splashify module, but it is not working.

Has someone else find a solution for this?

**Comment by RobJohnston** [comment]
We just have a plain old HTML page sitting at the root of the site and the order set in the web server is to serve splash.html before index.php, or splash_site1.html in the case of multisite.  Cheap hack.

**Comment by ssari** [comment]
Thanks Rob. BTW, nice picture!

That seems the best solution for now. 
I'll leave open the issue, in case someone has some idea of how to implement in the wetkit.

So summarizing.
- Add the HTML splash page (index.html) in the webdoc root;
- Add splash page (index.html) in the .htaccess file 
  example:
  ..................................................................................................
  # Set the default handler.
  DirectoryIndex  index.html  index.php   index.htm

**Comment by sylus** [comment]
Honestly for a splash page I agree that it makes complete sense to me to just use the web server or if using varnish leverage the vcl. You can change the paths to look at /profiles/wetkit/libraries/wet-boew so don't have to download two separate repo's.
