### ISSUE TITLE
How to fix Mega Menu IE problems?

### ISSUE THREAD

**Issue by katgarson** [wet-boew/wet-boew-drupal#879]
Hi, I noticed some serious issues with the mega menu in most versions of IE. Looking at https://github.com/wet-boew/wet-boew-drupal/issues/776 and https://github.com/wet-boew/wet-boew-drupal/issues/758 there seem to be some fixes for it coming in the RC2. I was just wondering how we can go about fixing this in our current RC1 installation without having to upgrade? Is there a patch?

Thanks

**Comment by ssari** [comment]
The mega-menu should be working for wetkit-rc1 in simple implementations.
Be carefull with the use of <span> tag. 
It seems the rc2 will have new module, and I also would like to have a patch.

**Comment by nrc-cnrc-web** [comment]
Can you post a screenshot of your megamenu (not the HTML output, but the Drupal megamenu list page itself)?

**Comment by ssari** [comment]
As I mentioned, this is a simple implementation. 
![issue - mega menu](https://f.cloud.github.com/assets/1461809/411242/6c10eeee-ab84-11e2-9fdf-42cf917fe3aa.png)

**Comment by nrc-cnrc-web** [comment]
I meant @katgarson - sorry! Mine is working fine; I was going to try to help.  :-)

**Comment by trainingcity** [comment]
I'm new to the wet distro so not sure if this is an option but I have been
using the Superfish menu with great success recently.  If it is available
in wet you may want to take a look and see if it can solve your problem.

On Tue, Apr 23, 2013 at 1:30 PM, nrc-cnrc-web notifications@github.comwrote:

> I meant @katgarson https://github.com/katgarson - sorry! Mine is
> working fine; I was going to try to help. :-)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wet-boew/wet-boew-drupal/issues/879#issuecomment-16873410
> .

## 

Thanks... John

John Downing
John@TrainingCity.com
613-435-1170 (w)
613-883-1235 (c)
johndowning (Skype)
www.twitter.com/TrainingCity

**Comment by katgarson** [comment]
Hi @nrc-cnrc-web I could post it but it doesn't fit in one screenshot. It's a complicated enough menu, 3 layers deep, some with <nolink>, some disabled, and both English and French.

At this point it doesn't look like we would be able to upgrade to RC2 even if it was available, so I'm trying to figure out how we can patch this in our existing installation.

Thanks

**Comment by ssari** [comment]
Since your menu  is woking @nrc-cnrc-web, I wonder if you are using the <span> or <separator> tags.
If so, how do you manage it to no be shown in the breadcrumbs.
Thanks.

**Comment by sylus** [comment]
Honestly the best bet would be to switch to RC2 once is released. Technically we are ready to release RC2 now but an upgrade path was promised so is going to take at least a week to make sure RC1 -> RC2 works.

**Comment by sylus** [comment]
@katgarson can you explain why you wouldn't be able to upgrade to RC2? There are more then a few benefits to the upgrade. It should also be a turn key upgrade so not sure why you wouldn't want to update? Particularly for security and code improvements.

**Comment by nrc-cnrc-web** [comment]
@ssari I used a taxonomy and the Taxonomy Breadcrumb module to display it. Not an ideal solution, but was quick to set up, and it worked.

Noob GitHub question: Do we have access to the current RC2 build from GitHub, should we want to test out a fresh install? I'm anxious to try it out.  :-)

**Comment by sylus** [comment]
Closing old issue(s).
