### ISSUE TITLE
URL alias is not displayed using Linkit module

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#891]
When Linkit is enabled in the Wysiwyg profile (admin/config/content/wysiwyg/profile/wetkit_wysiwyg_text) the target path is set “node/node_id”, and the URL is shown as “http://domain/node/node_id” 

This issue was posted in 
                              http://drupal.org/node/1322432, and 
                              http://drupal.org/node/1526284 

Not sure which version of the Linkit is included in the WetKit 7.x-1.0-rc1, but the Linkit project still has some related issues: 
http://drupal.org/project/issues/linkit?text=alias&status=All&priorities=All&categories=All&version=7.x&component=All 

Did I miss something in the WetKit configuration?

Should we add http://drupal.org/project/pathologic ?

Thanks,

**Comment by joel-osc** [comment]
Pathologic will take care of this, may be worth adding to the distro unless there are other better options available.

**Comment by ssari** [comment]
Thanks @joel-osc  for your support.

Pathlogic it seems working for this purpose, although it has some issues with TinyEMC
(http://drupal.org/node/257026 - WYSIWYG editor compatibility)

@joejoseph00

**Comment by ssari** [comment]
@sylus Will, could you have a look in this issue.
For now, Pathologic is working, but I'm not sure if it the solution, and you may review for RC2.
Thanks.

**Comment by sylus** [comment]
Thanks will take a look. If you can please file any other issues you have. As RC2 is coming soon and I'd like to have most bugs fixed.

**Comment by sylus** [comment]
This has been fixed upstream :)
