### ISSUE TITLE
Breadcrumbs should not display Menu separator

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#892]
In the WetKit 7.x-1.0-rc1 suggests to use the menu link title “span” with path “<separator>”, which nicely displays the sub-menu without having a sub-title. 

However, this title “span” is also shown in the breadcrumbs.

Digging the code, I tried to modify, with no effect, the template template-breadcrumb.inc (wetkit\profiles\wetkit\themes\wetkit_adaptivetheme\templates\inc) where the variable $separator is defined. 

The template wetkit_breadcrumbs.theme.inc – (wetkit\profiles\wetkit\modules\custom\wetkit_breadcrumbs\theme) in wetkit_breadcrumbs module, which integrates PathBreadCrumbs module, doesn’t deal with the separator. And, it might be the problem.

What could be a fast solution for it ?

**Comment by joel-osc** [comment]
Quick solution may be to use this - http://api.drupal.org/api/drupal/modules!system!system.api.php/function/hook_menu_breadcrumb_alter/7.

RC2 this is no longer an issue as spans are not necessary in the menu tree.

**Comment by mxlav** [comment]
You can also get around this by using Path Breadcrumbs..

**Comment by ssari** [comment]
Thanks Joe and Mark.

I've been working in two venues. 
1) Testing different settings and creating different paths in the Path Breadcrumbs, and
2) modifying the templates template-breadcrumb.inc and template-menu-blocks.inc
Unfortunately, I don't have the solution yet.

If I'm not wrong, Joe's suggestion implies to disable wetkit_breadcrumbs. Is this correct?

**Comment by joel-osc** [comment]
It is standard on a Drupal site you create your own small module for your 'glue' code. For my solution, all you need to do is invoke the hook mentioned above  in your module and remove the items that you don't want. No template changes required.

**Comment by ssari** [comment]
Thank you all.
My easy way around was to use the "Special menu items"
http://drupal.org/project/special_menu_items
