### ISSUE TITLE
TinyMCE with GoC plugins vs CKEditor

### ISSUE THREAD

**Issue by joejoseph00** [wet-boew/wet-boew-drupal#898]
Some of our stakeholders are weighing in:

"I like TinyMCE and I really like the enhancements we did"
"The 'accessibility' around CK is about the accessibility of the editor NOT the ability of the editor to support accessible coding."

So what (TinyMCE and GoC plugins already do) is strip code of extraneous things and the ability to tag up complex tables with headers and IDs properly.  Without these, I don't think we can or should do the change to CKEditor. These were really key changes that have allowed us to do some key tasks far more efficiently. If CK does not have this or the ability to port our functions to it, I cannot see using it.

And the E|F splitter is really a Secretariat requirement and we should confirm if and how this is still be used, and if there are alternatives.  ( the E|F splitter copies the french from a document with a table of bilingual content and places it into the french side of the bilingual side-by-side editor , this feature works at CTA on our legacy D6 site, but has not yet been added to the WETBOEW distribution plugins and has not yet been tested with the UOttawa side-by-side editor.)

**Comment by joejoseph00** [comment]
add @sylus 

I'll keep bugging our stakeholders to take a closer look at CKEditor, meanwhile could you perhaps have your stakeholders perhaps explain how they are living without the features that TinyMCE and the GoC plugins provide?

**Comment by joejoseph00** [comment]
Our group has looked at CKEditor, I'll provide some in depth comments/feedback shortly.

Meanwhile, check out these tiny apples:

Step 1, paste bilingual content from word
![1](https://f.cloud.github.com/assets/1028526/477883/520abb28-b7ec-11e2-8c7c-fc92078a8d69.png)

Second step, select split F|E  (in our case the French is on the left side, others might chose split E|F)
![2](https://f.cloud.github.com/assets/1028526/477882/520bd6fc-b7ec-11e2-84f7-64468c20ad1d.png)

Here's the result, table is gone on left, column content is split appropriately.
![3](https://f.cloud.github.com/assets/1028526/477881/51f69bac-b7ec-11e2-8776-fb0f9f91c8e0.png)

**Comment by StephenOTT** [comment]
@joejoseph00 why do you use tables for layout?

**Comment by StephenOTT** [comment]
The decision about which WYSIWYG editor that is "standard" should not be based on the current development of the "GoC plugin" as that development could change or end at any time.  

Multiple editors could be running at the same time so users that needed to use the TinyMCE plugin tools could still use those.

The thinking that needs to occur is about ongoing support, ease of use in the core product, documentation, maturity and development paths of the product, ease of extendibility, as well as community involvement.  With CKeditor becoming the standard for Drupal, we will likely see a lot more development occurring that is CKEditor based.

I believe that Drupal UG did some analysis of the different editors that is public.  Will try and find and share.

**Comment by joejoseph00** [comment]
Our Comms department writes bilingual documents using Tables in Microsoft Word or Corel Word Perfect where French is on the left and English is on the right side.

I've seen bilingual documents in other departments written with Microsoft Word or Word Perfect in a similar fashion.

It's the official Government documents that are written this way before they are published on the website.

**Comment by sylus** [comment]
A feature-tinymce branch was created in wet-boew-wem/wetkit_wysiwyg and @joejoseph00 has been given push and pull access to update :) Welcome to maintainership! :)
