### ISSUE TITLE
Path BreadCrumbs doesn’t translate path

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#901]
I couldn’t translate the breadcrumb because there is no field to translate the path, as shown in the picture. Is this supposed to happen?

So, I created ENG and FRA breadcrumbs, which work fine but one. This breadcrumb has rules including node:type, node:language, and node my_content: my_field . All criteria are passing in ENG but not in FRA. Bizarre!

I couldn’t find any lead in http://drupal.org/project/issues/path_breadcrumbs.

Any idea?
![issue - PathBreadCrumbs](https://f.cloud.github.com/assets/1461809/433221/df32435a-aec2-11e2-8c84-72440dcaac8d.png)

**Comment by sylus** [comment]
Ah I know what is going on, what you have to do for each area you use my_content:my_field is append i18n_name after so my_content:my_field:i18n_name this should resolve your problem. I'll file an issue with the module as it doesn't make this appear in the dropdown.
