### ISSUE TITLE
collapsible.inc Duplicate functions [Bug Report]

### ISSUE THREAD

**Issue by alar2** [wet-boew/wet-boew-drupal#905]
wet-boew-drupal / modules / custom / wetkit_core / plugins / styles / collapsible / collapsible.inc

Fatal error: Cannot redeclare theme_wetkit_core_collapsible_render_region() (previously declared in C:\Documents and Settings\arothmel\Sites\drupal_wet\profiles\wetkit\modules\custom\wetkit_core\plugins\styles\collapsible.inc:55) in C:\Documents and Settings\arothmel\Sites\drupal_wet\profiles\wetkit\modules\custom\wetkit_core\plugins\styles\collapsible\collapsible.inc on line 62

I had to add check if function exists for each function on this page:
/\* ------------------------------------------------------------------------------------
if (!function_exists('wetkit_core_collapsible_region_settings_form')) {
}

 if (!function_exists('wetkit_core_collapsible_pane_settings_form')) { 
}

if (!function_exists('wetkit_core_collapsible_pane_settings_form')) { 
}

  if (!function_exists('theme_wetkit_core_collapsible_render_region')) {
}

  if (!function_exists('theme_wetkit_core_collapsible_render_pane')) {
}

if (!function_exists('theme_wetkit_core_collapsible')) {
}
-------------------------------------------------------*/
But the good news is that was my only error on my Windows XP install at work :)

Status message

Thank you for installing the WxT-Drupal Variant for the Web Experience Toolkit. You may login at the following page: User Login

:)

Following: https://github.com/wet-boew/wet-boew-drupal/wiki/Download%2C-Installation%2C-and-Update

**Comment by sylus** [comment]
Fixed in latest dev
