### ISSUE TITLE
webkit css warnings in Firefox 20.01

### ISSUE THREAD

**Issue by joejoseph00** [wet-boew/wet-boew-drupal#906]
background-image:-webkit-linear-gradient(top,#333,#666)

Firefox 20.01 is complaining that the word "top" is not what it's expecting saying that there should be a colour value here.

This could be because Firefox is not wanting to use legacy css naming.  This might affect the latest version of Chrome as well.

http://caniuse.com/css-gradients

**Comment by joejoseph00** [comment]
I see something similar here:
Horodatage : 2013-05-06 09:24:49
Warning : Expected color, but found « bottom » instead.  Error processing the value for « background-image ».  Declaration skipped.
Source : /profiles/wetkit/libraries/wet-boew/dist/theme-gcwu-fegc/css/theme-min.css?mm8noq

**Comment by pjackson28** [comment]
@joejoseph00 Checking on Webkit.org, the Webkit version of the linear gradient is being implemented correctly. Here is an example taken from the site where the first value is not a colour:

 -webkit-linear-gradient(left, white, black)
Source: https://www.webkit.org/blog/1424/css3-gradients/

As for the warning, I can't really comment as I don't know the tool used and don't know what is the line of code that is triggering the warning.

**Comment by joejoseph00** [comment]
@pjackson28  I was trying to figure out what's going on.  Is this function webkit-linear-gradient part of the wetboew?  Or is it part of JQuery or some other tool?  It seems there's a lot of places it's being used.

So far I've found the following files containing "webkit-linear-gradient"

./themes/bartik/css/colors.css
./profiles/wetkit/modules/panopoly/panopoly_core/css/panopoly-jquery-ui-theme.css
./profiles/wetkit/modules/panopoly/panopoly_magic/css/panopoly-modal.css
./profiles/wetkit/modules/panopoly/panopoly_admin/panopoly-admin.css
./profiles/wetkit/modules/contrib/panels/panels_ipe/css/panels_ipe.css
./profiles/wetkit/modules/contrib/views/css/views-admin.seven.css
./profiles/wetkit/modules/contrib/views/css/views-admin.garland.css
./profiles/wetkit/modules/contrib/views/css/views-admin.theme.css
./profiles/wetkit/modules/contrib/views/css/views-admin.bartik.css
./profiles/wetkit/modules/contrib/facetapi/facetapi.admin.css
./profiles/wetkit/modules/custom/wetkit_core/sass/wetkit_core.scss
./profiles/wetkit/modules/custom/wetkit_core/css/wetkit_core.css
./profiles/wetkit/modules/custom/wetkit_layouts/css/layouts.css
./profiles/wetkit/libraries/ckeditor/skins/moono/editor.css
./profiles/wetkit/libraries/ckeditor/skins/moono/dialog_ie7.css
./profiles/wetkit/libraries/ckeditor/skins/moono/editor_gecko.css
./profiles/wetkit/libraries/ckeditor/skins/moono/dialog.css
./profiles/wetkit/libraries/ckeditor/skins/moono/dialog_opera.css
./profiles/wetkit/libraries/ckeditor/skins/moono/editor_iequirks.css
./profiles/wetkit/libraries/ckeditor/skins/moono/editor_ie.css
./profiles/wetkit/libraries/ckeditor/skins/moono/dialog_ie8.css
./profiles/wetkit/libraries/ckeditor/skins/moono/dialog_iequirks.css
./profiles/wetkit/libraries/ckeditor/skins/moono/editor_ie7.css
./profiles/wetkit/libraries/ckeditor/skins/moono/editor_ie8.css
./profiles/wetkit/libraries/ckeditor/skins/moono/dialog_ie.css
./profiles/wetkit/libraries/ckeditor/ckeditor.js
./profiles/wetkit/libraries/tinymce/1561882-cirkuit-theme-tinymce-3.5.8.patch
./profiles/wetkit/libraries/tinymce/jscripts/tiny_mce/themes/advanced/skins/cirkuit/dialog.css
./profiles/wetkit/libraries/wet-boew/dist/grids/css/util-min.css
./profiles/wetkit/libraries/wet-boew/dist/theme-gcwu-fegc/css/jquery.mobile-min.css
./profiles/wetkit/libraries/wet-boew/dist/theme-gcwu-fegc/css/theme-min.css
./profiles/wetkit/libraries/wet-boew/dist/theme-gcwu-intranet/css/jquery.mobile-min.css
./profiles/wetkit/libraries/wet-boew/dist/theme-gcwu-intranet/css/theme-min.css
./profiles/wetkit/libraries/wet-boew/dist/js/css/pe-ap-min.css
./profiles/wetkit/themes/wetkit_rubik/sass/wetkit_rubik.scss
./profiles/wetkit/themes/wetkit_rubik/css/wetkit_rubik.css
./profiles/wetkit/themes/wetkit_shiny/sass/_base.scss
./profiles/wetkit/themes/wetkit_shiny/css/shiny.css

**Comment by pjackson28** [comment]
@joejoseph00 It is used by WET and 3rd party solutions such as jQuery Mobile to provide CSS gradient support in Webkit browsers. It is currently necessary since even the latest version of Safari doesn't support linear gradients without the -webkit prefix (http://caniuse.com/css-gradients).

**Comment by joejoseph00** [comment]
@pjackson28   yes of course :)  ok, so that helps narrow things down a bit.  Also reveals that there's a lot of deprecated css in not only wetboew but in all those above css files.  

OK, I've narrowed this down a bit more:

if your string 'webkit-linear-gradient(top' is found in public_html/distro, the filename will show up below

./themes/bartik/css/colors.css
./profiles/wetkit/libraries/ckeditor/skins/moono/editor.css
./profiles/wetkit/libraries/ckeditor/skins/moono/dialog_ie7.css
./profiles/wetkit/libraries/ckeditor/skins/moono/editor_gecko.css
./profiles/wetkit/libraries/ckeditor/skins/moono/dialog.css
./profiles/wetkit/libraries/ckeditor/skins/moono/dialog_opera.css
./profiles/wetkit/libraries/ckeditor/skins/moono/editor_iequirks.css
./profiles/wetkit/libraries/ckeditor/skins/moono/editor_ie.css
./profiles/wetkit/libraries/ckeditor/skins/moono/dialog_ie8.css
./profiles/wetkit/libraries/ckeditor/skins/moono/dialog_iequirks.css
./profiles/wetkit/libraries/ckeditor/skins/moono/editor_ie7.css
./profiles/wetkit/libraries/ckeditor/skins/moono/editor_ie8.css
./profiles/wetkit/libraries/ckeditor/skins/moono/dialog_ie.css
./profiles/wetkit/libraries/ckeditor/ckeditor.js
./profiles/wetkit/libraries/tinymce/1561882-cirkuit-theme-tinymce-3.5.8.patch
./profiles/wetkit/libraries/tinymce/jscripts/tiny_mce/themes/advanced/skins/cirkuit/dialog.css
./profiles/wetkit/themes/wetkit_shiny/sass/_base.scss
./profiles/wetkit/themes/wetkit_shiny/css/shiny.css

**Comment by joejoseph00** [comment]
Now I see how it could be easy to be confused by wetkit and webkit.

BTW, my browser that I am testing with is Firefox 20.0.1 .  Radical changes have been made to firefox in the past 6 months.  when version 16 came out in January they changed rendering engines.

**Comment by joejoseph00** [comment]
Basically if I understand this correctly, this warning is telling us that certain browsers like Firefox 20.01 probably won't render legacy webkit gradients correctly so skipping webkit calls that it doesn't understand.  So there would be slight visual differences between browser versions.

It seems like a lot of people are testing this on Safari browsers so they probably don't notice this in Safari.

So fixing this would probably break current versions of Safari but not future versions of Safari that will eventually adopt the new standard.

**Comment by pjackson28** [comment]
In all those cases, the gradients are specified in multiple ways. They are specified with the normal CSS3 linear-gradient approach, the -webkit approach and in some cases the -moz approach. Firefox is correctly ignoring the -webkit approach and instead uses the CSS3 linear gradient approach in recent versions and the -moz approach in older versions.

So you can safely ignore any -webkit warning in Firefox just like you can safely ignore any -moz warning in Webkit.

**Comment by joejoseph00** [comment]
Ok, sounds good, we can close this issue then.
