### ISSUE TITLE
custom formatter for Canadian Currency localisation French and English

### ISSUE THREAD

**Issue by joejoseph00** [wet-boew/wet-boew-drupal#907]
@sylus 
We should probably include a currency formatter for Canadian Dollars correctly localized for French and English.

At the end of this post is a working custom formatter that does the following:
See it in action here: 
http://wet.7pro.ca/~joseph/aidedisplaysuite/fr/pd-contract
and
http://wet.7pro.ca/~joseph/aidedisplaysuite/pd-contract

Currency localized in English is $ 90,000.02 
Currency localized in French  is 90 000,02 $ 

Should we be  using the contrib module "http://drupal.org/project/custom_formatters"
for creating display types or is there a "new" panopoly way to do this without the contrib module?  I noticed that "Custom Formatter" is not included with the latest version of weboew , perhaps because Panopoly only supports US English currency?  Or perhaps because there may have been a new paradym shift in formatting/localizing Drupal fields?

$formatter = new stdClass();
$formatter->disabled = FALSE; /\* Edit this to true to make a default formatter disabled initially */
$formatter->api_version = 2;
$formatter->name = 'wetboew_money_cdn';
$formatter->label = 'wetboew_money_cdn';
$formatter->description = 'Canadian Dollars - Dollars Canadien';
$formatter->mode = 'php';
$formatter->field_types = 'number_decimal, computed';
$formatter->code = 'global $language;

$amount = $variables[\'#items\'][0][\'value\'];

if ($language->language == \'en\') {
      $amount = \'$ \' . number_format($amount, 2, \'.\' , \',\' );
}  elseif ($language->language == \'fr\') {
     $amount = number_format($amount, 2, \',\' , \' \' ) . \' $\';
}

return $amount;
';
$formatter->fapi = '';

**Comment by sylus** [comment]
Hey I actually had custom_formatters being used in an earlier version of distro but felt that since custom_formatters allows for what it creates to be exportable to drupal api would reduce another module dependency.

I love the module and do use it in most of my setups though. We could add it back but definitely not looking to add any more dependencies without clear benefits unless people want otherwise :)

**Comment by joejoseph00** [comment]
@sylus , so if custom_formatters allows for what it creates to be exportable to drupal api could we include the wetboew_money_cdn without the dependancy and still use it on fields through the GUI?

$formatter = new stdClass();
$formatter->disabled = FALSE; /\* Edit this to true to make a default formatter disabled initially */
$formatter->api_version = 2;
$formatter->name = 'wetboew_money_cdn';
$formatter->label = 'wetboew_money_cdn';
$formatter->description = 'Canadian Dollars - Dollars Canadien';
$formatter->mode = 'php';
$formatter->field_types = 'number_decimal, computed';
$formatter->code = 'global $language;

$amount = $variables[\'#items\'][0][\'value\'];

if ($language->language == \'en\') {
$amount = \'$ \' . number_format($amount, 2, \'.\' , \',\' );
} elseif ($language->language == \'fr\') {
$amount = number_format($amount, 2, \',\' , \' \' ) . \' $\';
}

return $amount;
';
$formatter->fapi = '';

**Comment by sylus** [comment]
Ideally for this another module could be created perhaps called wetkit_formatters, not very sure. Can leave this up to you but when a module is built can add it to wet-boew-wem.

**Comment by joejoseph00** [comment]
Would a feature be sufficient?  create a feature called wetkit_formatters?  include the obvious money_cad custom formatter?

**Comment by sylus** [comment]
Yeah feature / module is fine as long as a tight use case. You should have access to create a repo in wet-boew-wem

**Comment by joejoseph00** [comment]
Hi @sylus, I was unable to create a repo for wet-boew-wem "You don't appear to have permission to create repositories for this organization. Sorry about that. "

So instead I created a repo for the money_canadian custom formater under my name, it needs to be moved over to wet-boew-wem ,  it's basically just a feature for money_canadian using the custom formatters module as a dependancy (and ctools of course).

Here's the url, https://github.com/joejoseph00/wetkit_custom_formatters

**Comment by joejoseph00** [comment]
Hi @sylus , can this be re-openned?  There's a urgent request for this in Jira.

I believe that the currency formatter should be part of the distro, every govt agency dept will eventually need this .
