### ISSUE TITLE
Fix support for Boxes plugin for panels css ids and classes

### ISSUE THREAD

**Issue by minorOffense** [wet-boew/wet-boew-drupal#908]
The CSS class specified in Panels is missing a space before the generated classes are added. I'm unsure if this is a bug with Boxes of the wetkit boxes.

**Comment by sylus** [comment]
Boxes have been replaced  to Beans about 4 months ago? Are you referring to Beans generated classes? The wetkit boxes module no longer exists and hasn't for some time.

**Comment by sylus** [comment]
Thinking this is closed, please reopen if something I am missing.
