### ISSUE TITLE
GTEC / Awards / Prix de d'instinction / nomination status?

### ISSUE THREAD

**Issue by joejoseph00** [wet-boew/wet-boew-drupal#911]
Prix de d'instinction
http://www.gtec.ca/fr/renseignements-generaux-et-dates/?_mc=EMTWGT03

Awards
http://www.gtec.ca/awards/

**Comment by StephenOTT** [comment]
@sinkinsona

**Comment by sinkinsona** [comment]
We are working on submitting a joint nomination for the project and are hoping to have it completed soon.  @StephenOTT can we include the city?  I have contact many organizations that have implemented the distro but if I have not contacted you and you want to be part of nomination please let me know.
