### ISSUE TITLE
unable to create k://.drush

### ISSUE THREAD

**Issue by WayneWhitten** [wet-boew/wet-boew-drupal#919]
I'm getting this error occasionally during the make process and wondering if it's a real problem.  If so, I need to know how to fix.  The other steps in the process seem to run OK.

I also have a problem with both cloning step in these instructions:
https://github.com/wet-boew/wet-boew-drupal/wiki/Download%2C-Installation%2C-and-Update  
The process hangs at the end, and I don't get the .make file or any other files.

I've tried the following alternate instructions, but they didn't prove any better.
https://github.com/wet-boew/wet-boew-drupal
The make process out-right fails.

So I'm trying another method by extracting the zip into the drupal_wet directory, and currently running the make process but still getting the "unable to create k://.drush" error.

**Comment by nrc-cnrc-web** [comment]
I had tons of problems (Windows 7, 64-bit) using Drush. Here's how I got mine working:
1. Download and install GitBash 1.8 --> https://code.google.com/p/msysgit/downloads/detail?name=Git-1.8.3-preview20130601.exe&can=2&q=full+installer+official+git
2. Download and unpackage Drush for Drupal 8 (Drush 6) --> http://ftp.drupal.org/files/projects/drush-8.x-6.x-dev.tar.gz
3. If running Windows, update your PATH to include reference to Drush/PHP/MySQL (mine looks like this: C:\drush;C:\Program Files (x86)\acquia-drupal\php5_4;C:\Program Files (x86)\acquia-drupal\mysql\bin)
4. Open Git Bash and run these commands (modify paths to suit your preference and installation):
   
   git clone https://github.com/wet-boew/wet-boew-drupal.git c/git/wet-boew-drupal/profiles/wetkit;
   
   drush make --prepare-install --no-gitinfofile --working-copy c/git/wet-boew-drupal/profiles/wetkit/build-wetkit.make drupal_wet --yes --no-clean -v

You can then use the drush si command on the wiki page to install, or do what I do and install via the install.php script. It's longer but it works.

Cheers!

**Comment by sylus** [comment]
Sounds like this was fixed. Closing so can clear the issue queue.
