### ISSUE TITLE
Password Policy Module

### ISSUE THREAD

**Issue by pclatney** [wet-boew/wet-boew-drupal#920]
We recently experienced an issue with the Password Policy module where a user account expired and this caused the users content to be disabled. When we tried to reactivate the users account it forced the user to change the password but then the page freezes when we tried to save the changes. Not sure why the default setting is to disable/unpublish the content?

Is this a known issue? I have not been able to find anything reported on this one.

Thanks

**Comment by RobJohnston** [comment]
Don't know about the page freezing problem but for the future (if you haven't found it yet), I think you'll find the setting you need under /admin/config/people/accounts.  Yours might be set to "Disable the account and unpublish its content" and you want "Disable the account and keep its content".  

Alternately, set the password expiration to zero so they never expire under /admin/config/people/password_policy/1/edit.  This is a good option when using LDAP to not get into a password-reset conflict between Drupal and LDAP.

**Comment by pclatney** [comment]
Thanks for the response Rob. 

I am aware of the Account Settings page however even though the default of "Disable the account and keep its content" was selected the behavior was that the content was unpublished which basically broke the entire website.  We then were unable to reactivate the account because we could not successfully change the users password. I can only assume that the module is broken and causing this odd behavior. If I disable the module I can then update the users password with no issue.

**Comment by StephenOTT** [comment]
@pclatney are you able to reproduce this issue on a fresh install/default install of the Distro?

**Comment by joel-osc** [comment]
FYI, in checking the code for password_policy I don't think there is an issue with it - it does nothing to cause this when blocking an account:

function _password_policy_block_account($account) {
  if ($account->uid > 1) { // We never block the superuser account.
    db_update('users')
      ->fields(array(
        'status' => 0,
      ))
      ->condition('uid', $account->uid)
      ->execute();
...

The module does not even do a user_save which would trigger hook_update and potentially cause another module to do something wrong. Recreating this in a test environment would be good, even try it without password_expiry using the code above in /devel/php (enable devel module).

**Comment by pclatney** [comment]
Thanks for the suggestions. I will do some more testing to see if I can pinpoint the issue.

**Comment by RobJohnston** [comment]
Maybe related:
"Users with expired passwords that get blocked by cron, when unblocked by admin, get reblocked on login"
https://drupal.org/node/1711518

**Comment by sylus** [comment]
Closing this issue since inactive but please reopen if problems persist.
