### ISSUE TITLE
github permissions

### ISSUE THREAD

**Issue by joejoseph00** [wet-boew/wet-boew-drupal#922]
@sylus ,  does anyone other than you have access to merge code or to assign tasks in this git repository?

I was trying to fix something (didn't find the code that needs to be fixed) and asked myself whether anyone other than you would be merging any fixes.

There's a minor problem with the home page  (see graphic below)
![github_link_wetboewdrupal_points_to_wetboew](https://f.cloud.github.com/assets/1028526/556644/b754118a-c3dd-11e2-97f0-1671532ebc43.png)

if you check your base install of the distro, the GITHUB menu right side links to wet-boew instead of wet-boew-drupal

**Comment by sylus** [comment]
Hey a few people do and always willing to add more qualified people.

Right now I think it is:

@sylus
@joel-osc 
@mgifford 
@LaurentGoderre 
@openplus 
@jmdeleon 
@pjackson28 

For the past 2 weeks I have been preoccupied with a huge launch coming out early June. Promises to be the most visible drupal project in canada gov but as such has required all of my attention.

The nice thing is a lot of these fixes will be coming into the distro based on this work. Including over 300 accessibility improvements as found by CSE Validator.

I want alot to happen for rc2 as I am thinking it will be the last RC before a official release. I promise to be more active next week but yeah definitely all for opening up the commit rights to qualified people.

**Comment by mgifford** [comment]
Good to hear that you found so many improvements via the CSE Validator http://www.htmlvalidator.com I haven't used it before.

Although there are a bunch of folks who can manage pulls, I think so far @sylus is the only one who has made them. We have the technical permission, but not the social permission.

**Comment by sylus** [comment]
I think now that the modules have been separated into individual repos and only the main install profile is in wet-boew/wet-boew-drupal it should be easier to get maintainers. Ideally I'd like to have some people in charge of individual modules. 

The GitHub repo's are aligned with the repos on drupal.org with the same name.

**Comment by mgifford** [comment]
Agreed that when it's in smaller chunks it will be easier to get folks to contribute. Thanks for doing that.
