### ISSUE TITLE
Improve docs on main feature additions

### ISSUE THREAD

**Issue by pmackay** [wet-boew/wet-boew-drupal#923]
Hi, I've reviewed most of the docs but am still finding it hard to see what the key improvements are that WxT provides on top of say Panopoly + AdaptiveTheme.  Could https://github.com/wet-boew/wet-boew-drupal/wiki/WxT-jQuery-and-Drupal-Integration and the following Drupal Experience Improvements sections in the wiki be filled out more?

The other reason why some of this is confusing is that the WxT core features (http://wet-boew.github.io/wet-boew/index-eng.html#benefits) describe some unique things and some things that parts of Drupal has anyway. So it would be great to highlight what WxT provides on top of Drupal functionality.

**Comment by StephenOTT** [comment]
Great point @pmackay 

@sinkinsona

**Comment by mgifford** [comment]
The documentation on what WET's modules do over the default Drupal modules is really important for adoption.

For instance, is it a better choice to simply work with the Deploy module (which has a community & documentation but whose maintainer is focusing on D8) or WET's Deploy (which @sylus uses and is working great for his needs, but possibly nobody else has used it, it only works in a WET environment and has no community or documentation behind it).

This is a huge challenge and the example above is just one example.  My view is that if you need to make a bilingual or multi-lingual site for an institution that also needs to be accessible, this is probably your best bet.  For folks outside the Government of Canada though, it may be more expensive and time consuming (at least for now) than simply going with Panopoly + AdaptiveTheme.

**Comment by sylus** [comment]
Documentation site is being worked on at wiki.drupalwxt.org which should address most of these needs.
