### ISSUE TITLE
DrupalCon Portland was amazing!!!

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#924]
This is a reminder that the DrupalCon presentations are available online.

Great keynotes (http://portland2013.drupal.org/news/watch-drupalcon-portland-live-stream-courtesy-brightcove) and informative presentations (http://portland2013.drupal.org/program/schedule/).

It was really nice to meet the Drupal community in particular people from Ottawa, Montreal and Waterloo.

**Comment by pmackay** [comment]
Hi Solange, sorry not to have met you, I had a good chat with Mike Gifford though. 

Is there a discussion forum, Google Group or similar for this project? Using issues seems an odd way of broadcasting information IMHO :)

**Comment by mgifford** [comment]
I've set up the following Google community:
https://plus.google.com/communities/112948632976528554438

Would be easy to set up a Google group too if that helps.
