### ISSUE TITLE
Post to commons?

### ISSUE THREAD

**Issue by pmackay** [wet-boew/wet-boew-drupal#925]
If WxT or WxT-Drupal have deployments in Canadian gov, what about to post the project and related deployments on http://commons.codeforamerica.org/ ?

**Comment by mgifford** [comment]
Posting to the CfA Commons sounds good.  It seems American, but if they are open to folks from the commonwealth posting...  A marketplace for open innovation in government is definitely useful.

The latest launch is http://www.data.gc.ca/

**Comment by sylus** [comment]
Issue has been open for a while so closing cause OCD about having the issue queue clean :)
