### ISSUE TITLE
Problem with the sidebar for the Wetkit Layout

### ISSUE THREAD

**Issue by elaberge74** [wet-boew/wet-boew-drupal#926]
Here my problem.

From Pages, I use the Layout "Dallaire" and "Penfield" from the category "wetkit Layout".  The sidebar box, for both of them, it's impossible to be able to click on the top-left button to add "content"...  It's ok with the Content, Top or Bottom...  And if I change setting for an existing one in this sidebar, all changes are discarded....

thanks

Eric

**Comment by mgifford** [comment]
URLs & screenshots are often useful to help track down these types of problems.

**Comment by RobJohnston** [comment]
I bet the URL is: 
/eng/admin/structure/pages/nojs/operation/page-panopoly_admin_layout_library/handlers/page_panopoly_admin_layout_library_panel_context/layout

And then choose "WetKit Layouts" in the drop-down.

@elaberge74, I've seen a similar problem in the past (not being able to add content) and my work-around was to add the content to another area and then drag-and-drop it into the place that I really wanted it.  Don't know about changes being discarded, but make sure you click the "Update and save" button and not just the "Update" button.

**Comment by mgifford** [comment]
Yup, that seems to be it.  I've added a screenshot:

![screen shot 2013-08-09 at 8 29 13 am](https://f.cloud.github.com/assets/116832/935968/cdaaa7f4-0097-11e3-993f-09da17475220.png)

**Comment by sylus** [comment]
This has been fixed and will be pushed in next dev / rc10 release.
