### ISSUE TITLE
Translation of Alt and Title tags for Media File Selector overwrites original tags

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew-drupal#927]
Related to issue #87, I think there may be more work required regarding the alt and title tags. 
Here's the scenario:
1. Add a new image field to the "Basic Page" content type and use the media file selector as the widget.
2. Create a new page with an image and enter the alt and title fields for it.
3. Translate the page to French and edit the alt and title fields of the image, as one edits all the other fields when translating.
4. Review the original English page and see that the alt and title fields have been overwritten with the French alt and title tags.

Is this a process problem or a deficiency in the media file selector?

**Comment by RobJohnston** [comment]
Looks like somebody else filed this issue upstream yesterday:
https://drupal.org/node/2017647

**Comment by sylus** [comment]
Is this still a problem I can try to figure out the exact steps we did for data.gc.ca but I am pretty sure it was steps 1-4 and it worked for us. 

Only step I think might be missing is going to file entity -> image and then manually ensuring the alt + title fields are set to translatable.

**Comment by RobJohnston** [comment]
I think I solved it in our case (read the related issues).  Not an intuitive process... seems like the media module has been going through some flux lately.  Whether one has an image display as "image" or "rendered file" makes all the difference.

**Comment by supermoos** [comment]
Did any of you find a way to enable alt and title translations? I have enabled the alt & title fields as translatable under the file types. And under /admin/config/regional/entity_translation, I've also tried both enabling and disabling field translation of the image field on my content type - seems to make no difference. The only thing that seems weird is that under my node content type edit form and the "Synchronize translations"-tab, no fields are available for synchronization?

Also @RobJohnston could you elaborate on the difference it makes to choose image display type - and where do you make this change?

**Comment by RobJohnston** [comment]
@lasseyls I've been away for 6 weeks and thought that was the end of my Drupal experience, so I didn't give this a bit of thought over that time.  The place to make the change was under the "Manage Display" tab of the content type and I recall that change made a huge difference in how the output was rendered.  Sorry for the late response!

**Comment by sylus** [comment]
This is baked into RC9 by default all File Types working with ET.
