### ISSUE TITLE
Notice: Undefined index: #children in wetkit_menu_menu_link_menu_block_sidebar() (line 160 of /home/www/drupal_wet/profiles/wetkit/modules/custom/wetkit_menu/theme/menu.theme.inc).

### ISSUE THREAD

**Issue by rousellb** [wet-boew/wet-boew-drupal#928]
Getting the following error message on most page. Using Firefox 17.0.4 on a Linux server. Seams to have started when I applied panels to the content type. The menus display but getting the error messages.

Screenshot
![screenshot_errors](https://f.cloud.github.com/assets/4116981/637121/0c02cdee-d29c-11e2-81a8-760692adfc4a.jpg)

Notice: Undefined index: #children in wetkit_menu_menu_link_menu_block_sidebar() (line 160 of /home/www/drupal_wet/profiles/wetkit/modules/custom/wetkit_menu/theme/menu.theme.inc).

**Comment by sylus** [comment]
Menu system has been completely refactored and tested on data.gc.ca.
