### ISSUE TITLE
TabInteface home page

### ISSUE THREAD

**Issue by elaberge74** [wet-boew/wet-boew-drupal#930]
I created a Content Type with a field as Tabbed Interface with number of value of 4.

I created a Variant from Pages where  I called the Tabbed Interface field.  

I dont know why, all images appear one under one... without apply the wet-boew-tabbedinterface 

Am I using the good way to use it ?

**Comment by StephenOTT** [comment]
@elaberge74 you need to use the Fieldable Panel Panes

Structure > Fieldable Panel Panes > Select Add on the Fieldable Panel Pane group:
![screen shot 2013-07-23 at 6 49 38 pm](https://f.cloud.github.com/assets/1994838/845534/32ed2e30-f3ea-11e2-8d86-4208a80401b7.png)

And then you add the fieldable panel pane using the Page Manager or IPE.  If you did not add a category to the FPP then it is under Misc.
![screen shot 2013-07-23 at 6 52 49 pm](https://f.cloud.github.com/assets/1994838/845556/9ec931d0-f3ea-11e2-91d8-e56b1ecca12c.png)

**Comment by sylus** [comment]
FPP + Tabbed Interface is gone in favor of beans and to further simplify codebase.
