### ISSUE TITLE
Question: RC2 availability

### ISSUE THREAD

**Issue by nrc-cnrc-web** [wet-boew/wet-boew-drupal#931]
Hi,

Is RC2 available somewhere? If not, is there a release date set for it?

Thanks much!  :-)

**Comment by joejoseph00** [comment]
@sylus  @nrc-cnrc-web is asking about RC2

While on topic, any chance you can merge our latest TinyMCE enhancements into RC2?  Works with or without UOttawa side-by-side.

https://github.com/wet-boew/wet-boew-drupal/pull/806

First
![1](https://f.cloud.github.com/assets/1028526/477883/520abb28-b7ec-11e2-8c7c-fc92078a8d69.png)
Second step, select split F|E  (in our case the French is on the left side, others might chose split E|F)
![2](https://f.cloud.github.com/assets/1028526/477882/520bd6fc-b7ec-11e2-84f7-64468c20ad1d.png)
Third: the result, table is gone on left, column content is split appropriately.
![3](https://f.cloud.github.com/assets/1028526/477881/51f69bac-b7ec-11e2-8776-fb0f9f91c8e0.png)

**Comment by sylus** [comment]
RC2 is out on drupal.org. The readme on GitHub will need to be updated to reflect the changes to a D.O based workflow but separate issue.
