### ISSUE TITLE
Notice error in wetkit_wysiwyg_wysiwyg_editor_settings_alter() 

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#933]
In /eng/admin/structure/types/manage/location-summary/fields/field_location_type

I got the following notices:

```
Notice: Undefined index: content_css in wetkit_wysiwyg_wysiwyg_editor_settings_alter() (line 247 of /data/www/wet/profiles/wetkit/modules/custom/wetkit_wysiwyg/wetkit_wysiwyg.module).
Notice: Undefined index: language in wetkit_wysiwyg_wysiwyg_editor_settings_alter() (line 292 of /data/www/wet/profiles/wetkit/modules/custom/wetkit_wysiwyg/wetkit_wysiwyg.module).
```

With a fresh build of Wetkit.

**Comment by sylus** [comment]
I think this was a problem with an earlier version of wetkit_wysiwyg should be fixed now when moved to wet-boew-wem as some refactoring is done. Please reopen if problem persists and give exact steps to reproduce.
