### ISSUE TITLE
disallow authorize operations

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#934]
This shouldn't be enabled by default in government sites this line should be uncommented in the settings.php file by default:
    $conf['allow_authorize_operations'] = FALSE;

This just isn't a best practice, so let's disable it by default in the settings.php file.

**Comment by sylus** [comment]
We don't house the settings.php file it gets added during the build. This might be out of scope?

**Comment by mgifford** [comment]
Could just be a matter of adding it to the install documentation.

Could simply be a set of $conf's that are recommended to adding to the settings.php file.

We've also noticed a huge performance improvement in WET by enabling memcache (and corresponding module) which requires addition of code to the settings.php file too.

**Comment by sylus** [comment]
Yeah memcache + varnish in memory significantly improve performance. The vagrant-normandy project will solve all of this by having the following:

1) Drupal WXT
2) Solr 4.X + Multilingual Schema + SolrConfig + StopWords + ProtWords
3) Memcache
4) Varnish + Tailored VCL + In Memory -S malloc
5) Apache with tailored conf
6) Custom PHP.ini
7) Optimized PostgreSQL DB

Should be releasing an initial release today and instructions to install are vastly simplified.

**Comment by mgifford** [comment]
Looking forward to seeing it, so make sure to add a link here.

**Comment by mgifford** [comment]
Adding link:
https://github.com/sylus/vagrant-normandy

**Comment by sylus** [comment]
Added to documentation, so closing :)
