### ISSUE TITLE
Error in Solr when accessing the Help pages

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#935]
This is just using default WET Drupal, but after enabling Help and going /eng/admin/help/media (or to any other help page I've tried)

I get this nasty error:
    Recoverable fatal error: Argument 2 passed to search_api_solr_help() must be an array, null given in search_api_solr_help() (line 97 of /data/www/wet/profiles/wetkit/modules/contrib/search_api_solr/search_api_solr.module).

**Comment by sylus** [comment]
Advanced Help was moved under the dashboard but this was breaking the paths. This logic has been removed.
