### ISSUE TITLE
Section element wrapping the entire content area is disrupting the HTML5 outline

### ISSUE THREAD

**Issue by pjackson28** [wet-boew/wet-boew-drupal#938]
The Drupal variant is incorrectly wrapping the entire content area with a section element. This is disrupting the HTML5 outline which makes it less useful to users that have access to it (can access through browser plugins and some screen readers). The simple fix is to remove the section element that is wrapping the entire content area.

The following shows the impact that this one section element has on the HTML5 outline:

1) Here is the HTML5 outline of data.gc.ca which uses the Drupal variant. Notice that the Footer header is at the start of the outline and the data.gc.ca home h1 is the third nested section of the footer.

```
1. Footer
    1. Government of Canada navigation bar
    2. Site Menu
        1. About data.gc.ca(open the submenu with the enter key and close with the escape key)
        2. Open Data(open the submenu with the enter key and close with the escape key)
        3. Open Government(open the submenu with the enter key and close with the escape key)
        4. Participate(open the submenu with the enter key and close with the escape key)
    3. data.gc.ca home
        1. Google Hangout
        2. Open Government Licence – Canada
        3. Citizenship and Immigration Canada Open Data
        4. MASAS: a mapping tool for public safety.
        5. Tab list 1
        6. Search Data
        7. Tab list 2
        8. Untitled SECTION
        9. Search Data
        10. Open Government
        11. Participate
        12. Open Data in Canada
        13. Showcase
        14. Developers' Corner
    4. Site Footer
        1. About data.gc.ca
        2. Media
        3. Contact Us
        4. Stay Connected
    5. Government of Canada Footer
```

2) Here is the HTML5 outline of the WET working examples page. Note that the h1 is at the start of the outline and everything is nested within it which makes for a much better and more logical outline.

```
1. Working examples
    1. Header bar
    2. Search
    3. Site menu
        1. WET project(open the submenu with the enter key and close with the escape key)
            1. About WET
            2. About the Web Standards
        2. Implement WET (open the submenu with the enter key and close with the escape key)
            1. Getting started
            2. Designing sites and page layouts
            3. Working with WET
        3. Contribute to WET (open the submenu with the enter key and close with the escape key)
            1. Contributor guidelines
            2. Participating in a project
    4. Breadcrumb trail
    5. Footer
    6. Site footer
        1. About
        2. Contact us
        3. News
        4. Stay connected
```

**Comment by sylus** [comment]
Hey @pjackson28 thanks for the thorough explanation. Would it be satisfactory to change the section element to a div? Drupal still needs this element but can be a div instead.

**Comment by pjackson28** [comment]
@sylus Yes, changing it to a div would resolve the issue. By the way, is there a reason there are so many divs being generated? I noticed that the Drupal variant h1 is nested nearly 12 levels deeper than the WET core h1 resulting in a lot of markup.

**Comment by sylus** [comment]
Drupal generates alot of extra markup to assist themers. Ultimately it depends on the page you viewed. Correcting some of the extraneous div's is definitely high on my priority list :) 

Thanks for your feedback!

**Comment by sylus** [comment]
Thanks @pjackson28 this has been fixed in: https://github.com/wet-boew-wem/wetkit-adaptivetheme/commit/f44a149ac3ff2115aaa3e504325ae2326bf643b2
