### ISSUE TITLE
Add support for classes from Panels config into Blocks

### ISSUE THREAD

**Issue by minorOffense** [wet-boew/wet-boew-drupal#939]
I know blocks aren't typically used in Panopoly, but in some cases they're still added to some layouts.

But default however, Blocks won't respect the classes added through the Panels config.

The following adds support for those classes (added to template_preprocess_block)

``` php
/**
 * Implements template_preprocess_block().
 */
function mytheme_preprocess_block(&$variables) {
  // Add support for css classes and ids from panels
  // Add classes
  if (!empty($variables['elements']['#block']->css_class)) {
    $classes = explode(' ', $variables['elements']['#block']->css_class);
    $variables['classes_array'] = array_merge($variables['classes_array'], $classes);
  }
}
```

I haven't implemented anything for overriding the block ID since I was concerned about breaking code which assumes a certain pattern of block ID (ex: Views). But a similar technique could be used to add that.

Anyways, thought this might be handy.

**Comment by mgifford** [comment]
Thanks for sharing this! I wonder if there's a way to gather this type of information in the Wiki somewhere. Having a collection of useful code and context of when to use it would be great.

**Comment by sylus** [comment]
Committed to both GitHub and D.O

a) https://github.com/wet-boew-wem/wetkit-adaptivetheme/commit/d34807edbb8f274421b16b267b0a75a6c9934bbb

b) http://drupalcode.org/project/wetkit_adaptivetheme.git/commit/d34807e

Ideally we will eventually disable blocks like Panopoly did but till then this makes sense.
