### ISSUE TITLE
Multi-Lingual Dublin Core

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#940]
What is the best practice for adding multi-lingual content for the Dublin Core metadata?

So something like:
Agence Example, Gouvernement du Canada
Example Agency, Government of Canada

But the metatags don't have fields for i18n fields and these both pull the same content:
eng/admin/config/search/metatags/config/node
fra/admin/config/search/metatags/config/node

**Comment by sylus** [comment]
You can see what we do here for our metatags is create some custom tokens: https://github.com/wet-boew-wem/wetkit-metatag/blob/7.x-1.x/wetkit_metatag.tokens.inc

This is what we have been doing.

**Comment by mgifford** [comment]
I think this is the default way that Meta tags deals with translation - https://drupal.org/node/1282620#comment-7279740

1: add a metatag instance.
for keywords, input "test i18n"
2: Goto admin/config/regional/translate/translate
search "test i18n"
3: translate, game over.

However, I think some things probably could be built automatically. 

Dublin Core Publisher - probably should be the same as whatever you've added to admin/config/system/site-information?variable_realm_key_language=en or [site-name] 

Dublin Core Contributor - I'm assuming this should be null for the GoC.

Dublin Core Date - Can this be [node:bilingual_date_published] + 2 years?  Doubt that would work.

Dublin Core Type - I'm assuming that would be text for most nodes.

Dublin Core Format - ?? - not sure if this is needed.

Dublin Core Language  - [node:bilingual_prefix] should work fine. I've been asked to have it in 'scheme="ISO639-2/T" content="eng"'

Dublin Core Coverage - Canada

Dublin Core Rights - Is this generally just the government agency? Or something like "This site and all pages on it are non-exclusively licensed under the Crown Copyright."  Most agencies just seem to leave this blank.

Dublin Core Subject - You've used [current-page:bilingual_default_value] but we're looking to use something like [term:subject] but haven't tested this yet.

I probably should be re-naming this thread.

Again, a best practice should be identified and documented. Ideally it would be generated by default. 

http://www.collectionscanada.gc.ca/government/controlled-vocabularies/007004-4000-e.html
"Consult your departmental library and information management experts to determine if a controlled vocabulary or formal classification scheme is already in use in your department. The default vocabulary, if no departmental scheme is available, is the Government of Canada Core Subject Thesaurus (CST).

In any case, for interoperability purposes, it is highly recommended that one or more terms from the CST be selected as the content for "dc.subject". Other registered vocabularies and/or classification schemes may additionally be used."

**Comment by sylus** [comment]
Metatags module has good documentation on how to achieve this going to defer to them for how to do this.
