### ISSUE TITLE
Importing Multilingual Taxonomies

### ISSUE THREAD

**Issue by d-shields** [wet-boew/wet-boew-drupal#941]
Because of the need to use entity translation for taxonomies, I'm running into a great deal of trouble with localized multilingual taxonomies.
Entity Translation required the Title module in order to replace the taxonomy name and description with name and description fields, so that they can be translated.
This is fine, but I can't find any contrib modules that will help import a csv of translated taxonomies. 
I'd typically use either taxonomy_csv or feeds, but neither of these seem to work.

Has anyone found a way around this?

Importing huge lists of taxonomies in 2 languages MUST be a common challenge when developing sites for the GoC, no?

**Comment by sylus** [comment]
Just write a custom devel php script and call the appropriate api such as i18n_taxonomy_save.

**Comment by flyke** [comment]
I would like this functionality too. For now I am waiting until Feeds supports this (https://www.drupal.org/node/1183440).

If anyone has created a custom import script to import translated taxonomy terms (using entity translation and Title module) please post code or a link here so we have a good example to create our own script for that.

**Comment by d-shields** [comment]
@flyke - take a look at https://www.drupal.org/project/entity_translation_export_import
