### ISSUE TITLE
Gender field on User entity causes WSOD

### ISSUE THREAD

**Issue by d-shields** [wet-boew/wet-boew-drupal#943]
I'm not sure why nobody else has run into this issue, but without values to select in the Gender select list on the user edit page, editing a user gives a blank white screen.

I don't think we edited these options at all, so I'm assuming others may run into this.

A male and female option should be default values with integer keys - why integer keys? I'm not sure, but its required.

Anyone else seeing this issue on a fresh install of WxT?

**Comment by mgifford** [comment]
See https://drupal.org/node/1902564

**Comment by sylus** [comment]
Upstream issue.

**Comment by sylus** [comment]
Has been resolved upstream please read issue above.
