### ISSUE TITLE
Remove migration and demo content from profile dependencies

### ISSUE THREAD

**Issue by christophercook** [wet-boew/wet-boew-drupal#944]
The demo content is great for development purposes but is likely not useful for a production site. Further, if you want to upgrade/migrate an existing site to wetkit then the demo content types and migration are counter-productive. For my purposes it would be ideal if the migration and demo content feature were optional manual installs.

I'm trying to figure out a way to avoid having these features enabled during a site install but it seems that forking the profile to remove those dependencies is the only option. Do I have any other options?

**Comment by RobJohnston** [comment]
I think it would look kind of barren if there was nothing there after an install... would look like something didn't work correctly.

You could to "Content | Migrate", un-check everything and select "Rollback".  Then go to "Modules" and un-check "WetKit Migration".  Alternatively, something like "drush mr --all" and "drush dis wetkit_migrate" would do it.  You'd just be left with the content types after that.

**Comment by christophercook** [comment]
I'll add those steps to my build script. That should work although it makes me unhappy to have to.

For what it's worth, Drupal core does not install demo content and people would probably be unhappy if it did. I appreciate it being there to demonstrate how a wetkit site can look but question that any production website will use it.

**Comment by StephenOTT** [comment]
I agree with Chris.

On 2013-07-25, at 4:28 PM, christophercook notifications@github.com wrote:

I'll add those steps to my build script. That should work although it makes
me unhappy to have to.

For what it's worth, Drupal core does not install demo content and people
would probably be unhappy if it did. I appreciate it being there to
demonstrate how a wetkit site can look but question that any production
website will use it.

—
Reply to this email directly or view it on
GitHubhttps://github.com/wet-boew/wet-boew-drupal/issues/944#issuecomment-21582196
.

**Comment by sylus** [comment]
This has been committed to both GitHub and Drupal.org now there is an option to enable demo content + migration during the installation screen. If you wish with drush to have wetkit demo + migrations use you will have to pass a parameter:

``` php
drush si wetkit wetkit_wetboew_selection_form.theme=wetkit_adaptivetheme install_configure_form.demo_content=TRUE --sites-subdir=default --db-url=mysql://root:@127.0.0.1/wetkit_db --account-name=admin --account-pass=WetKit@2012 --site-mail=admin@example.com --site-name="Web Experience Toolkit" --yes
```

Diff is here: http://drupalcode.org/project/wetkit.git/commitdiff/d9502f9?hp=7b946d23e9b194cee1227282827d2a60b15fd22c
