### ISSUE TITLE
This doesn't look like the WetKit Adaptive Theme 

### ISSUE THREAD

**Issue by arothmel** [wet-boew/wet-boew-drupal#945]
My latest install of wet-boew-drupal has left me confused! I've tried both github and drupal. Neither one provides the WetKit Adaptive Theme that I have grown to <3!
I'm expecting GoC and instead it's well Wxt. Did I miss a release announcement? I'm new to using distros until now, but the concept is great! Apparently I am over thinking the install. Any and all advice appreciated! (for NRCan)!!!

**Comment by sylus** [comment]
The distro comes with four themes by default. 

a) WxT Theme (enabled by default)
b) Internet Theme
c) Intranet Theme
d) Base Theme

Just go to: admin/panopoly/wetkit_settings/wetkit_wetboew

Then select the intranet theme :)

**Comment by alar2** [comment]
This makes me very happy! 
Thank you so very much!!!

**Comment by RobJohnston** [comment]
This location isn't still valid, is it?  I've got RC9 installed and I expected the GC Web usability theme as per the picture for WetKit Omega but it installs with the WET theme.  Don't see where to change it anywhere.

**Comment by lampson** [comment]
It's under wetkit library. It used to be under wetkit wet-boew but has since been removed/renamed.

**Comment by RobJohnston** [comment]
Thanks a bunch!  I'd suggest changing the label from "WetKit Library" to "WetKit Theme", as that's the only thing that can be changed on that page.  When I saw "Library" I was thinking of the "/sites/all/libraries" directory where one would put superfish or video-js... nothing related to themes.

**Comment by sylus** [comment]
Hey I could change it to something else but we already have a wetkit_theme module that deals with theme related logic. The reason it is called WetKit Library is because the machine name is wetkit_wetboew and that module leverages the libraries api to integrate the wet boew jquery framework. I could set the name back to WetKit WET-BOEW or another option?

**Comment by RobJohnston** [comment]
I guess that makes sense from a coding perspective.  Another option is to make the comments shown on the /admin page more helpful.  Now it says, "This is the configuration screen for WetKit Library".  I'm thinking you could add something like, "Change to another of the various Drupal WEM-based themes".  That would have got me to where I needed to be... anything with the word "theme" in it would have.

**Comment by arothmel** [comment]
There it is, under library! I did not think of looking under there either. Agreed a note such as "Change to another of the various Drupal WEM-based themes" would be helpful.

**Comment by sylus** [comment]
This will be fixed in RC14. I have moved the title back to WetKit Wet-Boew and use the desciption heading suggested. Thanks a bunch!
