### ISSUE TITLE
Need Help with Windows Documentation

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#947]
I'm writing a WET Drupal Guide for Windows Server 2008 and could really use some input from others.  Last time I did Windows Server administration was probably in 1999, so it's all a bit rusty. 

I've got it mostly up and running, but really don't see it being close to production ready. 

I've set up a GoogleDoc and am able to share to folks who want to contribute comments, edits, etc.

**Comment by RobJohnston** [comment]
I'll pull some notes together and add something this weekend.

**Comment by mgifford** [comment]
Anything you can share would be useful.  Thanks!

**Comment by mcman12** [comment]
I can probably take a look and see if I can add anything to it if you still need inputs.

**Comment by mgifford** [comment]
Absolutely we could use more input. Thanks @mcman12

**Comment by mgifford** [comment]
We've got an instance up on Amazon's EC2 that we can share with folks who are willing to help with the documentation.  You can see it up and running here (note I will be turning this box on/off but it will be on for the rest of the day today):
  http://parks.aws.ox.ca/wetkit/

There really a smattering of information on running Drupal on Windows, so I'd like to consolidate best practices in a single document that we can continue to upgrade.  

Please let me know if you can help contribute to the documentation.  I am hoping to release it before the next WETKit meeting.
