### ISSUE TITLE
WetKit Omega Theme

### ISSUE THREAD

**Issue by deepesh-agarwal** [wet-boew/wet-boew-drupal#948]
Can I use the "WetKit Omega" theme without this distribution, I tried but it does not work - are there other requirements beyond "Panel" module ? 

One more suggestion, pls. offer users pre-built distributions for usage on these free services which we can use and later upgrade our accounts there to go live :+1: 

1). http://openshift.com/ - The RedHat Cloud with always free tier.
2). https://www.getpantheon.com/ - For one click dev install.

**Comment by sylus** [comment]
No you can't use wetkit_omega without the rest of wetkit as it has some hard assumptions. Particularly the presence of wetkit_wetboew.

No there are no considerations to make it stand alone as this has been addressed many times.

We are offer pre-built distribution drupal.org/project/wetkit itself.
