### ISSUE TITLE
Tabbed Interface issues

### ISSUE THREAD

**Issue by rousellb** [wet-boew/wet-boew-drupal#949]
I can't seam to be able to change the styles to the tabbed interface. When I try to change the style, I loose access to the selection buttons. When I go back the default is selected and as soon as I select another style I loose access to the buttons again. Anybody having the same issues?

**Comment by sylus** [comment]
Due to the problems with tabbed interface we have removed the current implementation so can introduce a more feature complete version leveraging beans. This will likely be added post 1.0 release.
