### ISSUE TITLE
WetKit Lightbox destination image styles are never generated.

### ISSUE THREAD

**Issue by MikeDucharme** [wet-boew/wet-boew-drupal#950]
When using the WetKit Lightbox field formatter on an image field, the Destination image style is not ever generated.

`Destination image style: panopoly_image_full
Source image style: thumbnail
Custom Class: non-responsive`

The thumbnail image style is generated when flushing image style caches but the panopoly_image_full is not.

This results in an "Image failed to load" response. Flushing the image style cache doesn't regenerate it.

`drush image-flush`

If I set the destination to "thumbnail", it works fine - as long at the thumbnail is used in the source image style or somewhere else on the site where that image style is used.

I can provide screenshots if necessary.

**Comment by d-shields** [comment]
any movement on this yet?

**Comment by sylus** [comment]
With panopoly now gone, thinking this issue no longer persists :)

**Comment by mgifford** [comment]
I'm not re-opening this, but the radical change in the architecture will fix some problems and add others.

I see no reason to assume that this will be fixed with the switch, but will test it internally.
