### ISSUE TITLE
Question: Upgrading from RC1 (or RC1a) --> RC2 --> RC3

### ISSUE THREAD

**Issue by nrc-cnrc-web** [wet-boew/wet-boew-drupal#951]
Hi,

I was wondering if there's a best practice to follow when upgrading a WxT-Drupal site - ie: from RC1/RC1a to RC2, and then from RC2 to RC3? I'm still rather new to Drupal and have heard there are ways to upgrade distros so as to make the next upgrade much harder than it should be. If someone could point me toward some information that would apply specifically to this distro, I'd appreciate it.

Cheers,
Matt

**Comment by sinkinsona** [comment]
What version of the distro are you currently running?  I know that an RC4 will be released soon with many improvements so you might be best to start with that.  At my organization we are running RC1 and are planning to use the migrate module to bring over our content to the newest build and features for content types, views, etc..

**Comment by nrc-cnrc-web** [comment]
Thanks for your response.

I had started on a site using RC1a. There aren't a ton of things to move over, (so starting from scratch is not a huge deal) but as a relative Drupal newbie I was hoping to get some advice as to how to handle migrating things like Content Types, custom User fields & data, Taxonomies and nodes themselves properly, so that any future WxT-Drupal upgrades can be done as painlessly as possible.

I'll investigate Wetkit's Migrate. As for Features, I've read that it's used to migrate content types, but I've also read it changes the way the content types are stored within Drupal? If it's considered the best way to handle those, I will follow suit. I was just a little hesitant to try it when I read that it wasn't going to provide me with an exact duplicate of the content types on my RC1a site (in that it changes the way they are stored).

Thanks for your insight. Now to start playing with those modules!

**Comment by mxlav** [comment]
@nrc-cnrc-web , I'm also looking at upgrading a few dev sites from RC1 to RC3. I looked at comparing everything and manually overwriting, then running update.php, but I a lot of things appear to have changed in the wetkit package itself, that I'm not to confident of the success.

I also haven't played with Features a lot, but my initial look at it isn't very promising (might be a lack of understanding)

I created a basic feature by selecting only one very small content type, brought it in a fresh RC3 site, and all the fields were appearing as overridden on the new site. Decided to upgrade Features on my test site to match Feature on RC3 (2.0-rc2). This removed a lot of the overridden indicators, but now I have a conflict with wetkit-core, field-title. Tried a second simple content type, this one has a conflict with wetkit-core, body.

Curious if you encountered anything similar?

**Comment by mxlav** [comment]
As an interim solution, I have 
- removed the conflicting fields from wetkit-core and create a CBSA-WET Shared Fields Feature
- added a dependancy to the new feature in  wetkit-core and my feature. 

Not sure if this is the best solution or not? @sylus any comments?
