### ISSUE TITLE
RC3 in IE9

### ISSUE THREAD

**Issue by nrc-cnrc-web** [wet-boew/wet-boew-drupal#952]
Hi,

Our sys admin downloaded and installed RC3 yesterday, and when I view the front page in IE9, this is what I see:

![wxt-drupal-rc3---ie9](https://f.cloud.github.com/assets/2982689/969663/c83d16a0-05c7-11e3-8ed1-5e0d2fe7e1b7.jpg)

**Comment by nrc-cnrc-web** [comment]
We've just installed a fresh copy of RC4, and this problem remains for IE9.
IE8 looks slightly different, but is also broken.

**Comment by mxlav** [comment]
I have this error in IE8.
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729)
Timestamp: Tue, 27 Aug 2013 16:57:23 UTC

Message: '0.parentNode' is null or not an object
Line: 9
Char: 17216
Code: 0
URI: http://localhost/wet_rc4_1/profiles/wetkit/libraries/wet-boew/dist/js/pe-ap-min.js?ms77rm

**Comment by lampson** [comment]
Can you turn off  "Aggregate and compress CSS files"?  This will solve the issue with IE until a permanent fix is in place.

**Comment by nrc-cnrc-web** [comment]
Fantastic - that solves the problem for both RC3 and RC4. Thanks very much, @lampson!  :-)
