### ISSUE TITLE
Just wondering...

### ISSUE THREAD

**Issue by nrc-cnrc-web** [wet-boew/wet-boew-drupal#953]
Is this still the correct place to report issues/ask questions? It's been pretty quiet here lately.

**Comment by sinkinsona** [comment]
Yes this is still the right place to ask questions regarding the distro.  We are still sorting out when we will use github vs Drupal.org and we will communicate our approach. A lot of my team have been away but we will try to answer your questions.

**Comment by nrc-cnrc-web** [comment]
Great, thanks much!
