### ISSUE TITLE
FYI to those using a WebKit browser and CKEditor

### ISSUE THREAD

**Issue by nrc-cnrc-web** [wet-boew/wet-boew-drupal#954]
There's a known issue regarding the insertion of inline styles when using them together:
http://dev.ckeditor.com/ticket/9998

**Comment by sylus** [comment]
I am going to close this issue as is a browser bug with Chrome. Though oddly enough I don't think I was able to reproduce with the nightly build.

However people will be able to find this issue should they have the problem.

Thanks for posting!
