### ISSUE TITLE
Changes in Release Candidates

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#955]
We really need to have a detailed change log with releases. Between RC's there seem to be a lot of changes, but they aren't documented anywhere.

These changes should also be discussed before they are implemented.  If this distribution is going to be supported by more than StatsCan then there needs to be involvement from others in the decision making.

**Comment by Pacoup** [comment]
Yes, it would be great if the repo was developed in the same <strong>clone to own repo + pull in main repo</strong> methodology as WET as well. This helps in tracking changes and commenting on them since pull requests appear in Notifications on GitHub whereas normal commits don't.

**Comment by mgifford** [comment]
This would be very useful too.  I was mostly wanting broad brush strokes though. What modules/themes were included would be a great start.  What work has been done on a migration path between versions. There really shouldn't be any surprises when a new RC is released and a department decides to do an upgrade.

**Comment by mgifford** [comment]
After talking to @sinkinsona I do think that this will be changing so that there will be better documentation between RC's.

**Comment by sylus** [comment]
Think can close this now as am:

a) Leveraging clone to own repo + pull in main repo for every commit now (sorry for being lazy)
b) Have a changelog which will documented major changes.

**Comment by mgifford** [comment]
I should have closed this earlier. Last few RC's have been good for documentation.
