### ISSUE TITLE
Is Susy the official wet-boew-drupal grid framework?

### ISSUE THREAD

**Issue by MikeDucharme** [wet-boew/wet-boew-drupal#968]
The Wetkit_Omega theme has required dependencies on the Susy grid framework.

`# Require any additional compass plugins installed on your system.
require 'compass-normalize'
require 'rgbapng'
require 'toolkit'
require 'susy'`

Is this grid framework that Wetkit has adopted or is this specific only to the Wetkit_Omega theme?

**Comment by sylus** [comment]
It is actually an artifact from the subtheme generation. So no Susy is not the official grid framework. Once WET v4.0 comes out the bootstrap grid will be the official one though.

**Comment by mgifford** [comment]
So to be clear, "require 'susy'" is going to be removed when WET v4.0 comes out, but is now the default grid that is being used with the distribution?

How is the WET grid used in the Omega theme?

**Comment by sylus** [comment]
No require susy came in during the omega sub theme generation. It is not used in any way shape or form. I will remove it in a next commit when I have time. Can leave this issue open till then.

**Comment by sylus** [comment]
This is fixed in next RC.

**Comment by d-shields** [comment]
hey @sylus - this seems to still be required in RC-19?
Am I missing something?
I think this should be re-opened..
