### ISSUE TITLE
What's WEM?

### ISSUE THREAD

**Issue by Pacoup** [wet-boew/wet-boew-drupal#981]
What does <em>WEM</em> mean? It's not written anywhere.

**Comment by StephenOTT** [comment]
Web Experience Management/Manager

On 2013-09-11, at 5:17 PM, Etienne Levesque Guitard <
notifications@github.com> wrote:

What does _WEM_ mean? It's not written anywhere.

—
Reply to this email directly or view it on
GitHubhttps://github.com/wet-boew/wet-boew-drupal/issues/981
.

**Comment by Pacoup** [comment]
Can you explain why Drupal WET is Web Experience Manager and not just a “Drupal Web Experience Toolkit”? I've only ever seen this term <a href="http://www.opentext.com/global/products/web-content-management/web-experience-management/opentext-web-experience-management.htm">OpenText use the term Web Experience Management</a>.

I think this would be a valid addition to the wiki and readme.

**Comment by mgifford** [comment]
Dries made a strong call for it here https://portland2013.drupal.org/live

There's a discussion about approaches to it here https://groups.drupal.org/web-experience-management

I do really wonder though if there is any realistic way for this to be implemented in WET in the GoC any time soon.

**Comment by sinkinsona** [comment]
Dries talks about it as well during his keynote at Sydney DrupalCon.
http://sydney2013.drupal.org/keynote/dries-buytaert

In my opining WEM is about creating a system that does more than just publish content to the web.  Its about attracting users to your site, giving them a dynamic and interactive experience and ultimately making them want to come back to your site.  

Here is a slide from Dries keynote that helps explain it. 
![screen shot 2013-09-17 at 8 55 16 pm](https://f.cloud.github.com/assets/1258144/1162038/dae640e4-2000-11e3-895b-8969415c4968.png)

Depending on the technologies chosen to power the GOC web presence I think that WEM is obtainable but maybe that is just my optimistic thinking :)

**Comment by Pacoup** [comment]
Thanks, I think this covers it.
