### ISSUE TITLE
Issue with RC11 install through Acquia Dev Desktop

### ISSUE THREAD

**Issue by nrc-cnrc-web** [wet-boew/wet-boew-drupal#990]
I downloaded RC11 today and installed it through Acquia Dev Desktop's import functionality (and I chose to import the demo content). At the end of the installation I clicked the link "Visit your new site", but instead of domain/eng (or domain/en, as the latest distro uses), it sends me to domain/?q=en, which is just a directory listing. If I change the path to domain/en or domain/eng, I get a 404 page.

Did something change in the way the distro works?

**Comment by joejoseph00** [comment]
This does not appear to be a problem with the distro.  I've seen this before and it's related to configuration on your stack.  Probably a modification to your vhost configuration, and or .htaccess configuration would fix this.
please try configuring the  RewriteBase in your .htaccess file

  # Modify the RewriteBase if you are using Drupal in a subdirectory or in a
  # VirtualDocumentRoot and the rewrite rules are not working properly.
  # For example if your site is at http://example.com/drupal uncomment and
  # modify the following line:
  # RewriteBase /drupal
  #
  # If your site is running in a VirtualDocumentRoot at http://example.com/,
  # uncomment the following line:
  # RewriteBase /

If this doesn't work, toss around your drupal folders, try putting the RC11 one where a working one is (toss the working one elsewhere, and copy/rename the RC11 to the place where the other one was working)

**Comment by joejoseph00** [comment]
Either that or you're missing the apache rewrite  mod, or it's not activated

**Comment by nrc-cnrc-web** [comment]
Thanks @joejoseph00 - I appreciate the suggestions. I'll give them a try tonight.
I installed it on my tablet today and it works just fine. Guess I should have tried that first before posting here. Apologies.

**Comment by lampson** [comment]
I would always try the browser installation through simplytest first since  it only takes a few minutes. But I prefer using drush site-install.
