### ISSUE TITLE
build issue continued

### ISSUE THREAD

**Issue by joejoseph00** [wet-boew/wet-boew-drupal#993]
@sylus, I've done some more testing on the build procedure.  
This time with 
Drush 6.0 , 
php 5.3.5, 
git 1.7.3.4

Three errors occur:
Unable to download https://drupal.org/files/deploy_new_alter_hook-2092335-4.patch. [error]
Unable to determine mime type for spyc.php. [error]
Unable to patch caption_filter with 1432092-button-and-image.patch. [error]

  Not sure why (maybe because of these three errors), the **build** folder is left in my "/tmp" partition after the drush make command is executed.

/tmp/make_tmp_1379780369_523dc711cd2c3/**build**/

, back in April, this **build** folder would be copied to the path entered as a parameter to the drush make command

Now the folder just sits in /tmp 

Here's the command sequence I'm executing:

cd /home/joseph/public_html
mkdir statcan
cd statcan
git clone https://github.com/wet-boew/wet-boew-drupal.git wet-boew-drupal;
Cloning into wet-boew-drupal...

sudo drush  make --prepare-install --no-gitinfofile --working-copy wet-boew-drupal/build-wetkit-github.make /home/joseph/public_html/statcan/statcan --yes
Make new site in the current directory? (y/n): y
Beginning to build wet-boew-drupal/build-wetkit-github.make.                                                                                                            [ok]

it continues for quite a while without error, then gets an error, continues without error, gets another error, continues for a while without error, gets another, then continues.

then it finishes, there's nothing in the expected folder /home/joseph/public_html/statcan/statcan

My next step would be to try manually copying over the stuff in the /tmp folder, so move /tmp/make_tmp_1379780369_523dc711cd2c3/**build**/ to my preferred destination.  However for almost 1 entire year I was able to do builds.  Then something happened between May and August, because it was working up until April 2013 on the same server.  

The only change I did to the server was upgrade Drush from 5.4 to 6.0 , and this was just yesterday to try and resolve the problem, but it didn't seem to help.

Please advise.

**Comment by joejoseph00** [comment]
BTW, I'm following the latest build instructions here: http://wiki.drupalwxt.org/concepts/drush-make/
of course on my server /var/www/html does not exist, and I'm installing to the userdir , shouldn't be a problem, as I did this before many times before May 2013.  The last time it worked for me was April 2013.  And it worked before that as far back as 2012.

**Comment by joejoseph00** [comment]
I'm trying again, this time without sudo on the drush make.  Might make a difference.  I'll check back in 30 minutes

**Comment by joejoseph00** [comment]
ok, so I copied the broken **build** folder from my /tmp/drush_make_hashNumbers/ folder, 
configured the drupal settings.php and .htaccess (for rewritebase)

and I get Notice: Undefined index: wetkit_shiny in theme_get_setting() (line 1431 of /home/joseph/public_html/statcan1/includes/theme.inc).

So the **build** looks to be incomplete.  I'll try debugging the build procedure and reviewing it again.

**Comment by joejoseph00** [comment]
Still getting errors on the latest build:

Examining /tmp/make_tmp_1379944502_5240483691501/spyc.php extension.     [debug]
[160.75 sec, 9.81 MB]

## Unable to determine mime type for spyc.php. [160.75 sec, 11.35 MB]   [error]

patching file b/js/langs/en.js
patching file b/js/langs/fr.js [284.27 sec, 9.63 MB]
Unable to patch caption_filter with 1432092-button-and-image.patch.  [error]

**Comment by joejoseph00** [comment]
downgraded to drush 5.8, 
same problem, Unable to patch caption_filter with 1432092-button-and-image.patch.

**Comment by joejoseph00** [comment]
ok this was driving me bonkers so I ran some more tests.
drush make SUCCEEDS with the patch of caption_filter when using Drush 5.7 with php 5.3.3 (git 1.7.1)

drush make FAILS with the patch of caption_filter using any combination of drush and php 5.3.5

conclusion: 
"drush make" has intermittent compatibility issues between "drush make" (patching some files for example) and at least one version of PHP , specifically php 5.3.5 (tried with all recent drush versions) doesn't seem to like this patch: "caption_filter with 1432092-button-and-image.patch." 
http://drupal.org/files/1432092-button-and-image.patch

But it FAILS on either drush 5.4 , drush 5.5,  drush 5.6, drush 5.7, drush 5.8, drush 5.9, or drush 6.0 on top of php 5.3.5 (git 1.7.3.4)
So assuming a problem with php 5.3.5 with drush make performing certain patch commands such as the patch command for http://drupal.org/files/1432092-button-and-image.patch

At least one other person has reported this problem as recently as LAST WEEK:
https://drupal.org/node/2024735

**Comment by joejoseph00** [comment]
due to the unable to patch problem the whole make fails on (any version of drush) and php 5.3.5, yet for some reason works fine on php 5.3.3 using Drush 5.7
So if you're on php 5.3.5, beware of the patch 1432092-button-and-image.patch, or change php versions

**Comment by joejoseph00** [comment]
For the spyc problem: 
https://drupal.org/node/1864308

**Comment by nrc-cnrc-web** [comment]
Wow. I hope you had a drink or 12 after all that...   ;-)

**Comment by sylus** [comment]
Yeah going to close this as is clearly your environment. If you continue to have problems just use the packaged build.
